### ISSUE TITLE
Cumulative Score Item - Calculate the thresholds and do not show the user 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1112]
As an editor, I want to use the cumulative score item to calculate thresholds based on user's responses but I do not want the user to see them so that I can collect these data points without the user's knowledge. 

Requirements 
- Give the option to the editor to show or not show the cumulative score results page on the mobile app
- It should be selected on by default 
- If the user turns off this option, then the data should still be collected but not shown to the user at the end of the activity. 

![mindlogger-admin.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/01eeec09-15b0-4eea-9c0e-54b3d9b957d6)

**Comment by natalia-muzyka** [comment]
1) [UI] The "Allow the user to see results" isn't vertical aligned
https://www.screencast.com/t/wFD8bnulE7L6

2) Is this already implemented on the mobile app side? And will be there a new build or it is just a backend implementation?
Currently, the cumulative screen is displayed for the activity with the turned off "Allow the user to see results" option
https://www.screencast.com/t/ucjvOHeh0ci

**Comment by Sshetty2** [comment]
https://github.com/ChildMindInstitute/mindlogger-app/pull/1817
https://github.com/ChildMindInstitute/mindlogger-applet-builder/pull/414

**Comment by Sshetty2** [comment]
@natalia-muzyka 
![image.png](https://images.zenhubusercontent.com/5c7c2db0568ea92b01579c9a/74e41f17-bcb2-45a3-89a9-34c27d10f76b)

**Comment by natalia-muzyka** [comment]
works as expected

Environment:
https://admin-staging.mindlogger.org/
Windows 10 // Chrome 92.0.4515.107 
macOS 10.15.6 // Safari 13.2
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0	
iPhone 6 Plus  // iOS 12.3.1
