### ISSUE TITLE
Remove initial slider bar knob

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1169]
- Remove the outline of the knob slider when the page initially loads.
- The Knob on the slider should not be visible until the user taps on the screen.

![File.jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/9e58ea86-3802-4349-84c8-11ba24dc4d45)

**Comment by sergeysemenuta** [comment]
Works, as expected on the iOS, devices.

- The outline of the knob slider is shown on the android devices
![IMG_1400.PNG](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/435851c9-68f4-4c67-9b7e-623e5458f5e1)
Checked on:
iPhone X // iOS 13.3
Pixel 4XL//Android 11

**Comment by sergeysemenuta** [comment]
Fixed on:
ML v 0.14.17
Pixel 4XL//Android 11
![IMG_1405.JPG](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/dbf33bf4-e7f7-4202-a2aa-0ff02f282b3b)
