### ISSUE TITLE
Design features / assessment representations

### ISSUE THREAD

**Issue by abadioli** [ChildMindInstitute/mindlogger-app#117]
I have been brainstorming options for assessment representation. There will eventually be a standardized format for each question type (to evaluate between some options).

https://drive.google.com/drive/folders/1Yy7PYSqG28DFyJkS6GjZlwYf0nUxrEdZ?usp=sharing

Feature/design requests:
1 standardized icons (for affect + activities) (see PAQ_C 2, 5-6)
2 slider: always lowest to highest
3 choosing days of week instead of number of times per week (see PAQ_C 3)
4 select option (never/sometimes/always) so that it becomes "blue" like NEXT and then press NEXT to submit
5 DONE screen at end of applet, so it doesn't directly exit to home (may feel like bug, may be deceiving, etc) (see PAQ_C 11)

**Comment by binarybottle** [comment]
Consolidating all design-related issues...
