### ISSUE TITLE
[Staging] The pop-up "Applet was not found" is shown after tapping the push notification

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1176]
**Preconditions:**
-The 'Pre-Questionnaire' is scheduled with settings: start time:11:35 am, start notification at: 11:35 am
-The 'Morning" is scheduled with settings: Timeout: 10 minutes ,start time:11:36 am, start notification at: 11:36 am
-The "Mid Day" is scheduled with settings: One time completion  option is marked, start time:11:37 am, start notification at: 11:37 am
-The 'Night' is cheduled with settings: start time:8:00 pm, start notification at: 11:38 am 
**Steps to reproduce:** 
1. Log in to the app
2. Left the  device in the background mode for about 30 minutes and wait for the notifications
3. Open the notification  'Pre-Questionnaire' and complete it
4. Open the notification  'Morning' 
5. Pay attebtion to the result
6. Open the  notification "Mid Day"
7. Pay attention to the result
8. Tap on any card on the activity screen
9. Pay attention to the result (Nothing happens after tapping the activity cards )
10. Open the  notification "Night"
11. Pay attention to the result

**Actual result:** The pop-up "Applet was not found" is shown after tapping the push notification
**Note:** This behavior has an impact to other assessments by opening the notification one by one
**Video:** https://www.screencast.com/t/hX3IrVCHSRG
**Expected result:** The pop-up "Applet was not found" is not shown after tapping the push notification. The user should be able to complete the assessment or see the corresponding pop-up

**Environment:**
 MindLogger app **v 0.13.1(185)**
Staging server
Samsung Galaxy S10 // Android 9

**Comment by ngonzalvez** [comment]
Since I updated to the latest version of the mobile app and backend API, I've no longer been able to replicate this issue. I spent 6 hours creating more than 30 notifications, and wasn't able to reproduce any blank screen, applet not found, nor unresponsive buttons. Not sure if it was fixed or it is just a very erratic behavior.

**Comment by ngonzalvez** [comment]
What I've tried with no success:
- Log everything that's going on inside of the FireBaseMessaging class (nothing relevant came out)
- Compare the code of the activity started from FBM from that started from the activity listing screen
- Persist the state of the store when going to sleep and restore it after waking up
- Automate the creation of events that reproduce this issue (even when creating events with an script, sometimes it works, and sometimes it doesn't)
- Log the state of the app when it fails. It only failed once when I opened an old notification for an applet I had deleted. In that case it makes sense for it to show the **Applet not found** error
- Using the debugger, debug step by step until it fails (tried this several times, didn't get it to fail while using the debugger)
- Try it on the emulator AND on the device
- Test with an old EMA applet
- Test with a new EMA applet
- Test on local
- Test on staging

**Comment by sergeysemenuta** [comment]
I was not able to reproduce the 'Applet was not found" issue
Checked on:
Staging
MindLogger app v 0.13.31
Samsung Galaxy S10 // Android 9
Pixel 4 XL // Android 11
