### ISSUE TITLE
Notifications should open activity 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1181]
Push notifications that are clicked on by the user should open the activity 

States of activity 
- Available in the future
- Available 
- Available but already started 
- Completed 
- Not completed but no longer available

**Comment by sergeysemenuta** [comment]
Available in the future - passed
Available - passed
Available but already started - passed
Completed- passed

- Not completed but no longer available - failed
Video: https://www.screencast.com/t/Xh4jj9jj
After the timeout, the user has access to the activity after tapping on the notification. And activity goes to unscheduled status
Expected: User should see the pop-up: This activity was due at: hh:mm,If progress was made on 'Activity name' , it was saved but it can no longer be taken today
Example: 
![2021-04-16_17-50-21.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/79b898ec-f56e-4ef5-9f0a-3c682477bb8f)

**Comment by sergeysemenuta** [comment]
The issue is fixed on:
Staging
ML v 0.16.20
iPhone X // iOS 13.3
Pixel 4XL//Android 11
