### ISSUE TITLE
Mindlogger app login

### ISSUE THREAD

**Issue by abadioli** [ChildMindInstitute/mindlogger-app#120]
too many spaces between NEW USER   or FORGOT PASSWORD

![IMG_0128](https://user-images.githubusercontent.com/48026772/54616201-b4e2df00-4a35-11e9-9c57-0c8a0e396e09.PNG)

**Comment by abadioli** [comment]
****it's confusing that New user & forgot password are two separate links. Perhaps display differently (one stacked on top of other)?

**Comment by henryrossiter** [comment]
@abadioli Do you think underlining each link helps with this? Something like this: 
![image](https://user-images.githubusercontent.com/31543235/55970403-1b2ddc80-5c45-11e9-9093-55e8e8c6eb52.png)

**Comment by abadioli** [comment]
Yes, that looks better!
