### ISSUE TITLE
New user panel

### ISSUE THREAD

**Issue by abadioli** [ChildMindInstitute/mindlogger-app#121]
Display fields in more appropriate order

FIRST NAME
LAST NAME
EMAIL
USERNAME
PASSWORD
![IMG_7AF46F8BD764-1](https://user-images.githubusercontent.com/48026772/54617333-70584300-4a37-11e9-9a15-af9dbd568408.jpeg)

**Comment by binarybottle** [comment]
Consolidating design-related issues into a single document...
