### ISSUE TITLE
Forgot password email does not arrive

### ISSUE THREAD

**Issue by abadioli** [ChildMindInstitute/mindlogger-app#122]

**Comment by abadioli** [comment]
Arrived after 35 minutes

**Comment by shnizzedy** [comment]
Duplicate of https://github.com/ChildMindInstitute/mindlogger-app/issues/122

In my experience, the first few attempts get caught in spam filters. I don't know a good way around that problem.

**Comment by shnizzedy** [comment]
Duplicate of ChildMindInstitute/mindlogger-app-backend#56

In my experience, the first few attempts get caught in spam filters. I don't know a good way around that problem.

**Comment by abadioli** [comment]
I checked - no spam.... they just took a long time arrive

**Comment by shnizzedy** [comment]
[Greylisting](https://en.wikipedia.org/wiki/Greylisting)?
