### ISSUE TITLE
[Staging] The app crashes after completing the same event several times

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1234]
**Preconditions:**
-The owner is scheduled  the "Pre-Questionnaire" (related to step 2)
-The owner is removed the "Pre-Questionnaire" from the calendar
-The owner is rescheduled the "Pre-Questionnaire" (related to step 2)

The "Pre-Questionnaire" is scheduled and removed from the calendar and scheduled  again several times on The admin panel
**Steps to reproduce:**
1. Log in to the app as owen@ml.com//123456
2. Complete the assessment "Pre-Questionnaire" several times
3. Stay on the "Surveys"  screen
4. Wait for some time
5. Pay attention to the result

**Actual result:**  The app crashes after completing the same event several times
Video: https://www.screencast.com/t/1C2lGCiLpKv
Crash log: 
[https://app.zenhub.com/files/103405139/7ace063c-37c3-4ffb-b2ba-a6bc8aefca73/download](https://app.zenhub.com/files/103405139/7ace063c-37c3-4ffb-b2ba-a6bc8aefca73/download)

**Expected result:** The app doesn't crash after completing the same event several times

**Environment:**
MindLogger app v 0.13.11  
iPhone XR//iOS13.2.3
Samsung Galaxy S8 // Android 8

**Comment by natalia-muzyka** [comment]
Not reproduces anymore:
https://www.screencast.com/t/4nXJH9jdVCc

Environment:
ML v0.19.21 staging
Samsung Galaxy S20 // Android 11
iPhone XR // iOS 14.3
Samsung Galaxy S7 // Android 8
Samsung Galaxy Tab S6 SM-T865 // Android  9.0
iPad Pro (10,5-inch) MQDX2 // iOS 15
