### ISSUE TITLE
The "Resume activity" pop up is displayed after the second tapping on the activity card

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1248]
**Preconditions:**
Events are "In Progress status"
**Steps to reproduce:**
1. Log in to the app ( everly@stage.com // 123456)
2. Select the NIMH applet
3. Tap on any activity card that is "In Progress" status
4. Tap the "RESTART" or "RESUME" button
5. Close the screen by tapping the close icon or return button
6. Repeat steps 3,4,5 several times
7. Pay attention to the response by tapping the activity card

**Actual result:** The "Resume activity" pop up is displayed after the second tapping on the activity card
**Video:**
https://www.screencast.com/t/uhawPR0DP
https://www.screencast.com/t/iU9m2ixIN
**Expected result:** The "Resume activity" pop up is displayed after the first tapping on the activity card

**Environment:**
 MindLogger app v 0.13.15
Samsung Galaxy S10 // Android 9
iPhone X // iOS 13.3

**Comment by natalia-muzyka** [comment]
Not reproduces on:
ML v0.19.21 staging
Samsung Galaxy S20 // Android 11
iPhone XR // iOS 14.3
Samsung Galaxy S7 // Android 8
Samsung Galaxy Tab S6 SM-T865 // Android  9.0
iPad Pro (10,5-inch) MQDX2 // iOS 15
