### ISSUE TITLE
TokenLogger. There are some differences  between iOS and Android platforms on the 'Data' screen

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1253]
**Steps to reproduce:**
1. Log in to the app as harper@prod.com // 123456 on Android and IOS devices 
2. Tap the TokenLogger applet card
3. Complete the  assessment
4. Navigate to the Data screen
5. Compare  the Data screen on both platforms

**Actual result:**  There are some differences  between iOS and Android platforms on the 'Data' screen
1. The name of the activity is displayed with Bold font-weight on the Android platform and normal on the iOS
2. The value is not displayed over the chart bar on the Android. The value is displayed over the chart bar on the iOS
3. The days of the week are not displayed on the Android platform. They are displayed on the iOS

![IMG_1322.PNG](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/6230fe10-2a1e-4f85-8a36-b9ad63d7185c)
**Expected result:** 
1. The name of the activity should have the same  font-weight on both platforms
2. The value is displayed over the chart bar on the Android.
3. The days of the week are displayed on the Android platform

**Environment:**
Production server
MindLogger app v 0.13.15
Samsung Galaxy S10 // Android 9
iPhone X // iOS 13.3

**Comment by prodev1101** [comment]
![image](https://user-images.githubusercontent.com/63484644/101780749-e072fa80-3b31-11eb-9c46-0268871c3dfa.png)

This is a view from android device and it show same except for the activity title

**Comment by WorldImpex** [comment]
@sergeysemenuta cannot reproduce any longer

**Comment by WorldImpex** [comment]
https://www.screencast.com/t/rAKNMeKh
