### ISSUE TITLE
The notifications are not fired the next day if the events are scheduled with the "Extended Past Due" option

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1255]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/  leo@stage.com // 123456
2. Select the NIMH applet and navigate to the general calendar
3. Schedule some events with the "Extended Past Due" option (Extended time: 7 days) and set notifications (start notification at 8:00 am etc) for them
4. Log in to the app
5. Left your device and navigate back to the app the next day
6. Look at the notification list

**Actual result:** The notifications are not fired the next day if the events are scheduled with the "Extended Past Due" option. The notification list is empty.
**Expected result:** The user should be notified for the next 7 days according to the scheduled settings
**Note:** The user receives notifications only for the current day
**Environment:**
Staging server
MindLogger app v 0.13.15
Samsung Galaxy S10 // Android 9
iPhone X // iOS 13.3

**Comment by natalia-muzyka** [comment]
This issue is probably reproduced for every repeated type (weekday, weekly, monthly).
As notifications can be received only in real-time (changing a device time won't work), @Tom1204  can you investigate these options as well, please, and continue working on this ticket? Thank you!
cc: @eleonova-scn

**Comment by yzenchanka** [comment]
Verified as fixed 
ML v0.21.68 staging
Google Pixel 3XL // Android 10
iPhone 7 Plus // iOS 14.4
