### ISSUE TITLE
Bug @Create new applet

### ISSUE THREAD

**Issue by abadioli** [ChildMindInstitute/mindlogger-app#126]
Spinner once clicked "CREATE NEW APPLET"

**Comment by abadioli** [comment]
<img width="765" alt="Screen Shot 2019-03-19 at 14 48 36" src="https://user-images.githubusercontent.com/48026772/54635256-1e74e480-4a5a-11e9-8dfb-025e38772657.png">

**Comment by binarybottle** [comment]
Consolidating design-related issues into a single document...
