### ISSUE TITLE
Staging. The push notifications are not received on the device

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1260]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ (leo@stage.com // 123456)
2. Select the NIMH applet or any other applets available
2. Schedule events with notifications and save
3. Log in to the app
4. Wait for the notifications
5. Pay attention to the result

**Actual result:** The push notifications are not received on the device
**Note:** Checked on several accounts. None of the users are received notifications
**Video:** https://www.screencast.com/t/a1dlSUUivaJo
**Expected result:**  The push notifications are received on the device

**Environment:**
Staging environment
MindLogger app v 0.13.17
Samsung Galaxy S10 // Android 9
iPhone X // iOS 13.3

**Comment by ngonzalvez** [comment]
## Testing

**NIMH APPLET**
- Login as user **wavanauken+3@gmail.com**, password **abcd123**
- Go to user-specific scheduling for **user3**
- Clear notifications
- Hit **Save**
- Create a new notification 5 minutes from now
- Save it
- Check the mobile app
> **RESULT:** No notification received


- Create the notification 10 minutes from now
> **RESULT:** No notification received


- Use general scheduling
> **RESULT:** No notification received


- Refresh the app after creating the notification 
> **RESULT:** No notification received


- Leave the app in the background
> **RESULT:** No notification received




**TOKEN LOGGER APPLET**
- Login as user **wavanauken+3@gmail.com**, password **abcd123**
- Go to user-specific scheduling for **user3**
- Clear notifications
- Hit **Save**
- Create a new notification 5 minutes from now
- Save it

- Check the mobile app
> **RESULT:** No notification received


- Create the notification 10 minutes from now
> **RESULT:** No notification received


- Use general scheduling
> **RESULT:** No notification received


- Refresh the app after creating the notification 
> **RESULT:** No notification received


- Leave the app in the background
> **RESULT:** No notification received


**TOKEN LOGGER SLEEP APPLET**
- Login as user **wavanauken+3@gmail.com**, password **abcd123**
- Go to user-specific scheduling for **user3**
- Clear notifications
- Hit **Save**
- Create a new notification 5 minutes from now
- Save it
- Check the mobile app
> **RESULT:** No notification received.


- Create the notification 10 minutes from now
> **RESULT:** No notification received.


- Use general scheduling
> **RESULT:** No notification received.


- Refresh the app after creating the notification 
> **RESULT:**  No notification received.


- Leave the app in the background
> **RESULT:** No notification received.



## Approaches

- Try to replicate the issue on local environment
- Check if `send_push_notification` function is called
- Check if firebase message is received in the app (log to console in `FireBaseMessaging#onNotification`)
- Log the CRON job string
- Log the `first_launch` datetime 
- Check redis to see if the job is being registered
- Spy on rq-scheduler code to see what's going on
- Spy on rq code to see what's going on
- Test if it works by re-uploading the NIMH applet
- Compare structure of old NIMH applet and new NIMH applet (diff both JSON)


## Notes 
- Issue is replicated on local env
- No firebase message is received in the app
- `PushNotification.set_schedules()` function is called when saving the event
- `send_push_notification()` is not called at the specified event time
- `PushNotification.set_job()` is called with the right `first_launch` time
- Redis doesn't always registers the job

**Comment by sergeysemenuta** [comment]
The push notifications are received. The issue is fixed.
Checked on the old and new accounts/applets
MindLogger app v 0.14.3
Staging
![2020-10-31_16-23-53.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/f0008cec-0a45-4576-b10c-eed0488b7c33)
