### ISSUE TITLE
Hide Data App/ Data Removal Options from the User 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1267]
We need to simply hide these buttons for now until we have a better use case for them in the future

![IMG_1928.PNG](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/8f0523a5-6f93-4b89-a282-ecf668a9942e)![IMG_1929.PNG](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/7e5416c0-4727-4bf6-97a9-1c4136b95e98)

**Comment by devbtech** [comment]
I already fixed this

**Comment by sergeysemenuta** [comment]
Reproducible on ML v0.14.38 (258)
![2020-12-28_19-19-02.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/ab7a3269-084f-4659-906b-39dd7101f56d)
Pixel 4XL//Android 11
iPhone XR // iOS 13.2.3
iPhone8 // iOS 14.0

**Comment by Eugenia299** [comment]
The 'Permanently Delete Account' option should be hidden as well
Reproduced on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 87
MindLogger app version 0.14.40
Devices:
Samsung Galaxy J8 2018 // android 8.0
iPhone X // iOS 13.
Video: https://www.dropbox.com/s/hv3v5abioj74tk9/delete.MP4?dl=0

**Comment by sergeysemenuta** [comment]
Fixed on:
ML v 0.14.45
Pixel 4XL//Android 11
iPhone XR // iOS 13.2.3
iPhone8 // iOS 14.0
