### ISSUE TITLE
All applets are disappeared from the app after setting the BEGINNING OF TIME to END OF TIME for an event on the calendar

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1289]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org and to the app as an owner mltestqa@yahoo.com // 123456
2. Select the NIMH applet and navigate to the general calendar
3. Navigate to the previous month
4. Select any date and choose an event (Morning)
5. Select a filter to repeat Monthly
6. Click the "BEGINNING OF TIME" and select any date  (SEPTEMBER 13TH,2020)
7. Select the "END OF TIME" (NOVEMBER 13TH,2020)
8. Save scheduled activities
9. Refresh the app screen
10. Look at the result

**Actual result:** All applets are disappeared from the app after setting the BEGINNING OF TIME to END OF TIME for an event on the calendar
**Video:**https://www.screencast.com/t/BVL7vwPDh7E
**Expected result:** All applets are not disappeared from the app after setting the BEGINNING OF TIME to END OF TIME for an event on the calendar

**Environment:**
https://admin-staging.mindlogger.org
Win 10 // Chrome Version 85
MindLogger app v 0.13.24
Samsung Galaxy S10 // Android 9
iPhone X // iOS 13.3

**Comment by Matchdev120** [comment]
I tested this issue on the account (mltestqa@yahoo.com // 123456) but it's not reproducible.

**Comment by sergeysemenuta** [comment]
The issue is reproducible.
https://www.screencast.com/t/V1R2vgpX
To reproduce:
1. Go to the previous month on the calendar
2. If today is 21 date then select for example 25 and  choose an event (Morning)
3. Select a filter to repeat Monthly
4. Click the "BEGINNING OF TIME" and select the  date (SEPTEMBER 25TH,2020)
5. Select the "END OF TIME" (NOVEMBER 25TH,2020)
6. Save scheduled activities (Note the activity is not saved on the admin panel )
7. Refresh the app screen
8. Look at the result

cc: @Matchdev120

**Comment by sergeysemenuta** [comment]
The issue is fixed.
Checked on:
Environment:
https://admin-staging.mindlogger.org
Win 10 // Chrome Version 85
MindLogger app v 0.13.29
Pixel 4XL/Android 11
iPhone X // iOS 13.3
