### ISSUE TITLE
Check User Image Response to ensure it works on iOS and Andriod

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1299]
1. We need to be sure that images are being stored to the database.
2. Write up how the photos are being stored so we understand data usage 
3. Check that it works for Andriod & iOS 
4. Allow images to be selected from either photo library or taken by the user 
![Screen Shot 2020-10-17 at 3.38.35 PM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/a1047cd8-eb81-42ac-a42f-8b40c3e1fdcc)

**Comment by sergeysemenuta** [comment]
@devbtech Please check the response on the  DB
Uploaded videos.  using iOS/Android devices
Accounts :
garry@ml.com // 123456
use2@ml.com // 123456

**Comment by WorldImpex** [comment]
confirmed by @devbtech
