### ISSUE TITLE
[REDESIGN] - User Widget Order 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1302]
1. Please update the buttons to -  edit, copy, delete refresh, transfer 
![Screen Shot 2020-12-17 at 6.16.41 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/1ff9e4e2-b832-4e30-8dac-f05676be4e4c)
2. Make the copy icon closer to the below image 
![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/0041dd33-5553-492f-87fb-8b06f71a8441)
3. Please update transfer icon to the below
![transfer-icon-300-black.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/24ff2511-de8d-4514-a141-7bb16011f7cb)
4. Add light lines in between each column header 
![mindlogger-admin (2).png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/5390fd64-23e7-4fcf-878c-7b0567d84cc3)
5. Update any MindLogger text to make sure the L is capital 
6. Left justify the text in lists
![Screen Shot 2020-12-21 at 6.56.42 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/450d6f85-01ed-4f2d-89c7-8d15f8ca59ac)

**Comment by prodev1101** [comment]
Fixed 4,5,6 except for icons issue.

**Comment by sergeysemenuta** [comment]
Looks as expected.
Checked on:
https://admin-new.mindlogger.org/
Win 10 Chrome 87
![2020-12-31_13-01-31.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/bc81c2f2-f478-4c85-a112-8502e9c518bd)
