### ISSUE TITLE
iOS 14.The background of the app screens is white

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1306]
**Steps to reproduce:**
1. Install and log in to the app (bughunterqa123@gmail.com // 123456)
2. Look at the screen
3. Observe the background of the applet screens
4. Select any applet (e.g. NIMH DBT)
6. Take assessments
7. Take a look at the question screens

**Actual result:** The top bar is not visible and the background is white on the app. All images/icons are not displayed on any applet
**Video:** 
https://www.screencast.com/t/o44WB2zwqB8d
https://www.screencast.com/t/iCF7peppz
![IMG_0911.PNG](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/ff916b24-1e28-4031-8468-c1c32f337040)
**Expected result:** The top bar is visible and the background is not white on the app. All images/icons are displayed on any applet screens
**Note:** On the iPhone X // iOS 13.3 looks as expected

**Environment:**
staging
MindLogger app v 0.13.27
iPhone 8 // **iOS 14**
iPhone 6s Plus // **iOS 14**

**Comment by WorldImpex** [comment]
qa'd by @jj105 as working

**Comment by sergeysemenuta** [comment]
Checked on MindLogger app v 0.14.1
The issue still reproduces
https://www.screencast.com/t/n5OPHW2jM

cc: @WorldImpex @jj105

**Comment by sergeysemenuta** [comment]
Rechecked on the MindLogger app v 0.14.3
iPhone 8 // iOS 14
The issue still reproduces
https://www.screencast.com/t/bPdaH0U0Aabw

**Comment by sergeysemenuta** [comment]
The issue is reproducible on the staging and production environments
https://www.screencast.com/t/gIvg3UtFMygh
 MindLogger app v 0.14.15 (225)
iPhone 8 // iOS 14

**Comment by sergeysemenuta** [comment]
The issue still reproduces
https://www.screencast.com/t/9x8eeBmuqO
Checked on:
MindLogger app v. 0.14.14(233)
iPhone 8 // iOS 14

**Comment by sergeysemenuta** [comment]
Fixed on ML v 0.14.18 (238)
iPhone 8 // iOS 14
![2020-12-01_15-13-16.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/35cee8d5-5b2d-4ea6-8634-a54e3ba57357)
