### ISSUE TITLE
There is no indication dot on the data screen after taking an activity

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1307]
**Steps to reproduce:**
1. Install and Log in to the app (e.g. bughunterqa123 // 123456)
2. Select the HIMH applet or any other that contains questions with radio input type
3. Take an assessment
4. Navigate to the data screen
5. Observe the result

**Actual result:** There is no indication dot on the data screen after taking an activity
![IMG_0915.PNG](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/1791f55f-5b25-42f4-98af-459d5c0ece8c)
**Expected result:** The blue indicator dot should be shown on the data screen for the items that were taken on the particular day

**Environment:**
Staging
MindLogger app v 0.13.27
Samsung Galaxy S10 // Android 9
iPhone 8 // iOS 14
Pixel 4 XL // Android 11

**Comment by sergeysemenuta** [comment]
The issue is fixed.
https://www.screencast.com/t/ycFFTFrqy
Verified on:
Staging
MindLogger app v 0.13.31
Samsung Galaxy S10 // Android 9
Pixel 4 XL // Android 11
iPhone X// iOS 13.3

**Comment by sergeysemenuta** [comment]
The issue is reproduced again on:
Staging
ML v 0.15.1
![2021-02-19_14-52-17.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/8856dbe0-071e-43e4-96bc-5fb8625c8995)
Only for sliders, the dot is shown but it is cut off
ML v 0.15.1 
Pixel 4XL//Android 11
iPhone X // iOS 13.3

**Comment by natalia-muzyka** [comment]
The issue is not reproducible anymore: https://www.screencast.com/t/wMvlyejv7rK

Environment:
ML v0.19.21 staging
Samsung Galaxy S20 // Android 11
iPhone XR // iOS 14.3
Samsung Galaxy S7 // Android 8
Samsung Galaxy Tab S6 SM-T865 // Android  9.0
iPad Pro (10,5-inch) MQDX2 // iOS 15
