### ISSUE TITLE
Increase the number of text available in Question field

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1310]
Editors are still having issues with the number of text that can fit in the question field not being enough. Can we increase it to its maximum? 

[Here are examples of text that didn't work](https://docs.google.com/spreadsheets/d/1bsxsyDsMhQNC0GHcZAb57lbfWVLh80XZnH30mnWcy1k/edit?usp=sharing)

**Comment by sergeysemenuta** [comment]
@WorldImpex 
The numbers of characters were increased up to 320  in the "Question" field
**Video:** https://www.screencast.com/t/KffmwSb2ZB
Checked on staging/prod environments
