### ISSUE TITLE
Android.The app crashes after tapping the 'About' button on the applet screen 

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1312]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ (bughunterqa123@gmail.com // 123456)
2. Navigate to the applet builder
3. Navigate to the About page modal
4. Insert an image to that page, choose the image  form the desktop, or insert the  URL and save
5. Upload the applet
6. Log in to the app
7. Select the newly created applet and tap the 'About' button on the applet screen
8. Pay attention to the result   

**Note:** The same behavior occurs after editing the about page for other applets inserting an image to the 'about applet' screen. On the ios devices works as expected.
**Video:**https://www.screencast.com/t/AWYtn1s4A
**Crash log:**
[https://app.zenhub.com/files/103405139/d37ca0a5-7d2f-420b-8249-b39e87d521f3/download](https://app.zenhub.com/files/103405139/d37ca0a5-7d2f-420b-8249-b39e87d521f3/download)

**Actual result:** The app crashes after tapping the 'About' button on the applet screen 
**Expected result:** The user should be navigated to the about page and view the content after tapping the 'About' button on the applet screen 

**Environment:**
Staging
MindLogger app v 0.13.29
MindLogger app v 0.13.27
Samsung Galaxy S10 // Android 9
Pixel 4 XL // Android 11

**Comment by Matchdev120** [comment]
@Sergey This is my screenshot on my android device
![Screenshot_20201025-203540.png](https://images.zenhubusercontent.com/5e248d759c666007f1a71211/a72f62fb-0341-4a55-8126-1cfa32f2a376)

**Comment by Matchdev120** [comment]
I added a new applet (sss) in your account (bughunterqa123@gmail.com // 123456)

**Comment by sergeysemenuta** [comment]
@Matchdev120 
The issue is not reproduced after unloading the image from the desktop. 

- The issue is reproduced after inserting the image via URL https://t3.ftcdn.net/jpg/02/89/02/18/240_F_289021817_C0dwjydbWPkU85GL5rMGpZPT5bEMycq1.jpg

Video:
https://www.screencast.com/t/pxkSk50Di2e
Environment:
Staging
MindLogger app v 0.13.31
Samsung Galaxy S10 // Android 9
Pixel 4 XL // Android 11

**Comment by sergeysemenuta** [comment]
Fixed on:
Staging
MindLogger app v 0.14.2
Samsung Galaxy S10 // Android 9
Pixel 4 XL // Android 11
https://www.screencast.com/t/J3KvlXYrbe
