### ISSUE TITLE
All items are selected after tapping the one item on the screen if options have the same title

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1313]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ (bughunterqa123@gmail.com // 123456)
2. Create an applet that contains the item with multi-select radio buttons with options that have the same title and upload it
3. Log in to the app, tap the newly uploaded applet card and navigate to the screen with multi-select radio buttons
4. Tap the first item 
5. Pay attention to the result

**Actual result:** All items are selected after tapping the one item on the screen if options have the same title
**Video:** https://www.screencast.com/t/cTBNe9XT5gcm
**Expected result:** It should be possible to select/unselect each item separately after tapping the one item on the screen if options have the same title

**Environment:**
https://admin-staging.mindlogger.org
Win 10 // Chrome Version 85
MindLogger app v 0.13.29
Samsung Galaxy S10 // Android 9
iPhone X // iOS 13.3
Pixel 4 XL // Android 11

**Comment by natalia-muzyka** [comment]
Not reproduces anymore: https://www.screencast.com/t/BmEHfV0H3m

Environment:
ML v0.19.21 staging
Samsung Galaxy S20 // Android 11
iPhone XR // iOS 14.3
Samsung Galaxy S7 // Android 8
Samsung Galaxy Tab S6 SM-T865 // Android  9.0
iPad Pro (10,5-inch) MQDX2 // iOS 15
