### ISSUE TITLE
Token values are doubled on the data  screen after editing the TokenLogger applet

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1317]
Steps to recreate:
1. Log in to the admin panel https://admin-staging.mindlogger.org/
2. Upload the TokenLogger applet
3. Log in to the app
4. Select the newly uploaded applet and take the assessment
5. Navigate to the Data screen
6. Look at the values
7. Edit the TokenLogger applet (eg. update the applet name or description) and save to the dashboard
8. Refresh the home screen on the app
9. Navigate to the data screen from step 5
10. Look at the result

**Actual result:** Token values are doubled on the data  screen after editing the TokenLogger applet
**Video**: https://www.screencast.com/t/t1vunqwMtMc
**Expected result:** Token values are not doubled on the data  screen after editing the TokenLogger applet

**Environment:**
https://admin-staging.mindlogger.org
Win 10 // Chrome Version 85
MindLogger app v 0.13.31
Samsung Galaxy S10 // Android 9
iPhone X // iOS 13.3
Pixel 4 XL // Android 11

**Comment by sergeysemenuta** [comment]
It displays incorrect values.
to reproduce:
1. Take the TL assessment
2. Observe the data screen
3. Edit The applet on admin (Change the applet name) and save
4. Take the TL assessment
5. Observe the data screen
6. Edit The applet on admin again
7. Observe the data screen

Video:https://www.screencast.com/t/JDOCs5p2OKF
https://admin-staging.mindlogger.org
Win 10 // Chrome Version 86
MindLogger app v 0.14.3
Samsung Galaxy S10 // Android 9
iPhone X // iOS 13.3
Pixel 4 XL // Android 11

**Comment by WorldImpex** [comment]
Steps to recreate:
1. Take TokenLogger assessment multiple times and record the tokens collected
2. View admin dashboard and see that the number of Tokens vs what was submitted matches
3. Check data tab on app
4. See Results

Expected: The number of tokens is the same as what is on the data tab
Actual: There are -2 tokens on the app data tab

**Comment by sergeysemenuta** [comment]
The issue is fixed
The token logger chart displays the correct values on the admin and app side
https://www.screencast.com/t/0kaFPUHtTcJG
Checked on:
Staging
MindLogger app v 0.14.5
Samsung Galaxy S10 // Android 9
iPhone X // iOS 13.3
Pixel 4 XL // Android 11
iPhone 8 // iOS 14.0
