### ISSUE TITLE
Muli-Select does not trigger the next conditional item 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1321]
Steps to recreate: 
1. Create a new applet with two multiple selection items
2. Create an condition where 1 item option drives the user to another mutli select item 
3. Take assessment on device 

Expected: 
Case 1: If the user selects the condition, then show the following question 
Case 2: If the user selects another option item that is not conditional, show the user the completion screen
Actual: The user selects any option and is shown the completion screen 

wavanauken+4@gmail.com/ abcd123 | Applet checkboxcondi (1) | iOS 13.7/ ML  0.13.31

![ezgif-6-fe157d095870.gif](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/aadf5b70-9b57-4f6a-8aa8-f4ffb99a61ef)

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/ac8ecb1b-2f0b-43d1-b30f-5db60def38f7)

**Comment by sergeysemenuta** [comment]
Works as expected according to steps
https://www.screencast.com/t/claj2Rq41
MindLogger app v 0.14.2
Samsung Galaxy S10 // Android 9
iPhone X // iOS 13.3
Pixel 4 XL // Android 11
