### ISSUE TITLE
Missing French Localization on App

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1322]
![IMG_2094.PNG](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/cbfccb05-e36a-46c2-be21-46aa6ac10b6c)
![IMG_2093.PNG](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/d6c68e24-7fd1-429e-bb19-0b1cec464a24)
![IMG_2092.jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/4d1d9b60-5c5d-4d95-bcc0-9462d5468bfe)
![IMG_2088.PNG](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/c6e8ce21-b533-47e5-9063-29c83763b3a2)
![File (1).jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/ad48406e-50f6-496a-98c3-caf2ab6647bd)
![IMG_2091 (1).PNG](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/6f5bf6fb-1136-49ae-bf28-7a9118c3ad9d)
![IMG_2090 (1).PNG](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/4c004bf1-0c21-425e-9283-89f09a8433db)
![IMG_2087 (1).PNG](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/83c773c2-faa0-4b7d-bf68-4e93768d8af0)
![IMG_2089 (1).jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/d64c53af-0790-4763-a87f-7f71ed788dc0)
![IMG_2085 (1).PNG](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/2663bfaa-83ab-4e0e-996b-b19a376aca32)
![File (2).jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/f18d76a6-8389-4aee-a637-6679e7dad290)
![IMG_2097.PNG](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/c4d42703-74b3-4d47-92f4-4b7d8af21169)

**Comment by sergeysemenuta** [comment]
Issues in the description are fixed.

Here new places where the text should be localized:
Data screen
![11.03.2020-17.16.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/472bdf8c-2f51-4a62-993b-336f0416cfd0)
Octobre/Novembre should start with a capital leter
![2020-11-03_19-15-24.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/71555fde-cc0c-4c4f-bdd7-98c083a26847)
![2020-11-03_19-21-26.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/3fd586a6-23b2-4cb4-ab31-ff00663d2fcc)
MindLogger app v 0.14.5
Samsung Galaxy S10 // Android 9
iPhone X // iOS 13.3
Pixel 4 XL // Android 11
iPhone 8 // iOS 14.0

**Comment by sergeysemenuta** [comment]
There is no translation for past due status for time stamp "Available :All Day">'Disponible : Toute la journée'
It shows - Mindlogger text -Google Sheets
![2020-11-04_11-16-48.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/70fca9d9-c8fa-4a11-a5d0-09d32dbd0cc6)
MindLogger app v 0.14.5
Samsung Galaxy S10 // Android 9
iPhone X // iOS 13.3
Pixel 4 XL // Android 11
iPhone 8 // iOS 14.0

**Comment by sergeysemenuta** [comment]
The issues that are pointed out in the last 2 comments are reproduced on MindLogger app v 0.14.14 (233)

**Comment by sergeysemenuta** [comment]
Testing is blocked by [1379](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/1379)

**Comment by sergeysemenuta** [comment]
the issues in the comment above are fixed
Checked on: 
Staging
ML v0.14.40
iPhone 8 // iOS 14
Pixel 4XL // Android 11
