### ISSUE TITLE
NIMH>Headache medication questions. There are dashes on the item "take over-the-counter medication" 

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1323]
**Steps to reproduce:**
1. Log in to the app
2. Select the NIMH applet 
3. Take the Morning questionnaire
4. Pay attention to the item 'take over the counter medication' on the “Since the last questionnaire, did you do any of the following to prevent a headache?”, “Which (if any) did you take to treat your headache?” question screens

**Actual result:** There are dashes on the item "take over-the-counter medication"  on the questions  “Since the last questionnaire, did you do any of the following to prevent a headache?”, “Which (if any) did you take to treat your headache?”
![2020-10-28_17-05-32.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/50457802-af29-4c1e-bb92-df38a9d2623f)
**Expected result:** There are no dashes on the item "take over the counter medication"  on the questions  “Since the last questionnaire, did you do any of the following to prevent a headache?”, “Which (if any) did you take to treat your headache?”

**Environment:**
Staging
MindLogger app v 0.14.1
Samsung Galaxy S10 // Android 9
iPhone X // iOS 13.3
Pixel 4 XL // Android 11

**Comment by WorldImpex** [comment]
It is in the code book so it must be as intended
