### ISSUE TITLE
Build Regression Testing Checklist for all ML Functionality 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1326]
This will be created to increase the efficiency and ease of use when regression testing the entire ML product.

**Comment by sergeysemenuta** [comment]
Checklists are created and ready to use
https://docs.google.com/spreadsheets/d/1if_tLrEtxBh1j1ID1OFiEkkLVuvPbgPM7OwZOl8ydtk/edit#gid=385535573
