### ISSUE TITLE
Localization. The button "Retourner" is cut off on the question screen

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1334]
**Steps to reproduce:**
1. Log in to the app in French (snakessqa@gmail.com // 123456)
2. Tap on any applet card
3. Tap on any activity card
4. Look at the "Retourner" button

Actual result: The button "Retourner" is cut off on the question screen
![2020-11-03_16-14-41.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/3e5eeeb4-3883-491a-aa43-730746da0870)
Expected result: The button "Retourner" should be fully visible on the question screen

**Environment:**
Staging
MindLogger app v 0.14.5
Samsung Galaxy S10 // Android 9
iPhone X // iOS 13.3
Pixel 4 XL // Android 11
iPhone 8 // iOS 14.0

**Comment by sergeysemenuta** [comment]
Testing is blocked by [1379](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/1379)

**Comment by Eugenia299** [comment]
Not reproduced on:
Win 10 // Chrome 87
MindLogger app version 0.14.40
Devices:
Samsung Galaxy J8 2018 // android 8.0
iPhone X // iOS 13.
![button.png](https://images.zenhubusercontent.com/5fe0464563e4d26035f8293f/de68a13b-678a-4030-81f8-4cc14765f5e9)
