### ISSUE TITLE
GraphoLearn Update

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1337]
Please update “did your child have any of the following technical challenges” with an extra response option “no challenges” option.

[image001.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/4793e628-00cb-4cbf-aaa6-ef05f6e67da9)

**Comment by Matchdev120** [comment]
@WorldImpex Each response option contains its own image so would you provide me an image for "no challenges"?
It should be an URL. Like this:
https://raw.githubusercontent.com/ChildMindInstitute/GraphoLearn_EMA_applet/master/images/snail.png

**Comment by sergeysemenuta** [comment]
The extra response option “No challenges” option with an image is added to the applet.
![2020-11-06_10-56-25.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/ca5a9d3e-9c7e-4a2e-b966-5b9153b9c814)
Checked on:
Production
ML 0.14.6
MindLogger app v 0.14.6
Samsung Galaxy S10 // Android 9
iPhone X // iOS 13.3
Pixel 4 XL // Android 11
