### ISSUE TITLE
Discovery: Look into App Caching & Optimizations 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1340]
Goal: Allow the local device to store 7 days of notifications nad scheduling while not impacting the user's experience loading and updating applets. 

* Also look into automatic updates of the applet so the user's device does not need to be manually refreshed. 
* Add appropriate loading UI for the user. Right now the loading shows as stopped but the visual has just timed out

**Comment by WorldImpex** [comment]
@Matchdev120 There is also a delay when user is offline with a schedule moving through the app. Please look into/ consider this when optimizing

**Comment by Matchdev120** [comment]
We've two main points to improve the mobile performance.

 First of all, we should optimize mobile app - decrease API calls and remove unnecessary functions.

 Secondly, the scheduled events and applets/activities should be optimized.
  - The events already finished don't need to be returned from back-end.
  - The unnecessary applets/activities also don't need to be returned.

 We should optimize the response data as much as possible in back-end.

**Comment by sergeysemenuta** [comment]
The main screen with applets refreshes faster

- When tapping 'done' button  and 'close' button there is a delay (about 5-10 seconds). When user stays on the activity screen and completes the same activity again in this case it works faster
Video:https://www.screencast.com/t/N9IOp4T7i
The is a delay to load the questions screen after tapping the notifications

Checked on:
Staging
ML v 0.15.1 
Pixel 4XL//Android 11
iPhone X // iOS 13.3

**Comment by sergeysemenuta** [comment]
Tapping the done button works faster

Refreshing the home screen and loading the home screen with lots of applets work slowly on android devices but faster on ios
android:https://www.screencast.com/t/N2gGd1xdjT
iOS: https://www.screencast.com/t/ETNQr9mWQ
I have 10+ applets in  the  account: janet@ss.com // 123456
api-new
ML v 0.15.11
Pixel 4XL//Android 11
iPhone X // iOS 13.3
cc: @WorldImpex

**Comment by Matchdev120** [comment]
@sergeysemenuta Actually, android devices is pretty slower than iOS devices and it's only slow at the first time even thought it is an Android device.

**Comment by sergeysemenuta** [comment]
Closing this issue for now. It works faster on the 
ML v 0.15.12
Pixel 4XL//Android 11
https://www.screencast.com/t/Xf48MI9Ph
