### ISSUE TITLE
Change itemvalue in Schema to start with 0 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1352]

**Comment by sergeysemenuta** [comment]
The item value starts with 'o' on the applets created via the applet builder in the export file

![2020-11-13_15-44-47.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/deff519f-cbe7-4ca6-ba79-a83bcdbdd8d1)
On the HIMH applet, it shows incorrect values  in the export file
![2020-11-13_16-05-59.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/6d493f43-fc3d-4cf8-b166-ce95cafa7a64)

CC: @WorldImpex

**Comment by WorldImpex** [comment]
Works as expected
