### ISSUE TITLE
TL Scores are not Registering

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1353]
Steps to recreate: 
1. Take TokenLogger Sleep assessment on owner account (wavanauken@gmail.com/ abcd123)
2. See Owner dashboard and a loading screen persists on admin
3. Go back to view users page and click the graph button without selecting a user
4. See results from step 1 
5. Click on user account
6. NO data is shown even though the user entered the data right before opening the chart

**Comment by WorldImpex** [comment]
@Matchdev120 This is for an account that has an applet from before the latest version. That applet has had a token item added to it

**Comment by WorldImpex** [comment]
@Matchdev120 This is for an account that has an applet from before the latest version. That applet has had a token item added to it

**Comment by Matchdev120** [comment]
@WorldImpex I think something goes wrong on Your account (wavanauken@gmail.com/abcd123)![Screen Shot 2020-11-16 at 8.36.52 AM.png](https://images.zenhubusercontent.com/5e248d759c666007f1a71211/9148245c-52a9-4cf3-b030-e0e2c57cb38b)

**Comment by WorldImpex** [comment]
Sorry @Matchdev120 this is for production

**Comment by Matchdev120** [comment]
@WorldImpex I tested your account on prod server and it works well.
if you click on the graph button without selecting a user, the chart shows owner's data. Like this

![Screen Shot 2020-11-16 at 8.25.52 PM.png](https://images.zenhubusercontent.com/5e248d759c666007f1a71211/fc7d1ff0-cdf4-4bfc-87c4-555bcf9b250d)


If you select user account, no data is displayed on the chart as you don't take any assessments.

**Comment by sergeysemenuta** [comment]
Checked the issue on the wavanauken@gmail.com account on production
There is no data when viewing the data selecting the user (Paul)
For the owner account, the data is shown
Checked on  another prod account using this case:
1.Edit the sleep applet
2.Go to the device and do not update it but take the assessment
3.Check TL dashboard and let me know if it shows on the dashboard
4.If not, then update on the device and retake the assessment
5.Check TL dashboard and let me know if it now shows
Works as expected the data is shown

**Comment by WorldImpex** [comment]
@Matchdev120 Here is an example of Paul taking the assessment yesterday at around 5:18 PM yesterday and it not displaying on the chart 

![Image.jpeg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/41343f25-6520-4df0-97b8-9b84fb6b9ba5)

**Comment by Matchdev120** [comment]
@WorldImpex I cannot see the issue on my side. Would you provide me the account info?

**Comment by WorldImpex** [comment]
Can you see the response data for that user? @Matchdev120  - It is a live account so we cannot get account login information

**Comment by Matchdev120** [comment]
Without login to the account, I cannot see the response data.

**Comment by WorldImpex** [comment]
I deleted Paul's account and reinvited him. Going to see if that fixes this issue

**Comment by sergeysemenuta** [comment]
@WorldImpex I see Joe's data on the dashboard. Paul has not accepted an invitation yet.

**Comment by sergeysemenuta** [comment]
Paul's data is shown up on the dashboard

**Comment by WorldImpex** [comment]
Paul was removed from the app and reinvited. The chart then worked as expected
