### ISSUE TITLE
🐆🔥 S3 Global Variable and Component

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-app#136]
In `/app/config.js`, the object keyed as `s3_images` seems to only ever be called in `/app/components/image/ImageBrowser.js` which itself seems to never be called. PR #133 leads me to believe assetstore direction can and should be handled through the API, meaning we can :fire: this parameter (and component and step in the README).

https://github.com/ChildMindInstitute/mindlogger-app/blob/e956304067ae0e4271e4a76c0b402c319f9dc421/app/config.js#L3-L6

https://github.com/ChildMindInstitute/mindlogger-app/blob/e956304067ae0e4271e4a76c0b402c319f9dc421/app/components/image/ImageBrowser.js#L46

https://github.com/ChildMindInstitute/mindlogger-app/search?q=s3_image&unscoped_q=s3_image

https://github.com/ChildMindInstitute/mindlogger-app/search?q=ImageBrowser&unscoped_q=ImageBrowser

https://github.com/ChildMindInstitute/mindlogger-app/blob/e956304067ae0e4271e4a76c0b402c319f9dc421/README.md#L17

Related #63, #133 
Maybe related #45

**Comment by binarybottle** [comment]
@shnizzedy -- Just trying to get up to date -- was this removed?
