### ISSUE TITLE
Show seconds on the activity timer on the activity card

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1373]
![2020-12-04_14-21-57.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/97464b36-88f2-42f8-98c7-63cd14151383)

**Comment by WorldImpex** [comment]
Remove seconds from admin @Matchdev120

**Comment by Eugenia299** [comment]
Fixed on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 87
![image.png](https://images.zenhubusercontent.com/5fe0464563e4d26035f8293f/0d947e19-002d-4776-b4a5-be57e926343d)
