### ISSUE TITLE
The app crashes when taking photo video using the app

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1376]
**Steps to reproduce:**
1. Log in to the app snakessqa@gmail.com // 123456
2. Tap the "DEMO" applet card
3. Navigate to the Video/Photo widgets screens
4. Take a photo and tap the "Use photo" button
5. Pay attention to the result
**Actual result:** The app crashes when taking photo /video and tapping the "Use photo" button  using the app
![2020-12-04_16-14-23.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/37de28b1-3e22-4170-b86e-8550633bc499)
**Expected result:** The app doesn't crash when taking photo/video and tapping the "Use photo" button  using the app

**Reproduced on:**
Staging
MindLogger app v 0.14.21 (241)
iPhone XR// iOS 13.2.3

**Comment by Eugenia299** [comment]
Fixed on:
Win 10 // Chrome 87
Version 0.14.5
Device:
iPhone 11 Pro Max // iOS 13.5.1
Samsung Galaxy S10 // Android 9
Video: https://www.dropbox.com/s/u42y04i98kdblrf/photo_video.MP4?dl=0
