### ISSUE TITLE
The app crashes after tapping the applet card in the French version

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1379]
**Steps to reproduce:**
1. Install the app v 0.14.22 (242)
2. Launch the app
3. Change Language to French
4. Log in (snakessqa@gmail.com // 123456)
5. Tap on any applet card
6. Look at the result
7. Launch the app again
8. Look at the result
**Note:** After these actions, the app crashes after launching as well
**Actual result:** The app crashes  after tapping the applet card in the French version
**Crash Log:**
[https://app.zenhub.com/files/103405139/2691ef92-d7cc-45a1-8dde-24f0a28f9889/download](https://app.zenhub.com/files/103405139/2691ef92-d7cc-45a1-8dde-24f0a28f9889/download)
**Video:** https://www.screencast.com/t/vWGbXYApT
**Expected result:** The app doesn't crash

**Environment:**
Staging
ML v 0.14.22 (242)
Pixel 4XL//Android 11
iPhone XR// iOS 13.2.3

**Comment by sergeysemenuta** [comment]
Reproducible on the production environment as well

**Comment by Eugenia299** [comment]
Not reproduced on:
https://admin-new.mindlogger.org/
https://admin-staging.mindlogger.org/
Win 10 // Chrome 87
MindLogger app version 0.14.40
Devices:
Samsung Galaxy J8 2018 // android 8.0
iPhone X // iOS 13.
