### ISSUE TITLE
The app crashes when tapping the resume button after tapping the notification

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1383]
**Preconditions:**
The events are scheduled on the admin panel
 The events are in progress status on the app for NIMH applet
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ snakessqa@gmail com//123456
2. Select the NIMH applet and navigate to the general calendar
3. Reschedule notifications for Pre-Assessment, Mid-day, Night, etc. events and save scheduling
4. Log in to the app as a user
5. Wait for the notification 
6. Tap on the notification
7. Tap the Resume button on the pop-up
8. Look at the result

**Actual result:** The app crashes when tapping the resume button after tapping the notification
![2020-12-08_16-12-30.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/8c6b7858-4ed8-4b18-a126-0a4d04db51cd)
**Expected result:** The user should be able to resume the activity when tapping the resume button after tapping the notification
Environment:
Staging
ML 0.14.23 (243)
Pixel 4XL//Android 11
iPhone XR// iOS 13.2.3

**Comment by Eugenia299** [comment]
Not reproduced on:
https://admin-new.mindlogger.org/
Win 10 // Chrome 87
MindLogger app version 0.14.36
Devices:
iPhone 8 // iOS 14
iPhone X // iOS 13.3
iPhone 8 Plus // iOS 13.3
Google Pixel 3a XL / Android 11
