### ISSUE TITLE
Check AND/ OR logic does not get removed when editing an applet

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1384]
1. Edit an EMA applet and see if the below OR operation fails 

In[ this activity ](https://github.com/ChildMindInstitute/NIMH_EMA_applet/blob/master/activities/day_set/day_set_schema)schema (EMA)
{
         “variableName”: “since_eaten_when”,
         “isAbout”: “since_eaten_when”,
         “isVis”: “since_eaten_amount.includes(1) || since_eaten_amount.includes(2) || since_eaten_amount.includes(3) || since_eaten_amount.includes(4)”

2. Edit a Pediatric Screener applet and see f the below AND operation fails
[In this activity](https://github.com/ChildMindInstitute/Pediatric_screener_applet/blob/master/activities/adult_report/adult_report_schema) schema (Pediatric)
            {
                “variableName”: “adult_Age”,
                “isAbout”: “adult_Age”,
                “isVis”: “adult_consent == 1 && adult_consent2 == 1"
            },

**Comment by sergeysemenuta** [comment]
Unable to edit applet name description on EMA applet. Getting upload error
https://www.screencast.com/t/Nt2qe0ignbxz
Unable to edit Pediatric Screener applet because of limitation of characters in questions field
https://www.screencast.com/t/11x8NMSquFhy
Checked on staging server

**Comment by WorldImpex** [comment]
EMA, Ped, DBT conditional logic is broken when editing with the builder.
