### ISSUE TITLE
Landscape mode. The calendar is displayed on the left side within the activity screen

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1387]
Steps to reproduce:
1. Log in to the app 
2. Rotate the device to landscape mode
3. Tap any applet card
4. Observe the screen

Actual result: The calendar is displayed on the left side within the activity screen
![2020-12-10_11-13-14.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/a7ba6482-981c-4693-ac12-4e4ad912628d)
Expected result: The calendar is displayed in full-screen width within the activity screen

Environment:
ML v 0.14.24
Pixel 4XL//Android 11
Galaxy s10/Android 9

**Comment by natalia-muzyka** [comment]
The rotation is turned off. Ticket can be closed.
