### ISSUE TITLE
Editing a DBT applet bugs 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1389]
Problems to fix: 
1. When editing a [DBT applet ](https://raw.githubusercontent.com/ChildMindInstitute/DBT_diary_applet/master/protocols/DBT_diary_card/DBT_diary_card_schema), the activity names do not match the original names and the new names have an underscore _ 
2. Conditional logic breaks when editing target behavior 

The goal is that an editor can change items in 'target behavior activity' without breaking the DBT app

**Comment by sergeysemenuta** [comment]
Testing is blocked by [582](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/582)

**Comment by sergeysemenuta** [comment]
Blocked by [593](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/593)

**Comment by sergeysemenuta** [comment]
1. Fixed
2. Failed. Updating any item breaks the conditional logic in 'target behavior activity' 
Video: https://www.screencast.com/t/0NOSXb5oOm6

Checked on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 88
ML v 0. 14. 77

**Comment by WorldImpex** [comment]
1. Activity description is required and it shouldn't be
2. The images are broken on the newly saved applet
3. Questions are broken as in they do not follow the order anymore
4. Going through the Daily Diary Card activity I got a crash
5. Events and Goals activity is completely missing  

This is not an exhaustive QA but significant

**Comment by WorldImpex** [comment]
The above have been fixed
