### ISSUE TITLE
Production - Using "Only for scheduled day" does not hide the activity on days not scheduled

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1390]
Steps to recreate: 
1. Create a scheduled activity for in the future and select "only scheduled day" 
2. Save
3. Refresh the applet 
4. See results

Expected: The activity scheduled in the future with this feature is not seen by the user until the day it is available 
Actual: Activity remains unscheduled

**Comment by Eugenia299** [comment]
Reproduced on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 87
MindLogger app version 0.14.40
Devices:
Samsung Galaxy J8 2018 // android 8.0
iPhone X // iOS 13.
![future.png](https://images.zenhubusercontent.com/5fe0464563e4d26035f8293f/d44f6ede-01e8-4bb5-a5da-4d62d26fbeb7)
![future2.png](https://images.zenhubusercontent.com/5fe0464563e4d26035f8293f/6b9033d2-c7c2-4fa6-bd18-d27c73b65f29)

**Comment by sergeysemenuta** [comment]
The issue still reproduces:https://www.screencast.com/t/EBMYbbJV4k
Checked on:
https://admin-staging.mindlogger.org/
ML v 0.14.49
Pixel 4XL//Android 11
iPhone XR // iOS 13.2.3
iPhone8 // iOS 14.0

**Comment by sergeysemenuta** [comment]
Verified on:
Staging
ML v 0.14.53
Pixel 4XL//Android 11
iPhone XR // iOS 13.2.3
iPhone8 // iOS 14.0
![2021-01-08_13-49-25.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/5767ee5a-648f-443b-a7a6-805c6f1315bd)
