### ISSUE TITLE
The new Token screens for each versions of the applet are shown up on the data screen

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1394]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ (snakessqa@gmail.com // 123456)
2. Create a TokenLogger applet and upload it
3. Log in to the app
4. Take the assessment
5. Edit the applet on admin (add some token value options)
6. Take the assessment on the app
7. Navigate to the data screen
8. Observe the screen

**Actual result:** The new Token screens for each version are shown up on the data screen
![2020-12-15_16-09-34.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/751fd76c-1161-4015-be01-7a53890051d5)
**Expected result:** The existing screen should be replaced with new changes made on the admin panel. User should see only one TokenLogger screen on the app

**Environment:**
Staging
Ml v 0.14.25 (245)
Pixel 4XL//Android 11
iPhone XR// iOS 13.2.3
Galaxy s10/Android 9

**Comment by prodev1101** [comment]
I can not reproduce this issue any more.

**Comment by sergeysemenuta** [comment]
The issue is not reproduced anymore on ML v 0.14.28 (248) // staging
