### ISSUE TITLE
The remaining timer is shown by default within  the activity  if the activity is open via notification

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1400]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ (snakessqa@gmail.com // 123456)
2. Select any applet and schedule an event with "All Day"  checkbox with the notification (Do not mark the Timed activity checkbox)
3. Log in to the app and wait for the notification
4. Open the received notification
5. Look at the result

**Actual result:** The remaining timer is shown by default within  the activity  if the activity is open via notification
**Video:** https://www.screencast.com/t/1dwnQhKK
**Expected result:** The remaining timer is not shown by default within  the activity  if the activity is open via notification

**Environment:**
Staging
ML v 0.14.26 (246)
Pixel 4XL//Android 11
iPhone XR // iOS 13.2.3
Galaxy s10 // Android 9

**Comment by Eugenia299** [comment]
Reproduced on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 87
Version  0.14.28
Devices:
iPhone 11 Pro Max // iOS 13.5.1
Pixel 4XL //Android 11
iPhone XR // iOS 13.2.3
Samsung Galaxy S10 // Android 9
![1608547187191.JPEG](https://images.zenhubusercontent.com/5fe0464563e4d26035f8293f/2719ba3a-30e1-46e9-bac1-7daac176b657)

**Comment by Eugenia299** [comment]
Fixed on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 87
MindLogger app version 0.14.31
Device:
iPhone 11 Pro Max // iOS 13.5.1
Samsung Galaxy S10 // Android 9
![time.PNG](https://images.zenhubusercontent.com/5fe0464563e4d26035f8293f/b87892c8-33dd-4eaa-8a8c-256f889d4a8b)
