### ISSUE TITLE
[REDESIGN] Data Vis Design Updates 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1405]
1. Remove black box around data viz 
![mindlogger-admin.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/537e0303-4852-405c-ae68-4255a11d56d6)
2. Move expand to left side of Activity 
3. Insert an expand all button 
![Data-Viz-Without-Scoring-Lucidchart.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/bfeb10d6-4760-4fb7-a46f-7db185d20295)
4. Move Versions in line with dates and do not show duplicate version numbers
![mindlogger-admin (1).png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/df7e9bbc-ed8e-4528-b4fb-b8937e3ad635)
5. Add Arrows between names in header 
![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/cf4ecd21-0d30-40b8-be8d-844158d9d9f0)
6. Clicking DBT Applet button should take the user back to the DBT users page 
![mindlogger-admin (2).png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/c898144d-c8e9-4df2-8ea5-fb65c83f10a8)

**Comment by sergeysemenuta** [comment]
- Missing spaces between dates button
![2020-12-30_11-37-46.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/cf8f4c01-6c58-45ba-861a-43d3704aaac2)
[EMA applet data viz]The 'SHOW VERSION CHANGES' text is shown in two lines
Expected: The 'SHOW VERSION CHANGES' text is shown in one line
![2020-12-30_11-39-14.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/86081acc-c304-4b18-86fa-401c7cd43a66)
Switching versions changes the position of the date buttons and the 'SHOW VERSION CHANGES' title
https://www.screencast.com/t/Urf8qvts

**Note:** Other changes mentioned in the ticket description  are applied and work as expected

Checked on:
https://admin-new.mindlogger.org/
Chrome 87// Win 10

**Comment by sergeysemenuta** [comment]
"Switching versions changes the position of the date buttons and the 'SHOW VERSION CHANGES' title"- this issue is still reproducible
![2020-12-31_12-15-52.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/092eaca2-92cc-443f-be36-5de504748e92)
There is no space between the 'SHOW VERSION CHANGES' title and Versions
![2020-12-31_12-18-30.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/2e22d3bc-b809-43a0-ac9b-87f9df0c1d55)
Checked on"
https://admin-new.mindlogger.org/
Win 10 // Chrome 87

**Comment by Matchdev120** [comment]
I cannot reproduce this issue.
`There is no space between the 'SHOW VERSION CHANGES' title and Versions`

**Comment by WorldImpex** [comment]
@Matchdev120 I just checked admin-staging and I can see the issue still 

![Screen Shot 2021-01-04 at 5.55.29 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/40bec21b-2d11-4239-9519-1999a2b06cde)

**Comment by Matchdev120** [comment]
@WorldImpex Would you provide me your account info?

**Comment by WorldImpex** [comment]
wavanauken+4@gmail.com/ abcd123

**Comment by sergeysemenuta** [comment]
The issue is fixed
Checked on:
https://admin-staging.mindlogger.org/
![2021-01-06_12-37-40.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/3c4b95de-f3f7-40ae-8683-53745b581cec)
