### ISSUE TITLE
[Security. IOS] The video recorded by the app are saved to the device gallery

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1412]
**Steps to reproduce:**
1. Log in to the app  (mrn@ml.com // 123456)
2. Tap the demo applet card
3. Proceed to the video widget
4. Take a video using the device camera
5. tap the "Use Video"
6. Finish the assessment
7. Check the device gallery
8. Look at the result

**Actual result:** The video recorded by the app are saved to the device gallery
**Video:** https://www.screencast.com/t/Z4XUDhuoNW
**Expected result:** The video recorded by the app are not saved to the device gallery

**Environment:** 
Staging
ML v 0.14.33 (253)
iPhone XR // iOS 13.2.3

**Comment by natalia-muzyka** [comment]
Not reproduces on
ML v0.19.21 staging
iPhone XR // iOS 14.3
iPad Pro (10,5-inch) MQDX2 // iOS 15
