### ISSUE TITLE
Offline Mode - After taking a scheduled activity, activity card shows past due

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1436]
Steps to recreate
1. Login to admin and create a new schedule (wavanauken+4@gmail.com/ abcd123) 
2. Log into a device and update applets 
3. Take device offline 
4. Wait until after the scheduled activity is available 
5. Take activity 
6. See results 

Expected: Since the activity is scheduled that day and has been completed, then the activity should not be available anymore that day 
Actual: Activity shows in past due state. Once the device goes back online then the activity is removed 

![File.jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/95874661-306a-456e-bfac-c354ac35eec3)

**Comment by sergeysemenuta** [comment]
After taking activities in Offline mode the events are disappeared
Verified on:
Staging
ML v 0.14.49
Pixel 4XL//Android 11
iPhone XR // iOS 13.2.3
