### ISSUE TITLE
[Staging]The notifications are not fired on any devices

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1442]
**Steps to reproduce:**
1. Log in to the admin panel https://web-staging.mindlogger.org/ (mikeownerml.com // 123456)
2. Schedule any event for any applet with notification
3. Log in to the app as a user (eg. set@ml.com // 123456)
4. Wait for the notification
5. Look at the result

**Actual result:** The notifications are not fired on any devices
**Expected result:**  The notifications are fired 

**Environment:**
https://admin-staging.mindlogger.org/
ML v 0.14.47
Pixel 4XL//Android 11
iPhone XR // iOS 13.2.3
iPhone8 // iOS 14.0

**Comment by sergeysemenuta** [comment]
The notifications are fired now
Rechecked on:
ML v 0.14.47
Pixel 4XL//Android 11
iPhone XR // iOS 13.2.3
iPhone8 // iOS 14.0

**Comment by sergeysemenuta** [comment]
The issue is reproduced again on ML v 0.14.77
I did not receive any notifications

**Comment by sergeysemenuta** [comment]
Still reproducible.Notifications are not fired.
Staging
ML v 0.14.80
Pixel 4XL//Android 11
iPhone XR // iOS 13.3

**Comment by sergeysemenuta** [comment]
Retested on:
Staging
ML v 0.14.80
Pixel 4XL//Android 11
iPhone XR // iOS 13.3
The issue is fixed.
![2021-02-16_11-55-57.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/3d0a3604-563d-46b2-a382-8a459a33d7a4)

**Comment by sergeysemenuta** [comment]
Notifications are down on Staging. I did not receive any notifications on:
Staging
ML v 0.15.23
Pixel 4XL//Android 11
iPhone XR // iOS 13.3

**Comment by sergeysemenuta** [comment]
Fixed on:
ML v 0.15.24
Pixel 4XL//Android 11
iPhone XR // iOS 13.3

**Comment by sergeysemenuta** [comment]
Notifications are not fired at all in staging and dev environment
ML v 0.16.24
Pixel 4XL//Android 11
iPhone XR // iOS 13.3

**Comment by natalia-muzyka** [comment]
Not reproduced
Environment:
ML v 0.16.24
Moto G5+ // Android 8.1
iPhone XR // iOS 14.3

**Comment by natalia-muzyka** [comment]
The issue is reproducible again
https://www.screencast.com/t/JlCqimIt

Environment
https://admin-staging.mindlogger.org/
ML v 0.16.34 (staging)
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0
iPhone XR // iOS 14.3

**Comment by natalia-muzyka** [comment]
Verified as fixed

Environment
https://admin-staging.mindlogger.org/
ML v 0.16.34 (staging)
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0
iPhone XR // iOS 14.3

**Comment by natalia-muzyka** [comment]
the issue is still reproducible,
video: https://www.screencast.com/t/GqqtdecW

**ML v 0.17.15 (staging)**
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0
iPhone 7 // iOS 13.1.1
owner: avani_ml@protonmail.com // 12345678
user: maddison_ml@protonmail.com // qwertyuio
applets: NIMH, Applet 1, TokenLogger School 
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
@devbtech @HarutQA 
we don't see a new build to check notifications,
on the 0.17.15 there is still the same issue 
also noticed that currently, after scheduling the activity status is displayed as "to 7:59 AM" though it was scheduled from 8:00 AM to 11:59 PM
https://www.screencast.com/t/gNRzNXo6o

**Comment by HarutQA** [comment]
Bug is still reproducible.Notifications are not fired.
Staging
https://admin-staging.mindlogger.org/#/dashboard?lang=en_US

Redmi note 9//Android Version 11
iPhone 11 Pro // iOS 13

**Comment by HarutQA** [comment]
Notifications are working correctly.
https://matter-lab.slack.com/files/U02AMARB2TD/F02CRFT4H7S/screen_recording_2021-08-23_at_19.59.44.mov

Environment:
https://admin-staging.mindlogger.org/
MacBook Chrome
Redmi note 9 // Android 11
iPhone 11 Pro // iOS 14.7.1

**Comment by natalia-muzyka** [comment]
**the issue is reproducible again,**
video: https://www.screencast.com/t/gRzzwAJ4fe

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 // Chrome 93.0.4577.63 
ML v 0.17.22 (staging)
Samsung Galaxy S7 SM-G930 // Android 8.0
iPhone 12 Pro Max // iOS 14.4
owner: avani_ml@protonmail.com // 12345678
user: maddison_ml@protonmail.com // qwertyuio
applets: subscales, Applet 1
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
verified as fixed
video: https://www.screencast.com/t/rSf4bfUqH

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 93.0.4577.63
ML v 0.17.22 (staging)
Samsung Galaxy S7 SM-G930 // Android 8.0
iPhone 12 Pro Max // iOS 14.4
owner: avani_ml@protonmail.com // 12345678
user: maddison_ml@protonmail.com // qwertyuio
applets: subscales, Applet 1, NIMH
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
Notifications aren't fired on **ML v0.17.51 (staging)**
Video: https://www.screencast.com/t/hTqtz5CCgiZ

Environment:
Samsung Galaxy S7 SM-G930 // Android 8.0
iPhone SE (2020) // iOS 14.2
owner:
josephine_ml@protonmail.com // qwertyui
applets: DBT 
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
Notifications are broken again on staging.
Video: https://www.screencast.com/t/wbCGRysskR5

Environment:
ML v0.17.76 (staging)
account owner:
kimberly_ml@protonmail.com // 12345678
applets: DBT, DBT (1), Conditionals (kimberly)
accounts:
bernard_ml@protonmail.com qwe123!!!
alyssia_ml@protonmail.com qwertyuio
loui_ml@protonmail.com 12345678
Applets password: Qwe123!!!

Devices:
Samsung S7 // Android 8.0
Samsung Tab S6 // Android 9
iPhone 6S // iOS 14.4

**Comment by natalia-muzyka** [comment]
Verified as fixed.
Video: https://www.screencast.com/t/2UUy0r6mv

Environment:
ML v0.17.76 (staging)
Devices:
Samsung S7 // Android 8.0
iPhone 6S // iOS 14.4

**Comment by natalia-muzyka** [comment]
@devbtech issue is reproducible on **ML v0.18.45** staging, ML Pilot(TF) 0.18.45 staging

Video: https://www.screencast.com/t/sD8Qo3xE1Z0

Environment:
Samsung Galaxy S7 Edge SM-G935FD // Android 8
iPhone 8 Plus // iOS 13.3
anita_ml@protonmail.com	qwe123!!!
applet name (anita)
bruce_ml@protonmail.com	12345678
notifications check
Applet password	Qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/HkpXJ8zp

Environment:
Samsung Galaxy S7 Edge SM-G935FD // Android 8
iPhone 8 Plus // iOS 13.3
anita_ml@protonmail.com qwe123!!!
tokenLogger (anita)
bruce_ml@protonmail.com 1234567
notifications check
Applet password Qwe123!!!

**Comment by natalia-muzyka** [comment]
@devbtech issue is reproducible on ML v0.18.61 staging

Video: 
https://www.screencast.com/t/AZfDj8zu7
https://www.screencast.com/t/xHFa5rqPPQ

Environment:
Samsung Galaxy S7 // Android 8
iPhone Xs Max// iOS 15.3
jeraka1732@wodeda.com	1234567890
jeligi9407@zneep.com	123456
tokenlogger, subscales, multiple

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/qNmda0eTXi

Environment:
Samsung Galaxy S7 // Android 8
iPhone Xs Max// iOS 15.3
jeraka1732@wodeda.com 1234567890
jeligi9407@zneep.com 123456
tokenlogger, subscales, multiple

**Comment by natalia-muzyka** [comment]
@devbtech notifications don't work on ML v0.19.15 staging

Video: https://www.screencast.com/t/oyLnzQHrcqt

Devices:
Samsung Galaxy S7 // Android 8
iPhone XR // iOS 14.3
owner: jeraka1732@wodeda.com	1234567890
jeligi9407@zneep.com	123456 (applets: sync test, subscales(jeraka))
Applet password	Qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/pNbsZV8sYmd

Environment:
ML v0.19.17 staging
Samsung Galaxy S7 // Android 8
iPhone XR // iOS 14.3

**Comment by natalia-muzyka** [comment]
@devbtech notifications don't work on ML v0.19.21 staging

Video: https://www.screencast.com/t/j0y0EGTaL

Devices:
Samsung Galaxy S20 // Android 11
iPhone XR // iOS 14.3
owner: jeraka1732@wodeda.com 1234567890
jeligi9407@zneep.com 123456 (applets: sync test, sync test (1), media upload test, DBT)
Applet password Qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/FJYsvLuck

Environment:
ML v0.19.23 staging
Samsung Galaxy S20 // Android 11
iPhone XR // iOS 14.3
owner: jeraka1732@wodeda.com 1234567890
jeligi9407@zneep.com 123456 (applets: sync test, sync test (1), media upload test, DBT)
Applet password Qwe123!!!

**Comment by natalia-muzyka** [comment]
@devbtech notifications are missing again. This time all the notifications are missing.

Previously scheduled notifications are failed: https://www.screencast.com/t/jWf9SyeI
New notifications are failed: https://www.screencast.com/t/yUkfxDcJYfr

Environment:
ML v0.19.24 staging
iPhone XR // iOS 14.3
Samsung Galaxy S20 // Android 11
owner: jeraka1732@wodeda.com 1234567890
jeligi9407@zneep.com 123456 (applets: sync test, sync test (1), DBT, mix applet)
Applet password Qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/yp34PRFxk

Environment:
ML v0.19.24 staging
iPhone XR // iOS 14.3
Samsung Galaxy S20 // Android 11
owner: jeraka1732@wodeda.com 1234567890
jeligi9407@zneep.com 123456 (applets: sync test, sync test (1), DBT, mix applet)
Applet password Qwe123!!!

**Comment by natalia-muzyka** [comment]
@devbtech notifications don't work on 
ML v0.20.12 staging
iPhone XR // iOS 14.3
Google Pixel 5a // Android 11

Video: https://www.screencast.com/t/AiJiX0krSl7Y

jeligi9407@zneep.com	123456
my applet web import
ml_general_acc@protonmail.com	12345678
notifications and schedule check
Applet password	Qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified as fixed:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/4d7e2293-8830-4d05-aa61-f2121746f95e)

**Comment by natalia-muzyka** [comment]
Video: https://www.screencast.com/t/ZnOejHeEnWar

Reproduces on:
ML v0.20.15 staging
Samsung Galaxy S7 // Android 8
Apple iPad 9th gen (2021) / iOS 15.5
test-user10@mail.com / 123456
DBT, EMA

**Comment by natalia-muzyka** [comment]
@devbtech 
notifications still don't work: https://www.screencast.com/t/4SCtg88rkY

Reproduces on:
ML v0.20.15 staging
Samsung Galaxy S7 // Android 8
Apple iPad 9th gen (2021) / iOS 15.5
test-user10@mail.com / 123456
DBT, EMA

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/7cg7uEb1G4Z

ML v0.20.15 staging
Samsung Galaxy S7 // Android 8
Apple iPad 9th gen (2021) / iOS 15.5
test-user10@mail.com / 123456
DBT, EMA

**Comment by MaksimYurys** [comment]
@devbtech notifications don't work on
ML v0.20.18 staging
iPhone 8// iOS 14.7.1
Samsung Galaxy S8 // Android 8

Video: https://www.dropbox.com/s/v2613ynxy913d5w/notifications.mp4?dl=0

qqtest.02@gmail.com // Qqww!123
DBT Daily Diary Card v1.06
Applet password Qqww!123

**Comment by MaksimYurys** [comment]
@devbtech Verified as fixed for Android
Samsung Galaxy S8 // Android 8

Video: https://www.dropbox.com/s/ltrxqch5lxdugj4/notifications%281%29.mp4?dl=0

@devbtech Notificftions don't work for iPhone

Video: https://www.dropbox.com/s/v2613ynxy913d5w/notifications.mp4?dl=0

ML v0.20.18 staging
iPhone 8// iOS 14.7.1
qqtest.02@gmail.com // Qqww!123
DBT Daily Diary Card v1.06
Applet password Qqww!123

**Comment by natalia-muzyka** [comment]
verified as fixed: 

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/60dc3248-5792-43d9-99c6-1b91fbf9a42d)

ML v0.21.24 staging
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
Samsung Galaxy Tab S6 SM-T865 // Android  9.0
Apple iPad 9th gen (2021) / iOS 15.5

**Comment by natalia-muzyka** [comment]
@devbtech 
the issue is reproducible again: https://www.screencast.com/t/WgfIr9Avrwp

ML v0.21.40 staging
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
user-stg@ml.com	123456
new applet
Applet password	Qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/Oog9X3Vn

ML v0.21.40 staging
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
user-stg@ml.com 123456
new applet
Applet password Qwe123!!!

**Comment by natalia-muzyka** [comment]
the issue is reproducible again: https://www.screencast.com/t/Goo6Y0fn

ML v0.21.48 staging
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
ml_general_acc@protonmail.com / 12345678
notifications and schedule check, my applet
Applet password Qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified as fixed.

ML v0.21.48 prod
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11

**Comment by natalia-muzyka** [comment]
The issue is reproducible again,
Video: https://www.screencast.com/t/bpauCc5IkZf

ML Pilot v0.21.48 staging
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
user-stg@ml.com	/ 123456
applet / activity: 
config reports v9  / Test A
test notification / 1, 1(1), 1(1)(1)
usr2-stg@ml.com	/ 123456
alerts test / a, b
applet / activity: 
Applet password: Qwe123!!!

**Comment by yzenchanka** [comment]
Verified as fixed

Environment
https://admin-staging.mindlogger.org/
ML v 0.21.48 (staging)
Samsung Galaxy S20 FE SM-G780G // Android 12
iPhone 7+ DM // iOS 14.4.1

**Comment by yzenchanka** [comment]
the issue is reproducible again,

ML v 0.21.54 (staging)
Samsung Galaxy S20 FE SM-G780G // Android 12
iPhone 7+ DM // iOS 14.4.1
account: juliyazenchenko+1@gmail.com // Ngromyko889
applets: Test Applet_4, Test Applet 2
Applet password: TestApplet4!, TestApplet2!

iPhone 13 // iOS 15.6
Google Pixel 5a // Android 11
anita_ml@protonmail.com / qwe123!!!
new applet test, dbt daily diary card v1.06
Applet password: Qwe123!!!

**Comment by yzenchanka** [comment]
Video: https://www.screencast.com/t/Pp6doZVVK2Bx
