### ISSUE TITLE
Remove Latest Score and Frequency from Response and Token Tabs 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1448]
If the applet does not contain scoring and subscales, remove the latest score/ frequency from data visualization 

![mindlogger-admin.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/eb4fd6a6-e668-41c0-880f-37517ae194e2)

**Comment by sergeysemenuta** [comment]
The latest score/ frequency is moved from the applets that do not contain  scoring and subscales
NIMH
![2021-01-06_12-42-53.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/23299c20-32c7-4261-a043-9b662727176b)

The  Frequency is not shown for the applets that contain scoring and subscales
![2021-01-06_13-36-54.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/37bfecf7-22cc-4f71-a1fa-4ccb9ad32a23)

**Environment:**
https://admin-staging.mindlogger.org/
Chrome 87

**Comment by WorldImpex** [comment]
fixed
