### ISSUE TITLE
Response Option Recorded Multiple Times is not visible 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1449]
If a user takes an assessment more then once in a day, the response options that were recorded 2+ times are not visually shown to the user

Steps to recreate
Account wavanauken+4@gmail.com/ abcd123 (Applet password Abcd1234!)
1. Log into admin
2. Go to users and select +7 and view visualization dashboard for TokenTest
3. See response tab results 

Expected: "Ate" was submitted twice by the user but you cannot tell that from the graph. It would be good to either show two overlapping dots or a bar coming from behind the circle. It might be a good idea to have a hoovering tooltip as well 
Actual: Reviewer cannot see how many times a response was recorded in one day 

[Screen Shot 2021-01-05 at 6.04.39 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/0ef19d11-d08a-4f91-9b8b-53c3b8d02413)

**Comment by WorldImpex** [comment]
The requirement is to show a tooltip for each response option dot with the number of times that response option was selected

**Comment by WorldImpex** [comment]
![Screen Shot 2021-01-07 at 5.53.19 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/8f63a391-f07b-47bd-9d1a-62f898d7cd28)

No data is displayed and visually this is very hard to read

**Comment by sergeysemenuta** [comment]
The tooltip for each response option dot with the number of times that response option is  shown
![2021-01-08_13-24-02.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/4db75811-a36d-4952-b460-e7e4771d766b)
Verified on: https://admin-staging.mindlogger.org/
