### ISSUE TITLE
Activity's Schedule is not updated when calendar is updated

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1451]
Steps to recreate:
1. Create a new schedule for an activity (wavanauken+4@gmail.com/ abcd123) 
2. Update your device to see the schedule has been created 
3. Update the calendar by deleting the event
4. Refresh the device 
5. See Results 

Expected: The event is removed from the activity on the device. 
Actual: Activity still shows a scheduled event 

In the below image, the scheduled should not be there and the item should not be greyed out since the schedule was deleted on the admin panel 

![File.jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/457fd233-d88e-4b05-b921-909eb6fd2dbe)

**Comment by sergeysemenuta** [comment]
The issue is not reproduced.
https://www.screencast.com/t/1189fpLXN
Verified on:
https://admin-staging.mindlogger.org/
ML v 0.14. 47
Pixel 4XL//Android 11
iPhone8 // iOS 14.0
