### ISSUE TITLE
The timed activity feature schedule is applied for the non-scheduled days on the app

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1453]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ (eg. mrn@ml.com  // 123456)
2. Select The NIMH applet and schedule any event (e.g. Pre-Questionaire) for the current day 
3. Schedule the event from step 2 for the next day with the timed activity option
4. Save the  scheduled activities
6. Log in to the ap and go to the activity screen 
7. Look at the result

**Actual result:** The timed activity feature schedule is applied for the non-scheduled days on the app. 
![2021-01-06_11-11-34.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/b7eba5cb-47fd-4738-9649-312a17df1ab9)
**Expected result:** The timed activity feature schedule  is applied only on the scheduled days on the app

**Environment:**
Staging
ML v 0.14.51
Pixel 4XL//Android 11
iPhone8 // iOS 14.0

**Comment by Matchdev120** [comment]
@sergeysemenuta 
Since admin-staging is down, I've tested it on admin-new but it works fine.

**Comment by WorldImpex** [comment]
Seems to be working on 0.14.52 | iPhone 6s

**Comment by sergeysemenuta** [comment]
Works as expected on ML 0.14. 53
Pixel 4XL//Android 11
iPhone8 // iOS 14.0
