### ISSUE TITLE
Time Activity Shows White Screen

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1460]
When starting an activity that has time remaining, after time expires when the user has not completed a white screen is shown 

Steps to recreate: 
1. Setup an activity with a timed activity feature
2. Update device
3. Start activity but do not complete it  
4. Wait until time has expired 
5. Navigate back to the activity
6. See Results 

Expected: User is landed back on the applet page that shows activities 
Actual: White screen is shown to the user

**Comment by sergeysemenuta** [comment]
The issue is not reproduced
https://www.screencast.com/t/bpmb6iAQJ3Ax
Verified on:
Staging
MindLogger app v 0.14.54
Pixel 4XL//Android 11
iPhone8 // iOS 14.0
Galaxy S 10 //Android 9
