### ISSUE TITLE
The user is navigated  to the start screen of the assessment after tapping the notifications from  the past days and  the app crashes when taking activity

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1463]
**Preconditions:**
The device is offline
The offline schedule with notifications is applied
Notifications are received and show on the notification list 
**Steps to reproduce:**
1. Tap the notification from yesterday 
2. Pay attention to the result
3. User is navigated to the start screen of the assessment
4. Try to complete the assessment
5. Look at the result

**Actual result:** The user is navigated to the start screen of the assessment after tapping the notifications from  the past days and the app crashes when taking the assessment
![IMG_0401.PNG](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/6011abba-9ef9-43eb-ba1f-2266a8a6207b)

**Crash log:** https://drive.google.com/file/d/1GXmEF13EqG-9bVkyqOLNJ9L8YNoQEjZL/view?usp=sharing
**Expected result:** User should see the popup - this activity was due to: XX XX XX
**Environment**:
Staging:
ML v 0.14.53
iPhone XR // iOS 13.2.3

**Comment by binaryExDev** [comment]
@WorldImpex @sergeysemenuta 
I tested this issue last 2 days. When I tapped on last day's notification, it doesn't open the current activity but if I open it manually, it works fine as expected.

**Comment by sergeysemenuta** [comment]
https://drive.google.com/file/d/1dbwWgq0u9rFTABAEpaYkewczF0uzHHxj/view

Works as expected on the ML v. 0.14.55 but when clicking the resume button the app crashes on iPhone XR // iOS 13.2.3

**Comment by sergeysemenuta** [comment]
Rechecked the issue. It is not reproduced anymore
