### ISSUE TITLE
 The activities are not open after tapping the push notifications one by one 

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1465]
**Preconditions:**
5+ events are scheduled with the notifications with different settings
Notifications are received on the device
The device in the background mode
**Steps to reproduce:**
1. Open the activities via push notification one by one
2. Look at the result
**Note:** The same behavior for one activity with multiple notifications. 
**Actual result:** The activities are not open after tapping the push notifications one by one 
**Video**:  https://www.screencast.com/t/CB5ieIo6qHLC
**Expected result:** The user should be navigated to the start screen of the assessment see the appropriate pop-pup according to the schedule. The user should be able to take the assessment via notifications

**Environment:**
MindLogger app v 0.14.54
Pixel 4XL//Android 11
Galaxy S10 // Android 9

**Comment by sergeysemenuta** [comment]
Reproduced on:
Staging
MindLogger app v 0.14.55
Pixel 4XL//Android 11
Galaxy S10 // Android 9
https://www.screencast.com/t/sVC5mRMsbD

**Comment by sergeysemenuta** [comment]
Reproducible on the  MindLogger app v 0.14.63

**Comment by sergeysemenuta** [comment]
The user is not navigated to the start screen after tapping the Push notifications
**Note:** 
The notifications are received
The device was about 15 minutes in the background mode

Once the user taps on the notification He/She is navigated to the activities screen but nothing happens. I saw only loading spinner for several seconds and after these actions, it is not possible to navigate within the app buttons do not respond

See the video: https://www.screencast.com/t/9yMeCNZc

Checked on:
Staging
Pixel 4XL//Android 11
ML v 0.14. 67

**Comment by binaryExDev** [comment]
@sergeysemenuta 
You should wait for a while after tapping 'Restart' or 'Resume' button.

**Comment by sergeysemenuta** [comment]
@binaryExDev  Did you watch the video in the comment above? I've waited enough.

**Comment by binaryExDev** [comment]
@sergeysemenuta I've watched the video but you didn't wait for a while.
Please do nothing and wait for about one min after tapping a notification. (you video is only 53 secs for tapping several notifications)

**Comment by sergeysemenuta** [comment]
I've just rechecked again.
1. Sometimes a user just not navigated to the start screen of the activity even if he waits for several minutes
2. Sometimes a huge delay of about 10-15 second to load the screen
3. Once closing the questionnaire without compleating and then trying to resume and restart the user is not navigated to the question screen
@binaryExDev Please, watch the video from the beginning to the end - https://drive.google.com/file/d/1aApT64PknDiBEFR0g1ubzIek-aN1SbZu/view?usp=drivesdk

**Comment by sergeysemenuta** [comment]
Reproducible on MindLogger app v 0.15.1
Pixel 4XL//Android 11

**Comment by sergeysemenuta** [comment]
Testing is blocked by [1701](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/1701)

**Comment by sergeysemenuta** [comment]
The issue is not reproduced on:
Staging
ML v 0.16.7
Pixel 4XL//Android 11
