### ISSUE TITLE
[TokenPrizes] When updating a TokenPrizes Applet, it sometimes does not load 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1469]
Steps to recreate: 
1. Create a TokenLogger with TokenPrizes 
2. Load it on the device 
3. Update content in the applet 
4. Refresh the device 
5. See results

Expected: The content is updated within a reasonable loading time
Actual: Sometimes the device freezes and the user has to fully exit the app and open it back up again 

Environment: iPhone 6s version 14 | MindLogger 0.14.55 

I have a video but it was to large to post to this ticket

**Comment by sergeysemenuta** [comment]
The issue is not reproducible
Checked on:
Staging
Pixel 4XL//Android 11
iPhone XR // iOS 13.0
iPhone 11 Pro Max // iOS 13.5.1
ML v 0.14. 73
