### ISSUE TITLE
Change "Survey" to "Activity" 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1471]
![File.jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/24dbb758-74af-41b9-a8aa-eec690473c69)

Update the admin panel logo to Move the CMI logo to the left of the MindLogger Logo

![mindlogger-admin (1).png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/4bdc535f-7b3b-4c37-9491-6c881fc023de)

**Comment by sergeysemenuta** [comment]
The 'Survey' is  changed to 'Activities'
 @WorldImpex In the summary is written that it should be changed to "Activity" not 'Activities'
Currently, it is named  "Activities"
![2021-01-18_11-49-04.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/3bbe8b05-59d1-4216-85c1-9fc25d87f291)
The CMI Logo is shown at the left of the MindLogger Logo on the admin panel
![2021-01-18_11-59-27.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/70b392a9-b9db-4be1-89b2-b9ac8ec419c9)

Checked on:
https://admin-staging.mindlogger.org/
ML v 0.14.67
Pixel 4XL//Android 11
