### ISSUE TITLE
Offline. The white screen is shown after the remaining time is expired.

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1480]
**Steps to reproduce:**
1. Log in to the admin panel  https://admin-staging.mindlogger.org/ (crashes@ml.com // 123456)
2. Select NIMH applet
3. Go to the  calendar and schedule an event (Night) with 'Timed activity' feature (Timed activity: 3 minutes)
4. Log in to the app
5. Tap the NIMH applet
6. Turn on the airplane mode
7. Start taking the Night assessment
8. Go to the end of the assessment
9. Wait for the expiring time
10. Look at the result

**Actual result:** The white screen is shown after the remaining time is expired.
**Video:** https://www.screencast.com/t/so87ZquY
**Expected result:** The time is up screen is shown after the remaining time is expired.

**Environment:**
Staging
MindLogger app v 0.14.58
Pixel 4XL//Android 11
iPhone XR // iOS 13.2.3
iPhone8 // iOS 14.0

**Comment by sergeysemenuta** [comment]
Reproducible on ML v 0.14.59 
https://www.screencast.com/t/fLqCd93knY
This occurs randomly but reproducibility more than 70 % on large activities

**Comment by Matchdev120** [comment]
@sergeysemenuta 
The fixes are not merged into staging so please wait for Ben to deploy the PR and check it again.

**Comment by sergeysemenuta** [comment]
I've got a crash when taking timed activity  in offline mode on Samsung Galaxy s10/Android 9 (It is reproduced randomly)
ML v 0.14.60
Crash log:
[https://app.zenhub.com/files/103405139/8b2da0eb-dccd-4ba2-9661-090fc007c382/download](https://app.zenhub.com/files/103405139/8b2da0eb-dccd-4ba2-9661-090fc007c382/download)

**Comment by sergeysemenuta** [comment]
Rechecked the issue on ML v 0.14.62 (283)
The white screen issue is not reproducible on the ios devices at all
Checked on:
iPhone 8 Plus // iOS 13.5
iPhone XR // iOS 13.2.3
The white screen issue is not reproduced on android devices as well. I've got only one crash while taking activity with the timed activity feature in Offline mode. 
Pixel 4XL//Android 11
Crash log:[https://app.zenhub.com/files/103405139/b8c8627f-223b-4ea7-bd89-15076b5ca594/download](https://app.zenhub.com/files/103405139/b8c8627f-223b-4ea7-bd89-15076b5ca594/download)

**Comment by sergeysemenuta** [comment]
Verified on:
Staging
ML 0.14.68
Pixel 4XL//Android 11
iPhone 11 Pro Max // iOS 13.5.1
