### ISSUE TITLE
Offline. The app crashes after the second attempt to complete the same event 

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1496]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ (snakessqa@gmail.com // 123456)
2.Select the NIMH applet
3. Schedule an event (Pre-Questionnaire) >Activity available All day
4. Schedule the  Pre-Questionnaire to start at 10 am
5. Schedule the  Pre-Questionnaire to start at 10: 20 am
6. Log in to the app 
7. Disable the Internet
8. Complete the Pre-Questionnaire
9. Wait until 10 am
10. Complete the Pre-Questionnaire again
11. Pay attention to the result

**Actual result:** The app crashes after the second attempt to complete the same event 
**Crash log:** https://drive.google.com/file/d/1iOL1o6HKK_ERzBVjR5PNtwgH0xUjeoJp/view?usp=sharing
![IMG_0970.PNG](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/3cd634d9-9e40-4db1-9bed-889887902c29)
**Expected result:** The app doesn't crash after the second attempt to complete the same event.

**Environment:**
**Staging:**
ML v0.14.65
iPhone8 // iOS 14.0
Pixel 4XL//Android 11
iPhone 11 Pro Max // iOS 13.5.1
Galaxy S10 // Android 9

**Comment by WorldImpex** [comment]
@sergeysemenuta Please attached a video of this happening. Please wait until after regression testing

**Comment by sergeysemenuta** [comment]
I was not able to reproduce this issue on:
Staging
ML v 0.15.17
Pixel 4XL//Android 11
iPhone X // iOS 13.3
Samsung Galaxy S8 //Android 8

Closing it out
