### ISSUE TITLE
[Prod]The white screen is shown after tapping the notification

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1510]
**Steps to reproduce:**
1. Log in to the admin panel https://admin.mindlogger.org/ (prodml@yandex.ua //123456)
2. Select the NIMH applet
3. Go to the users page
4. Schedule several events with notification and  timed activity option to available all day (On individual calendar)
5. Log in to the app as users prodml1@yandex.com//123456 and prodml2@yandex.com// 123456
6. Go to the activities screen and make sure that scheduling is applied
7. Navigate to the home screen
8. Move the app to the background
9. Wait for the notifications
10. Wait for some time (10-20 minutes)
11. Unlock the  device and tap on the notification
12. Look at the result

**Actual result:** The white screen is shown after tapping the notification
![2021-01-20_11-20-06.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/2e73adb7-89d1-48dc-a59c-04f4c4bb9583)
**Expected result:** The start screen of the activity with the remaining timer should be shown

**Environment:** 
 **ML app v 0.14.63**
Pixel 4XL//Android 11
iPhone 11 Pro Max // iOS 13.5.1

**Comment by hotavocado** [comment]
I just experienced this issue today as well!

I've had the NIMH EMA applet scheduled to go off 4 times a today for the last 1.5 weeks. Today morning was the first time I received a notification (android 11), and after I clicked it, I experienced the white screen shown above. Restarting the app and my phone did not fix this issue.

**Comment by Matchdev120** [comment]
@sergeysemenuta I'm not reproducible this issue.

This is what I did to reproduce the issue. So please correct me if something is wrong.

1. scheduled individual events with timed activity option and notifications.
2. waited for the notifications.
3. waited for about 10 mins and tapped on it.

**Comment by sergeysemenuta** [comment]
@Matchdev120 I was not able to reproduce as well

**Comment by Matchdev120** [comment]
@sergeysemenuta Would recheck this issue on the latest version again?
If it is not reproducible, we can close this ticket I think.

**Comment by sergeysemenuta** [comment]
Rechecked this issue in production. Couldn't reproduce
ML v 0.14.63 (296)
Pixel 4XL//Android 11
iPhone XR // iOS 13.2.3

Closing the ticket out.
