### ISSUE TITLE
Impossible values from NIMH EMA data export

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-app#1514]
Minji has been working with NIMH applet data and has found instances where there are impossible values recorded.

For example, for the now_pain item, 9 out of 166 assessments has the value 0, but the only possible values in the schema are 1 and 2. See below for the now_pain item schema from all 3 activities:

https://github.com/ChildMindInstitute/NIMH_EMA_applet/blob/master/activities/day_set/items/now_pain
https://github.com/ChildMindInstitute/NIMH_EMA_applet/blob/master/activities/evening_set/items/now_pain
https://github.com/ChildMindInstitute/NIMH_EMA_applet/blob/master/activities/morning_set/items/now_pain

Another question she found this issue with was morning_sleep_quality, where 1 out of 55 assessments had the value of 0, although the possible values are from 1-7.
https://github.com/ChildMindInstitute/NIMH_EMA_applet/blob/master/activities/morning_set/items/morning_sleep_quality

Maybe this is a problem with default values in data export?

**Comment by WorldImpex** [comment]
Minji will need to check this in production per Yao

**Comment by devbtech** [comment]
To clarify, FYI, the fixes can't restore recorded values in production(we can't expect what was the origin answer users submitted before) but it will make sure this will not happen again.

**Comment by WorldImpex** [comment]
Minji was asked to look out for this bug and report if she could recreate it in the future
