### ISSUE TITLE
Bold text no longer rendering on NIMH applet

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-app#1516]
Bold text is no longer rendering on the NIMH applet, see example of an item with bold text in the question:
https://github.com/ChildMindInstitute/NIMH_EMA_applet/blob/master/activities/day_set/items/now_activity

The value for the question field is "What are you doing at **this moment**?"

However "this moment" no longer shows up as bold in the app (unable to attach screenshot because of #1515)

**Comment by sergeysemenuta** [comment]
The issue is fixed:
![2021-03-04_14-22-44.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/008bb50e-97c3-44c6-83b0-516a45845c6c)
api-new
ML v 0.15.11
Pixel 4XL//Android 11
iPhone X // iOS 13.3
