### ISSUE TITLE
EMA.DBT. The app crashes when taking an activity

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1526]
**Steps to reproduce:**
1. Log in to the app snakessqa@gmail.com // 123456)
2. Take the Mid-day assessment 
3. Look at the result

Actual result: The app crashes when taking an activity
Video: https://www.screencast.com/t/WNT7Q1dp
Expected result: The app doesn't crash when taking an activity
**Note:** The same behavior for other applets from git hub that contain images in the header on the question screen 
**Environment:**
Staging
ML v.0.14.76 (298)
Pixel 4XL//Android 11
iPhone XR // iOS 13.2.3

**Comment by WorldImpex** [comment]
Still reproducible

**Comment by sergeysemenuta** [comment]
Still reproducible

**Comment by sergeysemenuta** [comment]
Fixed on:
Staging
ML v.0.14.80 
Pixel 4XL//Android 11
iPhone X // iOS 13.3
