### ISSUE TITLE
The schedule to be available all day is not applied  for the activity with the token prize feature on the device

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1529]
**Preconditions:**
The event with the token values is scheduled on the admin panel to be available 'all day'
**Steps to reproduce:**
1. Log in to the app (e.g. leo@stage.com // 123456 )
2. Tap the token applet (Token Prize Testing) with the token prizes
3. Look at the activities screen

**Actual result:** The schedule to be available all day is not applied for the activity with the token prize feature on the device. The event is not shown on the activities screen
![2021-01-28_15-25-26.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/31f661f1-4308-4735-81d6-a91e26285596)
**Expected result:** The event should be in "Past Due" status

**Environment:**
Staging
ML v 0.14.76 (298)
Pixel 4XL//Android 11
iPhone XR // iOS 13.2.3

**Comment by natalia-muzyka** [comment]
Ticket is closed due to TokenLogger changes.
