### ISSUE TITLE
Ped Screener Calculation Broken on Git

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1537]
The pediatric screener on GitHub no longer calculates a score at the end of the activity 

https://raw.githubusercontent.com/ChildMindInstitute/Pediatric_screener_applet/master/protocol/HBN_PMHS/HBN_PMHS_context

Scoring works in applet builder as expected

**Comment by natalia-muzyka** [comment]
testing is blocked by [The applet created with pediatric schema can't be edited and causes the applets in the mobile app to disappear#1818](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/1818)

**Comment by natalia-muzyka** [comment]
The summary screen still doesn't show the calculation results.

Environment:
ML v0.16.35
Moto G5+ // Android 8.1
geria2.test@gmail.com // McgzF127
Mental Health Screening Survey: English (1)
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
The calculation works now for a newly created applet:
https://www.screencast.com/t/be4EZvJFPL

Is there a possibility to check additionally does the calculation work properly within a separate cumulative item?
When I proceed to a separate cumulative item in the applet builder I don't see which screens are included for separate calculations:
https://www.screencast.com/t/fYG8sB4FmIRb

**Comment by natalia-muzyka** [comment]
As a #2 is moved to backlog, and this ticket verified as fixed
