### ISSUE TITLE
Update DatePicker for iOS/ Android 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1538]
Please update the date and timepicker to a tumbler for android and iOS like below 

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/bcfcf898-4137-4944-a047-09d6548394b3)

**Comment by sergeysemenuta** [comment]
- The date picker is not updated on ios

https://images.zenhubusercontent.com/103405139/949534fc-c55c-475f-8114-35f30b37e3ce/imip6387.mp4
The time picker is updated
On android devices works as expected
Staging
ML v 0.14.80
Pixel 4XL//Android 11
iPhone X // iOS 13.3

**Comment by sergeysemenuta** [comment]
The issue is fixed
![2021-02-22_17-04-36.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/6ed3eab6-53c8-451b-802f-0c443aa7106b)
Verified on:
Staging
ML v 0.15.2
iPhone X // iOS 13.3

**Comment by WorldImpex** [comment]
This issue is reproduced on iPhone 6s 14.4.1

**Comment by WorldImpex** [comment]
The time picker has changed. Please also check date to ensure it is the same as this ticket 

![File.jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/0cd8d7fa-a2a2-49ed-8aa4-83ffd2f0e088)

**Comment by sergeysemenuta** [comment]
The issue is fixed for the time and date pickers
![2021-04-14_11-45-31.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/782a5605-5bb7-42a1-b583-2ec22eb0838f)
Staging
ML v 0.16.7
iPhone X // iOS 13.3
Phone 7 // iOS 13.4.1
iPhone 6 S Plus//iOS 14.4

**Comment by sergeysemenuta** [comment]
The issue is reproduced again on ios 14
![2021-04-20_17-37-13.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/5eac7bff-4b31-4dcc-bd0b-37fa27b8f226)
Staging
ML v 0.16.15
iPhone 6 S Plus//iOS 14.4

**Comment by WorldImpex** [comment]
![IMG_2886.PNG](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/8d1eff4a-eb21-48e1-b55b-104249f9b130)
![IMG_2885.PNG](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/13132768-beca-4b60-b9c3-80a42cd64975)
Works as expected
