### ISSUE TITLE
Remove white space above items

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1541]
As a user, I want to not have to scroll if unnecessary so that I can more quickly move through an assessment 

If a screen does not contain a header mage, move the question to the stop of the screen as well as the response options to reduce the amount of verticle white space on each type of question 

If the screen does contain a header image, move the header image, questions and response option closer to the top of the screen

**Comment by hotavocado** [comment]
I think we should just revert back to the default auto-alignment, it looks completely fine. 
![Screen Shot 2021-03-17 at 11 05 18 AM](https://user-images.githubusercontent.com/24463939/111489897-f1bf3a80-8710-11eb-8dcd-b2d34ffb5295.png)

**Comment by WorldImpex** [comment]
This is the space that we are looking to remove 

![111489897-f1bf3a80-8710-11eb-8dcd-b2d34ffb5295-png-467×254-.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/bcc7172e-259c-4ee0-b3f3-37f399da7cba)

**Comment by sergeysemenuta** [comment]
It looks different on iOS and Android devices.

- The size of the images is different

- On iPhone 7 some images are cut off by height (DBT 5)
![IMG_1457.JPG](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/1e341a26-a155-40ff-b96c-3e1c53263047)
On applets created via builder looks as expected
![IMG_1454.JPG](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/ea899c55-d70f-458b-bbd9-e16df7548d6d)
Checked on:
Staging
ML v 0.15.26
Pixel 4XL//Android 11
iPhone 7// iOS 13.4.1

**Comment by WorldImpex** [comment]
@Matchdev120 Are image sizes changing? This version of the fix seems to have larger images which just pushes the question and response options further down on the page. That is what we are trying to avoid 

![File.jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/4100d19b-86dd-4c3a-9712-408d6ffad131)

**Comment by sergeysemenuta** [comment]
Fixed on IOS devices
![2021-04-09_18-25-43.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/a0e2f13b-50ba-4d6d-88ee-5145fce3d849)
![2021-04-09_18-29-02.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/ef6f6835-178c-4a8a-bf81-0fd67920bce8)

Staging
ML v 0.16.5
iPhone 7 // iOS 13.4.1
iPhone X // iOS 13.3

**Comment by sergeysemenuta** [comment]
Fixed on android as well
![2021-04-12_18-11-06.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/db7ab4c3-ab67-4482-bb49-5ad30e889b49)
Staging
ML v 0.16.6
Pixel 4XL//Android 11
