### ISSUE TITLE
Idle timeout is not working, affects current HBN EMA participants

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-app#1564]
In the HBN EMA protocol, we set an idle time of 2 minutes in the schedule. See below:
![Screen Shot 2021-02-22 at 5 08 47 PM](https://user-images.githubusercontent.com/24463939/108776716-bf1a8b80-7530-11eb-9a45-4f54839fd117.png)

Expected behavior: 
1. Open scheduled activity in EMA protocol
2. Do any of the following below:
      a. Leave the assessment open without touching screen for 2 minutes
      b. Hit X button on top right and wait for 2 minutes
      c. switch out of the app into home screen or another app and wait for 2 minutes
      d. exit out of the app and wait for 2 minutes
3. The applet autocompletes, MindLogger shows "Thanks! we've saved your answers!" screen.

Current behavior:
I do steps 1 and 2 above, the activity does not autocomplete. I am able to resume/restart activity.

I am using android 11.

**Comment by hotavocado** [comment]
Update: The activity still disappears from "In Progress" and becomes inaccessible after the timeout window for the activity passes, so this is not a deal breaker for HBN EMA

**Comment by sergeysemenuta** [comment]
Rechecked in production. I was not able to reproduce the issue on my accounts.
https://www.screencast.com/t/ONXT4HojS
https://www.screencast.com/t/iaKeHA74
Pixel 4XL//Android 11
iPhone X // iOS 13.3
ML v 0.14.63 (296)

**Comment by hotavocado** [comment]
@sergeysemenuta Really good to see it working on your devices!

I just tried again today and unfortunately it's not working on my device, I'm using an Oneplus 8 Pro, Oxygen OS 11 which is based on Android 11. I'm bit of an edge case here because Oneplus isn't that popular.

**Comment by WorldImpex** [comment]
Edge case based on the device
