### ISSUE TITLE
Update EMA's Conditional Logic 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1571]
Please update EMA using the **applet builder** to set up the conditional logic that is broken. You cannot update it from the refresh button or in git. So please create the conditions using the builder 

Or operation should be changed into || as it is not allowed to use in JavaScript.
You can see that the other ones are using || for Or and && for And
![Screen Shot 2021-02-25 at 9.14.50 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/61196ba1-1e31-4f3f-b889-827197d5ec94)

It’s in[ EMA/day_set Line 453](https://github.com/ChildMindInstitute/NIMH_EMA_applet/blob/master/activities/day_set/day_set_schema#L453)

**Comment by WorldImpex** [comment]
Mike will update EMA now that we are in production

**Comment by WorldImpex** [comment]
Mike tried to update but the builder froze when entering conditional logic for the 3rd activity. He refreshed and now the edit form is blank

**Comment by sergeysemenuta** [comment]
I have rechecked updating the conditional logic for EMA in staging. It works as expected. The only thing that is annoying the huge delay when switching between tabs and clicking edit icons. But functionally it works as expected. New conditions are applied correctly and work on the app. This is really poor performance for this huge applet

**Video:** https://www.screencast.com/t/N46DandTIQgk
https://admin-staging.mindlogger.org/
Staging
ML v 0.15.26
Pixel 4XL//Android 11
iPhone 7// iOS 13.4.1
