### ISSUE TITLE
Repeat activities not appearing under scheduled (affects HBN EMA users)

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-app#1572]
When I schedule the **same activity** twice on the same day, we should be able to see them both under 'Scheduled'. However, the second assessment isn't visible under scheduled until the first one is completed. This is causing a little bit of confusion for some HBN EMA end users, who believe there are only 3 assessments available per day even though 4 are scheduled. 

Pic1: The midday assessment is also scheduled for 4pm-7pm, but this isn't visible under 'scheduled'
![Image3](https://user-images.githubusercontent.com/24463939/109187731-2ec28d80-7760-11eb-99c7-672c7b27b271.jpeg)

Pic2: I took another picture after completing the 12pm midday assessment, the 4pm-7pm assessment is now available under scheduled
![Image](https://user-images.githubusercontent.com/24463939/109187874-4ef24c80-7760-11eb-8f3f-9905cd72a4ae.jpeg)

**Comment by sergeysemenuta** [comment]
This issue is reproduced
![2021-03-04_17-39-33.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/224185e0-d6c2-4085-b0e9-6abab16ca40a)
checked on:
api-new
ML v 0.15.11
Pixel 4XL//Android 11
iPhone X // iOS 13.3

**Comment by binaryExDev** [comment]
@sergeysemenuta On the screen, I can see that it works as expected.
Would you explain what goes wrong?

**Comment by hotavocado** [comment]
@binaryExDev In Sergey's example, we'd like to see 5 activities under 'scheduled' instead of 2. 3 pre-questionnaire activities at 7pm, 8pm, 9pm and 2 mid day assessments at 6pm and 9pm. That way it's immediately clear to the user how many times they need to complete an activity on that day and when they're supposed to complete it.

**Comment by sergeysemenuta** [comment]
Works as expected we can schedule one event at one day many times and they are shown in scheduled status. I raised a separate ticket related to this https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/1694

Closing this ticket out:
https://admin-staging.mindlogger.org/
Staging
ML v 0.16.2
Pixel 4XL//Android 11
iPhone 7// iOS 13.4.1
