### ISSUE TITLE
The unsuitable word wrapping for the long words on the stacked radio/checkbox/slider screens

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1583]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-new.mindlogger.org/ janet@ss.com // 123456
2. Create and upload an applet with the stacked radio/checkbox/slider items that contain long words for the option text
3.Log in to the app
4. Open the activity
5. Look at the screens

**Actual result:** The unsuitable word wrapping for the long words on the staked radio/checkbox/slider screens
![2021-03-01_18-33-57.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/932908c5-01bc-4650-855c-228d5e3c5876
Expected result: The word wrapping should be correct. All words should be clearly readable.
**Environment:**
api- new
ML v 0.15.6 
Pixel 4XL//Android 11
iPhone X // iOS 13.3

**Comment by sergeysemenuta** [comment]
The limitation of the characters was reduced for some fields but it did not solve the problem
![2021-03-03_17-26-59.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/c04312ce-4961-4c47-b32e-d72e348400e2)
api- new
ML v 0.15.10
Pixel 4XL//Android 11
iPhone X // iOS 13.3

cc: @WorldImpex

**Comment by sergeysemenuta** [comment]
The max character length has been updated to 11 for the option text. But it has not fixed the problem on the app view
![2021-03-12_15-38-48.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/4b77efee-887e-4289-b69d-b7c15c5ffdaa)
ML v 0.15.17
Pixel 4XL//Android 11
iPhone X // iOS 13.3
Samsung Galaxy S8 //Android 8

**Comment by sergeysemenuta** [comment]
I'm still experiencing the issue on stacked radio/slider  screens 

![IMG_1463.JPG](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/53781e3c-6539-4516-8269-49fbbc03e84f)
ML v 0.15.26
Staging
Pixel 4XL//Android 11
iPhone 7// iOS 13.4.1

**Comment by sergeysemenuta** [comment]
Rechecked it on :
ML v 0.16.6
iPhone X // iOS 13.3
Phone 7 // iOS 13.4.1
Pixel 4XL//Android 11
Looks as expected now
Only one minor issue discovered:
If some options have asterisks and some do not have in this case the words are not lined up
![2021-04-13_13-00-28.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/ac674335-4809-4c88-b1ee-ffd2c1f43c3b)
![2021-04-13_12-55-40.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/658ade90-cbc6-4d51-b7af-91b85c90cf08)

**Comment by WorldImpex** [comment]
Seems to size well on a iphone 6s - 0.16.20

**Comment by sergeysemenuta** [comment]
The issues are fixed
![2021-05-11_14-40-54.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/14762d0c-61fb-459a-a77d-be10de263829)
ML v 0.16.20
iPhone X // iOS 13.3
Pixel 4XL//Android 11
