### ISSUE TITLE
Advanced conditional logic is broken on the app

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1588]
**Steps to reproduce:**
1.  Log in to the admin panel https://admin-new.mindlogger.org/ janet@ss.com // 123456
2. Create an applet with advanced conditional logic 
3. Check conditional logic on the app

**Example1:** 
![2021-03-03_12-14-49.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/7e883b39-80fc-4c8f-9e55-762ceaf5882b)
**Actual:**
![2021-03-03_12-19-56.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/5e41149e-bc56-44a9-af76-2ff42ca859c6)
**Example 2:**
![2021-03-03_12-26-09.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/68d7e6ee-e821-4a10-8baf-d0a2d0888f88)
**Actual:**
![2021-03-03_12-30-15.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/739fe9bb-34ce-4047-872b-a2b4a468ac97)

**Expected:** Advanced conditional logic should work following the rules 
Api-new
ML v 0.15.9
Pixel 4XL//Android 11
iPhone X // iOS 13.3

**Comment by sergeysemenuta** [comment]
The issue is reproduced.
Api-new
ML v 0.15.11
Pixel 4XL//Android 11
iPhone X // iOS 13.3

**Comment by WorldImpex** [comment]
Reproduced on wavanauken+11@gmail.com/ abcd123

1. Set conditions for "admin" applet (Abcd1234!) 
2. Check conditions on the device
3. See results 

Expected: When a condition is met, show question 3 
Actual: When the condition is not met, question 3 is still shown 

![Screen Shot 2021-03-06 at 6.31.25 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/9ca8aa44-cb87-4578-b499-b35b65104ccf)

**Comment by sergeysemenuta** [comment]
Closing this ticket out. The case mentioned in the comment above is not a bug.
