### ISSUE TITLE
Notifications do not fire

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1609]
Notifications are not firing on admin-new 

Steps to recreate
1. Log into admin-new (wavanauken+1@gmail.com/ abcd123)
2. Set a reoccurring daily schedule for lookup applet/ activity with notification in the future
3. Navigate to the device and refresh the homepage
3. Wait until time passes
4. See results

Expected: A notification is received 
Actual: No notification is received but you can the schedule has been updated

**Comment by sergeysemenuta** [comment]
The notifications are not fired at all. 
api-new
ML v 0.15.15
Pixel 4XL//Android 11
iPhone X // iOS 13.3

**Comment by sergeysemenuta** [comment]
Rechecked the issue again
Notifications are fired
![2021-03-09_14-09-24.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/dcaf31e3-da3f-456c-bae5-963fb4581827)
api-new
ML v 0.15.15
Pixel 4XL//Android 11
iPhone X // iOS 13.3
