### ISSUE TITLE
Textbox does not have a next button

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1611]
Steps
1. Log into user account ( wavanauken+11@gmail.com/ abcd123)
2. Select an activity with a textbox response option (text applet) 
3. Add content to textbox
4. See Results

Expected: After adding content the user can go to the next screen or complete the activity
Actual: No textbox appears 

![ezgif-3-3141dddc2b76.gif](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/f58fa1a6-5110-4f18-990d-1e080c0ca6eb)

**Comment by sergeysemenuta** [comment]
The issue is fixed
Staging
ML v 0.15.17
Pixel 4XL//Android 11
iPhone X // iOS 13.3

**Comment by sergeysemenuta** [comment]
Reopening this issue again.
Staging
ML v 0.15.22
Pixel 4XL//Android 11
iPhone X // iOS 13.3
![2021-03-18_11-10-50.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/66add948-3ff2-4fa9-be51-db5883a9d23a)

**Comment by sergeysemenuta** [comment]
The issue is fixed.
![2021-03-19_10-33-03.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/82b0b13a-5ced-40fe-b609-8dc9d39becb5)
Staging
ML v 0.15.23
Pixel 4XL//Android 11
iPhone X // iOS 13.3

**Comment by sergeysemenuta** [comment]
Reopening this issue It is reproducible on Android devices. on the  iOS works as expected
Staging
ML v 0.16.17
Pixel 4XL//Android 11

**Comment by sergeysemenuta** [comment]
The issue is fixed
https://www.screencast.com/t/WOv5ojOBC5cg
Staging
ML v 0.16.18
Pixel 4XL//Android 11
