### ISSUE TITLE
The conditional logic for sliders in  the ' WITHIN' state is broken

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1629]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ snakessqa@gmail.com // 123456
2. Create an applet and set conditional logic for slider item in the  'within' state
an example of the condition:
**If** screen 1 **WITHIN** Min value **2** Max value **6**
IF **ALL** of the '**'If''** rules are matched, **SHOW** screen2
2. Check the logic on the app

**Actual result:** If the user hits 2 or 6 he is navigated to 'screen 3'
**Video:** https://www.screencast.com/t/9o5EjQyuePk6
**Expected result:** If the user hits 2,3,4,5,6, he should be navigated to screen2

**Environment:**
Staging
ML v 0.15.15
Pixel 4XL//Android 11
iPhone X // iOS 13.3

**Comment by Matchdev120** [comment]
@sergeysemenuta WITHIN 2 and 6 means 3, 4, 5, doesn't it?

**Comment by WorldImpex** [comment]
Update the text to between for within

**Comment by sergeysemenuta** [comment]
The state 'WITHIN'  is repaced with 'BETWEEN'. It solved the issue.
https://admin-staging.mindlogger.org/
ML v 0.15.17
Pixel 4XL//Android 11
iPhone X // iOS 13.3
