### ISSUE TITLE
Markdown Message Shows a Error on Required Fields 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1639]
When trying to create a markdown message, the error for required fields is shown but there isn't any other fields to fill out 

![Screen Shot 2021-03-16 at 5.18.52 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/e60d6e36-c005-4376-80d8-88a60909a078)

**Comment by sergeysemenuta** [comment]
The issue is fixed
![2021-03-18_10-05-42.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/6b7e89c4-0e2f-45df-8b77-8ea7372bb753)
https://admin-staging.mindlogger.org/
Win 10//Chrome 89
