### ISSUE TITLE
Conditional logic for the Prize activity is broken 

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1641]
**Steps to reproduce:**
1. Log in to the app as user ml2testbug@yandex.com // 123456
2. Open the 'TOKENLOGGER (Prizes)' applet
3. Tap the 'PriIzeActivity'
4. Select the first radio button
5. Click 'yes'
6. Look at the result
7. Close the activity and Tap the second radio button
8. Look at the result

**Actual result:** Conditional logic for the Prize activity is broken.
![2021-03-16_16-22-40.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/eabf2c8d-3259-4c12-940f-d96e08f23204)
**Expected result:** The user should be able to spend the Tokens separately for each response
**Note:** Reproducible only on the ios devices
**Environment:**
ML v 0.15.20

iPhone X // iOS 13.3

**Comment by sergeysemenuta** [comment]
Rechecked this issue. It is no longer reproducible.
Environment:
ML v 0.15.20

iPhone X // iOS 13.3

**Comment by WorldImpex** [comment]
Broken when trying to edit a Github created applet 

Steps to recreate
1. Upload a [GitHub TokenLogger Applet ](https://raw.githubusercontent.com/ChildMindInstitute/TokenLogger_school_applet/master/protocols/TokenLogger_school/TokenLogger_school_schema)
2. Edit Applet to add TokenPrizes 
3. Add TokenPrizes and save 
4. Check refresh and check device 
5. See Results 

Expected: User is shown the confirmation screen for the item selected 
Actual: A confirmation screen is shown for every question

**Comment by natalia-muzyka** [comment]
Ticket is closed due to TokenLogger changes.
