### ISSUE TITLE
The Skip button on TL causes the applet to crash 

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1644]
Steps to reproduce:
1. Log in to the app kai@ss.com // 123456
3. Open the activity  for TL applets from the git hub
TokenActivity assessment
Token Activity sleep
Token Activity Behavior
Token Activity School
4. Look at the screen

Actual result: The "Skip" button is displayed by default on the TL activities. The app crashes after tapping the skip button
https://www.screencast.com/t/TjoesvVs5
Expected result: The "Skip" button is  not displayed by default on the TL activities
Environment:
ML v 0.15.20
Pixel 4XL//Android 11
iPhone X // iOS 13.3

**Comment by WorldImpex** [comment]
This is intentional by the builder of those applets

**Comment by WorldImpex** [comment]
I think the skip error is due to the system not knowing where to skip to as it is the last question in the activity

**Comment by WorldImpex** [comment]
works as expected. @sergeysemenuta please test on android

**Comment by sergeysemenuta** [comment]
Checked on the ML v 0.16.2
Staging
Pixel 4XL//Android 11
Works as expected
