### ISSUE TITLE
The "Next" button is not shown up on the radio item with the Text input option enabled after selecting the first radio button

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1648]
**Steps to reproduce:**
1. Log in to the app snakessqa@gmail.com // 123456
2. Select the 'test all' applet
3. Open the activity
4. Choose the first radio button
5. Look at the result

**Actual result:** The "Next" button is not shown up on the radio item with the Text input option enabled after selecting the first radio button
https://www.screencast.com/t/vLd6eB1FY
**Expected result:** The "Next" button is shown up on the radio item with the Text input option enabled after selecting the first radio button

**Environment:**
Staging
ML v 0.15.22
Pixel 4XL//Android 11
iPhone X // iOS 13.3

**Comment by WorldImpex** [comment]
Quick fix is to hide the option. We will fix after launch

**Comment by sergeysemenuta** [comment]
The Text input option is hidden on the admin panel for all types of items
https://admin-staging.mindlogger.org/

**Comment by WorldImpex** [comment]
Works as expected
iphone 6s - 0.15.29

**Comment by sergeysemenuta** [comment]
works as expected on android ML v 0.16.2

Pixel 4XL//Android 11
