### ISSUE TITLE
Required Optional Text Box needs  a better UI/ UX experience on mobile/ builder

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1650]
- If an optional text box has been added, the textbox by default should be optional 
   - In this case, the user should not be able to fill in only the text box without selecting other options within the item screen. If the user enters some text and clicks the' next' button She/He would see some validation message.
   - If the user selects to make it required then the user must make a selection on the item type and enter text into the textbox field. The item's 'skippable' option should be greyed out and the user should not be able to select it. Put ghost text into the textbox that says "This is a required field." 
   - If the user selects skippable for the item, then the required field should be greyed out
- Make this textbox the as the one created in [1604](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/1604)

**Comment by sergeysemenuta** [comment]
Case 1:
If an optional text box has been added, the textbox by default should be optional. In this case, the user should not be able to fill in only the text box without selecting other options within the item screen. If the user enters some text and clicks the' next' button She/He would see some validation message.

**Comment by sergeysemenuta** [comment]
This is implemented a little bit different:
1. If an optional text box has been added, the textbox by default is optional

- The 'Next' button is shown only after selecting the option (radio, checkbox e.g) and then the user is able to navigate to the next screen

2. If the text box is required:

- The text box filed has the placeholder text: This is a required field.

- The  "Next" button shows up after making a selection and entering the text into the textbox


Video: https://www.screencast.com/t/miEKNSF6jox8
Staging
ML v 0.16.7
iPhone X // iOS 13.3
Phone 7 // iOS 13.4.1
iPhone 6 S Plus//iOS 14.4

**Comment by WorldImpex** [comment]
Implementation works and this can be closed

**Comment by sergeysemenuta** [comment]
Closing this issue as per the comment above. 
Rechecked on ML v 0.16.7. Works as expected.
iPhone X // iOS 13.3
Phone 7 // iOS 13.4.1
Pixel 4XL//Android 11
