### ISSUE TITLE
SubScale Age Question should be Numerical Keyboard 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1663]
By default we should show the numerical keyboard for the age question

**Comment by sergeysemenuta** [comment]
The regular keyboard is shown on the age screen
![2021-04-06_11-16-27.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/79d4fec3-f4b4-4f6f-a347-4ea99c3a47f4)
Staging
**ML v 0.16.3**
iPhone X // iOS 13.3
iPhone 7// iOS 13.4.1

**Comment by sergeysemenuta** [comment]
Rechecked on new applets. The issue is fixed
![2021-04-06_11-44-21.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/9c58c6af-01b9-47cc-951e-407c0fcf65ff)
Staging
ML v 0.16.3
iPhone X // iOS 13.3
iPhone 7// iOS 13.4.1
