### ISSUE TITLE
Pediatric Screener. The "Next" button is missing on the age screens

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1667]
**Steps to reproduce:**
1. Log in to the app prodml@yandex.ua // 123456
2. Open the Pediatric Screener applet
3. Open any activity
4. Navigate to the age screen
5. Select the age
6. Pay attention to the screen

Actual result: The "Next" button is missing on the age screens
![2021-03-24_15-57-33.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/f8198685-a21d-4b45-a304-239161530bd0)
Expected result: The "Next" button shows up after selecting the age
Environment:
Prod
ML v 0.15.25
Pixel 4XL//Android 11
iPhone X // iOS 13.3

**Comment by natalia-muzyka** [comment]
@devbtech is this a new schema for pediatric screener which I need to test?
https://raw.githubusercontent.com/ChildMindInstitute/Pediatric_screener_applet/master/protocol/HBN_PMHS/HBN_PMHS_context
from [here](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/1537)

the old schema isn't applicable now, right?
https://raw.githubusercontent.com/ChildMindInstitute/Pediatric_screener_applet/master/protocol/HBN_PMHS/HBN_PMHS_schema

**Comment by WorldImpex** [comment]
@natalia-muzyka - This is the correct URL 

https://raw.githubusercontent.com/ChildMindInstitute/Pediatric_screener_applet/master/protocol/HBN_PMHS/HBN_PMHS_schema

**Comment by natalia-muzyka** [comment]
@devbtech testing is blocked by [The applet created with pediatric schema can't be edited and causes the applets in the mobile app to disappear#1818](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/1818)

**Comment by natalia-muzyka** [comment]
The issue is still reproducible
https://www.screencast.com/t/3hZdc4NZk8X3

ML v0.16.28 (staging)
iPhone XR // iOS 14.3 
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0

**Comment by natalia-muzyka** [comment]
Not reproducible on:
ML v0.16.29 (staging)
iPhone XR // iOS 14.3 // Safari
https://www.screencast.com/t/28RFAAhEC

Waiting for a new build for Android.
