### ISSUE TITLE
[Prod] iOS. The push notifications do not have the activity names

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1668]
**Preconditions:** 
The activities are scheduled with notifications
Steps to reproduce:
1.Log in to the app 
2. Wait for the notifications
3. Pay attention to received push notifications

**Actual result:** The push notifications do not have the activity names. There is text ''Push Notification" instead of the activity name
![2021-03-24_16-17-50.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/49016323-7d5f-408a-b32e-75f34254e659)
**Expected result:** The push notifications should have the activity names
**Note:** Reproducible only on  iPhone X // iOS 13.3
**Environment:**
Prod
ML v 0.15.25
iPhone X // iOS 13.3

**Comment by sergeysemenuta** [comment]
This issue is reproduced only on iPhone X // iOS 13.3
I rechecked on:
iPhone 8 // iOS14.4 and it works as expected

**Comment by WorldImpex** [comment]
@sergeysemenuta Could you double check the settings? https://matter-lab.slack.com/archives/CRALZK8K0/p1617282844052700

**Comment by sergeysemenuta** [comment]
The issue is no longer reproducible. I did not touch the notification settings
![2021-04-05_10-37-33.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/5c18a1af-07d3-46e4-b8b7-b3fa9a604003)
iPhone X // iOS 13.3
Staging
ML v 0.16.2
