### ISSUE TITLE
Notifications not working for some users

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-app#1670]
Push Notifications are not working for a user in the clinician pilot study:
she has iPhone 7 and IOS is 14.4.1, and has double checked allow notifications for the app

Push Notifications have not been working for me for several weeks now, they still don't work after I updated app to most recent version 0.15.25. In the past I would receive notifications on some days but not others. However I can always get the red dot indicator on the top right corner.
I have a OnePlus 8 pro, Android 11

Paul Mitrani told me he hasn't been receiving push notifications.

I've also heard some participants from the HBN study haven't been receiving push notifications. 

I know push notifications are pretty fickle depending on the user device/settings etc, but can we double check to see that they are at least working on our QA devices?

**Comment by sergeysemenuta** [comment]
I have rechecked it on my side on the following devices in production accounts (General schedule):
**Pixel 4XL//Android 11**-  (was logged in as : prodml1@yandex.com // 123456)
Did not receive for  'Pre-Questionnaire'  and received for other EMA's activities
Did not receive some events for the applet created via the builder
![2021-03-25_10-24-50.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/050dbc68-a989-4131-ac3e-81ab67567835)
**iPhone X // iOS 13.3**-  (was logged in as : prodml2@yandex.com // 123456)
In the background, mode notifications did not fire when click on it some notifications are fired but the rest of them are not fired
![2021-03-25_10-27-45.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/8cc32711-9113-4ae6-88d5-047d9e4a0184)

**iPhone 7 // iOS 13.4.1** -  (was logged in as : prodml3@yandex.com // 123456)
Received all the notifications
![2021-03-25_10-19-04.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/6fbec5d8-1983-44a1-a9d5-a1dad57d809b)

**Owner account:** prodml@yandex.ua // 123456
https://admin.mindlogger.org/
Applet passwords: Qwe123!!!
Applets: HIMH, Check notifications

**Comment by sergeysemenuta** [comment]
This issue is reproduced on staging today. Some notifications are not fired in 3 cases:
1. Schedule events one time with notifications
2. Schedule one event to fire several times
3. Schedule events to fire at the same time.
ML v 0.15.26
Pixel 4XL//Android 11
iPhone 7// iOS 13.4.1

**Comment by WorldImpex** [comment]
@sergeysemenuta Could you double check [this](https://matter-lab.slack.com/archives/CRALZK8K0/p1617282844052700)?

**Comment by WorldImpex** [comment]
I am still experiencing a 7 minute delay on notifications on production account 15.25

**Comment by sergeysemenuta** [comment]
Rechecked notifications on staging
Case 1:
The event is scheduled to notify 5 times at the same time for example Start time: 10AM
Actual result: Ony 1 notification is received
Expected: 5 notifications are received
Case 2 :
The event is scheduled to notify in the range of times for example Star time: 10 am, 10:01 AM, 10:02 AM, 10:03,10:04,10:05 AM) 
Actual result: Received a couple of notifications. Some notifications had not been recieved
Expected: 5 notifications are received.
ML v 0.16.3 
ML v 0.16.2
iPhone X // iOS 13.3
Pixel 4XL//Android 11
iPhone 7// iOS 13.4.1
Xiaomi RedmiNote 8 Pro // Android 11
