### ISSUE TITLE
The questions text is not displayed on the data screen

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1672]
**Steps to reproduce:**
1. Log in to the app mrodml@yandex.com // 123456
2. Select an applet created via the builder that has radio checkbox and slider questions (e.g. Test applet)
3. Take an assessment and navigate to the data screen
4. Look at the result
**Note**: This issue is not reproduced for HIMH and DBT applets. Reproducible in staging as well
**Actual result:** The questions text is not displayed on the data screen
![2021-03-25_15-41-30.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/f5bfd8ff-4fff-4659-ac13-122b729533f0)
**Expected result:** The questions text is displayed on the data screen

**Environment:**
Staging
Production
ML v 0.15.25
Pixel 4XL//Android 11
iPhone X // iOS 13.3

**Comment by WorldImpex** [comment]
Works on iPhone - Please check android @sergeysemenuta

**Comment by sergeysemenuta** [comment]
Works on iPhone and Android devices. The questions are displayed
Checked on:
ML v 0.16.2
Pixel 4XL//Android 11
iPhone 7// iOS 13.4.1
