### ISSUE TITLE
Applet created in applet builder doesn't appear in the app after refreshing

### ISSUE THREAD

**Issue by charlie42** [ChildMindInstitute/mindlogger-app#1677]
Steps to reproduce:

1. Create an applet through applet builder
2. Open the app
3. Pull the screen down to refresh 
4. Navigate away from ML 
5. See Results 

Expected: The new applet is added to the list 
Actual: The list does not update and sometimes the lazy loader stops spinning like it is frozen 

Deleting and reinstalling the app from testflight fixes the issue

iOS, ML version 0.15.25 (328)

**Comment by anirudh4792** [comment]
Same issue for me (android, latest March 25 version downloaded). 

1. To check, invites were sent for a survey to 4 of my different emails.
2. I accepted them all. In one, the app takes 3 minutes to load (same experience for another person) but eventually the applet appears. This is an old account (first ML account). 
3. Applets do not load for any of the other emails

**Comment by WorldImpex** [comment]
Resolved with a QA session
