### ISSUE TITLE
The app crashes after selecting a radio button

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1678]
**Preconditions:**
The applet with alert is created and uploaded to the dashboard ("Alert" Applet)
**Steps to reproduce:**
1. Log in to the app snakessqa@gmail.com // 123456
2. Open the "Alert"  applet
3. Tap on the first radio button
4. Pay attention to the result:

**Actual result:** The app crashes after selecting a radio button
![2021-03-30_10-36-28.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/b8b0003e-100d-42f5-9599-622ca4ff3227)
**Expected result:** The app doesn't crash after selecting a radio button

**Environment:**
Staging
ML v 0.15.26
Pixel 4XL//Android 11
iPhone 7// iOS 13.4.1

**Comment by WorldImpex** [comment]
works as expected
