### ISSUE TITLE
Scheduling an event in the future should remove any unscheduled event

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1686]
Steps to recreate
1. Log into admin-staging (wavanauken+11@gmail.com/ abcd123) 
2. Create a group schedule for EMA 
3. Set an event to happen for an activity in the future (tomorrow) 
4. Save event and refresh device 
5. See results

Expected: The event does not show up under unscheduled anymore because it is scheduled in the future. The event should not show up again on the user's device unless it is scheduled 
Actual: Event still shows as scheduled 

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/f7cfb4f4-3b33-47b2-81f0-19b6a3a0c1e0)

**Comment by sergeysemenuta** [comment]
This issue is reproducible
The events are shown in the  unscheduled status after scheduling them in the future
https://www.screencast.com/t/k5M1b3KSZ
Staging
ML v 0.16.5
iPhone X // iOS 13.3

cc: @WorldImpex

**Comment by sergeysemenuta** [comment]
Reproducible on 
Staging
ML v 0.16.6
iPhone X // iOS 13.3
Pixel 4XL//Android 11
![2021-04-12_16-35-55.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/741d0228-25af-410e-84b8-3dbbca051466)

**Comment by sergeysemenuta** [comment]
The issue is fixed.
Works as expected.
https://www.screencast.com/t/LWA3tBe02tj
Staging
ML v 0.16.8
iPhone X // iOS 13.3
Phone 7 // iOS 13.4.1
Pixel 4XL//Android 11
iPhone 6 S Plus//iOS 14.4
