### ISSUE TITLE
Message does not make sense to user

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1687]
Steps to recreate: 
1. Login to admin-staging (wavanauken+11@gmail.com/ abcdd123) 
2. Set a schedule
3. Set the start and end time to be the same
4. See results

Expected: Error message that says something like "You cannot schedule an activity with the same start and stop time 
Actual: Error message doesn't make sense 

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/7e8f6adb-52ce-4a23-b051-d27bf3ab9301)

**Comment by Matchdev120** [comment]
@sergeysemenuta The Pr is not deployed yet - https://github.com/ChildMindInstitute/mindlogger-admin/pull/908

**Comment by sergeysemenuta** [comment]
The issue is fixed.
![2021-04-09_11-41-03.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/dadd90fa-123f-463c-9395-c1c4b4b721c7)
Verified on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 89
