### ISSUE TITLE
One-time complete does not function

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1691]
Steps to recreate
1. Log in to admin-staging (wavanauken+11@gmaill.com/ abcd123)
2. Create an event for DBT 
3. Turn on one time completion feature
4. Save it on admin 
5. Refresh the device 
6. Complete the same activity
7. See results

Expected: After completing the activity, it will never show up on the user's device anymore unless the scheduled event is deleted
Actual: Activity is still present

**Comment by sergeysemenuta** [comment]
The issue is fixed. 
Staging
ML v 0.16.4
iPhone X // iOS 13.3
Pixel 4XL//Android 11
https://www.screencast.com/t/Qxnxn1JSwxp
