### ISSUE TITLE
UI/ UX of Calendar 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1692]
1. Always available should be turned on by default 
2. The default end time should be 11:59 PM 
![Screen Shot 2021-03-31 at 5.46.01 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/b5ff902c-262e-4391-9c6f-d5a85af97dd4)
3. When turning off "always available the user should see the below. If the event is schedule for that day with any or none of the features here, the activity should only show up for that event and nothing in the present or future 
![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/2688d0b8-0078-4426-b32c-01424b0e4a85)
4. Idle timer and Timer should be able to be actioned at the same time

**Comment by sergeysemenuta** [comment]
Checked on staging
https://admin-staging.mindlogger.org/

1. -fixed
![2021-04-07_17-47-28.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/2ccff993-2c79-4d77-b69a-7e2a1caaa896)
2. Fixed
![2021-04-07_17-48-55.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/222e7a9a-ac73-4593-b65e-a102cce64c84)

4. **Failed**.Idle timer and Timer should be able to be actioned at the same time. Currently, it is not possible to use timer and idle time at the same time
![2021-04-07_17-53-42.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/08e42d6d-138c-44a2-8a10-6d2d229b8059)

**Comment by sergeysemenuta** [comment]
The issue is fixed.
![2021-04-09_11-14-21.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/fd1e6263-ef23-4f01-b72b-e3c2cc54e073)
Verified on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 89
