### ISSUE TITLE
Alert Emails are not Received

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1714]
Steps to recreat
1. Log into admin-staging (wavanauken+11@gmail.com/ abcd123)
2. Creat an applet (alert 2) with an alert 
3. Login device (iPhone 6s 0.16.5) 
4. Take assessment 
5. See results 

Expected: There is a notification on admin and an email sent 
Actual: Only a notification on admin. No email is received

**Comment by sergeysemenuta** [comment]
Rechecked this issue on the  old and new applets
The last successful email was recieved on my account 4 hours ago
Currently, emails are not sent

**Comment by sergeysemenuta** [comment]
Rechecked the issue  again using a user role only
If responses were submitted by the user role the emails are sent
![2021-04-12_18-48-30.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/450eaca5-4ce3-4033-9f93-da09d97058c8)

**Comment by WorldImpex** [comment]
This is by design. Only a user's account will trigger an email
