### ISSUE TITLE
There is a huge delay opening the Activities via notifications

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1722]
Steps to reproduce:
1. Schedule events on any applet with notifications https://admin-staging.mindlogger.org/ snakessqa@gmail.com // 123456
2. Log in to the app and wait for the notifications
3. Tap on the notification
4. Look at the result
Actual result: There is a huge delay opening the Activities via notifications. About 3-5 seconds and sometimes even more
Expected result: The activities si opened immediately after tapping the notification
Environment:
ML v 0.16.7
iPhone X // iOS 13.3
Phone 7 // iOS 13.4.1
Pixel 4XL//Android 11

**Comment by sergeysemenuta** [comment]
Video: https://www.screencast.com/t/8Ipxr0APcqs
Applet has 8 activities
Owner account: logan@ss.com // 123456
Applet Name: Test notifications
Applet password: Qwe123!!!
 Checked on:
ML v 0.16.7
iPhone X // iOS 13.3
Phone 7 // iOS 13.4.1
Pixel 4XL//Android 11
iPhone 6 S Plus//iOS 14.4

**Comment by WorldImpex** [comment]
This should be resolved in 772
