### ISSUE TITLE
Notifications are not fired if the notifications are set before the scheduled time

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1723]
Steps to reproduce:
1. Schedule events to be available to  take in the future on the current day  and set notifications before scheduled time https://admin-staging.mindlogger.org/ snakessqa@gmail.com // 123456
2. Log in to the app and wait for the notifications
3. Look at the result

Actual result: Notifications are not fired if the notifications are set before the scheduled time
Expected result:  Notifications are  fired if the notifications are set before the scheduled time

Environment:
Staging
ML v 0.16.7
iPhone X // iOS 13.3
Phone 7 // iOS 13.4.1
Pixel 4XL//Android 11

**Comment by jj105** [comment]
@sergeysemenuta I tested it on my local device but it works fine.

on my side, the only case I don't receive notification is when I already completed activity that day.

**Comment by sergeysemenuta** [comment]
Rechecked again. The issue is not reproduced anymore on staging. Notifications are fired
Environment:
Staging
ML v 0.16.7
iPhone X // iOS 13.3
Phone 7 // iOS 13.4.1
Pixel 4XL//Android 11
