### ISSUE TITLE
Tapping Notification for an activity that has already been started shows wrong error message

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1731]
Steps to recreate
1. Create a schedule for an activity (wavanauken+1@gmail.com/ abcd123) - Activity is scheduled to be available now with a notification in 2 minutes
2. Log into device/ fresh the schedule 
3. Start assessment 
4. Navigate away from Mindlogger and wait for notification to appear 
5. Notification received and clicked on 
6. See Results

Expected: User is able to restart or continue activity 
Actual: User is shown a message that the activity cannot be started yet 

![IMG_2823.PNG](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/87b45615-7db7-4c55-aa78-197663887b8e)

**Comment by sergeysemenuta** [comment]
The issue is fixed.
![2021-04-16_14-53-44.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/bde75239-7d91-4310-bb26-8c237bb400fa)
Staging
ML v 0.16.13
iPhone X // iOS 13.3
Phone 7 // iOS 13.4.1
Pixel 4XL//Android 11
