### ISSUE TITLE
Always Available Notifications do not work

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1732]
Steps to recreate 
1. Setup a schedule with an activity always available with a notification in the future
2. Refresh device and wait for notification 
3. When notification is received, click on the notification 
4. See results 

Expected: User is navigated to start the assessment 
Actual: User clicks notification and received an message that he/she cannot start assessment 

https://www.screencast.com/t/t4lkGTuicP

**Comment by sergeysemenuta** [comment]
Works as expected 
Checked on:
Staging
ML v 0.16.13
iPhone X // iOS 13.3
Phone 7 // iOS 13.4.1
Pixel 4XL//Android 11
