### ISSUE TITLE
Test Low Battery Functionality 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1739]

**Comment by sergeysemenuta** [comment]
I tested the application with 1-3% of the battery charge. In the Ema applet, when performing actions, I found poor performance during its execution.
Video: https://www.screencast.com/t/oFphqDVKJXY
Staging
ML v 0.16.15
iPhone X // iOS 13.3

Note: After powering off/on the device notifications are stored in the notifications list 

cc: @WorldImpex
