### ISSUE TITLE
Token Frequency is hard to read

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1741]
Please make it easier to read the graph

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/6352dbc5-8a19-4372-a0cd-f9891b1eacdd)

**Comment by Matchdev120** [comment]
@WorldImpex This is what I can see on my end.

[Uploading... Screen Shot 2021-04-18 at 11.58.59 PM.png]

**Comment by sergeysemenuta** [comment]
@Matchdev120 The different sizes for charts with radio items and checkbox items. And the line is gone outside of the graph

![2021-04-19_10-59-43.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/50b75c56-6c8c-4edd-aa64-87771590583c)

https://admin-staging.mindlogger.org/
Win 10 // Chrome 90

**Comment by sergeysemenuta** [comment]
The issue is fixed.
Video:
https://www.screencast.com/t/yuT2WMi4GAV
Checked on:
https://admin-staging.mindlogger.org/
Win 10  // Chrome 90

**Comment by sergeysemenuta** [comment]
The issue is fixed.
Video:
https://www.screencast.com/t/yuT2WMi4GAV
Checked on:
https://admin-staging.mindlogger.org/
Win 10  // Chrome 90

**Comment by sergeysemenuta** [comment]
The issue is fixed.
Video:
https://www.screencast.com/t/yuT2WMi4GAV
Checked on:
https://admin-staging.mindlogger.org/
Win 10  // Chrome 90
