### ISSUE TITLE
Update "Past Due" on mobile with "Available" 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1749]
![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/1ea3120c-1e0d-4226-be4d-a57d52773d02)

**Comment by sergeysemenuta** [comment]
The status is updated.

![2021-04-30_17-34-41.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/df948146-031d-4622-a614-c4117293a913)
Staging
ML v 0.16.19
iPhone X // iOS 13.3
Pixel 4XL//Android 11
