### ISSUE TITLE
Update time widget for 12 AM/ PM to "Noon" or "Midnight" 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1750]
![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/a4072348-6f29-4410-aaf6-a6f88aaf0f56)

**Comment by WorldImpex** [comment]
still reproducible 

![File.jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/57b985dd-6b38-4725-8bfc-a45b0694ab5c)

**Comment by WorldImpex** [comment]
Noon works as expected. 11:59 PM still shows as the time. Expected: "Midnight"

**Comment by sergeysemenuta** [comment]
Fixed on:
ML v 0.16.21
iPhone X // iOS 13.3
Pixel 4XL//Android 11
![2021-05-12_15-45-59.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/9c275f8f-b430-44be-a86e-76ca969d2336)
