### ISSUE TITLE
The schedule with the Always Available feature is not applied on the device

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1751]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ snakessqa@gmail.com // 123456
2. Select any applet and navigate to the calendar
3. Schedule an event with the  'Always Available' feature and save  (The toggle button 'Always Available' is turned on )
4. Log in to the app select the applet from step 2 and look at the result

**Actual result:** The schedule with the  Always Available feature is not applied on the device. The event is in "Unscheduled" status
_Video:_ https://www.screencast.com/t/w51oxKQInh
**Expected result:** The event should be in 'Past Due' ("Available") status 
Environment:
Staging
ML v 0.16.15
iPhone X // iOS 13.3
Phone 7 // iOS 13.4.1
Pixel 4XL//Android 11

**Comment by sergeysemenuta** [comment]
Reproducible on the  ML v 0.16.17 as well

**Comment by natalia-muzyka** [comment]
Reproducible on the ML v 0.16.28 as well
https://www.screencast.com/t/HnopUutzTkQ

iPhone XR // iOS 14.3 
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0

**Comment by natalia-muzyka** [comment]
Reproducible on the ML v 0.17.13 as well
https://www.screencast.com/t/enkVvtW3K

iPhone 7 // iOS 13.1.1
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0

**Comment by HarutQA** [comment]
Fixed, works correctly.

Redmi Note 9, Android 11
iPhone 11 Pro, iOS 14.7.1
