### ISSUE TITLE
Updating an existing applet causes all applets to disappear from the app

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1753]
Steps to reproduce:
1. Log in to the account that has several applets on the admin panel https://admin-staging.mindlogger.org/bughunterqa123@gmail.com // 123456
2. Log in to the app
3. Edit any applet on the dashboard and save updates (add new items to the activity, mark skippable optionsб update the activity name, etc.)
4. Refresh the home screen on the app
5. Logout and login again to the app
6. Look at the result

Actual result: Updating an existing applet causes all applets to disappear from the app. There are no applets on the app
![2021-04-28_10-36-13.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/8098e16f-fed5-4bfc-96b9-09b8499919f2)
Expected result: All applets are show and new updates are applied to the edited applet

Environment:
Staging
ML v 0.16.17
iPhone X // iOS 13.3
Phone 7 // iOS 13.4.1
Pixel 4XL//Android 11

**Comment by WorldImpex** [comment]
fixed on 0.16.19

**Comment by sergeysemenuta** [comment]
Works as expected.
ML v 0.16.20
iPhone X // iOS 13.3
Pixel 4XL//Android 11
