### ISSUE TITLE
Unable to take the activity via notification with the access before scheduled time option enabled

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1754]
Preconditions:
-The Night event is scheduled: Begins at 10 pm, ends at 11:59 pm
-Notification is set: Start time  at 11 AM
Steps to reproduce:
1. Log in to the app 
2. Wait for the notification (The notification is fired at 11 AM)
3. Tap on it
4. Look at the result

Actual result: Unable to take the activity via notification with the access before scheduled time option enabled. The popup' This activity was due at ...' is shown
![2021-04-28_11-24-17.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/18e76609-856f-41e4-b8a6-1548e432e3d7)
Expected result: The user should be able to navigate to the first screen of the assessment

Environment:
Staging
ML v 0.16.17
iPhone X // iOS 13.3
Phone 7 // iOS 13.4.1
Pixel 4XL//Android 11

**Comment by natalia-muzyka** [comment]
The issue is not reproducible anymore: https://www.screencast.com/t/fJauvHsf6IpP

Environment:
ML v0.21.52 staging
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
