### ISSUE TITLE
There is a huge delay updating the password on the "Change Password" screen

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1755]
Steps to reproduce:
1. Log in to the app as  a user
2. Tap the human icon
3. Tap the 'Change Password' item
4. Specify the current password and new password
5. Tap the "Update" button
6. Pay attention to the result:

Actual result:  There is a huge delay updating the password on the "Change Password" screen. It takes about 40 seconds to update and the Update title is disappeared from the Button once taps on it
Video: https://www.screencast.com/t/a4Xs66ESZ
Expected result: The password should be updated immediately after tapping the "Update" button on the "Change Password" screen

Environment:
ML v 0.16.17
iPhone X // iOS 13.3
Phone 7 // iOS 13.4.1
Pixel 4XL//Android 11

**Comment by WorldImpex** [comment]
Still reprodicible. @mtg137 Could we possibly show a message to the user that the password is being updated, allow the user to navigate away and in the background the process continues?

**Comment by sergeysemenuta** [comment]
Fixed on:
ML v 0.16.21
iPhone X // iOS 13.3
Pixel 4XL//Android 11
