### ISSUE TITLE
Feature Request: Reorder items/activities in applet builder

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-app#1758]
**Summary of requirements:**
1. Give users the ability to reorder items in the applet builder
2. Using the 'duplicate item' button and 'new item' button in applet builder adds the new item directly after the current item instead of at the end of an activity
3. Give the same new functions to the activity edit page
4. Add popup tooltips to all buttons

Here is my proposal below, [graphical assets are included](https://github.com/hotavocado/misc-graphics):

This is what the current applet builder looks like for items inside an activity:
![Screen Shot 2021-04-28 at 2 51 02 PM](https://user-images.githubusercontent.com/24463939/116469349-0b8b8b80-a840-11eb-8b7b-2278f4ba26bf.png)

1. Add a '[move](https://github.com/hotavocado/misc-graphics/blob/main/dots.svg)' button (3 dots on the right) and '[new item](https://github.com/hotavocado/misc-graphics/blob/main/plus.svg)' button.
![applet_builder_mock1](https://user-images.githubusercontent.com/24463939/116469802-9b313a00-a840-11eb-96c8-ee89bd5be3c2.png)

2. Please note the _extra space between the new move button and delete button_, this is to prevent the users from accidentally hitting delete when trying to move items. Please recreate this spacing accurately. 

3. Have the mouse turn into a '[move cursor](https://github.com/hotavocado/misc-graphics/blob/main/move_cursor.svg)' when hovering over/clicking/holding the move button.
![applet_builder_mock2-01](https://user-images.githubusercontent.com/24463939/116471004-28c15980-a842-11eb-93d9-28943a6392c4.png)

4. To move the item, click and hold the move button, then drag and place the item where it's desired. Replicate the behavior  shown in the Google Forms example below:
![reorder](https://user-images.githubusercontent.com/24463939/116471407-9f5e5700-a842-11eb-8e5c-e3063ec1cf8a.gif)

5. Currently when the duplicate item button is pressed, a duplicate appears at the end of the activity. Change this to make the duplicate item appear **directly after the item that is was duplicated**. The 'new item' button will also add the blank item **directly after the item for which the button was clicked**.

6. Add the same functions for the activity edit page.
![Screen Shot 2021-04-28 at 2 56 14 PM](https://user-images.githubusercontent.com/24463939/116472041-5c50b380-a843-11eb-8350-9f2c2d69a54e.png)

7. Most buttons in the admin panel have tool tips (example below):
![Screen Shot 2021-04-28 at 5 02 39 PM](https://user-images.githubusercontent.com/24463939/116472262-a8035d00-a843-11eb-84ef-1650d583ca0e.png)
Add them for applet builder buttons as well:
![mock3](https://user-images.githubusercontent.com/24463939/116472997-a0908380-a844-11eb-899f-2f8f1cf438d2.png)
For the activity page, replace the word 'item' with 'activity'. Note that I didn't include a tooltip for the 'move' button, this is intentional. The cursor change is sufficient.

8. Move items between activities - Allow the editor to move an item from on activity to another. 
![Move Between Activities .png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/b2931ba9-ff07-4532-83c8-5dc871aad8b0)

Other notes:
There's a blue 'Add item' and 'Add activity' button in the current applet builder that automatically adds a blank item/activity to the end of the activity/protocol. We can keep this button.

**Comment by natalia-muzyka** [comment]
@WorldImpex I have some suggestions (probably for the future versions of the feature):

1. Show warning if the final conditional item is moved higher in the list than conditional items
2. Show warning that if admin wants to move item which is included to the conditional rule then this rule will be removed
3. Show warning that if admin wants to move item which is included to the subscale to other activity, then this item will be removed from subscale
4. Show warning that if admin wants to move item which is included in the cumulative scoring, then it will be removed from the cumulative scoring item
5. Disallow to reorder/move the cumulative scoring item to another activity 
**/or** allow moving only if cumulative scoring item+included items are selected 
**but** disallow to move to the activity which is selected in cumulative scoring item as "show activity based on a threshold"
6. Disallow to reorder/move the token summary item 
**/or** allow moving only if selected: 
-past behavior tracker+token_summary; 
-future behavior tracker+timing prompt+token_summary
8. Show pop up about successfully moved item to other activity
9. Show tooltip after hovering the "Cancel" button in the move activities mode

**Comment by WorldImpex** [comment]
I think all are good points and deserving of being fixed this milestone. Please add bugs/ enhancements @natalia-muzyka

**Comment by WorldImpex** [comment]
Tickets created for all above issues 

https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-builder/711

https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/2410

**Comment by natalia-muzyka** [comment]
Related issues:
Duplicated activity is always on the top on mobile app and website and can't be reordered#1219
Error Messages for Reordering Items #711
[UI] Mouse cursor isn't changed to "move cursor" after hovering/clicking/holding the 3 dots button#709

**Comment by natalia-muzyka** [comment]
Works as expected.

Environment:
ML v0.18.61 staging
Samsung Galaxy S7 // Android 8
iPhone Xs Max// iOS 15.3
https://admin-staging.mindlogger.org/
https://web-staging.mindlogger.org/
