### ISSUE TITLE
The text is auto generated into the next screen on the textbox questions

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1769]
Steps to reproduce:
1. Log in to the app and select an applet that contain text box items
2. Open the first screen and enter some text
3. Hide the keyboard by tapping down error
4. Click the 'next' button
5. Tap into the text box
6. Look at the result
Actual result: The text is auto generated into the next screen on the textbox questions
Video:https://www.screencast.com/t/hC5sKjyPMEn
Expected result: The text is  not auto generated into the next screen on the textbox questions

Environment:
ML v 0.16.20
Pixel 4XL//Android 11

**Comment by natalia-muzyka** [comment]
The issue is fixed
Environment:
ML v 0.16.25 (staging)
Samsung S20 // Android 11
Samsung S7 Edge // Android 8.1
