### ISSUE TITLE
Changing the Background image for Draw Does not work

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1776]
Steps to recreate 
1. Create an applet with a draw item that contains a background image 
2. Update the mobile device to see the draw item 
3. Edit the applet and change the background image 
4. Update the mobile device and take the activity again 
5. See Results 

Expected: The newest image is shown 
Actual: The original image is shown

**Comment by natalia-muzyka** [comment]
The issue is fixed
Changing the Background image for Draw works after updating the mobile device and restarting the activity

Environment
ML 0.16.24
iPhone XR // iOS 14.3
Moto G5+ // Android 8.1
