### ISSUE TITLE
The cumulative scoring calculation is broken for the checkbox items on the "Summary" Screen

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1779]
**Steps to reproduce:**
1. Log in to the admin panel and go to the applet builder https://admin-staging.mindlogger.org/ (snakessqa@gmail.com // 123456)
2. Create an applet that has only checkbox items with scoring values
4. Create the cumulative item for these(Checkbox) items and upload the applet
5. Log in to the app and complete the assessment for that applet
6. Look at the final screen (Summary)
**Actual result:** The cumulative scoring calculation is broken for the checkbox items on the "Summary" Screen. It always shows 0
![2021-05-20_17-10-49.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/5c49cbde-4270-437c-8a11-6dbdbe66387a)
**Expected result:** The cumulative scoring calculation is not broken for the checkbox items on the "Summary" Screen.

**Environment:**
ML v 0.16.23
iPhone X // iOS 13.3
Pixel 4XL//Android 11

**Comment by natalia-muzyka** [comment]
The issue is still reproduced for existing and newly created cumulative activities if there are only checkboxes
Account:  (snakessqa@gmail.com // 123456)
Video:
https://www.screencast.com/t/4DAHS8x1j

Environment
https://admin-staging.mindlogger.org/
ML v 0.16.25 (Staging environments)
iPhone XR // iOS 14.3
Samsung Galaxy S7 Edge // Android 8.1

**Comment by natalia-muzyka** [comment]
@Matchdev120 seems that after the latest changes with cumulative scores the mobile app started crashing after taking an assessment with the cumulative score. It reproduces for activities that have multiple different item types(e.g. checkbox + slider + radiobutton).

Video: https://www.screencast.com/t/0qxW34DqC0ZM
Crashlog for Android: [https://app.zenhub.com/files/103405139/53f0bea1-075a-4778-8fcd-44408b2a5677/download](https://app.zenhub.com/files/103405139/53f0bea1-075a-4778-8fcd-44408b2a5677/download)

Environment:
Accounts: 
geria.test@yahoo.com // 3FuuFz60
snakessqa@gmail.com // 123456
https://admin-staging.mindlogger.org/
ML v0.16.26 (staging)
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0
iPhone XR // iOS 14.3

**Comment by natalia-muzyka** [comment]
Verified as fixed:
1) cumulative scoring calculation works as expected for multiple items(radio + checkbox +slider);
2) cumulative scoring calculation works as expected for the similar items (only radio, checkbox, slider);
3) the mobile app isn't crashing after an attempt to take an assessment/completing the assessment

Environment:
https://admin-staging.mindlogger.org/
ML v0.16.28 (staging)
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0
iPhone XR // iOS 14.3

Accounts:
snakessqa@gmail.com // 123456
applet: checkbox cumulative (Applet password: Qwe123!!!)
qatl.customer1@protonmail.com // 3FuuFz61
applet: cumulative test (Applet password: Qwe123!!!)
