### ISSUE TITLE
Duplicating Applets should require a password 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1780]
Steps to recreate 
1. Log into admin-staging.mindlogger.org (or prod) 
2. Click icon to duplicate applet 
3. See confirmation message 
4. Confirm 
5. See Results 

Expected: User is prompted to enter a new password 
Actual: Duplicated applet is shown

**Comment by natalia-muzyka** [comment]
Verified as fixed.
Video: https://www.screencast.com/t/x0umZoBc47r

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 93.0.4577.82 
macOS 11.0 // Safari 14.0.1
