### ISSUE TITLE
Update CMI Logo and Add it to the Ecosystem 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1781]
Areas to add 
- Applet List page next to about link 

Update 
- Email 
- Admin 
- Applet Builder
- Webapp 
- Applet Library 
- Login 

Ask @WorldImpex for image file

**Comment by WorldImpex** [comment]
@devbtech We will need to create our own s3 bucket for this

**Comment by natalia-muzyka** [comment]
@astef021 @WorldImpex  The CMI logo isn't updated on the: 
- mobile app (0.18..4 staging) / About page
- admin panel
- applet library

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/4d956684-f4b3-4f80-845d-7cb8bc9397f5)

**Comment by astef021** [comment]
I think my admin panel, applet library, and backend PRs are not merged
I missed logo on about page, I'll fix it

**Comment by natalia-muzyka** [comment]
Fixed for ML app About screen. 
@astef021 On the admin panel, applet builder, and library staging there is still an old logo.

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/a00e01a8-321f-4a06-81a9-73f0d40db24f)

**Comment by WorldImpex** [comment]
Could you also do the login logo with this image? 

![ChildMindInstitute_Logo_Horizontal_KO copy.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/75fffc3b-c261-4dfe-a123-aff010b7322c)

**Comment by astef021** [comment]
@devbtech My PRs for admin panel, applet library and backend are not merged yet

https://github.com/ChildMindInstitute/mindlogger-backend/pull/1172
https://github.com/ChildMindInstitute/mindlogger-admin/pull/1330
https://github.com/ChildMindInstitute/mindlogger-applet-library/pull/143

could you please check them?

**Comment by natalia-muzyka** [comment]
CMI logo is updated on:

- Mobile app
- Email
- Admin
- Applet Builder
- Webapp
- Applet Library

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/5c481e54-654b-46c3-ad02-0291ca87330c)
