### ISSUE TITLE
Share/ Export PDF Report of Cumulative Score on Mobile/ Web Applet

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1785]
As a user, I want to share my report that I receive from a cumulative score item so that I can use the native controls to send a PDF outside of MindLogger with my results 

Requirements 
- Show a share button on the cumulative score screen that use the native controls to send a PDF outside of MindLogger to others on mobile 
* The report at the end of the mobile and webapp should be updated to reflect the new fields) 
- Webapp should have a share button that downloads the PDF
- Admin panel should have a "Export Report" button that downloads the same PDF on the user's visualization page above the versions. (Please move versions down to make it fit nicely
![Screen Shot 2021-07-08 at 5.20.57 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/fc6413dd-01aa-455b-b207-df6a59bde879)
- From the applet builder, the editor should be able to setup the report based on filling out the below fields in markdown.
** Please add an overview markdown box for the first cumulative score but is not available for the next cumulative score. 
** Please add a description box using markdown for every cumulative score created 
- Require the user to select which direction the chart goes positive to negative or negative to positive 
- Markdown should be able to upload images or use emojis 
![Ped PDF .png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/68e3f8d7-f174-4cd2-b089-b9de2377331e)

[https://app.zenhub.com/files/103405139/e1dcb1b0-3e13-488d-989c-d10bfa43ef1a/download](https://app.zenhub.com/files/103405139/e1dcb1b0-3e13-488d-989c-d10bfa43ef1a/download)

**Comment by Sshetty2** [comment]
https://github.com/ChildMindInstitute/mindlogger-applet-builder/pull/476

https://github.com/ChildMindInstitute/mindlogger-admin/pull/1185

**Comment by Sshetty2** [comment]
https://github.com/ChildMindInstitute/mindlogger-app/pull/1908

https://github.com/ChildMindInstitute/mindlogger-web/pull/116

**Comment by Sshetty2** [comment]
New PRs.
https://github.com/ChildMindInstitute/mindlogger-applet-builder/pull/492
https://github.com/ChildMindInstitute/mindlogger-admin/pull/1224
https://github.com/ChildMindInstitute/mindlogger-web/pull/122

**Comment by devbtech** [comment]
Not ready for Web app yet but other platforms are good to go

**Comment by natalia-muzyka** [comment]
@WorldImpex could you help me, please, with the next questions:
**1) The mobile pdf report is displayed as the mobile view after downloading, meanwhile, the admin panel report is displayed in the desktop view.** Is this expected or should be both in the same view(desktop)?
Mobile report (downloaded):
[https://app.zenhub.com/files/103405139/0f3fa898-277e-4bc4-9b90-eb8a2a3fa8c1/download](https://app.zenhub.com/files/103405139/0f3fa898-277e-4bc4-9b90-eb8a2a3fa8c1/download)
Admin panel report: 
[https://app.zenhub.com/files/103405139/707b74d5-563b-430c-8ce4-a33cbebb8fd3/download](https://app.zenhub.com/files/103405139/707b74d5-563b-430c-8ce4-a33cbebb8fd3/download)
As I understand, this difference causes the UI issues in the admin panel report (big indents, broken images).
**2) Only the latest score results are reflected in the pdf report (I assume this is expected)**

**Issues:**
The "Share report" button is displayed as regular text on the summary screen #1945
The report at the end of the mobile doesn't reflect the new cumulative score fields #1946
The markdown text isn't completely supported in the report on mobile #1947
[Android] The mobile app crashes after tapping the "Share report" btn on the cumulative summary screen #1948
The user's score(scale) in the pdf report doesn't depend on the real user's score (progress is always displayed at the same point) #1949
The admin panel and mobile PDF report issues / differences #1950
Shared with email pdf report isn't received #1951
The direction images aren't displayed in the applet builder within the cumulative item #513

**Comment by WorldImpex** [comment]
@natalia-muzyka 
1. Yes both should be in desktop view 
2. Expected

**Comment by Sshetty2** [comment]
https://github.com/ChildMindInstitute/mindlogger-app/pull/1956
https://github.com/ChildMindInstitute/mindlogger-web/pull/155
https://github.com/ChildMindInstitute/mindlogger-admin/pull/1255

**Comment by natalia-muzyka** [comment]
All the issues are fixed except the "The markdown text isn't completely supported in the report on mobile" #1947 (moved to backlog). Verified and closed.
