### ISSUE TITLE
Transferring an applet   from the Library to the builder and saving causes all applets to disappear on the app

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1786]
**Steps to reproduce:**
1. Open the Library https://library-staging.mindlogger.org/#/?lang=en_US
2. Log in to the library ( snakessqa@gmail.com // 123456)
3. Mark the  'A a Nice applet' 
4. Navigate to the cart
5. Click the "add to the applet builder" button>Add to new applet
6. Save to the dashboard
7. Log in to the app
8. Look at the result

**Actual result:** Transferring an applet  to the builder and saving causes all applets to disappear on the app
See the video:
**Expected result:** The transferred applet and existing applets should be shown on the home screen
Note: The  'A a Nice applet' has all the types of items
**Environment:**
Staging
ML v 0.16.24
iPhone X // iOS 13.3
Pixel 4XL//Android 11

**Comment by natalia-muzyka** [comment]
The issue isn't reproduced for creating a new applet for the account
geria2.test@yahoo.com //	McgzF127

Need to be checked with 
- adding to the existing applet (now it is blocked by [#1041] (https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/1041))
- snakessqa@gmail.com (now it is blocked by [#53](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-library/53))

**Comment by natalia-muzyka** [comment]
The issue is fixed
https://www.screencast.com/t/9LmooGGgWAp

Accounts:
geria2.test@yahoo.com // McgzF127
snakessqa@gmail.com // 123456

Environment:
Staging
ML v 0.16.26
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0
iPhone XR // iOS 14.3
