### ISSUE TITLE
UI/UX Tablets issues

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#1792]
**1) The header is trimmed on the bottom**
https://www.screencast.com/t/URjtxlgyjmVH	
Environment:
ML 0.16.24
iPad Air 2 Wi-Fi // iOS 14.6 // 1536x2048 // 9.7"

**2) The active(current) date is trimmed on the bottom**
https://www.screencast.com/t/li7fWL08O8
Environment:
ML 0.16.24
iPad Air 2 Wi-Fi // iOS 14.6 // 1536x2048 // 9.7"
Samsung Galaxy Tab S6 SM-T865 // Android 9.0 // 1600 x 2560 // 10.5"

**3) The time picker isn't comfortable to use**
https://www.screencast.com/t/IjVgvbdDm
Environment:
ML 0.16.24
iPad Air 2 Wi-Fi // iOS 14.6 // 1536x2048 // 9.7"
Samsung Galaxy Tab S6 SM-T865 // Android 9.0 // 1600 x 2560 // 10.5"

**4) Bad video quality (pixelization) after selecting the video capturing** 
https://www.screencast.com/t/RIEmh3RiD
Environment:
ML 0.16.24
iPad Air 2 Wi-Fi // iOS 14.6 // 1536x2048 // 9.7"

**Comment by binaryExDev** [comment]
@natalia-muzyka I can't reproduce the 3rd issue (attached a screenshot)

I tested it on iOS13.3. What iOS version did you use to test it?

![Screen Shot 2021-07-08 at 8.58.53 PM.png](https://images.zenhubusercontent.com/5fc8d89138215d1055c6d606/a55ecf53-e672-4bb3-b386-418006078d77)

**Comment by natalia-muzyka** [comment]
@binaryExDev 
The issue is reproducible on iOS 14

**Comment by natalia-muzyka** [comment]
Fixed: 1, 2

Failed: 3, 4

**#3 user still needs to do at least 2 taps to get the time picker, and 3 taps to apply the changes and close it**
https://www.screencast.com/t/k2ojh1NqAFR
https://www.screencast.com/t/aByDtWy0m5

#4 is still reproducible for video recorder  
https://www.screencast.com/t/7ELaaXiNiNc

ML v0.17.6 (staging)
iPad Air 2 Wi-Fi // iOS 14.6 // 1536x2048 // 9.7"
iPhone 6S // iOS 14.4

**Comment by natalia-muzyka** [comment]
#3 time picker is still not user friendly
https://www.screencast.com/t/ciTnRlO5f

#4 verified as fixed
https://www.screencast.com/t/mELYoeub

ML v0.17.8 (staging)
iPad Air 2 Wi-Fi // iOS 14.6 // 1536x2048 // 9.7

**Comment by natalia-muzyka** [comment]
time picker didn't change on iOS 14:
https://www.screencast.com/t/N315eyj8p9p

ML v0.17.13 (staging)
iPad Air 2 Wi-Fi // iOS 14.6 
iPhone 8 Plus // iOS14.3

**Comment by natalia-muzyka** [comment]
@binaryExDev 
#3 the time picker issue is fixed(functionally) but on the tablet screen, it is shifted to the left side. 
Could you move it to the center?:
https://www.screencast.com/t/QX1Odq8s

ML v0.17.14 (staging)
iPad Air 2 Wi-Fi // iOS 14.6

**Comment by WorldImpex** [comment]
@binaryExDev Why is this on hold?

**Comment by Matchdev120** [comment]
on Purpose or by Accident???

**Comment by binaryExDev** [comment]
By Accident.

**Comment by HarutQA** [comment]
Works correctly. Tested on MacBook Pro Safari 14.0.3

**Comment by natalia-muzyka** [comment]
The issue is still reproducible on:
iPad Air 2 Wi-Fi // iOS 14.6
ML v0.17.25 (staging)
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/24925fd6-ba75-4e48-aad6-b61e58147c1a)

**Comment by natalia-muzyka** [comment]
@binaryExDev on the later models the time / date picker is shifted to the left as well:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/f9044be2-7ea9-453c-88e7-d3d237408002)

**Comment by natalia-muzyka** [comment]
@devbtech The date and time picker are still shifted to the left. Not reproducible on iPhone 8 Plus // iOS 13.3

Environment:
ML v0.18.1 (staging)
iPhone 11 // iOS 14.2
iPad Pro 10.5 // iOS 15.0.2

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/fd127bdc-d5c1-44b6-9876-b3e72d221c8f)

**Comment by natalia-muzyka** [comment]
@binaryExDev  The date and time picker are still shifted to the left. Not reproducible on iPhone 8 Plus // iOS 13.3

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/e09bbdc8-2f17-424d-b024-277caedc415d)

Environment:
ML v0.18.18, 0.18.19 (staging)
iPhone 11 // iOS 14.2
iPad Pro 10.5 // iOS 15.0.2

**Comment by natalia-muzyka** [comment]
Verified as fixed:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/98129cfb-e0c5-4180-bfd8-aee959482081)

ML v0.18.36 staging
iPhone 8 Plus // iOS 13.3
iPad Pro (10,5-inch) MQDX2 //  iOS 15
