### ISSUE TITLE
 The selected in the assessment responses don't match the mobile Data tab, admin panel DataViz, Review displaying

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#1801]
**Preconditions**
The mobile app is installed and launched
The user is logged in to geria.test@yahoo.com // 3FuuFz60

**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Log in to geria.test@yahoo.com // 3FuuFz60
3. In the mobile app complete the assessment 
4. Proceed to Data tab and compare the displayed data with actually selected responses
5. On admin panel proceed to the user's DataViz and compare the displayed data with actually selected responses
6. On admin panel proceed to the user's Review tab and compare the displayed data with actually selected responses
7. Observe the result

**Actual result**
 The selected in the assessment responses don't match the mobile Data tab, admin panel DataViz displaying

**Expected result**
 The selected in the assessment responses matches the mobile Data tab, admin panel DataViz, Review displaying

**Attachment**
Video: https://www.screencast.com/t/8v8kKmeUYYfu
Compare table mobile app & dataviz: https://www.screencast.com/t/gzJz7t9SyA

**Environment**
https://admin-staging.mindlogger.org/
Account: geria.test@yahoo.com // 3FuuFz60
Applet: Retest subscale 2 (Applet password: Qwe123!!!)

**Comment by natalia-muzyka** [comment]
Not reproducible for the applet from the ticket.

But I found some differences for other applets. 
@mtg137 , wdyt should I create separate tickets for these two cases?:

1) some responses aren't displayed on the data tab(mobile app) but displayed on the dataviz "responses" tab
https://www.screencast.com/t/pncFZhZFBB
https://www.screencast.com/t/iJVhzoNdm
video(taking an assessment): https://www.screencast.com/t/0RnBbTJJu
account: geria.test@gmail.com // 123456 
applet: DBT Daily Diary Card v1.06 
activity: Daily Diary Card
Applet password: Qwe123!!!

2) on the dataviz "responses" tab there are empty charts for the screens which weren't shown for the user because of conditional logic
https://www.screencast.com/t/0uf8qXb9
video(taking an assessment): https://www.screencast.com/t/dz7ui33rZ
account: https://www.screencast.com/t/dz7ui33rZ
applet: Healthy Brain Network (NIMH content) edited 
activity: EMA Assessment (Mid Day)
Applets password: Qwe123!!!

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 91

ML v0.16.28 (staging)
Samsung S7 Edged // Android 8.0
iPhone 12 Pro Max // iOS 14.4

**Comment by mtg137** [comment]
@natalia-muzyka thanks for checking.
1) is a bug. I'll fix it for this ticket.

I think 2) is not a bug.

**Comment by WorldImpex** [comment]
@mtg137 yes 2. is a feature

**Comment by natalia-muzyka** [comment]
moved the ticket to the sprint backlog due to the comment above,
#1 "some responses aren't displayed on the data tab(mobile app) but displayed on the dataviz "responses" tab" issue needs to be fixed

**Comment by natalia-muzyka** [comment]
Not reproducible on:
ML v0.16.29 (staging)
iPhone XR // iOS 14.3
https://www.screencast.com/t/qtuvGk4cW

Waiting for a new build for Android.

**Comment by natalia-muzyka** [comment]
Responses are broken (don't match) again:

Video of taking an assessment: 
https://www.screencast.com/t/dm2m6p0WN

Screenshots:
The response isn't shown on Data tab(app) and dataviz: https://www.screencast.com/t/kR2ojsJpwPHx
The wrong response is shown on  Data tab(app) and dataviz: https://www.screencast.com/t/2geRddZily
Some screens are missing on Data tab and dataviz at all: 

Account:
johndoeregress@protonmail.com	// 12345678
Applet:
Healthy Brain Network (NIMH content) v0.30 // EMA Assessment Mid Day

Account owner:
geria2.test@gmail.com // McgzF127
Account user:
johndoeregress@protonmail.com	// 12345678
Applet:
Healthy Brain Network (NIMH content) v0.30 // EMA Assessment Night

Applets password: Qwe123!!!

ML v0.16.30 (staging)
iPhone XR // iOS 14.3

**Comment by WorldImpex** [comment]
Seems to be fixed on iPhone 6s

**Comment by natalia-muzyka** [comment]
Verified as fixed

Account owner:
geria2.test@gmail.com // McgzF127
Account user:
johndoeregress@protonmail.com // 12345678
Applet:
Healthy Brain Network (NIMH content) v0.30 // EMA Assessment Night
TokenLogger
Educate EMA Applet // Daily Intervention Log

Applets password: Qwe123!!!

ML v0.16.31 (staging)
iPhone XR // iOS 14.3
