### ISSUE TITLE
The time of taking an assessment doesn't match between application, "Review" tab, "Responses" tab, exported CSV file

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#1807]
**Preconditions**
The application is installed and launched
The admin panel is opened https://admin-staging.mindlogger.org/
The user is logged in on the admin panel and application: 
geria.test@yahoo.com // 3FuuFz60

**Steps to reproduce**
1. Take an assessment on the mobile app
2. Proceed to the dataviz on the admin panel
3. Set start time according to the "Review" tab latest time data to see the latest assessment results
4. Pay attention to the dataviz
5. Compare the real-time of taking an assessment with the admin panel
6. Export data and pay attention to the date of taking an assessment
7. Observe the result

**Actual result**
The time of taking an assessment doesn't match the application, "Review" tab, "Responses" tab, exported CSV file.

**Expected result**
The time of taking an assessment matches the application, "Review" tab, "Responses" tab, exported CSV file.

**Attachment**
https://www.screencast.com/t/8TPqaInFp

**Environment:**
ML v0.16.28
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0
iPhone XR // iOS 14.3
https://admin-staging.mindlogger.org/
Account: geria.test@yahoo.com // 3FuuFz60

**Comment by natalia-muzyka** [comment]
@devbtech 
Applet key: Qwe123!!!

**Comment by natalia-muzyka** [comment]
@devbtech **The issue is still reproducible.**



Environment: 
https://admin-staging.mindlogger.org/
ML v0.16.28 (staging)
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0
iPhone XR // iOS 14.3

1) video: https://www.screencast.com/t/7mMQbbH2TkvL
https://www.screencast.com/t/l47jEW8ecH
Accounts:
geria.test@yahoo.com // 3FuuFz60
geria.test@gmail.com // 123456
Applet / activity:
Retest subscale 2 / average, sum

2) https://www.screencast.com/t/jUT7skzJDht
Account: geria.test@yahoo.com // 3FuuFz60
Applet / activity:
Healthy Brain Network (NIMH content) edited / Pre-Questionnaire

**Comment by WorldImpex** [comment]
@mtg137 Could you update the review tab to be in UTC?

**Comment by natalia-muzyka** [comment]
current behavior:
mobile app - user's timezone, eest (13:07)
dataviz "review" tab(timestamp) - user's timezone, eest (13:07)
dataviz "response" tab - utc (10:07)
data export - utc (10:07)
there's a difference between the "review" and "responses" tab on dataviz
if I set the time as on the "review" tab - I can't see responses (edited) 
https://www.screencast.com/t/jZTU5tsgt1UC

**Comment by natalia-muzyka** [comment]
The issue is fixed. 
Current behavior:
mobile app - user's timezone, eest
dataviz "review" tab(timestamp) - utc 
dataviz "response" tab - utc
data export - utc
https://www.screencast.com/t/kWhagl0gK

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 91

**Comment by natalia-muzyka** [comment]
Reproducible for the Tokens and Frequency tabs.
Expected: all the DataViz tabs are displayed in the UTC timezone

Video: https://www.screencast.com/t/zCYbyRsuzJC

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 91

**Comment by natalia-muzyka** [comment]
Verified as fixed
https://www.screencast.com/t/FjRgtRcYY

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 91
geria2.test@gmail.com // McgzF127
applet: TokenLogger Sleep geria2
Applet password: Qwe123!!!
