### ISSUE TITLE
The mobile app crashes on the markdown message screen

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#1825]
**Steps to reproduce**
1. Install and launch the mobile app (staging)
2. Log in geria2.test@gmail.com	// McgzF127
3. Take an assessment with a markdown message screen (applet: "All", activity:"header image")
4. Pay attention to the screen.

**Actual result**
The mobile app crashes on the markdown message screen.

**Expected result**
The markdown message screen is displayed after proceeding to it. The application works correctly.

**Video:** https://www.screencast.com/t/foMCrNAx
**Crash log:** [https://app.zenhub.com/files/103405139/7f8dc694-59ae-4346-993b-19fba27498c5/download](https://app.zenhub.com/files/103405139/7f8dc694-59ae-4346-993b-19fba27498c5/download)

**Environment**
ML v0.16.29 (staging)
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0

account:
geria2.test@gmail.com	// McgzF127
applet: "all"
activity: "header image"
applet password: Qwe123!!!

**Comment by Matchdev120** [comment]
@natalia-muzyka
I cannot reproduce the issue and see the markdown message on your account. 
 ![Screen Shot 2021-07-02 at 8.28.09 AM.png](https://images.zenhubusercontent.com/5e248d759c666007f1a71211/1e6c1a0c-9043-456e-8b65-5a6edd7bab01)

**Comment by natalia-muzyka** [comment]
@Matchdev120 which device do you use? it's still reproducible for my android device (for iOS it's not reproducible):
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0
ML v0.16.30 (staging)

Video:
https://www.screencast.com/t/JDKoOdJc

**Comment by natalia-muzyka** [comment]
I'm able to reproduce crashes on iOS too.
There is an additional step: you need to skip one of the media screens (photo, video, audio, drawing).
Here is the video for iOS:
https://www.screencast.com/t/OFTSdvDFBt

**Comment by natalia-muzyka** [comment]
@Matchdev120 I have new details, I'm not sure but maybe this crash is caused by selecting together the next options for the photo, video, time range, drawing item on the admin panel:
- skippable item
- response required

I've just created a new [report](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-builder/421) regarding the "skippable item" checkbox (it isn't greyed after allowing the "response required"), and the "skip" button continues to display in the mobile app

**Comment by natalia-muzyka** [comment]
Probably, after the [latest changes](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/1844) there is appeared a new issue (new crash): 
the screen with audio record with selected text input(even non-required) crashes now:
https://www.screencast.com/t/oKvTQtS2

Environment
ML v0.16.34 (staging)
iPhone XR // iOS 14.3
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0
https://admin-staging.mindlogger.org/
geria2.test@gmail.com // McgzF127
applet: All
activity:
skippable test, header image, text input test
password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
@Matchdev120 
I'm able to reproduce a crash:
- on the markdown activity screen with audio link (Android only) https://www.screencast.com/t/qqZrxVCeH
- on the "About" applet screen with audio link (Android only) https://www.screencast.com/t/o0akQIfdple
- on the audio record screen + text input (Android and iOS) https://www.screencast.com/t/oKvTQtS2

Crash log(taking a header image (2) assessment, crash on the markdown activity screen):
[https://app.zenhub.com/files/103405139/cda0c4f9-63bc-4cb9-a656-c702eda62d48/download](https://app.zenhub.com/files/103405139/cda0c4f9-63bc-4cb9-a656-c702eda62d48/download)

**Environment**:
ML v0.16.35 (staging)
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0
Samsung A31 // Android 10
Pixel 3 XL	 // Android 10
iPhone XR // iOS 14.3 (crash on audio record + text input activity screen)

https://admin-staging.mindlogger.org/
owner: geria2.test@gmail.com // McgzF127
users: 
johndoeregress@protonmail.com	// 12345678
janedoeregress@protonmail.com	// %pVgPJ*O

applet: All
password: Qwe123!!!
activities:
header image, text input test (crash on audio + text input screen)
header image (2), markdown with audio (crash on markdown activity screen)

crash on About applet screen:
DBT Applet 1, All
password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
All the issues from the comment above are fixed

Environment:
ML v0.17.1 (staging)
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0
iPhone 6 Plus  // iOS 12.3.1
