### ISSUE TITLE
Confirmation Screen: Optimize so it doesn't freeze 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1833]
When the user completes an activity, the thank you page freezes for 2-5 seconds. Please figure out a way to not impact the user's experience when encrypting the response data

**Comment by natalia-muzyka** [comment]
Verified as fixed:
https://www.screencast.com/t/nY2O6cVH

Environment:
ML v0.16.37 (staging)
iPhone 6 Plus // iOS 12.3.1
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0
Samsung Galaxy S9 // Android 9.0
