### ISSUE TITLE
The time remaining is 2 minutes instead of 1 minute accordingly to scheduling

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#1834]
**Preconditions**
The admin panel is opened https://admin-staging.mindlogger.org/
The mobile app is installed and launched
The user is logged in on the admin panel and mobile app:
geria2.test@gmail.com	McgzF127

**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Proceed to the calendar of any activity that wasn't completed in the mobile app yet
3. Set the activity with a timer (0 hours 1 minute)
4. Start this activity on the mobile app
5. Pay attention to the timer

**Actual result**
The time remaining is 2 minutes instead of 1 minute accordingly to scheduling

**Expected result**
The time remaining is displayed accordingly to scheduling

**Environment**
https://admin-staging.mindlogger.org/
ML v0.16.31 (staging)
iPhone XR // iOS 14.3 	
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0 /

**Attachment**
![2021-07-06_13-04-10.jpg](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/b5921633-8bcf-4f77-9149-8692c97d2d14)

**Comment by Matchdev120** [comment]
@natalia-muzyka This is not reproducible on my side.

![Screen Shot 2021-07-08 at 7.47.30 AM.png](https://images.zenhubusercontent.com/5e248d759c666007f1a71211/135c82a4-2457-4924-83e8-736c18aefb19)

**Comment by natalia-muzyka** [comment]
the issue isn't reproducible anymore, the ticket can be closed
