### ISSUE TITLE
The conditional logic doesn't work for manually created activities and after editing the uploaded applets

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#1836]
**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Log in 
3. Create a new applet
4. Create a new activity with radio, checkbox, slider screens 
5. Add the conditional logic for any screen and save
6. Log in to the same account on the mobile app
7. Complete this activity on the mobile app
8. Observe the result

**Actual result**
The conditional logic doesn't work for manually created activities.

**Expected result**
The conditional logic works for manually created activities and after editing the uploaded applets.

**Notes**
Reproduces for checkboxes, radio buttons, sliders; for the applets that were uploaded with a github schema:
- after editing an uploaded activity
- after creating a new activity

**Environment**
https://admin-staging.mindlogger.org/
ML v0.16.31(staging)
iPhone XR // iOS 14.3	
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0 
Account owner: geria2.test@gmail.com // McgzF127
Account users:
johndoeregress@protonmail.com	// 12345678
janedoeregress@protonmail.com	// %pVgPJ*O
Applet/activity:
TokenLogger
conditionals
NIMH

**Attachment**
https://images.zenhubusercontent.com/103405139/6b62d768-fb2a-4c7e-8272-da36c67f50ee/conditional.mp4

**Comment by Matchdev120** [comment]
@natalia-muzyka Just tested it and it works.
I took a look at the video as well and I don't think you've deep understanding about the conditional logic.
If the conditional is met, then the target item is visible in the item list.

Let's say that have a Conditional like this:

If Screen2 includes option1, show Screen 4

 - if Screen2 doesn't have option1,
The item order will be Screen1 -> Screen2 -> Screen3 -> End (Thank you Screen)
 - if Screen2 includes option1,
This is the item order that user can see. Screen1 -> Screen2 -> Screen3 -> Screen4 -> End (Thank you screen)

Did you think that it would be Screen1 -> Screen2 -> Screen4 -> Screen3 -> End ???

**Comment by natalia-muzyka** [comment]
@Matchdev120 great thank you for an explanation! I really misunderstood the conditional logic. 
I thought it would be: Screen1 -> Screen2 -> Screen4 -> End
