### ISSUE TITLE
[UI] Mobile app issues

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#1840]
**1. The "text" input field placeholder is cropped on the activity screen**
https://www.screencast.com/t/Oz5RqpBNZt
Samsung A31 // Android 10
1080 x 2400 pixels, 20:9 ratio

**2. The "email" input field entered value is cropped on the login screen**
https://www.screencast.com/t/keNnk3O8tSD
iPhone 8  // iOS 12.3.1
750 x 1334 pixels, 16:9 ratio 

ML v0.16.31 (staging)

**Comment by mtg137** [comment]
@natalia-muzyka For 1), could you please upload video for taking assessment?
( I tested on 1080 x 2400 simulator, but I wasn't able to repro )

**Comment by natalia-muzyka** [comment]
@mtg137 
Maybe this is caused by the system navigation bar?
So you should decrease the device height in your simulator to reproduce this issue.

video: https://www.screencast.com/t/xD9vQjqZx03
account: johndoeregress@protonmail.com // 12345678
applet / activity: all / photo + text input

**Comment by mtg137** [comment]
thank you!

**Comment by mtg137** [comment]
@natalia-muzyka could you please double check video link? I am getting page not found error.

**Comment by WorldImpex** [comment]
Item 1 is going to go backlog 

Item 2 @mtg137 is going to create a PR for it

**Comment by natalia-muzyka** [comment]
email field issue is fixed, but now there is an issue with the password field:
after entering even 2-4 characters the password mask is shortened with "..."
https://www.screencast.com/t/S9Q55RIuuKH

**Environment:**
ML v0.17.8
iPhone 6 Plus  // iOS 12.3.1 // 1080x1920 // 5,5"
iPhone 6s  // iOS 14.4 // 750x1334 // 4,7"

**Comment by natalia-muzyka** [comment]
verified as fixed
https://www.screencast.com/t/imWnCrje

Environment:
ML v0.17.9 (staging)
iPhone 6 Plus // iOS 12.3.1 // 1080x1920 // 5,5"
iPhone 6s // iOS 14.4 // 750x1334 // 4,7"
