### ISSUE TITLE
The infinity loader after an attempt to load the unshared applet detail page

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#1842]
**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Log in: geria.test@gmail.com // 123456
3. Share any applet to Applet library (e.g. "111")
4. Copy a sharing link
5. Open the applet detail page in a new tab
6. Unshare the applet on the admin panel (turn off the "Share" toggler)
7. Refresh the applet detail page in the library
8. Pay attention to the screen

**Actual result**
The infinity loader after an attempt to load the unshared applet detail page. 

**Expected result**
@WorldImpex One of the suggestions need to be confirmed:
#1 The warning message(pop-up) "The applet was removed from the Library or the applet detail page link is invalid".
"OK" button (closes the pop-up and redirects the user to the main page)
#2 Placeholder "The applet was removed from the Library or the applet detail page link is invalid"

**Notes**
The infinity loader reproduces after entering the invalid link (e.g. if one character is missed)

**Video**: https://www.screencast.com/t/vzU89E8PpxR

**Environment**
https://library-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.124

**Comment by WorldImpex** [comment]
Lets do #2 @natalia-muzyka thanks!

**Comment by natalia-muzyka** [comment]
Verified as fixed
https://www.screencast.com/t/mCiLNqmJ5

Environment
https://library-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.124
macOS 10.15 // Safari
