### ISSUE TITLE
Mobile app crashes after completing the assessment with the uploaded video (>100Mb)

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#1860]
**Preconditions**
The mobile app(Mindlogger Pilot) is installed and launched 
The user is logged in:
geria2.test@gmail.com // McgzF127

**Steps to reproduce**
1. Open a mobile app
2. Start an assessment with the video media type (e.g. "Media(lazy loader)")
3. Upload the >100Mb video or record the max size video (1 minute)
4. Complete the assessment
5. Pay attention to the screen

**Actual result**
Mobile app crashes after completing the assessment with the uploaded video (>100Mb)

**Expected result**
The assessment with the uploaded video (>100Mb) is completed successfully. The mobile app is continuing to work.

**Notes**
After this crash for a while(~10 minutes) all the media type activities cause the mobile app crash.
After an attempt to log out noticed once the warning pop-up about the uploading fil in progress.

**Video**:
https://www.screencast.com/t/nFUU1aQE
Crash log: 
[https://app.zenhub.com/files/103405139/aa21b5bb-86a1-46bb-9850-aaf0c44a5f43/download](https://app.zenhub.com/files/103405139/aa21b5bb-86a1-46bb-9850-aaf0c44a5f43/download)
Uploaded video(mp4/360p):
https://en.savefrom.net/21/#url=http://youtube.com/watch?v=jFBpUnSc1KM&utm_source=youtube.com&utm_medium=short_domains&utm_campaign=ssyoutube.com&a_ts=1626782019.822

**Environment**:
https://admin.mindlogger.org/
https://admin-staging.mindlogger.org/
ML Pilot v0.16.35 (prod)
ML v0.16.37 (staging)
ML v0.16.38 (staging)
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0
Samsung Galaxy S9 // Android 9.0

**Comment by natalia-muzyka** [comment]
still reproducible on:
ML v0.17.32 (staging)
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0

**Comment by natalia-muzyka** [comment]
Still reproducible after recording the maximum (1 minute) video and completing the activity.
Video: https://www.screencast.com/t/SgTjgf9Lx3VZ

ML v0.17.69 (staging)
Samsung Galaxy S8 // Android 9.0

**Comment by WorldImpex** [comment]
@natalia-muzyka Agreed - lets back log this. I am waiting to hear what suggestions come from the security firm and media storage and transit is one of them on the list

**Comment by natalia-muzyka** [comment]
@jj105 on mobile app side the issue is fixed, but on the admin panel side videos are missing.
I completed the activity twice ~5h ago and still don't see videos in the export. Could you help, please?

Environment:
ML v0.19.1 staging
Samsung Galaxy S7 // Android 8
iPhone Xs Max// iOS 15.3
owner: jeraka1732@wodeda.com	1234567890
applet: media upload test
Applet password	Qwe123!!!

**Comment by natalia-muzyka** [comment]
@jj105 was there only a backend fix so it should be tested on the latest plain app ML 0.19.7?

**Comment by natalia-muzyka** [comment]
Blocker issue:
The mobile app crashes after completing the activity#2081

**Comment by natalia-muzyka** [comment]
Verified as fixed on:
ML v0.19.13 staging
Samsung Galaxy S7 // Android 8
iPhone Xs Max// iOS 15.3
https://admin-staging.mindlogger.org/
Win 10 // Chrome 100.0.4896.75
