### ISSUE TITLE
feat: applet theme - reskinning

### ISSUE THREAD

**Issue by peterpeterparker** [ChildMindInstitute/mindlogger-app#1864]
### Feature Description

For the cooperation with external studies, it was suggested that applets' design should becomes more flexible to adapt external studies. To limit the scope of the feature, the idea is to introduce themes, so that a theme (a set of predefined style) can be applied to an applet.

Themes have to be configured by the team in the database, there is no GUI to create and handle these.

If no themes are defined, no theme should appear in the administration panel and nothing should change across the platform and apps, UI remains the same.

To the contrary, if themes are defined in the database, upon creating or editing an applet in the admin, user should be able to select a theme. To do so, a dropdown of themes will be presented on the applet' details page.

If a theme is selected and therefore save with the applet data, the UI of the applet should inherits the theming, its options, in the mobile application.

Scope of the theming is limited to following option:

- applet primary color: applied for the header and footer in the applet in the app
- applet background: an image which would be applied instead of the default background image of the applet
- applet logo: a logo which should be displayed in each applet cards in the list of applets of the end user

All theming options are optional and once again, have to be defined by the team.

### Screenshots

Logo:

![Simulator Screen Shot - iPhone 11 - 2021-07-15 at 13 58 29](https://user-images.githubusercontent.com/16886711/126378900-1d5046f6-de6d-417f-926d-c5099cd2f4aa.png)

Header and footer with primary color + custom backgroung:

![Simulator Screen Shot - iPhone 11 - 2021-07-15 at 13 58 36](https://user-images.githubusercontent.com/16886711/126378978-fb4c5892-86b0-48a5-be85-fd80ecdb1cf8.png)

**Comment by natalia-muzyka** [comment]
@BarrySunderland @WorldImpex how can I test this feature? 
Are there separate schemas with defined themes or all the schemas should contain themes?

**Comment by WorldImpex** [comment]
@natalia-muzyka There should be a way to define which skin the editor wants for the applet in the builder

**Comment by peterpeterparker** [comment]
As documented above:

> Themes have to be configured by the team in the database, there is no GUI to create and handle these.

There is an API Endpoint (CRUD) which can be use by the developer or admin to set themes in the database. 

> If no themes are defined, no theme should appear in the administration panel and nothing should change across the platform and apps, UI remains the same.

If no themes are defined, set in the database, there are no themes available in the administration panel respectively the editor cannot select a theme. If there are themes defined, then a dropdown with a list of themes is made available in the applet builder of the administration console.

**Comment by WorldImpex** [comment]
@peterpeterparker When will a theme be added so we can QA?

**Comment by peterpeterparker** [comment]
Do not know. That should probably be discussed between Wil, Anirudh and @BarrySunderland 

For QA I guess you can also define "a theme", does not have to be "the theme".

**Comment by WorldImpex** [comment]
@natalia-muzyka Yes these are expected behaviors. Thanks for the detailed write up!

**Comment by natalia-muzyka** [comment]
As per the comment above, the requirements are met. Verified and closed.
