### ISSUE TITLE
Previously created ped screener applets are disappeared from the mobile app (after refreshing on the admin panel the applets are still hidden)

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#1888]
**Preconditions**
The mobile app is installed and launched

**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Log in to the account with the previous version of pediatric screener:
geria.test@gmail.com // 123456
3. Open the mobile app and log in to the same account
4. Compare the applets list on the admin dashboard and mobile app
5. Observe the result

**Actual result**
Previously created ped screener applets are disappeared from the mobile app.

**Expected result**
The applet list in the mobile app is displayed according to the user's access and roles.

**Notes**
After refreshing on the admin panel (for the applet that wasn't previously edited) the applet is still hidden on the mobile app.

**Video:** https://www.screencast.com/t/uxF22w6lorx2

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 // Chrome 92.0.4515.107
ML v0.17.8 (staging)
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0
iPhone 6 Plus // iOS 12.3.1
geria.test@gmail.com // 123456
applets:
Mental Health Screening Survey: English
Mental Health Screening Survey: English (1)
Mental Health Screening Survey: English (2)
applet password: Qwe123!!!
schema:
https://raw.githubusercontent.com/ChildMindInstitute/Pediatric_screener_applet/master/protocol/HBN_PMHS/HBN_PMHS_schema

**Comment by WorldImpex** [comment]
HBN has created a new ped screener using the applet builder so developer efforts have stopped supporting the GitHub version of ped screener

**Comment by natalia-muzyka** [comment]
I assume this ticket can be closed because of its irrelevance?

**Comment by WorldImpex** [comment]
agreed
