### ISSUE TITLE
The watermark is displayed with an incorrect ratio (stretched horizontally)

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#1894]
**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Create a new applet with at least one activity
3. Add a watermark 101.jpg
4. Save the activity
5. Complete the activity with a watermark on the mobile app 
6. Pay attention to the screen

**Actual result**
The watermark is displayed with an incorrect ratio (stretched horizontally)

**Expected result**
The watermark is displayed with the correct ratio on the top left corner of the activity page.
The watermark should overlap content on the page.
Mockup: https://www.screencast.com/t/xtRnaHC1tS

**Screenshot:**
https://www.screencast.com/t/o82hUjln

**Environment**
ML v.0.17.9 (staging)
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0
iPhone 6 Plus // iOS 12.3.1
geria2.test@gmail.com // McgzF127
applet: watermark test, watermark test new, watermark from URL
Applet password: Qwe123!!!

**Comment by binaryExDev** [comment]
@natalia-muzyka I'm not certain if I use a static width with the ratio. Btw, this is what I fixed the issue.

![Screen Shot 2021-08-04 at 8.13.19 PM.png](https://images.zenhubusercontent.com/5fc8d89138215d1055c6d606/2029fd28-bd17-47eb-99b0-6cb21a4ea695)

**Comment by natalia-muzyka** [comment]
@binaryExDev could you make, please, the watermark smaller (80% of the current size) and put it on the top left corner in the scope of this ticket? thank you)
for example https://www.screencast.com/t/xtRnaHC1tS

**Comment by natalia-muzyka** [comment]
Verified as fixed
https://www.screencast.com/t/rmeNKdMp11

Environment
ML v.0.17.13 (staging)
Samsung Galaxy Tab S6 SM-T865	// 9.0
iPad Air 2 Wi-Fi // 14.6
iPhone 7	// 13.1.1
Samsung Galaxy S7 Edge SM-G935FD	// 8.0
