### ISSUE TITLE
The video recording is missing in the exported csv file and ZIP archive

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#1906]
**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Log in: avani_ml@protonmail.com	// 12345678
3. Create a new activity with media items: photo, video, audio record, drawing
4. Complete the activity on the mobile app, add all the media (take a photo, record a video, record audio, draw smth)
5. Proceed to the admin panel/users tab
6. Export data
7. Compare the actually added data on the mobile app, displaying the responses in csv exported file and archive

**Actual result**
The video recording is missing in the exported csv file and archive

**Expected result**
All the added to the activity media files are exported successfully. Responses are displayed in the csv file.

**Screenshot:** https://www.screencast.com/t/k8Yx8t5KcTK

**Environment**
https://admin-staging.mindlogger.org/
owner: avani_ml@protonmail.com // 12345678
user: maddison_ml@protonmail.com //	qwertyuio
applet: media export
Applet password: Qwe123!!!
ML v0.17.14 (staging)
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0	
iPhone 7 // iOS 13.1.1

**Comment by WorldImpex** [comment]
.Quicktime file cannot be played on macbook pro

**Comment by HarutQA** [comment]
Bug is reprodusable

Steps to reproduce
1. Open a site https://admin-staging.mindlogger.org/
2. Log in: avani_ml@protonmail.com // 12345678
3. Create a new activity with media items: photo, video, audio record, drawing
4. Complete the activity on the mobile app, add all the media (take a photo, record a video, record audio, draw smth)
5. Proceed to the admin panel/users tab
6. Export data
7. Compare the actually added data on the mobile app, displaying the responses in csv exported file and archive

Actual result
"View Data" section is empty. Audio record chart do not exist.

Expected result
There should be information on "View Data" screen
![Screen Shot 2021-08-23 at 19.48.15.png](https://images.zenhubusercontent.com/61125099ad96283f91ec1d29/381d8300-48e8-4583-8b2e-86af0b2de8ca)

Environment
https://admin-staging.mindlogger.org/
owner: avani_ml@protonmail.com // 12345678
user: maddison_ml@protonmail.com // qwertyuio
applet: Test 1906
Applet password: Harutyun910325$
ML v0.17.19 (staging)
red Note 9 // Android 11
iPhone 11 Pro // iOS 14.7.1

**Comment by HarutQA** [comment]
Works correct, downloaded file has all the answers.
![Screen Shot 2021-08-23 at 21.15.33.png](https://images.zenhubusercontent.com/61125099ad96283f91ec1d29/41a2cfb5-9a59-4797-9722-f6e7c9d9589f)

Environment
https://admin-staging.mindlogger.org/
owner: avani_ml@protonmail.com // 12345678
user: maddison_ml@protonmail.com // qwertyuio
Applet password: Harutyun910325$

Redmi note 9// Android 11
iPhone 11 Pro // iOS 14.7.1
