### ISSUE TITLE
Only one activity is shown up after the user achieved the treshold for both cumulatives

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#1912]
**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Log in: avani_ml@protonmail.com	12345678
3. Create a new applet with at least two activities
4. Create third activity and set up :
- at least three items with option scores
5. Create cumulative item with at least two cumulatives
- for cumulative 1 select the item1 + item2 scores, and displaying the activity 1 if user meet the threshold
- for cumulative 2 select the item3 scores, and displaying the activity 2 if user meet the threshold
6. On mobile app start a cumulative activity (#3)
7. Meet the threshold for both cumulatives
8. Complete the assessment and pay attention to the screen

**Actual result**
Only one activity is shown up after the user achieved the threshold for both cumulatives

**Expected result**
All the activities are added accordingly to the user's progress (two activities are added)

**Video:** https://www.dropbox.com/s/b2awz0f2wquadn9/video-1a27551bf24fc8d1538897ffdca3bbab-V.mp4?dl=0

**Environment**
https://admin-staging.mindlogger.org/
avani_ml@protonmail.com	12345678
applet: activity based on cumulative score
applet password: Qwe123!!!
ML v0.17.15 (staging)
Moto G5 Plus // Android 8.0
iPhone 7 // iOS 13

**Comment by Matchdev120** [comment]
@WorldImpex Would you please explain the expected result?

Actually, I'm not sure what should happen after the user achieved the treshold for both cumulatives.

**Comment by WorldImpex** [comment]
If the applet has multiple cumulative score groupings and 2 or more thresholds are met that are supposed to show an activity. Only one activity is shown

**Comment by WorldImpex** [comment]
Works as expected. New issue 

If the user takes the assessment more then once then the activities shown is reset 

Steps to recreate 
1. Take an assessment with more than one activity to be shown 
 avani_ml@protonmail.com 12345678 | Cumulative with multiple activities 
2. Take assessment once to score under 4 total points 
3. See activity 3 shown 
4. Take assessment again with score above 4 
5. See activity 1 and 2 shown 
6. See Results 

Expected: User should see activity 1,2 and 3
Actual: Every time an assessment is taken the activities shown is reset.

**Comment by HarutQA** [comment]
Fixed, tested during regression testing.
