### ISSUE TITLE
PROD Translation issue

### ISSUE THREAD

**Issue by HarutQA** [ChildMindInstitute/mindlogger-app#1929]
Steps to reproduce
1. Open https://admin-staging.mindlogger.org/#/login?lang=en_US
2. Change language into French
3. Log in. Example: haruttsd@gmail.com / harut91
Pay attention to the "CONFIGURE AN APPLET" button

**Actual result**
"CONFIGURE AN APPLET" button is in English

**Expected result**
"CONFIGURE AN APPLET" button should be in French - CONFIGURER UNE APPLET

Environment
Macbook Pro Chrome Version 92.0.4515.159

**Comment by WorldImpex** [comment]
Button was updated to Build/ Edit an applet - CRÉER/MODIFIER UNE APPLET

**Comment by natalia-muzyka** [comment]
Verified as fixed
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/1a835c1d-73b9-4ebe-9524-63de3433e00e)

Environment:
https://admin-staging.mindlogger.org/
Windows 10 x64 // Chrome 94.0.4606.61
