### ISSUE TITLE
Password eye icon issue

### ISSUE THREAD

**Issue by HarutQA** [ChildMindInstitute/mindlogger-app#1931]
Steps to reproduce
1. Open https://admin-staging.mindlogger.org/#/login?lang=en_US
2. Log in. Example: haruttsd@gmail.com / harut91
3. Select any applet. e.g. First applet
4. Tap on "View Data" 
5. enter any password 
Pay attention to "Enter password" password eye icon

Actual result
Password eye icon works incorrect

Expected result
When password is invisible eye icon should be with closed sign, when password ic visible eye icon should be without close sign

https://matter-lab.slack.com/files/U02AMARB2TD/F02CTT5N20K/screen_recording_2021-08-27_at_23.03.44.mov

Environment
Macbook Pro Chrome browser

**Comment by jj105** [comment]
@HarutQA could you please put url in the channel and upload link to it? ( it's not viewable on my side )

**Comment by HarutQA** [comment]
@jj105 Do you see the video now?
https://matter-lab.slack.com/files/U02AMARB2TD/F02D6PXJ717/screen_recording_2021-08-27_at_23.03.44.mov

**Comment by natalia-muzyka** [comment]
Not a bug:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/5bbc7b20-1539-478e-a27e-5142ef33a521)
