### ISSUE TITLE
Update ToolTip Icon 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1932]
Update the design of the tooltip on mobile and webapp to the below 

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/23219e9b-7973-4e03-ae23-65e9d888248f)

**Comment by natalia-muzyka** [comment]
**Issues:**
[UI] The tooltip icon design doesn't match the requirements [#1941](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/1941)
Website tooltip issues [#133](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-web/133)

**Comment by natalia-muzyka** [comment]
Verified and closed.
