### ISSUE TITLE
Token Chart Refresh 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1942]
As a user, I want to see a new token chart with a better UI so that I am more engaged in earning tokens 

Requirements
- Update the icons at the button of the screen when a token activity is within an applet 
- Always show the user's total accumulated tokens 
- The chart should show tokens as they accumulate 
- Allow the user to change the chart by day, week, 2 weeks, 1 month, 3 months, 1 year and all 
   - Each time the time duration is changed, the 'total earned since' and total occurrences for each response option is updated to reflect that time range 
   - In the day view, show starts at each point an assessment was completed 
- Average distress and impairment is based on that time range and should show for each response option. 
- If there are other items within the activity then at the bottom show the regular data visualization for radio, checkbox, slider etc. 
- The color of the behaviors is related to if they are positive (in blue) or negative (in purple) 
- [Design assets](https://xd.adobe.com/view/3b371973-24ef-4965-85b4-8fd01ac87f28-6e64/screen/10ac8dc7-fcc5-40fe-af6d-547219fe7bca/)

**Comment by natalia-muzyka** [comment]
@WorldImpex @jj105 
Token chart screen is totally different from the latest assets that were published in the [slack channel](https://matter-lab.slack.com/archives/CEHC2AVTJ/p1635539239009800).
Link to the latest assets from the slack channel: 
https://xd.adobe.com/view/c550ec48-7d76-4f21-90e2-0e71bcec4948-9003/screen/1814dc2f-f47c-4d5d-8c15-96cce87dd948/specs/

Can anyone clarify, please, is the old design expected for the first version of TL applet?

**Comment by WorldImpex** [comment]
@natalia-muzyka Lets stick with the older design. We will update to the newest on a future version

**Comment by WorldImpex** [comment]
Chart crashes when navigating to it 
Steps to recreate
1. Log into mobile device (iPhone 13 pro) 
2. Navigate to TokenLogger Activity 
3. Open Data tab and wait 3-5 seconds 
4. See results 

Expected: Data is loaded and user can scroll up and down 
Actual: There is a crash 

account:
bernard_ml@protonmail.com // qwe123!!!
applet: tokenlogger applet positive
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
Waiting for fix: [Mobile app + admin panel] The past earned tokens quantity is not reflected below the total quantity accordingly to the selected time range#2338

**Comment by natalia-muzyka** [comment]
Works as expected on the mobile app side.

Environment:
ML v0.18.47 staging
Samsung Galaxy S7 Edge SM-G935FD // Android 8
iPhone 8 Plus // iOS 13.3
Samsung Galaxy Tab S6 SM-T865 // Android  9.0
iPhone 7 // iOS 13.1.1
iPad Pro (10,5-inch) MQDX2 // iOS 15
iPhone 6S // iOS 14.4.2
