### ISSUE TITLE
The report at the end of the mobile doesn't reflect the new cumulative score fields

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#1946]
**Preconditions**
The mobile app is installed and launched
The user is logged in to the mobile app and admin panel:
https://admin-staging.mindlogger.org/
avani_ml@protonmail.com // 12345678

**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Create a new applet with cumulative activity:
- allow the user to see results
- fill the overview, cumulative score description, select the scale(score) direction (or leave a default value)
3. Save the activity
4. Open a mobile app
5. Proceed to the cumulative score activity
6. Select any responses on each screen (proceed to the cumulative summary screen)
7. Pay attention to the screen

**Actual result**
The report at the end of the mobile doesn't reflect the new cumulative score fields

**Expected result**
The report at the end of the mobile should reflect the new cumulative score fields as per the [requirements](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/1785)
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/37e402d7-618b-4534-8475-3eed9bad9c15)

**Screenshot:** ![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/07274bb8-4226-40a8-bae0-8534b1fd943b)

**Environment:**
ML v0.17.25 (staging)
iPhone SE (2020) // iOS 14.2
Samsung Galaxy S7 SM-G930FD // Android 8.0
avani_ml@protonmail.com // 12345678
applet: pdf export test
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
@Sshetty2
Reproducible for webapp pdf report as well:
The new fields aren't displayed in the webapp report (summary page).

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/c91867f7-727b-4d5e-9cef-8812ad9f0c22)

Win 10 // Chrome 93.0.4577.82
applet / activity: pdf export test / cumulative activity
avani_ml@protonmail.com // 12345678
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
the behavior is the same.
was it accepted as a correct behavior?
@WorldImpex @Sshetty2 
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/37108c7b-a358-454a-824f-07a2c573b2f0)

**Comment by WorldImpex** [comment]
@natalia-muzyka Summary screen should be shown on webapp as well

**Comment by natalia-muzyka** [comment]
The summary screen reflects the new fields with some issues.
Mobile markdown issues I added here in the related [ticket](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/1947).

**1) [webapp summary page] The score and cumulative item description are displayed in the wrong order**
Expected: the description should go first, as on the mobile app and in the applet builder
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/430fd439-3813-4020-84cd-b4293aeb07ff)

**2) The progress bars are missing in the mobile and the webapp summary as well.** 
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/5e665f24-7c13-4197-9a9c-17a9e269dd2b)

**Comment by WorldImpex** [comment]
This is the right summary view - current view with only adding the new fields (overview, items descriptions, but without progress bars)

**Comment by natalia-muzyka** [comment]
The cumulative fields on webapp are still displayed in the same order: 
1) cumulative score title, 
2) user's score, 
3) cumulative score description,
4) message (at or above, etc)

On the mobile app and in the applet builder the cumulative score description goes before the user's score.
@WorldImpex We can leave this displaying as acceptable (we have no requirements for that, I was only comparing with the mobile app), wdyt?

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/cadef7ce-ff2a-43dd-847b-2930bcfbcd7c)

**Comment by WorldImpex** [comment]
Yes lets fix in next milestone so the reports are the same @natalia-muzyka

**Comment by natalia-muzyka** [comment]
Created a separate ticket for the ordering:
https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-web/161

Verified and closed.
