### ISSUE TITLE
The admin panel and mobile PDF report issues / differences

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#1950]
**Preconditions**
The mobile app is installed and launched
The user is logged in to the mobile app and admin panel:
https://admin-staging.mindlogger.org/
avani_ml@protonmail.com // 12345678
There is a cumulative score activity with allowed ability to see results 
applet / activity: pdf export test / cumulative activity

**Steps to reproduce**
1. Open a mobile app
2. Proceed to the cumulative score activity
3. Select any responses on each screen (proceed to the cumulative summary screen)
4. Download the pdf report 
5. Proceed to the user's DataViz on the admin panel
6. Download the pdf report
7. Compare the mobile app report and the admin panel report with the [mockup](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/68e3f8d7-f174-4cd2-b089-b9de2377331e)
8. Observe the result

**Actual result**
The admin panel report is presented in the desktop view, the mobile report is in the mobile view.
1. The "Your/Your Child's Score" title is missing in both reports above the progress bar.
2. @WorldImpex could you confirm, please: this is the possible max score value on the mockup? (confirmed)
3. The achieved score isn't reflected in the admin panel report. Both conditionals are displayed in the report.
The conditional (if score...) is missing in the mobile report. The user's score and appropriate message are displayed on the different rows.
**Screenshot:**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/a75e8c92-4827-4d4f-9035-2330d886d638)

**Expected result**
Both reports are exported/shared in the **desktop** view. This should be the same report.
1. The "Your/Your Child's Score" title is displayed above the progress bar.
2. [UPD] confirmed by Wil: The possible max score value is displayed below the progress bar.
3. [UPD] confirmed by Wil: 
- there should be only one conditional (if score...) in the report (which is achieved by the user);
- there should be a pattern(sentence) with integrated cumulative score title and user's score: "Your/Your child's score on the ***cumulative score title*** subscale was ***user's score***". And right after it should go the appropriate message, that was specified in the applet builder (at or above, out of range etc). 

**Environment:**
https://admin-staging.mindlogger.org/
ML v0.17.25 (staging)
iPhone SE (2020) // iOS 14.2
avani_ml@protonmail.com // 12345678
applet: pdf export test
Applet password: Qwe123!!!

Mobile report:
https://app.zenhub.com/files/103405139/0f3fa898-277e-4bc4-9b90-eb8a2a3fa8c1/download
Admin panel report:
https://app.zenhub.com/files/103405139/707b74d5-563b-430c-8ce4-a33cbebb8fd3/download

**Comment by WorldImpex** [comment]
@natalia-muzyka 
2. Yes you are correct
3. Yes your assumptions are true. These mockups were provided to us so I think we need to stay within the requirement for them for now

**Comment by natalia-muzyka** [comment]
@WorldImpex thank you, I've already updated a ticket

**Comment by natalia-muzyka** [comment]
@Sshetty2 
the webapp report looks the same as on mobile app 9mobile view instead of the desktop view)
Video: https://www.screencast.com/t/D4ZsNb0SG

**Comment by natalia-muzyka** [comment]
There are few new issues:

**1) [admin panel] The Overview and Cumulative score title description are missing admin panel pdf report:**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/a4f788d4-9db2-495a-b141-1c893c44084f)

**2) [mobile][webapp] The "Your/Your Child's Score" title is trimmed when the user's progress is nearly on the edge case. 
[admin panel]  The "Your/Your Child's Score" title is displayed in a few rows.**
Expected: it should be displayed centered, above the progress bar
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/3d549e14-b2da-45c9-a054-75954e1f2b87)

**Comment by natalia-muzyka** [comment]
#1, 2, 4, and 5 from the comment above are fixed

**Still reproducible:**
**3) [UI][admin panel report] The "Your/Your Child's Score" title is displayed in a few rows and overlaps the progress bar**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/2ef6d9f6-ffea-47d7-b9d7-0ce2f2f23010)

**6) [UI][webapp report] The font styles issues in the pdf report
-the conditional (IF SCORE...) is displayed as a regular text instead of bold + italic**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/d717d917-79b0-4afd-bd22-2e04e94e9a15)

---
**New UI/UX issues:**
**7) [webapp report][admin panel report] The uploaded image (1920x1920 px jpg) is missing in the report**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/4fc27300-7ac7-4a19-884a-035cc2665549)

**8) [mobile report] The uploaded image (1920x1920 px jpg) is trimmed on the right (isn't adaptive to the report width)**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/b8d668b3-242d-4342-bbfa-fef4f5163358)

**9) [webapp report][admin panel report] The progress bars are too big (in comparison with the mobile report)
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/2b171f29-673c-4b04-8290-96bb544d2b7d)

**10) [mobile report] The font size is too small in the exported mobile report (isn't comfortable to read)**
The font size is different between platforms
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/708cb155-4f6b-41cb-80ec-d408dbe6cb33)

**Comment by WorldImpex** [comment]
@Sshetty2  Just so it is clear, the intention for the summary on web and mobile is everything but the progress bars "This is the right summary view - current view with only adding the new fields (overview, items descriptions, but without progress bars)"

**Comment by natalia-muzyka** [comment]
moved #7 and 8 to the new ticket [#1964](https://github.com/ChildMindInstitute/mindlogger-app/issues/1964)

**Comment by natalia-muzyka** [comment]
#3:  [UI][admin panel report] The "Your/Your Child's Score" title is displayed in one row, but it is left-trimmed when the score is small:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/64c997ba-830c-4b1e-82b8-a910ac00a68c)

#6 fixed: 
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/71f0c025-ab16-434c-a598-39c0c191a20e)

**Comment by WorldImpex** [comment]
@Sshetty2 Please fix 3 & 6 with priority

**Comment by natalia-muzyka** [comment]
Verified as fixed:

#3 [UI][admin panel report] The "Your/Your Child's Score" title 
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/7f626b82-01a0-44da-8403-dd424b17c400)

#6 [webapp report] the cumulative activity title 
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/6dbe8fe1-d955-453d-8788-085b3f3af88a)
