### ISSUE TITLE
Shared with email pdf report isn't received

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#1951]
**Preconditions**
The mobile app is installed and launched
The user is logged in:
avani_ml@protonmail.com // 12345678
There is a cumulative score activity with allowed ability to see results

**Steps to reproduce**
1. Open a mobile app
2. Proceed to the cumulative score activity
3. Select any responses on each screen (proceed to the cumulative summary screen)
4. Share the report by email
5. Proceed to a receiver mailbox
6. Pay attention to the screen

**Actual result**
Shared with email pdf report isn't received

**Expected result**
Shared with email pdf report is received

**Video:** https://www.screencast.com/t/ehG6a1N0BU

**Environment:**
ML v0.17.25 (staging)
iPhone SE (2020) // iOS 14.2
avani_ml@protonmail.com // 12345678
applet: pdf export test
Applet password: Qwe123!!!

**Comment by jj105** [comment]
@natalia-muzyka I think it works on @WorldImpex 's physical device
I think there might some configurations needs to be checked/fixed on your mailing app on your phone ( I think you can discuss with @WorldImpex if you need help on that )

**Comment by natalia-muzyka** [comment]
@jj105 thank you, probably you were right about my mailing box.
I've just tested again (on IOS and Android) and it works well now.
I'm able to see previous reports as well (those that are related to this ticket).
So I close the ticket as the issue isn't reproducible anymore.
