### ISSUE TITLE
The timer is restarted after resuming the activity

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#1971]
**Preconditions**
The mobile app is installed and launched
The user is logged in:
loui_ml@protonmail.com // 12345678
There is an activity with the drawing item. (applet: timer test, activity 3)
The "Set timer response" is activated on the item (e.g. 15 seconds). 

**Steps to reproduce**
1. Open the activity in the mobile app
2. Proceed to the drawing item
3. Draw something
4. Close the activity while the timer is working
5. Resume the activity (e.g. in a few seconds)
6. Pay attention to the screen

**Actual result**
The timer is restarted after resuming the activity

**Expected result**
The timer should continue or complete if the user resumes as per the [requirements](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-builder/6)

**Notes: The timer is also restarted after tapping the "Back" button and proceeding again to the same screen**

**Video:** https://www.screencast.com/t/iHBBrkavfU

**Environment**
ML v0.17.33 (staging)
iPhone SE (2020) // iOS 14.2	
Samsung Galaxy S7 SM-G930FD // Android 8.0
owner:
johndoeregress@protonmail.com // 12345678
users:
loui_ml@protonmail.com // 12345678
alyssia_ml@protonmail.com // qwertyuio
applet timer test: activity 3
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
@mtg137 @WorldImpex could you confirm, please, are my expectations correct in the next case?

**Case:**
The app goes to the background after the timer is started.

**Actual behavior (on iOS and Android):** 
When time is up the new screen is automatically triggered (in the background). 
If the new screen has a timer as well, it starts working (still in the background). 

**Expected behavior:** 
When time is up the new screen is automatically triggered (in the background). 
If the new screen has a timer as well, this timer should start working only after resuming the activity.
The timer on the new screen shouldn't start working in the background. 

**Video:** https://www.screencast.com/t/CVKfc8skBAvB

**Comment by WorldImpex** [comment]
@natalia-muzyka No the timer should continue to run in background mode

**Comment by mtg137** [comment]
I discussed with @WorldImpex about this previously

1) let's say that I have an activity with 3 screens, and all screen has 10 secs time limit
I started activity mobile app and closed screen.
if I reopen activity 30 secs later, I should see a "thank you" page

2) if user taps "back" button and proceeding again to the same screen then timer should be restarted

**Comment by natalia-muzyka** [comment]
Ok, thank you both for clarification!
In this case, the issue is verified as fixed.

Environment:
ML v0.17.40 (staging)
iPhone SE (2020) // iOS 14.2
Samsung Galaxy S7 SM-G930FD // Android 8.0
owner:
johndoeregress@protonmail.com // 12345678
users:
loui_ml@protonmail.com // 12345678
alyssia_ml@protonmail.com // qwertyuio
applet timer test: activity 3
Applet password: Qwe123!!!
