### ISSUE TITLE
Incorrect punctuation spacing in the French version

### ISSUE THREAD

**Issue by lioneldeveauxcri** [ChildMindInstitute/mindlogger-app#1974]
French punctuation rules are not correctly followed in the French version of the app.
In French, the following punctuation marks:
:
;
?
!
should always be preceded by a space, preferably a non-breaking space.
Example: in the "about" page, "Qu'est-ce que Mindlogger?" should be "Qu'est-ce que Mindlogger ?"

**Comment by natalia-muzyka** [comment]
Fixed on About, About (applet), Thank you, pop-up (restart/resume)
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/623faff0-41c3-4c2d-933a-0355b12bbdd1)

iPhone 8 Plus // iOS 13.3
Samsung S7 // Android 8
