### ISSUE TITLE
"Location saved" message when using an applet twice the same day

### ISSUE THREAD

**Issue by lioneldeveauxcri** [ChildMindInstitute/mindlogger-app#1976]
If I answer an applet containing a geolocation item twice the same day: the second time, the message "location saved" is already there before I tap the button

**Comment by natalia-muzyka** [comment]
Verified as fixed.
Video: https://www.screencast.com/t/z6y8b24nkGW

Devices:
iPhone SE 2020 // iOS 14.2
Samsung S7 // Android 8
Samsung Tab S6 // Android 9
