### ISSUE TITLE
Delays in the drawing process

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#1982]
**Steps to reproduce**
1. Install and launch the app
2. Log in: janedoeregress@protonmail.com	// %pVgPJ*O
3. Proceed to the activity with a draw item
4. Start drawing
5. Pay attention to the screen

**Actual result**
There are delays in the drawing.

**Expected result**
There are no delays, the drawing process is smooth. 

**Video:** https://www.screencast.com/t/kmfmyYXE0BeM

**Environment:**
ML v0.17.36 (staging)
iPhone 6S // iOS 14.4
janedoeregress@protonmail.com	// %pVgPJ*O
applet: media export check
activity: drawing

**Comment by natalia-muzyka** [comment]
Delays started to be reproducible on Android on ML 0.17.39 (staging).
Video: https://www.screencast.com/t/vfIqYhLYdiU

**Comment by WorldImpex** [comment]
@binaryExDev What is the status of this?

**Comment by WorldImpex** [comment]
@natalia-muzyka Could you retest ot see if this is an issue on the latest version?

**Comment by natalia-muzyka** [comment]
@WorldImpex drawing is much smoother now, but if I try to draw smth quickly, there is a delay:
https://www.screencast.com/t/HRz8pJsnK

ML v0.17.76 (staging)
iPhone 6S // iOS 14.4

**Comment by WorldImpex** [comment]
We can reopen if this becomes an issue again

**Comment by natalia-muzyka** [comment]
Issue is reproducible

Video: https://www.screencast.com/t/WEfgQaTcqE

Environment:
ML v0.18.42 staging
Samsung Galaxy S7 Edge SM-G935FD // Android 8
Samsung Galaxy S7 // Android 8

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/duhf3ciR

Environment:
ML v0.18.44 staging
Samsung Galaxy S7 Edge SM-G935FD // Android 8
iPhone 6S // iOS 14.4
