### ISSUE TITLE
Update Splash Screen button from Skip to "next" 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1985]
![File.jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/58641a1d-98ba-42bd-8a15-35abfdf7c6d1)

**Comment by Matchdev120** [comment]
@Wil @natalia-muzyka Do you have an applet with splash screen?

**Comment by natalia-muzyka** [comment]
@Matchdev120 
geria2.test@gmail.com // McgzF127
applet: All (1)
Applet password: Qwe123!!!
activities:
header image (URL gif)
header image (1) (uploaded mp4)

**Comment by Matchdev120** [comment]
Thank you!

**Comment by natalia-muzyka** [comment]
Verified as fixed.
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/c4e87a1b-425a-4088-b3db-a89b20dd5c4d)

Environment:
ML v0.17.39 (staging)
geria2.test@gmail.com // McgzF127
applet: All (1)
Applet password: Qwe123!!!
activities:
header image (URL gif)
header image (1) (uploaded mp4)
