### ISSUE TITLE
Upload image for About Page in TokenLogger 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2000]
- Upload an image to the about us page that fills the page 
   - Give an editor the ability to either configure an about screen with text or with a full page image
    - Display the size the user should upload
    - Allow the user to replace and delete 
    - Editor cannot use text and image upload at the same time
![mindlogger-admin.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/54744b90-7ade-47ad-91f2-9d5749b82c2e) 

[https://app.zenhub.com/files/103405139/8d707277-a187-4894-bcda-60a2bc2c1a2e/download](https://app.zenhub.com/files/103405139/8d707277-a187-4894-bcda-60a2bc2c1a2e/download)

**Comment by natalia-muzyka** [comment]
@WorldImpex @mtg137 accordingly to the attached requirements (presentation), as I understand, a user should have the ability to specify an image and text as well. So the requirement in the ticket:

> Editor cannot use text and image upload at the same time

means that uploading the text and uploading the image just should be divided into two options (windows), right? But user should be able to upload both. Currently, user isn't able to specify both at the same time. Just text or image:
https://www.screencast.com/t/kHPFIjuH

**Comment by natalia-muzyka** [comment]
@WorldImpex other than that is it expected that 
- the edit About screen is changed now for all the applets
- the Markdown stands as a separate option

**Comment by WorldImpex** [comment]
Yes I think they should be separate and it should be a global change @natalia-muzyka

**Comment by natalia-muzyka** [comment]
@mtg137 as per the discussion with @WorldImpex :
1. The option "text" should be removed
(we need to have only two options: for uploading old markdown OR upload image)
2. I suggest showing options as regular context menu options (without checkboxes), 'cause checkboxes are multivariant, and we need to have just a single select (markdown OR image)
3. I assume, that "Add markdown" should be renamed to "Add text"?

**Comment by WorldImpex** [comment]
Yes this looks good @natalia-muzyka

**Comment by natalia-muzyka** [comment]
1. The uploaded image is centered vertically and horizontally. 
The landscape-oriented image width fits the "About" tab width.
The portrait-oriented image width fits the "About" tab height.
@WorldImpex could you clarify, please, is this expected result or image should fill the screen? And if it should fill the screen, is this a case as w have with the Splash image (when we use specific image size), or image should be just centered and trimmed to fill the screen (e.h. how it works with applet image on the home screen and activity image on the activity card)?

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/5c870956-6b0a-4752-9c13-e6e927da4003)

2. Background theme is missing on the About tab

**Comment by WorldImpex** [comment]
Image should fill screen and an image size should be required when uploaded so the user is successful in doing so @natalia-muzyka

**Comment by natalia-muzyka** [comment]
@WorldImpex so if I understand correctly, it is similar to PDF splash screen.
There will always be an issue because of the different screens sizes/proportions, I suggest: 
1. mobile app: 
- image is vertically and horizontally aligned, 
- image width should fit the "About" tab width ant the rest should be trimmed,
2. applet builder: add info text in the applet builder, that for a better experience (to avoid too pixelate picture) the uploaded image should be portrait-oriented and have at least ~800px width 

Current behavior (700x1000px image on iPhone 6S, iPhone X and iPad Pro 10.5):

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/8088d18c-c517-4e54-9fb2-f1f8699767b5)

**Comment by WorldImpex** [comment]
@natalia-muzyka Agreed

**Comment by natalia-muzyka** [comment]
@mtg137 
1. The uploaded image is not shown on the mobile app (reproducible for TL applet and regular applet).
2. There's no additional info in the applet builder
Video: https://www.screencast.com/t/AhitRce8X6K4

Environment:
https://admin-staging.mindlogger.org/
tl_account9@mail.com 123456
applet: tl test 2, 123
Applet password: Qwe123!!!
ML v0.18.42 staging
Samsung Galaxy S7 Edge SM-G935FD // Android 8
iPhone 7 // iOS 13.1.1
iPhone 6S // iOS 14.4.2
Samsung Galaxy Tab S6 SM-T865 // Android 9.0

**Comment by natalia-muzyka** [comment]
All the issues are fixed. 
Additional (not a blocker): For the image requirements, there are default requirements (100 to 1920 px).
I suggest adding info that the image should have at least 800px for the smallest side to avoid pixelate image on mobile app and at least 1000px on tablets.
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/62b03a16-8e8f-4882-86c3-f535cef4992c)

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/7ef4480d-bd73-4526-9762-319d49f2713c)

Environment:
https://admin-staging.mindlogger.org/
ML v0.18.43 staging
Samsung Galaxy S7 Edge SM-G935FD // Android 8
iPhone 7 // iOS 13.1.1
Samsung Galaxy Tab S6 SM-T865 // Android  9.0
iPad Pro (10,5-inch) MQDX2 // iOS 15
iPhone 8 Plus // iOS 13.3

**Comment by natalia-muzyka** [comment]
Works as expected:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/46d47ea1-cf37-4515-8265-e5db63295c49)

Requirements are met. Verified and closed.

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 98.0.4758.82
macOS 10.15 // Chrome 98.0.4758.82
ML v0.18.43 staging
Samsung Galaxy S7 Edge SM-G935FD // Android 8
iPhone 7 // iOS 13.1.1
Samsung Galaxy Tab S6 SM-T865 // Android 9.0
iPad Pro (10,5-inch) MQDX2 // iOS 15
iPhone 8 Plus // iOS 13.3
