### ISSUE TITLE
The entered text in the text input field isn't accepted by tapping the keyboard return key

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2007]
**Preconditions**
The mobile app is installed and launched.
The user is logged in: alyssia_ml@protonmail.com // qwertyuio
There is an activity with text item: applet "multiple item types" / activity "text input"

**Steps to reproduce**
1. Start the activity on the mobile app
2. Enter any text
3. Tap the keyboard return key
4. Tap outside the keyboard.
5. Observe the result.

**Actual result**
The entered text in the text input field isn't accepted by tapping the keyboard return key

**Expected result**
The entered text in the text input field is accepted by tapping the keyboard return key 

**Video:** https://www.screencast.com/t/DgdLdxyieo

**Environment:**
ML v0.17.41 (staging)
iPhone SE (2020)	// iOS 14.2
IT-10340	Samsung Galaxy S7 Edge SM-G935FD	// Android 8.0

**Comment by WorldImpex** [comment]
Works as expected for iPhone 13 pro

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/2hwHjGmv6

Environment:
ML v0.18.39 staging
Samsung Galaxy S7 // Android 8
iPhone X // iOS 14.6
iPad Pro (10,5-inch) MQDX2 // iOS 15
