### ISSUE TITLE
No scheduled Activities - Do not show "Unscheduled"

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2016]
As a user, I want to see simply activities if there is no schedule so that I do not get confused when I see unscheduled 

Requirements
- Remove "Unscheduled" text when there are no activities that are schedule that day
- The line would remain to keep the date and the activity section separate on mobile 
- This fix is for webapp and mobile

**Comment by natalia-muzyka** [comment]
@astef021 
**Issues:**
Mobile app & webapp: if only some of the activities are scheduled then "Unscheduled" header is displayed
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/90f952fc-bf3b-4f69-b6b8-b3a834c6ed67)

Make space below the dates smaller if unscheduled activities go right below the dates
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/adc10d1b-d9f3-4247-900b-34d0e26cb392)

Environment:
ML v0.19.2 staging
Samsung Galaxy S7 // Android 8
iPhone Xs Max// iOS 15.3
https://web-staging.mindlogger.org/
Win 10 // Chrome 99.0.4844.51

**Comment by natalia-muzyka** [comment]
Issues:
[UI] There's no line that divides unscheduled activities "In progress" from the other unscheduled activities that weren't started yet#405

**Comment by natalia-muzyka** [comment]
@astef021 @Matchdev120   There is an Unscheduled label for unscheduled activities on website:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/fe70936b-3417-41e7-8802-ecd5ceed69d1)

**Comment by Matchdev120** [comment]
![Screen Shot 2022-04-04 at 9.23.46 PM.png](https://images.zenhubusercontent.com/5e248d759c666007f1a71211/79290245-6afc-4f22-b09c-1949ffe935ae)

**Comment by WorldImpex** [comment]
@Matchdev120 Lets go with the blank space from the first one

**Comment by natalia-muzyka** [comment]
@Matchdev120 
there is still an "Unscheduled" label on the website when there are no scheduled activities on the current day:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/028590e7-cb67-4089-8650-c9540dfc8c65)

**Comment by natalia-muzyka** [comment]
**Fixed:** 1 - [web] there is still an "Unscheduled" label on the website when there are no scheduled activities on the current day: https://www.screencast.com/t/gpHX86Cto

---

@Matchdev120 after the latest changes there are still issues:
**still reproducible from the comment above:** 
**2 - [mobile app]** there is no blank space below the activity "in progress", all the activities look like "in progress" _if there are no scheduled activities on the current day_
Video: https://www.screencast.com/t/sqdmmHjdR3
applet: sync test (1)

**new:** 
**3 - [mobile app]** there is no "in progress" section after opening and closing any activity _when some of the activities are scheduled on the current day_ 
Video: https://www.screencast.com/t/QSFijrYPm
applet: mix applet (jeraka)

**4 - [web]** first opening the page, there are some scheduled activities:
- (expected) all the activities are shown as "available"
- (issue) the first activity in the list(the only scheduled activity) has a blank space below
- (expected) after starting any activity below the first activity it is shown with the "in progress" after moving back to the activities list
- (issue) the first activity is still on the very top with the space below and all the other available activities are displayed below the activity "in progress"
Video: https://www.screencast.com/t/GVwuoYBV
applet : optimization test (200 items)

**Environment:**
ML v0.19.18 staging
Samsung Galaxy S7 // Android 8
iPhone XR // iOS 14.3
https://web-staging.mindlogger.org/#/
Win 10 // Chrome 100.0.4896.127 
jeraka1732@wodeda.com	1234567890
Applet password	Qwe123!!!

**Comment by Matchdev120** [comment]
@natalia-muzyka I don't understand the issues in web app.

Would you explain the issues in detail?

 - (issue) the first activity in the list(the only scheduled activity) has a blank space below
 - (issue) the first activity is still on the very top with the space below and all the other available activities are displayed below the activity "in progress"

**Comment by natalia-muzyka** [comment]
@Matchdev120  Issues 2&3 are fixed.
These are reproducible again:
**1 -** [mobile app][web] The "Unscheduled" is displayed again when there are no scheduled/avaliable activities on the current day

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/89f94cc2-ed47-438c-b4b9-8912751abf87)

**4 -** [mobile app][web] the "Unscheduled" is missing when there are scheduled/avaliable activities + UNscheduled activities + activity "in progress"

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/5da5bc5b-2337-49ad-82d5-2c366ddc2f75)

Environment:
https://web-staging.mindlogger.org/#/
ML v0.19.23 staging
iPhone XR // iOS 14.3
Samsung Galaxy S20 // Android 11

---

**Additional cases if it helps:**

**case 1:** 
there are only unscheduled activities on the current day.
_expected_: unscheduled label is NOT shown

**case 2:** 
there are only unscheduled activities on the current day.
one activity is "in progress".
_expected / mobile app:_ unscheduled label is NOT shown. there is only "in progress", and the _divide line_ below activities "in progress". below the line there are unscheduled activities.
_expected / website:_ unscheduled label is NOT shown. there is "in progress", and the _blank space_ below activities "in progress". below the line there are other unscheduled activities.

**case 3:**
there are scheduled/avaliable activities + unscheduled activities on the current day.
_expected_: unscheduled label is shown (as in the old version, which is on prod now)

**case 4:**
there are scheduled/avaliable activities + unscheduled activities on the current day.
one activity is "in progress".
_expected_: unscheduled label is shown (as in the old version, which is on prod now)

**Comment by natalia-muzyka** [comment]
@Matchdev120 issues are fixed on mobile app but still reproducible on **website**:

1 - The "Unscheduled" is displayed when there are no scheduled/available activities on the current day
expected: unscheduled label is NOT shown

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/d18751c2-6358-45e9-b765-c8a71ab0e5fa)

2 - the "Unscheduled" is missing when there are scheduled/avaliable/in progress activities + UNscheduled activities
expected: all the labels are shown including the "unscheduled" label if there are other statuses then "unscheduled"

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/e1ade437-87c9-4946-a0b1-817e8639b991)

Environment:
ML v0.19.25 staging
iPhone XR // iOS 14.3
Samsung Galaxy S20 // Android 11
https://web-staging.mindlogger.org/#/	
jeraka1732@wodeda.com	1234567890
applet with NO scheduled activities: subscales (jeraka)
applet with all the possible statuses: optimization test (200 items)
Applet password	Qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified and closed.

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/d1cbae4b-9a44-447c-87a7-20955f652ed0)

Environment:
ML v0.19.25 staging
iPhone XR // iOS 14.3
Samsung Galaxy S20 // Android 11
Samsung Galaxy S7 // Android 8
Samsung Galaxy Tab S6 SM-T865 // Android  9.0
iPad Pro (10,5-inch) MQDX2 // iOS 15
https://web-staging.mindlogger.org/#/
Win 10 // Chrome 101.0.4951.54 
macOS Catalina 10.15 // Chrome 101.0.4951.41 // Safari 13.1
