### ISSUE TITLE
Mobile app crashes after an attempt to open the activity with stacked items (stacked slider)

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2029]
**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Log in: josephine_ml@protonmail.com // qwertyui
3. Create an activity with stacked items: radio, checkbox, slider
4. Save the applet
5. Start this activity on the mobile app
6. Pay attention to the screen

**Actual result**
Mobile app crashes after an attempt to open the activity with stacked items

**Expected result**
The activity is opened after tapping on it

**Video:** https://www.screencast.com/t/j8GynzHcE
**Crash log (android):** [https://app.zenhub.com/files/103405139/80fec20b-9ecc-4f87-a9a4-4e8246525f01/download](https://app.zenhub.com/files/103405139/80fec20b-9ecc-4f87-a9a4-4e8246525f01/download)

**Environment:**
ML v0.17.47 (staging)
owner: josephine_ml@protonmail.com // qwertyui
applet: all item types
activity: stacked items
users:
loui_ml@protonmail.com	12345678
alyssia_ml@protonmail.com	qwertyuio
Samsung S7 Edge // Android 8.0	
iPhone SE (2020) // iOS 14.2

**Comment by natalia-muzyka** [comment]
@devbtech The issue is reproducible on ML v0.18.3 (staging) with a particular activity

Video: https://www.screencast.com/t/5m69pqyMyq

Environment:
Samsung S7 // Android 8
iPhone 8 Plus // iOS 13.3
kimberly_ml@protonmail.com	12345678
applet: all items (mobile app only)
activity: stacked items
applet password: Qwe123!!!

**Comment by Matchdev120** [comment]
@natalia-muzyka I just tested this applet and activity and it's working fine on my end.
all items(mobile app only) / stacked items

Would you test it once again?

**Comment by natalia-muzyka** [comment]
@Matchdev120  I'm sorry, wrong applet name, it's multiple item types / stacked items:
Video: https://www.screencast.com/t/09Gyqm3Vt
ML v0.18.7 (staging)
iPhone SE 2020 // iOS 14.2
Samsung S7 // Android 8

**Comment by natalia-muzyka** [comment]
Verified as fixed.
Video: https://www.screencast.com/t/FbVTNK0EW3

ML v0.18.9 (staging)
iPhone 8 Plus // iOS 13.3
Samsung S7 // Android 8
