### ISSUE TITLE
Update Tooltip for Stacked Items to be a Hyperlink

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2030]
Remove the asterisk and replace with the text being hyperlinked

 ![Tooltip (1) (1).png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/62a876fb-f1f3-4f90-9c42-2ba94cfa7588)

**Comment by WorldImpex** [comment]
Works as expected. The color of tooltip is black and should remain the light blue color

**Comment by natalia-muzyka** [comment]
Response option text is small and hard to read with light blue color, I suggest to make the text little bit darker:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/0f27ea88-13c0-48bd-b1b0-eab9b3419060)

**Comment by WorldImpex** [comment]
Agreed
