### ISSUE TITLE
Add Splash Screen to PDF Export 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2040]
The Splash screen that is shown on mobile, should be added to the PDF export on webapp and mobile. 

It should take up the full first page of the PDF

**Comment by natalia-muzyka** [comment]
@WorldImpex could you clarify, please:
the splash screen should be displayed as a full separate page before every activity, right?
Right after the activity name and overview, here:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/a5458027-2761-42b4-ace5-f5ee337985bc)

**Comment by WorldImpex** [comment]
@natalia-muzyka It should be the first full page before the text. The usual export should start on page 2

**Comment by natalia-muzyka** [comment]
The latest discussion with @WorldImpex 
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/a9c1c4e0-ffb1-4cac-bf15-4c8a18f0a5bb)

**Issues:**
The PDF report isn't opened after tapping the "Share report" button if there is a splash screen [#2069](https://app.zenhub.com/workspaces/mindlogger-webapp-
5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/2069)
The splash screen is displayed on the summary screen after resuming the activity [#2070](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/2070)
The splash screen image isn't displayed in the admin PDF report [#1314](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/1314)
