### ISSUE TITLE
Remove all text - "Remove text that says if score >= X"

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2042]
Remove text that says if score >= X in PDF export

**Comment by natalia-muzyka** [comment]
Works as expected on:
ML v0.17.60 (staging)
iPhone 8 Plus // iOS 14.2
https://admin-staging.mindlogger.org/
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/1409ad77-a233-4042-95fd-d61b42301cc7)

Testing on Android and webapp is blocked (0.17.60 build is failed and there is still reproducible #1165 on webapp)
