### ISSUE TITLE
Revert to original design of cumulative score 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2043]
We need to revert to the original design of the cumulative score page with a share report  button 

* Only show the cumulative score tiles, message based on threshold met and score. 
* Share report button should still be present as well 

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/e110de89-168f-423f-9861-0b33d1f1aa87)

**Comment by natalia-muzyka** [comment]
Works as expected on:
ML v0.17.60 (staging)
iPhone 8 Plus // iOS 14.2

Testing on Android and webapp is blocked (0.17.60 build is failed and there is still reproducible #1165 on webapp)
