### ISSUE TITLE
Summary Screen for all Token Activities 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2060]
* Show a summary screen at the end of every TokenLogger Activity (past and future) 
* Add Scoring for filling out a background info card and completing an activity 
[Designs and additional specs ](https://docs.google.com/presentation/d/1hBYUvqo6E2ABqh_bqMe56VJjQH0zwRGx-yCHH0MOcrw/edit?usp=sharing)

**Comment by natalia-muzyka** [comment]
@WorldImpex 
1. should be there the "0" value on the behavior icon if user didn't earn any tokens?
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/782b1fc7-d14d-4a89-89dd-4dd1a957da0b)

2. tokens for completing the activity can be earned only after completing the future behavior tracker?
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/37ea374b-236c-4e7f-9764-8c6171fb7c65)

**Comment by WorldImpex** [comment]
1. I dont think we should show in the summary the token items not earned 
2. Retrospective = past and prospective = future. So for everytime a past activity is completed the user should receive 2 tokens

**Comment by natalia-muzyka** [comment]
I'm sorry, question #1 was incorrect, it is the token value for behavior and it should be shown always. There is an issue in displaying the token value (creating report)

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/7dd5658e-f381-4aec-b681-a99b260e2c2d)

**Comment by natalia-muzyka** [comment]
@WorldImpex should user have the ability to turn Back from the Summary screen? On assets there is a Return button Does it mean closing the activity? Currently, user can move back and change selections. Data on Summary screen will be changed accordingly to the new selections.

**Comment by WorldImpex** [comment]
1 Yes 
2 I think we should remove that The user might think that the first submission was saved and go back to add more and lose data. Good catch

**Comment by natalia-muzyka** [comment]
@WorldImpex 
for #2: So if I understand the requirements and your answer correctly, after completing the past behavior activity I should always see 2 tokens earned, right?
And if I complete the future activity, earned tokens depend on the preset timer duration (time option that was selected in the very beginning, but not the actual time that I spent, 'cause I can hit Next before time is up(I assume that is correct).
But in the case of completing an activity with "No time limit", what should be earned?

**Comment by mtg137** [comment]
I think if I complete future behavior activity with "no time limit option", I should earn 2 tokens

and after completing the past behavior activity I should always earn 2 tokens

**Comment by WorldImpex** [comment]
@natalia-muzyka For future behavior tracker, the user has a choice of up to 15 minutes. 
![image](https://user-images.githubusercontent.com/22243307/147692566-183db995-b4b6-47fd-9e14-a34f32481a47.png)


The calculation is based on the time the user spends and the calculation is based on every 5 minutes earning 2 tokens. So as a user if I select 15 minutes then I receive 6 tokens. If I end the session after 10 minutes, then I still receive the 6 tokens from how the requirements are worded I believe - I am double checking that

![image](https://user-images.githubusercontent.com/22243307/147692611-a3faf375-f6e4-48b9-9a8a-b28f5032a810.png)

**Comment by natalia-muzyka** [comment]
Works as expected.
Checked on:
Environment:
ML v0.18.38-39 staging
Samsung Galaxy S7 // Android 8
iPhone X // iOS 14.6
Samsung Galaxy S9 // Android 10
iPhone XS // iOS 15.2
iPad Pro (10,5-inch) MQDX2 // iOS 15
iPhone 8 Plus // iOS 13.3
iPhone 6S // iOS 14.4.2
iPhone 11 // iOS 14.2
Samsung Galaxy S20 // Android 11
