### ISSUE TITLE
Update the Color of the Anchor Text on Sliders for TokenLogger

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2064]
Update the color of the anchor text for the slider (distress/ impairment) 

https://xd.adobe.com/view/c550ec48-7d76-4f21-90e2-0e71bcec4948-9003/screen/1814dc2f-f47c-4d5d-8c15-96cce87dd948/specs/

**Comment by natalia-muzyka** [comment]
Verified on:
ML v0.18.28 staging
Samsung Galaxy S7 // Android 8
Samsung Galaxy S9 // Android 10
iPhone 8 Plus // iOS 13.3
iPhone 11 // iOS 14.2
Samsung Galaxy S20 // Android 11

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/3285c2b2-8123-42f7-a80c-6b28c6ebd220)
