### ISSUE TITLE
The splash screen image isn't displayed in the PDF mobile report

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2072]
**Preconditions**
The user is logged in on the admin panel
https://admin-staging.mindlogger.org/
loui_ml@protonmail.com // 12345678
The mobile app is installed and launched
The user is logged in

**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Create an activity with cumulative item (allow to see results)
3. Add the splash screen to the activity and save the applet
4. Refresh the mobile app
5. Start the cumulative activity, select any responses to see the summary screen
6. Tap the "Share report" button
7. Pay attention to the screen

**Actual result**
The splash screen image isn't displayed in the PDF mobile report

**Expected result**
The splash screen image is displayed as the full first page in the PDF mobile report as per the [requirements](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/2040)

**Video:** https://www.screencast.com/t/pUOBVX9m

**Environment:**
ML v0.17.60 (staging)
ML v0.17.61 (staging)
Samsung S7 // Android 8.0
iPhone 8 Plus // iOS 14.3
loui_ml@protonmail.com // 12345678
applet: cumulative (splash)
Applet password Qwe123!!!

**Comment by natalia-muzyka** [comment]
Testing is blocked by The PDF report can't be opened if there is a splash screen #2080
https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/2080

**Comment by WorldImpex** [comment]
Reproducible

**Comment by Matchdev120** [comment]
@WorldImpex @natalia-muzyka Just tested it and it's working on my end.

**Comment by natalia-muzyka** [comment]
@Matchdev120 issue is still reproducible for PDF mobile report.
Video: https://www.screencast.com/t/lGduLkjLg1

loui_ml@protonmail.com	12345678
applet / activity:
cumulative + splash retest / PC JPG

kimberly_ml@protonmail.com	12345678
applet / activity:
splash screen test (1) / PC 100x100jpg

Samsung S8 // Android 9.0	
iPhone 8 Plus // iOS 13.3

**Comment by WorldImpex** [comment]
PDF shown on iphone 6s

**Comment by natalia-muzyka** [comment]
Splash screen image is displayed in the mobile PDF report.
Verified with:
- uploaded from PC: jpg, png, gif
- URL images:  jpg, png, gif

ML v0.17.71 (staging)
Samsung S7 // Android 8.0	
iPhone 8 Plus // iOS 13.3
