### ISSUE TITLE
Remove Activity Title from PDF Report

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2075]
Remove the activity title from the top of the PDF report for all platforms 

![1409ad77-a233-4042-95fd-d61b42301cc7-758×532- (1).png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/60d49bed-91da-4499-a81e-0d1ff3097eab)

**Comment by natalia-muzyka** [comment]
@WorldImpex the activity name should be replaced by applet name or removed at all?

**Comment by WorldImpex** [comment]
@natalia-muzyka Removed completely

**Comment by natalia-muzyka** [comment]
Activity title is still displayed on mobile app, webapp, admin panel reports
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/2b7ea647-a270-46be-948d-549a53b1b13e)

**Comment by WorldImpex** [comment]
Reproducibile

**Comment by natalia-muzyka** [comment]
@binaryExDev @Matchdev120 
Activity title is removed on admin panel and webapp but **still displayed on mobile app**.
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/e1f3700c-c762-4f24-a39a-c435c81142b1)

ML v0.17.69 (staging)
iPhone 8 Plus // iOS 13.3
Samsung S8 // Android 9

**Comment by natalia-muzyka** [comment]
Activity title is removed on admin panel and webapp.
Waiting for the fix on mobile app.
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/72550d15-5057-4f4e-8933-604edf1a3d54)

**Comment by WorldImpex** [comment]
Title removed from iphone 6s

**Comment by natalia-muzyka** [comment]
Activity title is removed on Android and iOS mobile app as well.
Verified and closed.

https://web-staging.mindlogger.org/
https://admin-staging.mindlogger.org/
ML v017.71 (staging)
Samsung S7 // Android 8.0	
iPhone 8 Plus // iOS 13.3

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/c23e5a40-e97b-470b-bc69-7dcc3b2a061f)
