### ISSUE TITLE
Add a horizontal dividing line and smaller text for Legal - PDF Export

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2076]
The legal jargon at the bottom of the PDF export should be very small (to make it look like a disclaimer) and have a horizontal line above it to separate it. Please also make it the same font as the rest of the doc 

![1409ad77-a233-4042-95fd-d61b42301cc7-758×532-.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/a01d276d-6189-443e-9011-f878006686f2)

**Comment by binaryExDev** [comment]
@natalia-muzyka I don't completely understand the ticket description.
Could you explain it a little more?

**Comment by natalia-muzyka** [comment]
@binaryExDev Wil asks to add a horizontal line right above the "I understand that the information..." text (as it is shown on mockup). So this line will divide the report and legal jargon(terms of use). 
Terms of use("I understand that the information..." text) should have the same font as all the rest text in the document, but needs to be smaller.

@WorldImpex could you clarify, please: the line should be red as on the mockup? I thought would be better if it'll be grey.

**Comment by WorldImpex** [comment]
Yes grey or black is what the color of the line should be @natalia-muzyka

**Comment by WorldImpex** [comment]
legal jargon needs to be the same font and font size 

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/4b7d7809-8b31-463f-8b1e-a2668dd7ba8a)

**Comment by natalia-muzyka** [comment]
@binaryExDev other than the font issue, the horizontal dividing line is missing in webapp report:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/3837043d-1ed1-484f-8fb5-bfa649b93354)

**Comment by natalia-muzyka** [comment]
1) Fixed: A horizontal dividing on webapp report is added
2) The legal jargon font and font size is still not displayed in the same size and font as all the rest text in the report on all the platforms:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/04d3d4f9-365f-49bc-9d53-7a407cb12fba)

**Comment by Matchdev120** [comment]
![Screen Shot 2021-11-16 at 3.22.10 PM.png](https://images.zenhubusercontent.com/5e248d759c666007f1a71211/3a45b44a-47ab-40cb-8a5c-63d2a3f6d233)

**Comment by natalia-muzyka** [comment]
@Matchdev120 On webapp and admin panel the second block of legal jargon(caps) looks almost the same size as the rest text. You can compare with Message at or above(caps). And it feels like the 1st block has a smaller font size than the 2nd.
Should this be fixed or we can leave it as acceptable? @WorldImpex 

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/4178e43d-2356-41cd-978b-1a98ec5c73a5)

Environment:
https://web-staging.mindlogger.org/
https://admin-staging.mindlogger.org/
Win 10 //Chrome 96.0.4664.45
macOS 10.15 // 
ML v0.17.73 (staging)
iPhone 8 Plus / iOS 13.3
Samsung S7 // Android 8
Samsung Tab S6 // Android 9

**Comment by WorldImpex** [comment]
Please fix @Matchdev120

**Comment by Matchdev120** [comment]
@WorldImpex @binaryExDev The 1st block and 2nd block have the same font-size.
But in English, the capital letters look a little bigger than small letters. Do we still need to modify the font-size for the 2nd block?

**Comment by natalia-muzyka** [comment]
Verified as fixed:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/c082dcd0-7874-40d9-bbea-04c5f290f0db)
