### ISSUE TITLE
The "false" tooltip is added to the response options after the "hide" option was deactivated on the radio item

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2077]
**Preconditions**
The user is logged in on the admin panel
https://admin-staging.mindlogger.org/
kimberly_ml@protonmail.com // 12345678
The mobile app is installed and launched.
The user is logged in.
There is an applet uploaded via github schema on the account with radio item (e.g. DBT, EMA)

**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Proceed to the applet builder of the applet 
3. Edit activity with radio item: activate hide option on the item
4. Save the changes, check displaying on the mobile app
5. Edit activity:  deactivate hide option on the item
6. Save the changes, check displaying on the mobile app
7. Observe the result

**Actual result**
The "false" tooltip is added to the response options after the "hide" option was deactivated on the radio item

**Expected result**
There are no "false" tooltips after deactivating the "hide" option.

**Video:** https://www.screencast.com/t/4x1O7XQC1LKj
**Screenshot:** 
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/5aca3242-6550-4ec0-862d-fb6f54cec072)

**Environment**
https://admin-staging.mindlogger.org/
kimberly_ml@protonmail.com // 12345678
applet / activity:
DBT / Target Behaviors Bank
EMA / Weekly
Samsung S7 // Android 8.0	
iPhone 8 Plus // iOS 14.3

**Comment by natalia-muzyka** [comment]
@binaryExDev the issue is fixed for EMA / Weekly / skip_playing item.
For DBT / Target Behaviors Bank the issue is still reproducible.
After hiding/showing the items in DBT / Daily card and EMA / Daily activities issue is reproducible as well.
Video: https://www.screencast.com/t/Ezf3dQN4uv

Environment
https://admin-staging.mindlogger.org/
kimberly_ml@protonmail.com // 12345678
applet / activity:
DBT / Target Behaviors Bank
EMA / Weekly
Samsung S7 // Android 8.0
iPhone 8 Plus // iOS 14.3

**Comment by binaryExDev** [comment]
@natalia-muzyka Would you test it on a new account? Or you can delete and create a new one for testing.

**Comment by natalia-muzyka** [comment]
@binaryExDev issue is reproducible on the new account(just created) as well.
sevav47523@mainctu.com // 123456
DBT applet

Sure, I'll create a new one to retest after your fix will be deployed.

**Comment by natalia-muzyka** [comment]
@binaryExDev 
issue is still reproducible, checked with old account + new applet and new account + new applet: https://www.screencast.com/t/3hp39t11

Environment
https://admin-staging.mindlogger.org/
ML v0.18.38 staging
Samsung Galaxy S7 // Android 8
iPhone X // iOS 14.6

bernard_ml@protonmail.com	qwe123!!!
DBT 123

new_account@mail.com 123456
DBT

Applet password:	Qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/RzTDR4Z8G

Environment:
ML v0.18.42 staging
Samsung Galaxy S7 Edge SM-G935FD // Android 8
iPhone 6S // iOS 14.4.2
