### ISSUE TITLE
The PDF report can't be opened if there is a splash screen

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2080]
**Preconditions**
The user is logged in on the admin panel
https://admin-staging.mindlogger.org/
loui_ml@protonmail.com // 12345678
The mobile app is installed and launched
The user is logged in

**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Create an activity with cumulative item (allow to see results)
3. Add the splash screen to the activity and save the applet
4. Refresh the mobile app
5. Start the cumulative activity, select any responses to see the summary screen
6. Tap the "Share report" button
7. Pay attention to the screen

**Actual result**
The PDF report can't be opened if there is a splash screen. Nothing happens after tapping the "Share report" button on the Summary screen.

**Expected result**
The PDF report is opened after tapping the "Share report" button on the Summary screen. The splash screen image is displayed as the full first page in the PDF mobile report as per the [requirements](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/2040)

**Video:** https://www.screencast.com/t/NyByGTn6l

**Environment:**
ML v0.17.63 (staging)
Samsung S7 // Android 8.0
iPhone 8 Plus // iOS 14.3
loui_ml@protonmail.com // 12345678
applet: 
cumulative (splash),
cumulative + splash retest
cumulative (splash + watermark)
Applet password Qwe123!!!

**Comment by natalia-muzyka** [comment]
Still reproducible on ML v0.17.67 (staging)
Video: https://www.screencast.com/t/7kO0NoNekfab

Devices:
iPhone 8 Plus // iOS 13.3
Samsung S8 // Android 9

**Comment by WorldImpex** [comment]
PDF can be open with a splash screen

**Comment by natalia-muzyka** [comment]
Can be open but there's no splash screen image. This issue should be retested when image will be added to the mobile report.

Video: https://www.screencast.com/t/lGduLkjLg1

loui_ml@protonmail.com 12345678
applet / activity:
cumulative + splash retest / PC JPG

kimberly_ml@protonmail.com 12345678
applet / activity:
splash screen test (1) / PC 100x100jpg

Samsung S8 // Android 9.0
iPhone 8 Plus // iOS 13.3

**Comment by natalia-muzyka** [comment]
Verified and closed.
