### ISSUE TITLE
Update MindLogger Theme to remove logos

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2109]
Where there is a logo from the Theme, remove it

**Comment by WorldImpex** [comment]
Logo is still on Applet card

**Comment by natalia-muzyka** [comment]
Verified as fixed:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/50286146-d741-47e3-999e-767d2d03f50d)

Environment:
ML v0.18.38 staging
Samsung Galaxy S7 // Android 8
iPhone X // iOS 14.6
