### ISSUE TITLE
[PROD] Watermark should not be shown on Splash Screen 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2119]
Steps to recreate: 
1. Create an applet with a splash screen and watermark
2. Look at applet in mobile 
3. See results 

Expected: The splash screen should not show the watermark
Actual: The splash screen shows the watermark

**Comment by natalia-muzyka** [comment]
@jj105 @devbtech Waiting for a new build to retest this issue.

**Comment by natalia-muzyka** [comment]
@jj105 @WorldImpex 
Verified as fixed **on staging**
Video: https://www.screencast.com/t/zZ73j3xeXD1z

ML v0.18.3 (staging)
iPhone 8 Plus // iOS 13.3
Samsung S7 // Android 8
