### ISSUE TITLE
Summary Screen as last screen is missing "Done" 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2131]
When taking the ped screener, there is a summary screen based on the cumulative score. When the user gets to the last item requiring using input the user sees done and then the cumulative score shows done

Expected: The last item that requires user input shows next and the done is shown on the cumulative score item 

![IMG_3827.PNG](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/74308e60-43b9-4b59-b147-3e1df6c6a689)

![IMG_3828.PNG](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/526cdd28-4a9e-4828-ab89-7575500480c4)

**Comment by natalia-muzyka** [comment]
Need to retest after fixing the new related issue:
https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/2152

**Comment by natalia-muzyka** [comment]
Verified as fixed.
Video:
https://www.screencast.com/t/BwoayLKhNOz3
https://www.screencast.com/t/XTvaDbbB

ML v0.18.11 (staging)
iPhone 12 Pro Max // iOS 15.0.1
Samsung S7 // Android 8.0
