### ISSUE TITLE
[UI] The watermark is trimmed in mobile app if image width is bigger than height

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2132]
**Expected result:**
The watermark block has max height and max width. Depending on what side(width or height) is bigger in the uploaded image, this image should fit this max-width or max-height.

https://www.screencast.com/t/hQ6uyy0jPz5
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/66bd3133-ff05-4db2-b01a-91cf99c59f07)

Environment:
ML v0.18.4 (staging)

**Comment by binaryExDev** [comment]
@natalia-muzyka Could you share me the applet/activity that you used to test watermark?

**Comment by natalia-muzyka** [comment]
@binaryExDev 
kimberly_ml@protonmail.com / 12345678
applets:
all item types (from applet library), all items
Applet password:	Qwe123!!!
original images:
![NIMH logo.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/2f9f3a68-e397-48aa-bdbe-00df546a157f)
![MindLogger_AppScreens_700x1000.jpg](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/d578fbaa-0730-4bda-b174-19b542b097b0)

**Comment by natalia-muzyka** [comment]
Verified as fixed on ML v0.18.15 staging
iPhone 6s 14.4
Samsung Galaxy S7 SM-G930FD 8.0
iPad Pro (10,5-inch) MQDX2 15.0
Samsung Galaxy Tab S6 SM-T865 9.0
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/1746d622-eed1-4683-9499-063125ac2a3e)
