### ISSUE TITLE
[FR][webapp][mobile app][admin panel] Share/download report button and PDF report(automatically generated text) aren't translated to French

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2143]
mobile app - https://www.screencast.com/t/VWQlXbpvN
webapp - https://www.screencast.com/t/tfjMxj8TZ
admin panel - https://www.screencast.com/t/tlxnN0FVbl

https://admin-staging.mindlogger.org/
https://web-staging.mindlogger.org/
ML v0.18.8 (staging) 
Samsung S7 // Android 8
iPhone 8 Plus // iOS 13.3

**Comment by natalia-muzyka** [comment]
@astef021 could you share with me the translation file that you used, please?

**Comment by astef021** [comment]
@natalia-muzyka 

**Here are some texts blocks inside pdf report**
Your Child's Score

Your child's score on the xxx subscale was xxx.

I understand that the information provided by this questionnaire is not intended to replace the advice, diagnosis, or treatment offered by a medical or mental health professional, and that my anonymous responses may be used and shared for general research on children's mental health.

CHILD MIND INSTITUTE, INC. AND CHILD MIND MEDICAL PRACTICE, PLLC (TOGETHER, "CMI") DOES NOT DIRECTLY OR INDIRECTLY PRACTICE MEDICINE OR DISPENSE MEDICAL ADVICE AS PART OF THIS QUESTIONNAIRE. CMI ASSUMES NO LIABILITY FOR ANY DIAGNOSIS, TREATMENT, DECISION MADE, OR ACTION TAKEN IN RELIANCE UPON INFORMATION PROVIDED BY THIS QUESTIONNAIRE, AND ASSUMES NO RESPONSIBILITY FOR YOUR USE OF THIS QUESTIONNAIRE.


**And this is translation**
Le score de votre enfant

Le score de votre enfant pour la sous-échelle xxx est de xxx.

Je comprends que les informations fournies par ce questionnaire ne sont pas destinées à remplacer les conseils, le diagnostic ou le traitement offerts par un professionnel de la santé médicale ou mentale, et que mes réponses anonymes peuvent être utilisées et partagées pour des recherches sur la santé mentale des enfants.

CHILD MIND INSTITUTE, INC. ET CHILD MIND MEDICAL PRACTICE, PLLC (ENSEMBLE, "CMI") NE PRATIQUENT PAS DIRECTEMENT OU INDIRECTEMENT LA MÉDECINE ET NE DISPENSENT PAS DE CONSEILS MÉDICAUX DANS LE CADRE DE CE QUESTIONNAIRE. CMI DÉCLINE TOUTE RESPONSABILITÉ EN CE QUI CONCERNE LE DIAGNOSTIC, LE TRAITEMENT, LES DÉCISIONS OU LES ACTIONS PRISES SUR LA BASE DES INFORMATIONS FOURNIES PAR LE PRÉSENT QUESTIONNAIRE ET DÉCLINE TOUTE RESPONSABILITÉ QUANT À L'UTILISATION DE CE QUESTIONNAIRE.

**Comment by natalia-muzyka** [comment]
@astef021 

1. [mobile app] the "Share report" button is still not translated to French

![export - 2022-01-25T183156.066.pdf.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/83c6a81d-7cef-4cf7-87f7-1654eda8353f)

---

2. [admin panel / dataviz] the "Download report" button is still not translated to French

![image_2022_01_26T11_25_43_075Z.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/857c8666-f501-4788-868c-2d295d2b121b)

---

3. [website] Unexpected symbols in the web report

![image_2022_01_26T11_25_51_878Z.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/ce2f8aea-2a96-4caa-86f5-df36c8e6d043)

--- 

4. [website] The "rapport de partage' starts from lowercase letter instead of capital (Rapport de partage)

![image_2022_01_26T11_26_00_340Z.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/2d7b78ba-4057-4bf6-a50b-380f51157ee4)

Environment:
https://admin-staging.mindlogger.org/
https://web-staging.mindlogger.org/
ML v0.18.39 staging
Samsung Galaxy S7 Edge SM-G935FD // Android 8
iPhone X // iOS 14.6

**Comment by natalia-muzyka** [comment]
@astef021 there is still an unexpected symbol in webapp report:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/f7d53fee-b0e7-426a-b22a-42d004aee9eb)

**Comment by natalia-muzyka** [comment]
Verified as fixed:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/00d14ade-d6eb-4732-9cc2-d6d64a11cddd)
