### ISSUE TITLE
Add CMI Theme to Applet Builder 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2144]
name: CMI  
logo: CMI Logo from s3 
backgroundImage: CMI Logo from s3 
primaryColor: #0067A0  
secondaryColor: #FFFFFF   
tertiaryColor: #404040

- Add CMI logos in different places
   - Applet list page - top right (update the theme to accept the logo. This should not impact users that have a circle logo
   - Activity list page top right header bar 
- Change the header on the applet list page
- Thank you page 

Please see the style guide for further updates

https://app.zenhub.com/files/103405139/8d707277-a187-4894-bcda-60a2bc2c1a2e/download

**Comment by WorldImpex** [comment]
When switching between CMI theme to MindLogger theme and then back nothing happens 

bernard_ml@protonmail.com/ qwe123!!! - CMI Theme applet

**Comment by natalia-muzyka** [comment]
@devbtech CMI theme is applied automatically when user creates the applet with past / future behavior item,
if user tries to change the ML theme to CMI theme in existing applets then nothing happens on mobile app side.
Video: https://www.screencast.com/t/z4lVexaF

Environment:
https://admin-staging.mindlogger.org/
Applet Builder  v0.13.1
ML v0.18.38 staging
Samsung Galaxy S7 // Android 8
iPhone X // iOS 14.6
