### ISSUE TITLE
[UI] The images on TokenLogger summary screen are pixelate

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2201]
Screenshot: 
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/cd6ada1e-0cf7-41cf-87b8-b3078a6a99d0)

Environment:
ML v0.18.24 staging
Samsung Galaxy S9 // Android 10.0
iPhone 8 Plus // iOS 13.3
account:
bernard_ml@protonmail.com // qwe123!!!
applet: TL refresh test
Applet password: Qwe123!!!

**Comment by binaryExDev** [comment]
@natalia-muzyka For the success image, we're currently using a small icon like this.
![image.png](https://images.zenhubusercontent.com/5fc8d89138215d1055c6d606/2ff2caa5-61a7-4396-aa47-c692e6bc3c5d)
We need to replace with a big image so I did googling to search the image but I cannot find it anywhere.

**Comment by natalia-muzyka** [comment]
@binaryExDev do you use the latest assets, that were shared 03/01 in the [slack channel](https://matter-lab.slack.com/archives/CEHC2AVTJ/p1641222133028700)? 
There are three types of this "confetti" image. And as per the design, the confetti image should be smaller on the Summary screen:
https://xd.adobe.com/view/c550ec48-7d76-4f21-90e2-0e71bcec4948-9003/screen/6ff9f92b-4f1a-4abb-84cc-5fe21042210d/specs/

**Comment by WorldImpex** [comment]
@binaryExDev Still reproducible. Are you using the assets @natalia-muzyka mentioned?

**Comment by natalia-muzyka** [comment]
Verified as fixed:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/69778f59-6ebb-4ec5-b6d8-cf42055b5ba5)

Environment:
ML v0.18.37 staging
Samsung Galaxy S9 // Android 10
iPhone XS // iOS 15.2
