### ISSUE TITLE
[UI] Menu button isn't pulsing when there are occurences with not filled out time/slider

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2206]
Question:
[Requirements](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-builder/498):
Menu button opens a new page where the user can enter the time of the occurrence and a 2D slider to rate distress and impairment.
If any occurrence does not have a time and 2D slider filled out then show the blue/ purple in the button pulsing.

@WorldImpex could you clarify, please, do we have animation or video of how it should look?

Video: https://www.screencast.com/t/bbnwqe8o

**Comment by WorldImpex** [comment]
@natalia-muzyka It should pulsate through this gradient 

![Uploading Screen Shot 2021-12-29 at 5.05.23 AM.png…]()

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/YUR0Nl1Crk

Environment:
account:
bernard_ml@protonmail.com // qwe123!!!
ML v0.18.28 staging
Samsung Galaxy S7 // Android 8
iPhone 8 Plus // iOS 13.3
