### ISSUE TITLE
[Summary] The "Done" button is displayed instead of the "Next" button

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2208]
**Preconditions**
User is logged in on the admin panel
https://admin-staging.mindlogger.org/
bernard_ml@protonmail.com // qwe123!!!
There is activity with past behavior tracker item (at least one positive behavior with name and token value is added):
applet: TL refresh test
Mobile app is installed and launched, user is logged in

**Steps to reproduce**
1. Open the TL past behavior activity on the mobile app
2. Tap any behavior
3. Tap the Next button
4. Pay attention to the screen

**Actual result:**
 The "Done" button is displayed instead of the "Next" button on the TL Summary screen

**Expected:** 
 The "Next" button  is displayed on the TL Summary screen

**Screenshot:**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/1aa8b437-967f-4165-863a-5471c786be4f)

**Environment:**
https://admin-staging.mindlogger.org/
account:
bernard_ml@protonmail.com // qwe123!!!
applet: TL refresh
Applet password: Qwe123!!!
ML v0.18.24 staging
Samsung Galaxy S9 // Android 10.0
iPhone 8 Plus // iOS 13.3

**Comment by mtg137** [comment]
@natalia-muzyka - I discussed with @WorldImpex for this, I think we want to display "Done" button on summary screen
