### ISSUE TITLE
CST remove off target crash

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2220]
The user should be able to be off-target for the duration of the sample or test without an automatic crash

**Comment by natalia-muzyka** [comment]
how long should continue the test phase after these changes? @mtg137 @WorldImpex

**Comment by mtg137** [comment]
@natalia-muzyka - I think length of test phase is equal to previous

in the past, the stimulus disc was going back to center point and test was restarted after it doesn't overlap target point for 15 seconds ( OTCD time )

that feature should be deactivated in new build

**Comment by natalia-muzyka** [comment]
@mtg137 I'm sorry, I want to clarify about training. How long it should continue.

**Comment by mtg137** [comment]
focus phase should last 5 mins
