### ISSUE TITLE
Earned tokens for completed behaviors aren't reflected on mobile app Data tab and admin panel DataViz

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2230]
**Preconditions**
User is logged in on the admin panel
https://admin-staging.mindlogger.org/
bernard_ml@protonmail.com // qwe123!!!
There is activity with past behavior tracker item (at least one positive behavior with name and token value is added):
applet: tokenlogger applet positive
Mobile app is installed and launched, user is logged in

**Steps to reproduce**
1. Open the TL past behavior activity on the mobile app
2. Tap a few times on the positive behavior/behaviors
3. Tap the Next button
4. Complete the activity by "Done" button
5. Open Data tab
6. Pay attention to the screen
7. Open user's DataViz and pay attention to the screen
8. Export user's data
9. Observe the result

**Actual result:**
Earned tokens for completed positive behaviors aren't reflected on mobile app Data tab and admin panel DataViz. But times that behaviors were selected are displayed. On admin panel data aren't reflected as well: there is the dot on the timeline about the completing activity but no data other than that. The "frequency" tab is missing. No button to export PDF report. In the general CSV report there is the "Response" value [Object object].

**Expected:**
The user's total accumulated tokens is updated immediately after positive behaviors were selected and at 3 AM for negative behaviors.
Data are reflected on the [token chart (Data tab)](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/1942) in the mobile app. 
After opening DataViz there is the "Frequency" tab displayed with appropriate data as per the [requirements](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/1199). There is an [ability to download PDF report](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/302) with additional comments.

**Video:** https://www.screencast.com/t/S7fuEwQ03

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 // Chrome 96.0.4664.110 
macOS 10.15 // Chrome 96.0.4664.110 
account:
bernard_ml@protonmail.com // qwe123!!!
applet: tokenlogger applet positive
Applet password: Qwe123!!!
ML v0.18.25 staging
Samsung Galaxy S20 // Android 11
iPhone 11 // iOS 14.2

**Comment by natalia-muzyka** [comment]
@jj105 Negative tokens are not displayed as well after changing the Date/time to the next day: https://www.screencast.com/t/mEGX5xxe91m

bernard_ml@protonmail.com // qwe123!!!
applet: new tokenlogger applet
Applet password: Qwe123!!!

**Comment by jj105** [comment]
I think data export is not a current request

**Comment by natalia-muzyka** [comment]
@WorldImpex there were no TL requirements for CSV report, currently, there is just the "Response" value [Object object]. Is this acceptable for the first version?
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/4fe74c76-2994-4c5d-99de-78b778f7c746)

**Comment by WorldImpex** [comment]
@natalia-muzyka Yes there are no requirements for export today
