### ISSUE TITLE
Update Flanker Instructions and Name

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2241]
Update name to: Flanker_360

Update instructions to the below: 
You will see arrows presented at the center of the screen that point either to the left ‘<’ or right ‘>’. Press the left button if the arrow is pointing to the left ‘<’
or press the right button if the arrow is pointing to the right ‘>’. These arrows will appear in the center of a line of other items. Sometimes, these other items will be arrows pointing in the same direction, e.g.. ‘> > > > >’, or in the opposite direction,
e.g. ‘< < > < <’. Your job is to respond to the central arrow, no matter what direction the other arrows are pointing. For example, you would press the left button for both  ‘< < < < <’, and ‘> > < > >’ because the middle arrow points to the left. Finally,
in some trials dashes ‘ - ’ will appear beside the central arrow. Again, respond only to the direction of the central arrow. Please respond as quickly and accurately as possible.

**Comment by WorldImpex** [comment]
Please remove the indent on the last paragraph![IMG_5D8161604409-1.jpeg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/51d26f63-a869-439a-84b1-4ee161405787)

**Comment by WorldImpex** [comment]
Reproducible

**Comment by natalia-muzyka** [comment]
@WorldImpex  There are a few issues in the instructions text:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/a7dac00e-a2d9-43af-922f-b086b4ad167a)

**Comment by natalia-muzyka** [comment]
Verified as fixed:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/ed47f6ed-a4c6-4085-b03d-3cc1c80c4e9e)

ML v0.18.37 staging
Samsung Galaxy S7 // Android 8
iPhone 8 Plus // iOS 13.3
