### ISSUE TITLE
[UI][Token chart] Today view: "X from Y activities" text style doesn't match the design

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2249]
Expected: text should be yellow, number of tokens in bold

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/07763743-a761-487e-acfe-523861159d44)

ML v0.18.28 staging
iPhone 6s 14.4 750x1334 4,7" 16:9
iPhone 8 Plus 13.3 1080x1920 5,5 16:9
iPhone 11 14.2 828x1792 6.1" 19.5:9
Samsung Galaxy S7 SM-G930FD 8.0 1440x2560 5.1" 16:9

**Comment by natalia-muzyka** [comment]
@mtg137 nothing has changed:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/35ef632a-945d-46f3-a3b7-8e867a764c1e)

Environment:
ML v0.18.33 staging
Samsung Galaxy S7 // Android 8
iPhone 6S // iOS 14.4.2

**Comment by mtg137** [comment]
my [PR](https://github.com/ChildMindInstitute/mindlogger-app/pull/2299) is not merged yet

**Comment by natalia-muzyka** [comment]
@mtg137 

Actual: Token chart height is changed after switching between Today and all other views

Video: https://www.screencast.com/t/ud3NYJbS8

Expected: Token chart height is not changed after switching between Today and all other views. Only the "Today you'll earn at least" is removed

Environment:
ML v0.18.37 staging
Samsung Galaxy S9 // Android 10
iPad Pro (10,5-inch) MQDX2 // iOS 15

**Comment by natalia-muzyka** [comment]
Verified as fixed:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/005676c5-f063-4904-b790-b1e2de5fc7a2)

Environment:
ML v0.18.37 staging
Samsung Galaxy S9 // Android 10
iPad Pro (10,5-inch) MQDX2 // iOS 15
