### ISSUE TITLE
[UI][Token chart] 2D slider(diamond) is displayed out of behavior card

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2254]
Reproducible for behaviors with long names, especially on small screens.

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/4fa93c15-4c62-45a4-9fad-a67aad12dbd6)

ML v0.18.28 staging
bernard_ml@protonmail.com	qwe123!!!
applet: tl data test
iPhone 6s 14.4 750x1334 4,7" 16:9
iPhone 8 Plus 13.3 1080x1920 5,5 16:9
iPhone 11 14.2 828x1792 6.1" 19.5:9
Samsung Galaxy S7 SM-G930FD 8.0 1440x2560 5.1" 16:9

**Comment by WorldImpex** [comment]
fixed on iPhone 13 pro

**Comment by natalia-muzyka** [comment]
Verified as fixed:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/dd1e1594-3ce0-452e-a519-4fb55251141f)

ML v0.18.32 staging
bernard_ml@protonmail.com qwe123!!!
applet: tl data test
iPhone 6s 14.4 750x1334 4,7" 16:9
Samsung Galaxy S7 SM-G930FD 8.0 1440x2560 5.1" 16:9
