### ISSUE TITLE
[UI] Uploaded behavior images aren't displayed on Summary screen and Data tab (Token chart)

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2256]
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/0a6d7a75-43e3-4499-8b64-6c42a7356d18)

ML v0.18.28 staging
bernard_ml@protonmail.com qwe123!!!
applet: tl data test
Applet password	Qwe123!!!
iPhone 6s 14.4 750x1334 4,7" 16:9
iPhone 8 Plus 13.3 1080x1920 5,5 16:9
iPhone 11 14.2 828x1792 6.1" 19.5:9
Samsung Galaxy S7 SM-G930FD 8.0 1440x2560 5.1" 16:9

**Comment by WorldImpex** [comment]
Blocked due to no images showing up anymore and when trying to upload a new image, faced with the below message 
![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/ade2957e-b4f9-4fa7-9863-7d0ef44339c9)

**Comment by Matchdev120** [comment]
@WorldImpex It's working fine in this account (Natalia's testing account).

bernard_ml@protonmail.com qwe123!!!
applet: tl data test
Applet password Qwe123!!!

**Comment by natalia-muzyka** [comment]
@Matchdev120 images are still not displayed on the Summary screen, they are replaced by coins images.
On Data tab the issue is fixed.

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/ec2acc50-b723-4e1e-83fa-64568333703e)

bernard_ml@protonmail.com qwe123!!!
applet: tl data test, token chart refresh
Applet password Qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified as fixed:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/906d786f-f885-411f-9683-ccd29ff3cf67)

Environment:
ML v0.18.37 staging
Samsung Galaxy S9 // Android 10
iPhone XS // iOS 15.2
iPad Pro (10,5-inch) MQDX2 // iOS 15
Samsung Galaxy S7 // Android 8
