### ISSUE TITLE
[UI][Time_Activity_Last_Completed] The "exact time from the last completed activity to now" span is black instead of blue

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2269]
**Actual:**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/9cb7b6d5-4ada-42ca-b44e-aa900eae2a6b)

**Expected:**
Last updated assets: https://xd.adobe.com/view/47b33089-cdc2-492f-826a-349c57b7fcee-12e0/screen/73b24229-bc37-4ffc-b289-cdabf1566b64/

**Environment:**
ML v0.18.28 staging
Samsung Galaxy S9 // Android 10
iPhone 8 Plus // iOS 13.3
bernard_ml@protonmail.com // qwe123!!!
applet "Time_Activity_Last_Completed" / past behavior activity
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
verified as fixed:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/e76ad39a-bdc9-42ca-b422-adf0ee0e197b)

ML v0.18.31 staging
Samsung Galaxy S9 // Android 10
iPhone 6S // iOS 14.4.2

**Comment by natalia-muzyka** [comment]
@devbtech as per the requirements there just time diapason(timestamps) in blue color,
and we have all the row in blue, if this row contains timestamps [Time_Activity_Last_Completed] and [Now] (if timestamps aren't on the separate row).
Is it possible to make just time diapason in blue?

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/2f93001a-e26f-4e45-8f7d-8c59e5c154f0)

**Comment by WorldImpex** [comment]
It is okay for first version - There is technical difficulties fulfilling this blue requirement
