### ISSUE TITLE
Applet Builder: Duplicated items change question text when another item is deleted

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-app#2297]
![duplicate_issue](https://user-images.githubusercontent.com/24463939/149212503-85f3bcb7-3d22-4ea0-a092-fe28e7e73f7c.gif)

When 2 or more items are duplicated, and then an item is deleted, then the text field of one of the duplicated items will change to the text field of the one before it.

Steps to replicate:
1. create applet with 2 questions
2. duplicate both questions
3. delete one of the original questions
4. now the text of the second duplicate will change to the value of the first duplicate, however the item name and response are still correct

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/B6j7VAA4Wox

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 97.0.4692.99
