### ISSUE TITLE
ML-321 ⁃ 🐛 🍎 Reset Password → Unexpected Token (iOS)

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-app#23]
Clicking "Reset Password" on the iOS app gives the following error and no password reset email:

![Unexpected token " in JSON at position 0	ok](https://user-images.githubusercontent.com/5974438/37836551-16a09ff8-2e89-11e8-87e5-c3272227e301.png)

Related: ChildMindInstitute/ab2cd-app-admin-panel#13

**Comment by erik-ilyin** [comment]
For new API, please provide forgot password example @shnizzedy

**Comment by shnizzedy** [comment]
@erik-ilyin ― re: [forgot password](https://github.com/ChildMindInstitute/mindlogger-app/issues/23#issuecomment-420854890)
> For new API, please provide forgot password example @shnizzedy

```javascript
var xhr = new XMLHttpRequest();
xhr.withCredentials = true;
xhr.addEventListener("readystatechange", function () {
  if (this.readyState === 4) {
    console.log(this.responseText);
}
});
var data = new FormData();
data.append('email', email);
data.append('token', window.authToken);
xhr.open("PUT", "http://" + window.host + "/api/v1/user/password/temporary", true);
xhr.send(data);
```

Ref [`664d821`](https://github.com/ChildMindInstitute/mindlogger-app-backend/commit/664d821c70df3d50a1d474cdb7228ed8fbc2b26c)

**Comment by erik-ilyin** [comment]
This is not example for forgot password, user can't have authToken.

**Comment by shnizzedy** [comment]
Oh right, so no authToken:

```javascript
var xhr = new XMLHttpRequest();
xhr.addEventListener("readystatechange", function () {
  if (this.readyState === 4) {
    console.log(this.responseText);
}
});
var data = new FormData();
data.append('email', email);
xhr.open("PUT", "http://" + window.host + "/api/v1/user/password/temporary", true);
xhr.send(data);
```

or 

```javascript
var xhr = new XMLHttpRequest();
xhr.addEventListener("readystatechange", function () {
  if (this.readyState === 4) {
    console.log(this.responseText);
}
});
xhr.open("PUT", "http://" + window.host + "/api/v1/user/password/temporary?email=" + email, true);
xhr.send(null);
```

**Comment by shnizzedy** [comment]
Both of the above worked for me (the one above that worked for me as well, since I was logged in). However, ChildMindInstitute/mindlogger-app-backend#65 is preventing me from resetting my password once I get the temporary access token.
