### ISSUE TITLE
Updating Negative Behavior Calculation 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2303]
1. Any negative behavior recorded reduces the user's overall score regardless of time or the equation by 1 token
2. A user is active if an activity has been completed with a behavior recorded in the last 24hrs
3. The negative behavior calculation is a way for the user to earn tokens by not doing a negative behavior. So prior to the ETR, the user must have been active in the last 24 hours. During the ETR, if behaviors are recorded then we do the math. If no behaviors are recorded then the user receives the maximum number of tokens based on the math.
4. So number 1 happens every time a negative behavior is recorded, negative tokens behavior calculation only happens if the user is active and the behavior is recorded within the ETR window/ if no behavior calculated then the user receives max tokens
5. If a past behavior is recorded after 3 AM for a time before that is within the ETR, then the calculation would show up the following 3 AM. ie This statement is true -> I set up TV = 1 for one negative behavior at a rate of 1/hr. If I set an ETR 19:00-07:00, then if no negative behavior was recorded between 1/3 and 1/4 - I earn 8 tokens (1900-0259) on 1/3 at 3 AM for negative behaviors and 4 tokens (0300-0700) on 1/4 at 3 AM for negative
6. We should not give half points to users that start in the middle of an ETR. If the user is starting late on the ETR then the next full hour will be earned if a negative behavior isn't recorded

**Comment by natalia-muzyka** [comment]
@WorldImpex 

1. Any negative behavior recorded reduces the user's overall score regardless of time or the equation by 1 token
- you mean 1 Token Value of the recorded behavior 
- you mean the user's overall DAY score(calculation happens separately for the day), and the total balance is refreshed at the 3 AM with this day score
- day score can be negative but it won't have a negative impact on user's balance

2. A user is active if an activity has been completed with a behavior recorded in the last 24hrs
- the active and inactive state described in the document is related to the passive tokens accruing

6. If the user is starting late on the ETR then the next full hour will be earned if negative behavior isn't recorded
- you mean the next full Rate of increase

**Comment by WorldImpex** [comment]
This ticket is being closed based on a new document with different requirements
