### ISSUE TITLE
Header images are too small on the activity screen

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2308]
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/5b3dcc7d-e98f-4c15-9072-1ad20736d773)

ML v0.18.34 staging
Samsung Galaxy S7 // Android 8
iPhone 8 Plus // iOS 13.3

**Comment by binaryExDev** [comment]
@natalia-muzyka Could you provide me your testing account info?

**Comment by natalia-muzyka** [comment]
@binaryExDev 

issue doesn't depend on account,
if you compare the images in DBT, NIMH applets with prod version, you'll see that images were resized.
expected is prod example.

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/dea1b21a-76f3-4545-a365-64cbb2bc6ba4)

josephine_ml@protonmail.com // qwertyui
applet: DBT

**Comment by natalia-muzyka** [comment]
Verified as fixed on:
ML v0.18.37 staging
Samsung Galaxy S7 // Android 8
iPhone 8 Plus // iOS 13.3
iPad Pro (10,5-inch) MQDX2 // iOS 15
Samsung Galaxy Tab S6 SM-T865	// Android 9.0

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/7b83c5dc-c2ec-4ecd-854a-e2d43efad17d)
