### ISSUE TITLE
[Draw item/ A/B Trails] X and Y coordinates are displayed as decimals and negative decimals

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2320]
Video: https://www.screencast.com/t/F3azpFFjjd

Export files:
https://drive.google.com/drive/folders/1FEfZJ-zjSiewDMDObMXp-SSOo2i8eB2r?usp=sharing

Environment:
ML v0.18.37 staging
iPad Pro (10,5-inch) MQDX2 // iOS 15

**Comment by Matchdev120** [comment]
Created two Prs in admin and app
 - https://github.com/ChildMindInstitute/mindlogger-admin/pull/1429
 - https://github.com/ChildMindInstitute/mindlogger-app/pull/2323

The Prs include:
 - Updated X, Y coordinates to be between 0 ~ 100 in all the devices (regardless of screen size).
 - Fixed negative values in drawing responses.

**Comment by natalia-muzyka** [comment]
Verified as fixed.

A/B trails:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/265c75f1-4fc4-4f3f-8fb5-3380c648fe3d)

Draw item:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/50ab842d-3273-45dd-a34a-04c3ac58c4be)

Environment:
ML v0.18.38 staging
Samsung Galaxy S9 // Android 10
iPhone X // iOS 14.6
iPad Pro (10,5-inch) MQDX2 // iOS 15
