### ISSUE TITLE
Adding Terms of Service 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2322]
We need to add terms of service to MindLogger. Locations 

1. mobile app 
2. Webapp 
3. Admin panel
4. Library

- Hyperlink to https://mindlogger.org/terms. 
- Add a footer like the one on webapp to admin panel and library 
- On website and mobile signup add a checkbox requiring the user to agree with the terms of service in order to create an account 
   - Text: "I agree to the [Terms of Service](https://mindlogger.org/terms)"
- Add Terms of Service hyperlink to the login page Change Language

**Comment by natalia-muzyka** [comment]
Functionally it works well, there are just non-blocker UI issues.

**Issues:**
[UI][New user] I agree to terms checkbox is not left-aligned #2465
[UI]The "Sign up" button doesn't look inactive when the "I agree to the Terms of Service" checkbox is disallowed #2466
[App][Website][Admin panel] The "I agree to the Terms of Service" label is not actionable (only the checkbox icon) #2467
[UI][Admin panel][Website][Library] There's not enough space between elements in footer #409
[UI][Mobile][Portrait] Footer is not well adaptive on mobile devices #410
[UI] Mouse cursor is not changed to the Pointer after hovering the "I agree to the Terms of Service" checkbox #411
[FR][All platforms] No French localization for "Terms of Service" #2468

**Comment by natalia-muzyka** [comment]
Requirements are met.

Verified on:
ML v0.19.7 staging
Samsung Galaxy S7 // Android 8
iPhone Xs Max// iOS 15.3
Samsung Galaxy Tab S6 SM-T865 // Android  9.0
iPad Pro (10,5-inch) MQDX2 // iOS 15
https://web-staging.mindlogger.org/
Win 10 // Chrome 99.0.4844.82
