### ISSUE TITLE
Trails/ Draw Canvas - Sampling Rate

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2334]
There is variation in the sampling rate for the draw canvas. It looks like after X time the sampling rate decreases. Please investigate and provide a solution 

[Example 1](https://docs.google.com/presentation/d/1rp-RZOZG78CVoX1aeXQDUlcWyaSfIbX8lpYop20KbmM/edit?usp=sharing)

(![processed-ecf41372-a796-4714-bad6-b6c02061d3fe_nEM0Z5RG.jpeg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/9e9d21b4-70b5-4c2a-ad4b-822b898dedaa)

**Comment by natalia-muzyka** [comment]
@mtg137 @WorldImpex 
1. Line is interrupted occasionally and looks angular
2. [iOS] The canvas frame becomes thicker after user continues drawing for a while
3. [iOS] The Draw image is disappeared after a few seconds of drawing
4. [Android] Canvas is black colored after few seconds of drawing

Video 1 (iPhone X): https://www.screencast.com/t/CqFamISRnqe5
Video 2 (iPad Pro): https://www.screencast.com/t/KvaqVwSks6
Video 3 (Samsung Tab S6): https://www.screencast.com/t/rSS7n44XwVv
Video 4 (Samsung S7 Edge): https://www.screencast.com/t/Zm9pZrlQB0

Environment:
ML v0.18.41 staging
Samsung Galaxy S7 Edge SM-G935FD // Android 8
iPhone X // iOS 14.6
Samsung Galaxy Tab S6 SM-T865 // Android  9.0
iPad Pro (10,5-inch) MQDX2 // iOS 15

**Comment by mtg137** [comment]
@natalia-muzyka - for 1, I think we are fine with sampling rate for first 0.5 ~ 1 minute.

In this image, the last section looks less smooth than first section
![image.png](https://images.zenhubusercontent.com/5fbce3e9259bafeab239c8c3/8be314b7-eb7c-4be5-b583-8513f6ada5e7)

I think that is issue we want to resolve for this ticket
( smoothness of lines shouldn't change even after few minutes of drawing )

**Comment by natalia-muzyka** [comment]
@mtg137 thank you for clarification, 
I tried to retest the main issue, but seems that after the latest changes accordingly to its fix these new blockers appeared, that's why I gathered all in my comment in this ticket. Previously none of these issues that I described were reproducible.

**Comment by natalia-muzyka** [comment]
@mtg137 4 issues from my comment aren't reproducible anymore.
But the main issue is reproducible. The line is still not smooth:

iPad Pro (10,5-inch) MQDX2 // iOS 15
![42408.jpg](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/ed1e1b42-3852-48d5-b229-758fbc26cfd8)

iPhone 12 Pro Max	// iOS 15.0.1
iPhone 7 // iOS 13.1.1
![34577.jpg](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/782826b3-899c-4964-a42a-60a5767908a2)

Samsung Galaxy Tab S6 SM-T865 // Android 9.0
Video: https://www.screencast.com/t/Zhth9Wthl7z

Samsung Galaxy S9	 // Android 10.0
Video: https://www.screencast.com/t/FhdnKKBlL

Environment:
ML v0.18.42 staging

**Comment by natalia-muzyka** [comment]
Verified as fixed.

iPad Pro 10.5: https://www.screencast.com/t/50NI7A9B
iPhone 7: https://www.screencast.com/t/n25s1TLRqh
Samsung S7 Edge: https://www.screencast.com/t/8UoFOyyMYNr

ML v0.18.44 staging
