### ISSUE TITLE
The average distress/impairment value on DataViz is different from mobile app

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2340]
The average distress/impairment value on DataViz is different from the mobile app:
- On mobile app average value is rounded
- On admin panel in some cases it is displayed with more than 10 characters after decimal point

@WorldImpex  could you help, please, with the expected behavior?

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/063674cf-b5e9-4710-9a9d-8774823d5f8c)

Environment:
ML v0.18.39 staging
Samsung Galaxy S7 // Android 8
iPhone X // iOS 14.6
tl_account2@mail.com	123456
applet: mac test
Applet password:	Qwe123!!!

**Comment by WorldImpex** [comment]
Let do up to 3 decimals on admin

**Comment by natalia-muzyka** [comment]
Verified as fixed:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/b851ff68-27f9-4d62-952e-0b946d1b670a)

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 97.0.4692.99
