### ISSUE TITLE
[Past/Future behavior tracker] There is no warning(pop-up) when user tries to set up 24h time range for the negative behavior

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2343]
There is validation but no warning (explanation) why user can't set up 24h timerange.
Video: https://www.screencast.com/t/umshNRcn

Expected: Section is highlighted with error message "Time cannot exceed 23 hours and 59 minutes or be zero. Please reconfigure."

**Comment by natalia-muzyka** [comment]
@WorldImpex could you clarify, please, why 23 hours and 59 minutes? Shouldn't be there 24 hours instead?

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/HKj0Ujed8

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 97.0.4692.99

**Comment by WorldImpex** [comment]
@natalia-muzyka So the user does not set a 12 AM to 12 AM time.

**Comment by natalia-muzyka** [comment]
@WorldImpex thank you for clarification, I misunderstood the text for the first time,
issue is fixed and closed
