### ISSUE TITLE
[Time activity last completed] Item that shouldn't be displayed for the first time is shown if activity contains splash screen

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2380]
**Preconditions**
User is logged in on the admin panel:
https://admin-staging.mindlogger.org/
Mobile app is installed and launched

**Steps to reproduce**
1. Create an activity
2. Add splash screen
3. Add a few items
4. Add conditional logic: if activity is NOT shown for the first time, show item1
5. Save the applet
6. Open the activity in the mobile app
7. Click "Next" on splash screen
8. Pay attention to the screen

**Actual result:**
Item that shouldn't be displayed for the first time is shown if activity contains splash screen

**Expected result:**
Item that shouldn't be displayed for the first time is shown only if activity was completed at least once

**Video:** https://www.screencast.com/t/2MYDNlgvn2

**Environment:**
https://admin-staging.mindlogger.org/
ML v0.18.43 staging
Samsung Galaxy S7 Edge SM-G935FD // Android 8
iPhone 7 // iOS 13.1.1
anita_ml@protonmail.com	qwe123!!!
applet: applet name (anita) / activity 6
Applet password:	Qwe123!!!

**Comment by WorldImpex** [comment]
fixed
