### ISSUE TITLE
[Future behavior tracker] Mobile app crashes in copied from library TL future activity that contains splash screen

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2381]
Not reproducible if:
- original future activity + splash screen (owner account)
- copied from library past activity + splash screen
- splash screen added after copying the future activity from library

Video: https://images.zenhubusercontent.com/103405139/2a6d5579-b457-48b1-8436-e5e12ceb6477/2022_02_03_18_23_00.mp4
Crashlog (Android): [https://app.zenhub.com/files/103405139/24f5849b-3846-4c5f-8503-bfa40a7268da/download](https://app.zenhub.com/files/103405139/24f5849b-3846-4c5f-8503-bfa40a7268da/download)

Environment:
ML v0.18.43 staging
Samsung Galaxy S7 Edge SM-G935FD // Android 8
iPhone 7 // iOS 13.1.1
iPhone 8 Plus // iOS 13.3

reproducible on:
anita_ml@protonmail.com	qwe123!!!
applet: tokenlogger (anita)

not reproducible on:
bruce_ml@protonmail.com	12345678
applet: tokenlogger
anita_ml@protonmail.com	qwe123!!!
applet: tokenlogger, tokenlogger no splash

Applet password	Qwe123!!!

**Comment by WorldImpex** [comment]
Now app freezes on Splash screen

**Comment by WorldImpex** [comment]
A crash is still experienced on Anita's account when the user tries to execute future behavior and clicks on how long they would like to log behaviors for. A crash report has been sent

**Comment by WorldImpex** [comment]
issue resolved on MindLogger 0.18.51 (500) - iPhone 13 pro

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/wf8ynpnaL

Environment:
ML v0.18.53 staging
Samsung Galaxy S7 Edge SM-G935FD // Android 8
iPhone Xs Max// iOS 15.3
anita_ml@protonmail.com qwe123!!!
saxise9093@moxkid.com	123456
