### ISSUE TITLE
[PROD] "Is shown/is not shown for the first time" condition is broken in the copied activity if original activity was completed first

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2407]
**Preconditions**
Mobile app is installed and launched
User is logged in on the admin panel
https://admin.mindlogger.org/
anita_ml@protonmail.com	qwe123!!!

**Steps to reproduce**
1. Open a site https://admin.mindlogger.org/
2. Create a new applet
3. Create activity with "Is shown/is not shown for the first time" condition 
4. Save the applet
5. Complete activity on the mobile app
6. Edit the applet, copy the completed activity and save the changes
7. Complete copied activity on the mobile app
8. Observe the result

**Actual result**
"Is shown/is not shown for the first time" condition is broken in the copied activity if original activity was completed first

**Expected result**
"Is shown/is not shown for the first time" condition isn't broken in the copied activity if original activity was completed first

**Notes: 
Reproducible of admin creates original activity, and copy it right before the first saving the applet.
Not reproducible if original activity is not completed before the copied activity is started.**

**Video:** 
Creating original activity and complete: https://www.screencast.com/t/pMXQjw2cb2g
Copy and complete: https://www.screencast.com/t/chy7mbL4M

**Environment:**
ML Pilot v0.18.49 prod
Samsung Galaxy S7 Edge SM-G935FD // Android 8
iPhone 8 Plus // iOS 13.3
anita_ml@protonmail.com	qwe123!!!
applet: time activity completed
activities: activity 5 (copy), activity 7 (1)

**Comment by WorldImpex** [comment]
When trying to edit a newly created applet, no fields are filled in. 
Staging environment 
anita_ml@protonmail.com qwe123!!!
applet: One time 

Steps to recreate 
1. Log into staging-admin using Antia's account 
2. Go to one time completion and try to edit 

Expected: When the applet builder is shown, there is content filled in
Actual: When the applet builder is shown, no content is displayed 

![mindlogger-admin.gif](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/6b74e60d-763d-4489-a879-1c901af6f6ad)

**Comment by Matchdev120** [comment]
@natalia-muzyka I created a new applet in my account (new16@test.org/abcd1234) and it works fine.
I'd like to have a pair testing when you're available.

**Comment by natalia-muzyka** [comment]
@Matchdev120 I was able to reproduce the issue with this applet on your account. 
The one difference is that I completed the first activity twice. 
Video: https://www.screencast.com/t/5cs86QtZ
applet: Conditional applet test 
applet password: Abcd1234!

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/5nLcrQiT

Environment:
ML v0.18.61 staging
Samsung Galaxy S7 // Android 8
iPhone Xs Max// iOS 15.3
