### ISSUE TITLE
The tooltip doesn't reflect the variable value of any valid input item

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2420]
**Preconditions**
User is logged in on the mobile app
There is an activity with at least two items: radio and checkbox.
Radio item name is added as a variable name to the tooltip of any checkbox option (item name is in the brackets [[]])

**Steps to reproduce**
1. Start an activity on mobile app
2. Select any response on the radio item
3. Proceed to the checkbox screen
4. Check the tooltip
5. Observe the result

**Actual result**
The tooltip doesn't reflect the variable value of any valid input item

**Expected result**
Any markdown field in MindLogger (Text creator (question text), Option text, markdown message, cumulative score markdown fields should reflect the variable value

**Video:** https://www.screencast.com/t/YM43pN4te

Environment:
ML v0.18.53 staging
Samsung Galaxy S7 Edge SM-G935FD // Android 8
iPhone Xs Max// iOS 15.3
anita_ml@protonmail.com qwe123!!!
applet: applet name (anita) / variable name tooltip
Applet password Qwe123!!!

**Comment by WorldImpex** [comment]
Fixed on iPhone 13 Pro

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/hoDy7c6mnIzr

Environment:
ML v0.18.58 staging
Samsung Galaxy S7 Edge SM-G935FD // Android 8
iPhone Xs Max// iOS 15.3
