### ISSUE TITLE
The variable name is shown instead of variable value(selected option) if the user's response contains the optional text

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2423]
**Preconditions**
User is logged in on the mobile app
There is an activity with the next items:
radio item (with text input option allowed), 
checkbox item (with [[radioItemName]] added as an option text)

**Steps to reproduce**
1. Start an activity on the mobile app
2. Select any response on the radio item and enter any text
3. Move to the next screen
4. Pay attention to the screen

**Actual result**
The variable name "radio" is shown instead of variable value(radio Option 2) if the user's response contains the optional text

**Expected result**
The variable value(radio Option 2) is displayed if the user's response contains the optional text

**Notes: Needs to be fixed for radio, checkbox, slider on the option text, markdown message**

**Video**: https://www.screencast.com/t/FumVEZbpiZ
**Screenshot**:
https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/f462c4a5-522a-4ef0-90e6-52672912e2f1

**Environment:**
ML v0.18.53 staging
Samsung Galaxy S7 Edge SM-G935FD // Android 8
iPhone Xs Max// iOS 15.3
anita_ml@protonmail.com qwe123!!!
applet: applet name (anita) / variable name text input option
Applet password Qwe123!!!

**Comment by WorldImpex** [comment]
fixed on iPhone 13 Pro

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/ySkkpwMwf

Environment:
ML v0.18.58 staging
Samsung Galaxy S7 Edge SM-G935FD // Android 8
iPhone Xs Max// iOS 15.3
