### ISSUE TITLE
The applet image is repeated for every activity in the compared PDF report on mobile app

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2427]
Video: https://www.screencast.com/t/lnPfP5IFzL

Expected: Applet image is displayed only at the very beginning of the report (if there's a splash screen then it goes right on the next page)

Environment:
ML v0.18.54 staging
Samsung Galaxy S7 Edge SM-G935FD // Android 8
iPhone Xs Max// iOS 15.3
loui_ml@protonmail.com	12345678
applet: daisy chain loop / activity 3
Applet password	Qwe123!!!

**Comment by natalia-muzyka** [comment]
@Matchdev120 
nothing is changed on iOS: https://www.screencast.com/t/xm2V3vTe
on Android report layout is broken: https://www.screencast.com/t/q3POKfgWgBkt

Environment:
ML v0.18.58 staging
Samsung Galaxy S7 Edge SM-G935FD // Android 8
iPhone Xs Max// iOS 15.3
loui_ml@protonmail.com 12345678
applet: daisy chain loop / activity 3
Applet password Qwe123!!!

**Comment by Matchdev120** [comment]
@natalia-muzyka Is this issue related to applet image? or splash image.
If it's just related to applet image, is that fine if we have splash image in each activity?

**Comment by Matchdev120** [comment]
@natalia-muzyka Just reviewed the requirements for splash screen and it was an activity-level feature.
Let me remove applet-image. Actually, I removed splash screen. My apologies.

**Comment by natalia-muzyka** [comment]
@Matchdev120 you're right, there's might be something related to splash image. 
I see that uploaded splash images for activity 2 and activity 3 aren't displayed on mobile app now.
There is no specific ticket that requires removing splash images from the mobile report. 
Is it possible that changes were applied to the splash images instead of applet images?

@WorldImpex could you help with the use case, please?
I was thinking about if admin wants to have a daisy chain report, then he/she sets up splash screen only for the very first activity and in the compared report he/she sees the splash image on the first page. Then applet image goes on the second page and doesn't need to be repeated for every next activity.

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/8runhAPX5PM

Environment:
ML v0.18.59 staging
Samsung Galaxy S7 Edge SM-G935FD // Android 8
iPhone Xs Max// iOS 15.3
