### ISSUE TITLE
Crash when executing TL, Educate EMA and NIMH EMA Applet

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2433]
Steps to recreate 
1. Log into mobile 
2. Try to execute an activity on TL, Educate EMA or NIMH EMA 
3. See Results

Expected: User can complete an activity 
Actual: Mobile app crashes 

anita_ml@protonmail.com qwe123!!!
tokenlogger (anita), 
bruce_ml@protonmail.com 12345678
tokenlogger, nimh ema, educate ema
Applet password Qwe123!!!

**Comment by natalia-muzyka** [comment]
Reproducible for NIMH 

Fixed for 
anita_ml@protonmail.com qwe123!!!
tokenlogger (anita),
bruce_ml@protonmail.com 12345678
tokenlogger, educate ema
Applet password Qwe123!!!

Environment:
ML v0.18.58 staging
Samsung Galaxy S7 // Android 8
iPhone Xs Max// iOS 15.3

**Comment by Matchdev120** [comment]
@natalia-muzyka I have tested it for NIMH applets but worked as expected.

Shared a couple of screenshots and accounts/applets
 - Healthy Brain Network (NIMH) / new16@test.org abcd1234
 - Healthy Brain Network (NIMH) / bruce_ml@protonmail.com 12345678

![Screen Shot 2022-02-28 at 7.39.18 AM.png](https://images.zenhubusercontent.com/5e248d759c666007f1a71211/9ceda8d6-755b-4b67-90c8-aa43dc084a53)

**Comment by natalia-muzyka** [comment]
@Matchdev120 I'm sorry for the missed video. App crashes on completing Pre-Questionnaire.
You can see crash on 00:55
https://www.screencast.com/t/1deppMlu
