### ISSUE TITLE
Update login cursor to be white

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2434]
Users cannot see if the username or password field has been selected because the cursor is blue. Please update it to white 

![File.jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/b1d5cf51-ef3a-4381-849c-070cb4c6e116)

**Comment by natalia-muzyka** [comment]
Verified as fixed:

![bandicam 2022-03-01 20-37-50-028.jpg](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/53e5bf3b-76b4-46ac-97b8-b39db2b0eb6e)

ML v0.18.59
Samsung Galaxy S7 // Android 8
iPhone Xs Max// iOS 15.3
