### ISSUE TITLE
[mobile app][admin panel][website]It is possible to register/change password with password that contains only space characters

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2443]
**Steps to reproduce**
1. Install and launch mobile app
2. Open the "New user" screen
3. Enter valid email and user name
4. Enter the password with 6 space characters
5. Tap the "Sign Up" button
6. Pay attention to the screen

**Actual result**
It is possible to register a new user with password that contains only space characters

**Expected result**
It's not possible to register a new user with password that contains only space characters

**Video:** 
mobile app: https://www.screencast.com/t/bkpAgtLpkNqJ
admin panel & website: https://www.screencast.com/t/z11sWsBXCxns

**Environment:**
ML v0.18.60 staging
Samsung Galaxy S7 // Android 8
iPhone Xs Max // iOS 15.3
https://admin-staging.mindlogger.org/
https://web-staging.mindlogger.org/

**Comment by Matchdev120** [comment]
@WorldImpex @natalia-muzyka I'd like to make sure the password enhancement. If the password can't be spaces, would you let me know the requirements?

Like this:
 - 8 characters minimum
 - One uppercase characters minimum
 - One number minimum
 - One special character minimum

**Comment by natalia-muzyka** [comment]
@WorldImpex could you help us with password requirements, please?
the old requirement was just 6 symbols, but I see a new @astef021 ticket that all the passwords should be changed:
https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/2437

**Comment by WorldImpex** [comment]
For now 

6 digits and no spaces

**Comment by natalia-muzyka** [comment]
@Matchdev120 

1 - I see a new validation (password requirements) on admin panel (one capital letter, small letter, number, special character, 8+ length), 
the website and mobile app still requires only 6+ characters on Sign Up and Change password pages (spaces issue is fixed)
Expected: it was decided to use the old requirements for password (6 characters)

2 - [admin panel] it is still possible to register with the password that contains spaces (in the beginning, in the middle, and in the end) 
Video: https://www.screencast.com/t/ojKP7uPBpP

3 - [mobile app] it is possible to change password to only spaces or that contains spaces
Video: https://www.screencast.com/t/8RU0JbGL

Environment
Win 10 // Chrome 100.0.4896.75 
https://admin-staging.mindlogger.org/
https://web-staging.mindlogger.org/#/
ML v0.19.14 staging
Samsung Galaxy S7 // Android 8
iPhone Xs Max // iOS 15.3

**Comment by natalia-muzyka** [comment]
@Matchdev120 @devbtech I don't see changes on the admin panel and website:

1 - Failed: admin panel still requires a new validation (one capital letter, small letter, number, special character, 8+ length) instead of just 6 characters length
Video: https://www.screencast.com/t/2j71Kbyp

2 - Failed: on the admin panel it is still possible to register with spaces in the password
Video: https://www.screencast.com/t/wFE2PuvPI

3 - Fixed on mobile app: https://www.screencast.com/t/3MSoBTDZmWuo
Failed on website: https://www.screencast.com/t/BdQfpXgQQ2LT

Environment:
https://admin-staging.mindlogger.org/
https://web-staging.mindlogger.org/#/
ML v0.19.20 staging
Samsung Galaxy S7 // Android 8
iPhone XR // iOS 14.3

**Comment by Matchdev120** [comment]
@natalia-muzyka It is because two PRs are not merged yet.

https://github.com/ChildMindInstitute/mindlogger-web/pull/473 (web)
https://github.com/ChildMindInstitute/mindlogger-admin/pull/1545 (admin-panel)

@devbtech Would you merge these PRS?

**Comment by Matchdev120** [comment]
@natalia-muzyka It is because two PRs are not merged yet.

https://github.com/ChildMindInstitute/mindlogger-web/pull/473 (web)
https://github.com/ChildMindInstitute/mindlogger-admin/pull/1545 (admin-panel)

@devbtech Would you merge these PRS?

**Comment by natalia-muzyka** [comment]
1&2 - [admin panel] fixed: https://www.screencast.com/t/dHyqowOVYYO
3 - [website] fixed on user's settings page: https://www.screencast.com/t/auinetqqJSdq

@Matchdev120 change password (user's settings page) validation is updated, but there is also a "reset password" page, could you update validation there as well, please? I didn't mention it separately, sorry.
Reset password page: https://www.screencast.com/t/7yGiABpl7

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/S41axx6cjWu

Environment
Win 10 // Chrome 100.0.4896.75
https://web-staging.mindlogger.org/#/
