### ISSUE TITLE
Applets missing on Account

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2452]
Steps to recreate 
1. Log into web-staging (wavanauken+5@gmail.com/ abcd123)
2. Check list of applets
3. See Results 

Expected: See applets on list page 
Actual: No applets are shown

**Comment by natalia-muzyka** [comment]
Verified as fixed:
https://www.screencast.com/t/hihx7JMSg
https://www.screencast.com/t/m290MIO1wAn

Environment:
https://web-staging.mindlogger.org/
ML v0.18.61 staging
Samsung Galaxy S7 // Android 8
iPhone Xs Max// iOS 15.3
