### ISSUE TITLE
Flanker: Do not allow buttons to be selected

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2462]
Per the attached image, the user is able to select the button text on Flanker. Please remove that ability 

![IMG_8893.jpeg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/57cde0a2-d877-4e20-8702-53ae764ef93b)

**Comment by MaksimYurys** [comment]
@Matchdev120 Bug was reproduced https://images.zenhubusercontent.com/103405139/0354471e-446a-4eb4-895c-3ebe2c72baed/20220613_162418.mp4

Devices:
Samsung Galaxy A6 // Android 9.0
iPhone 8 // iOS 14.7.1

Build:
0.21.1

**Comment by natalia-muzyka** [comment]
The issue is reproducible on Android if user taps on the buttons on the fixation/feedback.
Video: https://www.screencast.com/t/OdGfhfBLG

ML 0.21.27 staging
iPhone 7 // iOS 13.1.1
flanker_test@mail.com / 123456
Flanker_360 (12)
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified as fixed; https://www.screencast.com/t/kpV7rbvka

ML 0.21.29 staging
Google Pixel 5a // Android 11
flanker_test@mail.com / 123456
Flanker_360 (12)
Applet password: Qwe123!!!
