### ISSUE TITLE
Remove Share Report Button 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2486]
If the cumulative summary has a Share all Reports button then hide the share report button

**Comment by natalia-muzyka** [comment]
If the cumulative summary has a Share all Reports button then the share report button is hidden.
If the cumulative summary has a Share all Reports button then the share report button is shown and there's no Share all Reports button.

Checked with simple daisy chain and daisy chain loop.

Environment:
https://admin-dev.mindlogger.org/
https://web-dev.mindlogger.org/
Win 10 // Chrome 99.0.4844.82 
ML pilot v0.18.62 dev
Samsung Galaxy S7 // Android 8
iPhone Xs Max// iOS 15.3
Samsung Galaxy Tab S6 SM-T865 // Android  9.0
iPad Pro (10,5-inch) MQDX2 // iOS 15
