### ISSUE TITLE
CST: Trackpad should act like a Mousepad

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2505]
Requirements
- The user's touch within the trackpad should be a 1:1 
  - Speed and acceleration should be based on the user finger movement 
- If the user's position starts in the middle of the field and the user places finger on the far right of the trackpad swiping left then when the user reaches the middle the user's position would start to run off of the playing field 
- Bring the edges of the playing field up to the trackpad. In the below image the red sections should be changed to white so that the trackpad is the same size of the area the user has to move within 

![Blank diagram.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/422cb53f-98be-4fc4-a953-ce213921b147)

Examples; 
1. If the user's first touch of the trackpad is the far left edge, then the puck does not move until the user drags right
2. If the user's first touch is the right side of the trackpad and moved right then the puck will start moving right. If the user remove's finger then the puck will stop progressing right and will wait for another input of movement from the user. 
3. If the user's first touch is in the middle and moves the finger to the left, the puck will move left. If the user picks up the finger, touches left most edge and slides right, then the puck will change direction to the right.
4. If the user touches the right side of the trackpad and does not move, then the puck does not move. 
5. If the user's position is in the middle and the user touches the far right side of the track pad and drags left into the middle of the trackpad then the user's position will go out of the field hitting the green bar on the left

**Comment by WorldImpex** [comment]
I believe it should be zero - @mtg137 Could you confirm?

**Comment by WorldImpex** [comment]
I think the score increasing initially without any effort is accurate. It is the systematic change in slope that causes the puck to start to drift one way or another which becomes increasingly hard for the user to counter as time progresses

**Comment by mtg137** [comment]
I think 0.075 is correct for lambda value in the csv export. it is initial lambda value in the CST and it is increased depending on lambdaSlope and time. ( it does not depend on user's position or stimulus position )

**Comment by mtg137** [comment]
I think "swipe to start" and "swipe to restart" is correct.

**Comment by natalia-muzyka** [comment]
@mtg137 on restart the swipe was not required in the previous version, just the tap worked, so only the "Tap to start" should be edited to "Swipe to start" then.

And we should revert the changes according to this ticket:
https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/2660

cc: @WorldImpex

**Comment by mtg137** [comment]
I discussed with @WorldImpex, I think we want to keep "tap here to start" and "tap here to restart" text.
initial speed of disk will depend on user's first tap position. ( disk will move left if I tap left side of touch pad initially )

**Comment by natalia-muzyka** [comment]
@mtg137 thank you for the clarification, then the next issue should be fixed: 
The puck starts moving always to the right after tapping on the right/middle/left on the touch pad or far right/left edge.
Video: https://www.screencast.com/t/gHIiLIwvfeK

Environment:
ML v0.21.5 staging
iPhone 7 // iOS 13.1.1
Samsung Galaxy S7 // Android 8
Google Pixel 5a // Android 11
Samsung Galaxy Tab S6 SM-T865 // Android 9.0
cst_test@ml.com 123456
Stability task touch (2)
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
@mtg137 
The issue with moving the disk always to the right is fixed: https://www.screencast.com/t/zTZJbaeJrQs
Also, we need to update general instructions as the user is required to swipe now to control the disk.
cc: @WorldImpex 

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/a2362ee7-9eb7-4cd1-b09f-5afd33863b58)

Environment:
ML v0.21.9 staging
Samsung Galaxy Tab S6 SM-T865 // Android 9.0
Apple iPad 9th gen (2021) / iOS 15.5
ml3_general_acc@protonmail.com	/ 12345678
stability_task_touch
cognitive tasks / stability_task_touch
Applet password: Qwe123!!!
