### ISSUE TITLE
Flanker: Update Pass Threshold for Practice Round

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2506]
As an editor, I want global changes made to how Flanker is setup so that it aligns with the industry standard better. 

Requirements 
- Update the % correct threshold to be 75% 
   - User can progress forward to test once achieving 75% or higher on any practice block. The user has 3 blocks to "pass" the practice round 
   - If the user does not achieve 75% or higher after 3 practice blocks then record in the export a new column called failed practice

**Comment by natalia-muzyka** [comment]
@mtg137 @WorldImpex
1 - The 75% threshold (or actually, 23/30 correct answers required threshold) was already implemented from the very first version. What exactly was changed except the report representation? 
2 - If the user does not achieve 75% or higher after 3 practice blocks then he/she still able to move to the main test or activity will be completed?

**Comment by WorldImpex** [comment]
1. I think it was originally 80% and then changed but the big update is the column in the export
2. Yes the user still moves onto the test and the system records the failed practice rounds in the export

**Comment by WorldImpex** [comment]
Agreed @natalia-muzyka

**Comment by natalia-muzyka** [comment]
The implementation met the requirements.
Verified on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 101
ML v0.20.3 staging
iPhone XR // iOS 14.3
Samsung Galaxy S7 // Android 8
Google Pixel 5a // Android 11
iPad Pro (10,5-inch) MQDX2 // iOS 15.3
