### ISSUE TITLE
Entered text is not reflected in the text input field

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2529]
Video: https://www.screencast.com/t/imMy1S9d2Y

Additional info: The fix of this issue BUG: Free text response character limit won't change from 50 #1520
 probably has an impact on the current issue

Environment:
ML v0.19.13 staging
Samsung Galaxy S7 // Android 8
iPhone Xs Max // iOS 15.3
anita_ml@protonmail.com	qwe123!!!
webapp applet name (anita) / variable name, text
dbt / events and goals

**Comment by shauryam-exe** [comment]
Can you explain the issue a bit more so it is clear

**Comment by natalia-muzyka** [comment]
@shauryam-exe, when I enter any text in the text input field on the entered text, is not displayed.
The expected result you can see in the video below:
https://www.screencast.com/t/cvwAczRX

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/Ld9Lovm3

Environment:
ML v0.19.17 staging
Samsung Galaxy S7 // Android 8
iPhone XR // iOS 14.3
