### ISSUE TITLE
Add a greyscale pixel to Flanker

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2541]
Add a greyscale pixel to Flanker that changes every time the screen changes. This will help analyze when the screen changes

**Comment by MaksimYurys** [comment]
@Matchdev120
 Grayscale pixel present in iPhone app 
iPhone 8 // iSO 14.7.1 
https://images.zenhubusercontent.com/103405139/c25bdaef-11bb-4483-a769-e8e19bc308aa/20220615_134100.mp4

 But missing in android app 
Samsung Galaxy A6 (SM-A600FN) // 9.0 
https://images.zenhubusercontent.com/103405139/9b0ef446-d439-4ac4-98a5-05db41400f40/20220615_135442.mp4

Build 0.21.5

**Comment by natalia-muzyka** [comment]
@Matchdev120 there is no grey pixel on Flanker and Configurable Flanker, for both iOS and Android. We are using a new Flanker protocol now, maybe there's the reason for the issue?
Video: https://www.screencast.com/t/AEB3d9OUPmN

Environment:
ML v0.21.27 staging
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
flanker_test@mail.com / 123456
applet protocol: https://raw.githubusercontent.com/mtg137/Flanker_applet/staging/protocols/flanker/flanker_schema

**Comment by natalia-muzyka** [comment]
@Matchdev120 

**1 - grey pixel is still missing on iOS:**

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/12d7272f-d4b7-4d71-aac8-602043347ea8)

---

**2 - grey pixel is missing on Android if there is only one button:**

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/4ce7cd0b-0bfc-4332-8c2f-a8f9ad3a4fa1)

---

**3 - android config flanker - pixel is too big on Android and adds distraction. in the first iOS implementation, it was way smaller and located on the bottom right below the right button. now it's located above the left button.** 
sugest making the location on the bottom right below the right button and make it 30% of the current size.

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/14940e38-0fd0-4a93-adc8-3a21b21e5c2c)

---

**4 - android flanker applet - grey pixel overlaps with the stimulus image:**

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/1e3768c8-a46c-4761-86a8-9a47308b0bb6)

---

**5 - shouldn't the pixel be displayed on every screen (stimulus, fixation, feedback)? now it is shown only on the stimulus.** Video: https://www.screencast.com/t/kbGX3FCZqYP

cc: @WorldImpex 

Environment:
ML v0.21.31 staging
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
flanker_test@mail.com / 123456
config flanker v5, flanker_360(13)
Applet password Qwe123!!!

**Comment by WorldImpex** [comment]
@Matchdev120 We have a native version of Flanker is that potentially why the grey pixel isn't shown?

**Comment by natalia-muzyka** [comment]
@Matchdev120 could you clarify, please, what exactly was fixed? there is still no greyscale pixel on iOS, and Android issues are still reproducible

ML v0.21.43 staging
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11

**Comment by WorldImpex** [comment]
@polividskyi / @mtg137 worked on this ticket. Please advise 

1. Android/ Native should have grey scale pixel on every screen

**Comment by anq83** [comment]
done
will be deployed in version > 0.21.59

**Comment by natalia-muzyka** [comment]
conversation in slack:
https://matter-lab.slack.com/archives/C015UPV6B8U/p1667298711019619

**Comment by natalia-muzyka** [comment]
Verified on:
ML v0.21.59
iPhone 7 // iOS 13.1.1
iPhone 13 // iOS 15.6
Google Pixel 5a // Android 11

Android: https://images.zenhubusercontent.com/103405139/63466150-af89-4b17-9585-d2d5b3b7af76/bandicam_2022_12_02_13_51_16_648.mp4
iOS: https://images.zenhubusercontent.com/103405139/650cde17-8cea-41f9-9378-c06a87879a75/bandicam_2022_12_02_13_51_16_648.mp4

**Comment by yzenchanka** [comment]
Verified on:
ML v0.21.62
iPhone 7 Plus // iOS 14.4
Samsung Galaxy S20 FE SM-G780G / Android 12
