### ISSUE TITLE
Flanker: Fix Initial Delay in fixation time due to loading 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2561]
Please test by taking Flanker on iphone and android and providing @WorldImpex the export

**Comment by natalia-muzyka** [comment]
@WorldImpex 
Export files: 
https://drive.google.com/drive/folders/1LlsjhpnMlzgORVZXOo9BhQ-t6OMF0wD2?usp=sharing

Environment:
ML v0.19.21 staging
Samsung Galaxy S20 // Android 11
iPhone XR // iOS 14.3
owner: cst_test@ml.com	123456
applet: Flanker_360
Applet password	Qwe123!!!
