### ISSUE TITLE
Update activity statuses representation

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2579]
1 - Remove the "Unscheduled" label and group the no scheduled activities with "Available" activities

2 - Change the order of sections:
"In progress" should be at the very top
then "Available"
then "Scheduled" at the very bottom (activities that are scheduled on the current day, but not yet available)

**Comment by MaksimYurys** [comment]
Verified as complete

Screenshots: ![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/7e22ac05-d5b3-4840-a52d-4dade4576066)
![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/be76c307-e438-4bf8-9c99-d8f0d9ca7cb4)

Environment: 
https://web-dev.mindlogger.org/
ML v0.21.23 dev
iPhone 8 // 14.7.1
Samsung Galaxy S8 // 8.0.0
OmaewaShinderou123@gmail.com // Qqww!123
Applet - activity statuses (2)
