### ISSUE TITLE
[PROD] [Combined PDF report] Variable value of text item and date are displayed as [object Object] and [undefined-NaN-Nan]

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2589]
Variable value of text item and date are displayed as [object Object] and [undefined-NaN-Nan].

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/74b7a613-30c3-488f-a6aa-4a21599695e1)

Reproducible on:
iPhone 13 Pro / iOS 15.4.1

Not reproducible on:
iPhone XR // iOS 14.3
iPad Pro (10,5-inch) MQDX2 // iOS 15
iPad Air 2 Wi-Fi // iOS 14.6
iPhone 12 PRO // iOS 14.4

ML v0.18.63 (prod)
PMHSA@childmind.org (PMHSA - RUMC (11+)" applet

**Comment by natalia-muzyka** [comment]
Testing is blocked by:
App crashes immediately on start#2239

**Comment by natalia-muzyka** [comment]
@WorldImpex could you retest the issue on your device on the latest build, please?

**Comment by WorldImpex** [comment]
This issue has be fixed @natalia-muzyka
