### ISSUE TITLE
Update Confirmation Screen for Activity Flow 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2598]
As a user, I want the next activity to be started when completing the first one so that I do not have to click so many times between activities in a flow 

Requirements 
- Replace the thank you screen with the "interim" screen found in [this design](https://www.figma.com/file/VYuZ9vFaPfK6JnXeAXG8wW/Pre-SRC-Features?node-id=333%3A9986) 
- The next activity's name, x of y and activity flow icon should be shown 
- Allow the user to go back if he or she wants to review or change answers 
   - If back is disallowed in the applet builder then remove back button from interim screen 
- Once the user hits submit, the first item of the next activity should be shown

**Comment by natalia-muzyka** [comment]
@WorldImpex could you clarify more on the removing back button, please?
Let's say we have the next flow: Activity A -> Activity B
Currently, if the "remove back button" is not activated anywhere in Activity A and user hits "back" on the interim screen, he/she is moved back to the very first Activity A screen.
Could you confirm if my expectations are correct, please:
it doesn't matter where the "remove back button" is activated in "Activity A" - if it is activated somewhere in the activity, then the "Back" button should be removed on the interim screen.

**Comment by WorldImpex** [comment]
1. If the "remove back button" is turned on for an activity, then the back button is removed from the interim screen 
2. If the "remove back button" is turned off for an activity, then the back button is shown on the interim screen 
3. If the user selects the back button on the interim screen, then the last question should be shown

**Comment by natalia-muzyka** [comment]
Implemented as per the requirements.

Environment:
ML v0.21.48 
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
Samsung Galaxy Tab S6 SM-T865 // Android  9.0
Apple iPad 9th gen (2021) / iOS 15.5
