### ISSUE TITLE
Mobile app crashes after tapping the Data tab in the Welcome applet

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2600]
**Preconditions**
The mobile app is installed and launched
The user is logged in

**Steps to reproduce**
1. Open the Welcome applet
2. Tap the Data tab
3. Observe the result

**Actual result**
Mobile app crashes after tapping the Data tab in the Welcome applet

**Expected result**
@WorldImpex  I suggest removing the Data tab in the Welcome applet 
OR making it inactive

**Video:** https://www.screencast.com/t/MEW1Ob7wVeM

**Environment:**
ML v0.20.3 staging
Google Pixel 5a // Android 11
iPad Pro (10,5-inch) MQDX2 // iOS 15
owner (admin): ml_general_acc@protonmail.com	/12345678
old user: ml2_general_acc@protonmail.com	/ Qwertyuiop123!!!
new user: new-user@ml.com / 123456

**Comment by WorldImpex** [comment]
Agreed - it should be disabled

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/QvIiGhj0eYB7

Environment:
ML v0.20.6 staging
iPhone XR // iOS 14.3
Samsung Galaxy S7 // Android 8
Google Pixel 5a // Android 11
owner (admin): ml_general_acc@protonmail.com /12345678
old user: 
ml2_general_acc@protonmail.com / Qwertyuiop123!!!
new-user@ml.com / 123456
new users:
new-user1@ml.com / 123456
new-user3@ml.com / 123456
