### ISSUE TITLE
Remove Your child's scrore from Report

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2619]
- This is a mobile report update only 
- We need to remove the "your childs score" from report and replace it with the below 

![your child's score (1).jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/6b2caaa1-cb13-4318-bc27-591bdf62279d)

**Comment by natalia-muzyka** [comment]
There is "Score" instead of "The Score" in the sentence below the scale:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/805e7a79-47f1-4bc3-8c13-c662488c088f)

Environment:
ML v0.20.8 staging
iPhone XR // iOS 14.3
Samsung Galaxy S7 // Android 8

**Comment by natalia-muzyka** [comment]
Verified as fixed:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/3db401c7-8285-4b5a-b273-d9442111be2c)

Environment:
ML v0.20.9 staging
iPhone XR // iOS 14.3
Samsung Galaxy S7 // Android 8
