### ISSUE TITLE
[Flanker Native timestamps] The "Respond faster" feedback screen is shown in the test block

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2647]
**Preconditions**
Mobile app is installed and launched
User is logged in to the account with a Flanker applet:
flanker_test@mail.com / 123456

**Steps to reproduce**
1. Start the Flanker activity
2. Pass the practice and proceed to the test block 
3. Start a test and wait for 5 seconds
4. Pay attention to the screen

**Actual result**
The "Respond faster" feedback screen is shown in the test block

**Expected result**
A feedback screen should be shown only in the practice block.

**Video**: https://www.screencast.com/t/yU1uyUsKS

**Environment:**
ML v0.20.14 staging
iPhone XR // iOS 14.3
flanker_test@mail.com / 123456
Applet password: Qwe123!!!

**Comment by WorldImpex** [comment]
This looks to be resolved

**Comment by natalia-muzyka** [comment]
Verified as fixed on iOS: https://www.screencast.com/t/ixDspo3ss
Android still crashes on old and new Flanker protocol: https://www.screencast.com/t/kMGd86GbG

Environment:
ML v0.21.4 staging
iPhone 7 // iOS 13.1.1
Samsung Galaxy S7 // Android 8
flanker_test@mail.com / 123456
Flanker_360 
protocol: https://raw.githubusercontent.com/mtg137/Flanker_applet/master/protocols/flanker/flanker_schema
Flanker_360(1)
protocol: https://raw.githubusercontent.com/mtg137/Flanker_applet/staging/protocols/flanker/flanker_schema
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
Android is still blocked. Ticket:
https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/2657

**Comment by natalia-muzyka** [comment]
Verified as fixed on Android: https://www.screencast.com/t/AdrJ1WWS6o7

Environment:
ML v0.21.13 staging
Samsung Galaxy S7 // Android 8
flanker_test@mail.com / 123456
Flanker_360 (6)
protocol: https://raw.githubusercontent.com/mtg137/Flanker_applet/staging/protocols/flanker/flanker_schema
Applet password: Qwe123!!!
