### ISSUE TITLE
CSV responses aren't downloaded for DBT applet on a new account

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2648]
data export doesn't work on a new account for DBT applet (CORS error)  after completing it on 0.20.15 staging:
qqqttest01@gmail.com // Qqww!123
applet password: Qqww!123

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/98fc1dd1-8db8-456f-900d-1451f0aacc23)

Environment:
ML v0.20.15 staging
iPhone XR // iOS 14.3

**Comment by mtg137** [comment]
data export works fine for me on staging, I think staging server was down or was not stable when you were checking.

https://images.zenhubusercontent.com/103405139/6180d6c0-a8e8-4eb3-a778-db047c42c3f3/record.mov

**Comment by natalia-muzyka** [comment]
Verified and closed: https://www.screencast.com/t/2DoBccAuL

https://admin-staging.mindlogger.org/
Win 10 / Chrome 102
qqtest.02@gmail.com // Qqww!123
