### ISSUE TITLE
Trails: When restarting the lines are still present from previous attempts 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2652]
Expected: When restarting the Trails activity, previously drawn lines are not present 
Actual: When restarting the Trails activity, sometimes previously created lines are shown

**Comment by WorldImpex** [comment]
[Uploading... residual_after_restart_then_crashes.m4v]

**Comment by natalia-muzyka** [comment]
Previously created lines are shown after resuming the activity (old behavior): https://www.screencast.com/t/dU4OO1wf

After restarting the activity the previously created lines aren't shown: 
https://www.screencast.com/t/pQwhd5OmFr6

Environment:
ML v0.21.3 staging
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
Samsung Galaxy Tab S6 SM-T865 // Android  9.0
iPad Air 2 WiFi // iOS 14.6
Apple iPad 9th gen (2021) / iOS 15.5
