### ISSUE TITLE
The blank screen is shown after passing the first practice/test block if summary screen is disallowed

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2654]
@WorldImpex we don't have some 'pause' screen as in the main test block (Instructions), would you agree to add it?

**1 - Blank screen if only the Summary screen is disallowed on the Practice block**
Video of practice with no summary: 
https://www.screencast.com/t/St4FFHd8KeNg
https://www.screencast.com/t/8Epx3EHS

**2 - Blank screen if the Summary screen is disallowed in the Main test block**
Video: https://www.screencast.com/t/9zmJjzxy0

Main test instructions screen (the default version implementation).
Suggest adding the pause screen(Instructions: Press the next button to start the next block) between practice blocks.
https://www.screencast.com/t/hPzDBgKEiO

Environment:
ML v0.21.1 staging
iPhone 7 // iOS 13.1.1
Samsung Galaxy S7 // Android 8
jeligi9407@zneep.com	123456
Flanker test / no summary, edit, edit with practice summary, edit with summary
Applet password	Qwe123!!!

**Comment by WorldImpex** [comment]
@natalia-muzyka Agreed!

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/liKUZHl03

Environment:
ML v0.21.12 staging
iPhone 7 // iOS 13.1.1
Samsung Galaxy S7 // Android 8
