### ISSUE TITLE
The uploaded stimulus and button images/text do not fit the screen/button

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2655]
**Issue:**
1 - Image fills out all the screen
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/9f657857-8c74-44fb-897c-8d25cd6a76bb)
2 - Text with 4ch+
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/6450db65-74eb-4d30-aead-a19f86c2d6de)

**Suggestion:**

**1. Images:**
There should be an area(square) with min/max width and height in which the image fills the full width or height (depends on ratio). This area should be vertically and horizontally aligned and have enough paddings, e.g (green is just a defined area, it could be vertically and horizontally aligned in addition, I just draw over the current implementation).
The buttons should have the same min/max width and height (as well as an image block).
The same suggestion is for the fixation screen.

**2. Buttons Text:**
Padding should be bigger, font size could be smaller on the Mobile screen and bigger on Tablet screen.
Or if we need to have the same font size then there should be added more paddings and a text input limit of 3 characters. The button should have the same min/max width and height. The text should be aligned.

![image (2).png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/59ced451-fe2c-4264-bc21-f205013b83a9)

Environment:
ML v0.21.1 staging
iPhone 7 // iOS 13.1.1
Samsung Galaxy S7 // Android 8
jeligi9407@zneep.com 123456
Flanker test / new
Applet password	Qwe123!!!

**Comment by natalia-muzyka** [comment]
@jj105 @WorldImpex may I add about the button image?
Probably the expected is to **replace** the button with the uploaded image> If so, then the uploaded image should be the same min/max height/width as the button with a specified text

**Comment by natalia-muzyka** [comment]
@jj105 images look way better now, and could you fix, please the next:

**1 - make the images fit the height or width of the image block depending on image orientation (image block as on mockups) to avoid different representations of images with different sizes:**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/85a999d4-a376-48b2-9c4d-98a773f80b4d)

---

**2 - fixation image should fit the screen as the stimulus image does after fixing the 1st issue**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/fd352f44-eae6-4b02-bceb-b1b59c2febc1)

---

**3 - buttons text: right and left paddings are missing, and the text is trimmed, so suggest adding a limitation in 5 characters on button text(on the admin side) 
4 - buttons are too narrow on tablets now (after changing the font size)**

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/3654adc0-a89d-4d77-ae1c-18b3de214294)

---

**5 - button images should **replace** the buttons: the uploaded button images should have max height/width and be clickable**

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/90ad5fdd-1d62-404f-b86a-c6ba31aa8f9f)

---

**6 - when there is one button it fills all the screen width: could you add max-width for a button so it will have a possible max-width**

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/48d43b87-f03a-4e37-accf-e77bce039f7c)


**Environment:**
ML v0.21.7 staging
iPhone 7 // iOS 13.1.1
Samsung Galaxy S7 // Android 8
Samsung Galaxy Tab S6 SM-T865 // Android  9.0
Apple iPad 9th gen (2021) / iOS 15.5
jeligi9407@zneep.com 123456
Flanker test / new, one button, buttons text
Applet password Qwe123!!!

**Comment by MaksimYurys** [comment]
**1. Cropped pictures on buttons go beyond the borders of buttons**

![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/b66025bf-6f12-4150-ba6f-160eded1b20e)

Environment:
iPhone 8 // 14.7.1
Samsung Galaxy S8 // 8.0.0

Build:
0.21.9

**2. Screen can be scrolled** 

https://images.zenhubusercontent.com/103405139/6419b9d6-8f8c-4fe5-acb9-e96f825ac56c/20220617_144127.mp4

Environment:
Samsung Galaxy S8 // 8.0.0

Build:
0.21.9

**Comment by jj105** [comment]
@MaksimYurys could you let me know email/password of your account and name of applet and activities?

**Comment by MaksimYurys** [comment]
@jj105

"1. Cropped pictures on buttons go beyond the borders of buttons" - **fixed**

Environment:
iPhone 8 // 14.7.1
Samsung Galaxy S8 // 8.0.0

Build:
ML v0.21.12 staging

"2. Screen can be scrolled" - **fixed**

Environment:
Samsung Galaxy S8 // 8.0.0

Build:
ML v0.21.12 staging

" 3 - Frame in the crop tool still has an inappropriate ratio change.
When you're changing the frame it jumps randomly from one fixed ratio to another (from mobile to tablet).
Expected: There should be one ratio defined. Let it be the mobile button ratio.
Video: https://www.screencast.com/t/wbM5yFaMouDk " - **reproduced**

Environment:
Win 10 // Chrome 102

"4 - [iOS] The button image is changed to the blue color on fixation screens
Video: https://www.screencast.com/t/mxhu2cBYGnQ" - **not reproduced**

Environment :
iPhone 8 // iOS 14.7.1
ML 0.21.12 staging
jeligi9407@zneep.com 123456
Flanker test / new
Applet password Qwe123!!!

**Comment by natalia-muzyka** [comment]
3 - **Fixed** - Frame in the crop tool still has an inappropriate ratio change.
When you're changing the frame it jumps randomly from one fixed ratio to another (from mobile to tablet).

4 - **Fixed** - [iOS] The button image is changed to the blue color on fixation screens

@jj105 could you clean up, please, the next:
the cropped button image is not centered in the button (it is left aligned):

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/714dee45-d5ad-42db-8442-80c35f6a129d)

Environment :
ML 0.21.16 staging
jeligi9407@zneep.com 123456
Flanker test / new
Applet password Qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified as fixed:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/e34c62e3-6bae-47d6-a7d2-1b9592a4f0d6)

Environment :
ML 0.21.18 staging
jeligi9407@zneep.com 123456
Flanker test / new
Applet password Qwe123!!!

**Comment by natalia-muzyka** [comment]
@jj105 

On iOS ML v0.21.26 (staging+Native Flanker)

1 - stimulus, fixation images overlap with buttons and do not have min-max width and height
2 - button images are stretched horizontally on iPad and vertically on iPhone
3 - buttons text font size is too big on iPhone and button missing the paddings

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/26e09cea-1f48-4e87-be37-57cb72d0b5c9)

Environment :
ML 0.21.26 staging
flanker_test@mail.com
Config Flanker v3
Applet password Qwe123!!!

**Comment by natalia-muzyka** [comment]
@polividskyi after the latest fixes there are left some issues on iOS/iPadOS. If it helps, I added screenshots from the 0.21.18 build as the expected result:

**1 - stimulus, fixation image is still too big, especially on iPad and buttons(+buttons text) are too small on iPad**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/a677921b-1969-4e9e-8a3a-f9874ed56f1d)

**2 - the uploaded original button image (without cropping) doesn't fit the button height/width, is not cropped and centered**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/9929e812-b08a-4368-85aa-d7fbbca48a03)

**3 - when there is one button it is too wide (fits the screen width) and has the too small font on iPad**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/b52db902-f2d4-4802-b702-5135324c6ff1)

Environment:
ML v0.21.30 staging
iPhone 7 // iOS 13.1.1
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
flanker_test@mail.com / 123456
config flanker v4
Applet password Qwe123!!!

**Comment by WorldImpex** [comment]
Please check on iPad @MaksimYurys / @natalia-muzyka but it looks good on iPhone 13 Pro

**Comment by natalia-muzyka** [comment]
Verified as fixed:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/fe00fbcc-4daa-4022-88b7-8689ca9fe48c)

Environment:
ML v0.21.36 staging
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
Samsung Galaxy Tab S6 SM-T865 // Android  9.0
Apple iPad 9th gen (2021) / iOS 15.5
