### ISSUE TITLE
[Flanker Native] The application is crashed/blank screen is shown after starting "Flanker_360" applet

### ISSUE THREAD

**Issue by MaksimYurys** [ChildMindInstitute/mindlogger-app#2657]
https://images.zenhubusercontent.com/103405139/587e7b7a-14c5-40b9-a572-365a193508ae/20220613_153227.mp4

Devices:
Samsung Galaxy A6 // Android 9.0
iPhone 8 // iOS 14.7.1

Build:
0.21.1

**Comment by WorldImpex** [comment]
Android will not be scope for this initial implementation

**Comment by natalia-muzyka** [comment]
On Android **0.21.8 staging (native flanker)** there is a blank screen after tapping next on the second practice instructions screen: https://www.screencast.com/t/Uf47csqJzu
On iOS Flanker activity can be processed and completed.

Environment:
ML v0.21.8 staging
iPhone 7 // iOS 13.1.1
Samsung Galaxy S7 // Android 8
flanker_test@mail.com / 123456
Flanker 360 (3)
Applet password: Qwe123!!! (

**Comment by natalia-muzyka** [comment]
@WorldImpex @devbtech  I don't see new flanker builds and android blank screen issue is still there on 0.21.8. was the ticket moved to qa accidentally or there will be a new build soon?

**Comment by WorldImpex** [comment]
Sorry I didn't realize this ticket was being used for the blank screen! Moving back to Sprint Backlog

**Comment by natalia-muzyka** [comment]
@WorldImpex 
The crash issue is reproducible again on both platforms (Android and iOS).
Video: https://www.screencast.com/t/JSUPiRExuD
Log file (Android):
https://drive.google.com/file/d/1pHDiaW-TGJD_mgIZFFfEqiXt0EY7hUtN/view?usp=sharing

Environment:
ML v0.21.11 staging
iPhone 7 // iOS 13.1.1
Samsung Galaxy S7 // Android 8
flanker_test@mail.com / 123456
Flanker 360 (5) - a newly created applet with the staging protocol
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
@WorldImpex 
The crash issue is reproducible again on both platforms (Android and iOS).
Video: https://www.screencast.com/t/JSUPiRExuD
Log file (Android):
https://drive.google.com/file/d/1pHDiaW-TGJD_mgIZFFfEqiXt0EY7hUtN/view?usp=sharing

Environment:
ML v0.21.11 staging
iPhone 7 // iOS 13.1.1
Samsung Galaxy S7 // Android 8
flanker_test@mail.com / 123456
Flanker 360 (5) - a newly created applet with the staging protocol
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/qOGc4GGTT

Environment:
ML v0.21.13 staging
iPhone 7 // iOS 13.1.1
Samsung Galaxy S7 // Android 8
flanker_test@mail.com / 123456
Flanker 360 (6) - a newly created applet with the staging protocol
Applet password: Qwe123!!!
