### ISSUE TITLE
Add padding to top and bottom menu items

### ISSUE THREAD

**Issue by MaksimYurys** [ChildMindInstitute/mindlogger-app#2665]
Add padding to top and bottom menu items
![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/d6fef560-6853-45a4-b69b-299f81362776)
Environment
macOS Catalina // Safari 13.1
https://admin-staging.mindlogger.org/

**Comment by natalia-muzyka** [comment]
Verified as fixed: 
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/d0389184-f7b4-4cad-8198-6ecfa4baada3)

Environment
Win 10 // Chrome 102
macOS Catalina // Chrome 102 //Safari 13.1
https://admin-staging.mindlogger.org/
