### ISSUE TITLE
Flanker: implement requirement  "Show error pop-ups when editor clicks the "close" button on the modal with edited data (uploaded images, edited fields, etc)"

### ISSUE THREAD

**Issue by MaksimYurys** [ChildMindInstitute/mindlogger-app#2689]
**Flanker: implement requirement  "Show error pop-ups when editor clicks the "close" button on the modal with edited data (uploaded images, edited fields, etc)"
Add "X" button to the modal**
Configureable Flanker Requirements - https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-builder/766

Requirement - ![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/d2e24a0f-fcef-4b72-b5fd-505dfcb9ff5b)

![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/3edaf6a7-c29b-43bf-a565-0091e825059d)

**Comment by natalia-muzyka** [comment]
Verified as fixed; https://www.screencast.com/t/APZHUhGhy

https://admin-staging.mindlogger.org/
v0.17.11
Win 10 / Chrome 103
