### ISSUE TITLE
The error 401 is shown on "Reset Password" page after submit the valid email

### ISSUE THREAD

**Issue by MaksimYurys** [ChildMindInstitute/mindlogger-app#2692]
1. Go to "Reset Password"  page
2. Enter valid email in "Email" field
3. Click on "Submit" button
4. Pay attention on the screen

The same bug on mobile app and web.

Actual result: The error 401 is shown on "Reset Password" page after submit the valid email

Expected result: Message with password recovery is sent on valid email after click on submit button

Video: https://www.screencast.com/t/J3uxl2ibtFJ

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 102
qqtest.02@gmail.com // Qqww!123
ML v0.20.18 staging

**Comment by natalia-muzyka** [comment]
Verified as fixed on admin panel, website and mobile app: https://www.screencast.com/t/bebynORWubg

Environment:
https://admin-staging.mindlogger.org/
https://web-staging.mindlogger.org/
Win 10 // Chrome 103
ML v0.20.18 staging
