### ISSUE TITLE
Creating an Activity Flow causes Blank Applet List

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2697]
Steps to recreate 
1. Log into dev admin (wavanauken+2@gmail.com/ abcd123) 
2. Create an applet with linked activities 
3. Try to open the applet on mobile 
4. See results 

Expected: The applet is shown in the list 
Actual: No applets are now shown in the list since the activity flow applet was created

**Comment by natalia-muzyka** [comment]
The issue is reproducible as well on:
user-dev@ml.com	/ 123456
user3-dev@ml.com	/ 123456

Video: https://www.screencast.com/t/M3L5eFDGkEJ

ML v0.21.23 dev
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11

**Comment by MaksimYurys** [comment]
@astef021 The user can see the activities in the applet list, but the activity flow is not displayed on the applet screen.

**Preconditions:**
1. User loggen in app
2. User have applet with activity flow

**Steps to reproduce:**
1. Open applet with activity flow.
2. Pay annetntion to the screen.

**Actual result:** The activity flow is not displayed on the applet screen.

**Expected result:** The activity flow is shown on the applet screen.

Video: https://images.zenhubusercontent.com/103405139/16c0eaf6-51b2-46d4-ab6d-bdf9342fe8c5/2022_07_05_11_13_24.mp4

Environment:
ML v v0.21.28 
iPhone 8 // iOS 14.7.1
Samsung Galaxy S8 // 8
OmaewaShinderou123@gmail.com // Qqww!123
