### ISSUE TITLE
There is a blank screen with some fixation time and a "Fixation" record in the report although the fixation screen is not specified

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2712]
Video: https://www.screencast.com/t/1bV0mVpe8N

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/0b4c2ae5-7480-4ebf-8c08-ec5023052777)

Environment:
ML 0.21.26 staging
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
flanker_test@mail.com / 123456
Config Flanker v3 / Simple & Choice Reaction Time Task Builder
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
@mtg137 @polividskyi 
there are a couple of issues related to fixation now:
1 - [ios] feedback is missing / shown for a millisecond when there is no fixation, 
video: https://www.screencast.com/t/LkdVX8HNSee
2 - [android] the next image is skipped if there is no fixation and feedback
video: https://www.screencast.com/t/Yjynva8B
3 - report "trial_start_timestamp" and "trial_offset" values are 0 and negative numbers if there is no fixation screen
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/2d0abad2-c6c0-4659-9578-3909f0391218)

Environment:
ML v0.21.30 staging
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
flanker_test@mail.com / 123456
config flanker v4
Applet password Qwe123!!!

**Comment by devbtech** [comment]
@natalia-muzyka It's mentioned that new changes just fix 2) & 3). Please confer with @mtg137

**Comment by natalia-muzyka** [comment]
@mtg137 @polividskyi 

do you want me to create a separate ticket for this or we will continue with the current one? 
**1 -** [ios] feedback is missing / shown for a millisecond when there is no fixation

**2 fixed -** [android] the next image is skipped if there is no fixation and feedback (it was fixed before merging with native)
Video: https://www.screencast.com/t/nuWyfJClSY

**3 -** trial_start and trial_offset are fine, but the event_offset is differentiating if there were no response + fixation or no fixation. If there is no fixation the event_offset for stimulus and feedback is 0

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/45c7f528-66b8-48bc-9925-e2236939122c)

Environment:
ML v0.21.31 staging
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
flanker_test@mail.com / 123456
config flanker v5
Applet password Qwe123!!!
