### ISSUE TITLE
Flanker: There is only a 1-2 millisecond delay between Touch_Event and next screen being shown

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2719]
Based on the data export, there is still only a 1-2 millisecond delay between the user's touch of the button and when the next screen is shown. This is not consistent with the screen refresh rate and the recorded video

**Comment by WorldImpex** [comment]
![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/c05863b1-160c-4acd-bb64-e2eb40d92776)
 
Epoch times aren't showing correctly

**Comment by natalia-muzyka** [comment]
The delay is bigger than 1-2 milliseconds on iOS now:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/f6265ea6-a7aa-4834-b7fe-26eb386195db)

cc: @WorldImpex 

Environment:
ML v0.21.38 staging
iPhone 7 // iOS 13.1.1
flanker_test@mail.com / 123456
Config Flanker v7 / Simple & Choice Reaction Time Task Builder
Flanker_360 (14)
Applet password: Qwe123!!!

**Comment by WorldImpex** [comment]
We are missing the actual fully loaded time stamp - team is working on this now

**Comment by natalia-muzyka** [comment]
@WorldImpex was this issue confirmed by Arno in slack?
https://matter-lab.slack.com/archives/CT1R0BCF7/p1657940941852449

**Comment by WorldImpex** [comment]
CLOSE THIS TICKET!!!!!! :)
