### ISSUE TITLE
ML-521 ⁃ Unrenderable Content can't be Skipped

### ISSUE THREAD

**Issue by henryrossiter** [ChildMindInstitute/mindlogger-app#272]
When content isn't rendered properly, the user can't skip the question to access the rest of the activity.
![image](https://user-images.githubusercontent.com/31543235/64799697-e2bf6100-d54a-11e9-8c7c-94d838203b5d.png)

**Comment by shnizzedy** [comment]
@henryrossiter did #594 resolve this issue? The change is in [v0.9.11](https://github.com/ChildMindInstitute/mindlogger-app/tree/v0.9.11)+.

**Comment by WorldImpex** [comment]
@jon confirmed resolved 

![image](https://user-images.githubusercontent.com/22243307/72550576-067c1600-3861-11ea-841e-aa24034df075.png)
