### ISSUE TITLE
Collecting data from the flow's activities issues

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2729]
**Preconditions**
The app is installed and launched
User is logged in to the account with the activity flow
user3-dev@ml.com / 123456

**Steps to reproduce**

1. Open the applet and start the activity flow
2. Complete the flow by selecting any responses
3. Compare the submitted responses with the: 

- mobile app Data tab, 
- admin DataViz, 
- plain CSV report, 
- activity user journey CSV report

4. Observe the result

**Actual result**
On the admin DataViz and mobile app Data tab only the last activity responses are shown.
In the plain and user journey reports all the responses were collected but under the last activity activity_id, activity_name, item, prompt.

**Expected result**
All the data from the completed flow activities are collected and displayed on the admin DataViz, mobile app Data tab, and CSV reports, ZIP archive files

**Video**: https://www.screencast.com/t/LMxM3iizP

**Environment:**
https://admin-dev.mindlogger.org/
Win 10 / Chrome 103
ML v0.21.28 dev
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
user3-dev@ml.com / 123456
Activity Flow 4
Applet password	Qwe123!!!

**Comment by MaksimYurys** [comment]
Verified as fixed.

Video:  https://images.zenhubusercontent.com/103405139/0691879d-4a04-4a8d-82fd-bf910e5d895c/ef852fad_8ca3_47ee_8706_6c6bc1c6bc59.mp4

Environment:
Win 10 // Chrome 103
v0.17.17
https://admin-staging.mindlogger.org/
ML v0.21.42
iPhone 8 // iOS 14.7.1
Samsung Galaxy S8 // Andoid 8
JhoneeMind@gmail.com // Qqww!123
Applet with Activity Flow 3 // activity flow -flow
password // Qqww!123
