### ISSUE TITLE
[UI] Interim screen issues

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2730]
1 - the background should be white
2 - the "Submit" word should start with the capital letter and be in bold

Design:
https://www.figma.com/file/VYuZ9vFaPfK6JnXeAXG8wW/Pre-SRC-Features

Requirements:
https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/2598

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/277422f2-bd7c-439a-a76a-a26a70d41bb8)

Environment:
ML v0.21.28 dev
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
user3-dev@ml.com / 123456
Activity Flow 4
Applet password Qwe123!!!

**Comment by MaksimYurys** [comment]
Verified as fixed

Screenshot: ![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/beee6b3d-0872-48ca-9dfa-f40efe0d13c2)

Environment:
ML 0.21.38 staging
iPhone 8 // 14.7.1
Samsung Galaxy S8 // Android 8
JhoneeMind@gmail.com // Qqww!123
applet - Applet With Act Flow // Qqww!123
