### ISSUE TITLE
The splash screen doesn't show on the screen after starting the activity

### ISSUE THREAD

**Issue by MaksimYurys** [ChildMindInstitute/mindlogger-app#2744]
**Preconditions:**
The user is logged in mobile app
The user has an applet with an activity flow
The activity flow has  activity with the splash screen

**Steps to reproduce:**
1. Launch the activity flow
2. Pay attention to the first screen

**Actual result:** The splash screen doesn't show on the first screen after starting the activity

**Expected result:** The splash screen shown on the first screen after starting the activity

**Video:** https://images.zenhubusercontent.com/103405139/03066699-0124-41ab-ae2d-cc72142b18b1/55600853_7cc3_45e8_b54c_7a3f9638e8c2.mp4

**Environment:**
ML 0.21.33 dev
iPhone 8 // iOS 14.7.1
Samsung Galaxy S8 // Android 8
OmaewaShinderou123@gmail.com // Qqww!123
applet - New700applet

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/RMjBfcl4

Environment:
ML v0.21.42 staging
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
user-stg@ml.com	/ 123456
Activity Flow 1 / My Flow 3
