### ISSUE TITLE
App crashes on opening the Trails activity in the flow

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2745]
**Preconditions**
The app is installed and launched
User is logged in to the account with the activity flow which contains Trails activity at the first place
user3-dev@ml.com / 123456

**Steps to reproduce**

1. Open the applet and start the activity flow
2. Pay attention to the screen
3. Start Trails activity out of the flow
4. Observe the result

**Actual result**
App crashes on opening the Trails activity in the flow

**Expected result**
The user is able to complete trails activity in the flow

**Video**:  https://www.screencast.com/t/jBt5DG8hA
**Crash log (Android):**
https://drive.google.com/file/d/1dET8SxwAtZ7LzG_GLrWERnirGkk0uE9h/view?usp=sharing

**Environment:**
ML v0.21.33 dev
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
user3-dev@ml.com / 123456
Activity Flow 7 / My Flow 1
Applet password Qwe123!!!

**Comment by WorldImpex** [comment]
Crash no repro but instructions are not shown and user cannot write on the screen 

https://images.zenhubusercontent.com/103405139/918bf472-9f5a-4c89-a431-09e8324e6e5a/rpreplay_final1657535968.mp4

**Comment by mtg137** [comment]
could you please check it on new applets? we previously had issues in applet-builder for activity flows, so old applets still have some issues.

**Comment by natalia-muzyka** [comment]
Verified as fixed on a new applet: https://www.screencast.com/t/Ugh9UTTTigBS
@WorldImpex could you look at my new applet on your iPhone 13, please? to make sure that it works for you as well, an invitation:
web-staging.mindlogger.org/join/45e5f975-741b-4e03

Environment:
ML v0.21.36 staging
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
user-stg@ml.com / 123456
Activity Flow 1 / My Flow 1
Applet password: Qwe123!!!

**Comment by WorldImpex** [comment]
I got a crash on the Flanker activity after the practice round. I shared the crash log

**Comment by natalia-muzyka** [comment]
@WorldImpex I created a new ticket for Flanker:
https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/2764
