### ISSUE TITLE
Add an Android warning in the applet builder for Flanker 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2747]
Add a warning to applet builder

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/44bd2b85-1943-4e83-9ddc-326e7c4b5ecc)

Add a warning message on an android device under the activity description in red *The timestamps collected for an android are not as accurate as iOS devices."

**Comment by WorldImpex** [comment]
Not on applet builder

**Comment by natalia-muzyka** [comment]
@mtg137  There is no warning in the applet builder:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/14f79219-2650-4803-a548-d6c69692614d)
