### ISSUE TITLE
[Markdown HTML] The web page is opened partially within the ML app after tapping the link on the markdown message and can't be closed

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2750]
**Preconditions**
The app is installed and launched
User is logged in to the account with the markdown message item and link created with <a> tag within this item
user3-dev@ml.com / 123456

**Steps to reproduce**

1. Open the applet and start the activity
2. Select any responses and proceed to the markdown message screen
3. Tap the link
4. Scroll the web page down
5. Try to move back to the original screen where the link was tapped
6. Observe the result

**Actual result**
The web page is opened partially within the ML app after tapping the link on the markdown message and can't be closed

**Expected result:** 
The external link should be opened fully in the device browser. User shouldn't be limited by the opened link and should have the ability to move back to the original screen (from where the link was tapped).

**Video**: https://www.screencast.com/t/jWWsOsHJn0LC

**Environment:**
ML v0.21.33 dev
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
user3-dev@ml.com / 123456
Activity Flow 8 / Test A
Applet password Qwe123!!!

**Comment by MaksimYurys** [comment]
Verified as fixed.

Video: https://images.zenhubusercontent.com/103405139/2e07c1ef-f6f0-4f79-a10f-5dc72b5ea403/5b82163a_15d4_4ef3_bf6c_6dd5f8b83b83.mp4

Environment:
ML v0.21.40 staging
iPhone 8 // iOS 14.7.1
Samsung Galaxy S8 // Android 8
JhoneeMind@gmail.com // Qqww!123
Conf Reports 2 // activity 3
applet password Qqww!123
