### ISSUE TITLE
Expired/due activities + scheduling specifics

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-app#276]
> Once a user gets a notification for an activity we need red dots on:
> 
> * the mindlogger icon
> * the applet
> * the activity
> 
> and also in ActivityListView we have a section for "Scheduled"/"Due"/"Completed" and that would need to be updated
> 
> To get started, go to https://admin.mindlogger.org and create an applet and update its schedule. Right now, "turn on notifications" works, but we need to respect:
> 
> - [ ] the ability to schedule random notifications between 2 times
> - [ ] disable and activity if it is not a whole-day activity (only let a user answer in the time frame specified by the calendar event)
>   - [ ] the "Due" section should have activities that are scheduled for that current time
>   - [ ] "scheduled" section should tell the user when it will be activated
>   
>   it might be useful to check out
>   
>   * [app/components/ActivityList/sortActivities.js](https://github.com/ChildMindInstitute/mindlogger-app/blob/master/app/components/ActivityList/sortActivities.js) where the activities are sorted into expired/due/completed
>   * [app/services/time.js](https://github.com/ChildMindInstitute/mindlogger-app/blob/master/app/services/time.js) may be deprecated because the parsing of the schedule happens with the [dayspan library](https://github.com/ClickerMonkey/dayspan) so make changes accordingly
>   * [app/state/applets/applets.selectors](https://github.com/ChildMindInstitute/mindlogger-app/blob/master/app/state/applets/applets.selectors.js#L57) contains info about the next/last scheduled activities

― https://github.com/ChildMindInstitute/MATTER-spec-docs/blob/master/active/MindLogger/MindLogger-app/expired-due-activities.md

**Comment by shnizzedy** [comment]
Related https://github.com/ChildMindInstitute/mindlogger-app/issues/306, https://github.com/ChildMindInstitute/mindlogger-app/issues/308

**Comment by binarybottle** [comment]
To summarize and update our requirements, in addition to the red dots on the icon for the app, applet, and activity, we need the ability to configure an optional expiration/timeout for each activity:

- expiration: after getting notified to do an activity, you have X minutes to do that activity

**Comment by WorldImpex** [comment]
duplicated of #623
