### ISSUE TITLE
The white screen is shown on the mobile app after tapping on the "Submit" button in the scheduled flow

### ISSUE THREAD

**Issue by MaksimYurys** [ChildMindInstitute/mindlogger-app#2760]
**Preconditions:**
The user is logged in to the mobile app
The user has an applet with a scheduled activity flows

**Steps to reproduce:**
1. Open an applet with a scheduled activity flows
2. Go to the interim screen
3. Tap on the "Submit" button
4. Pay attention to the screen

**Actual result:**
The white screen is shown on the mobile app after tapping on the "Submit" button

**Expected result:**
The user sees the next screen(next activity) on the mobile app after tapping on the "Submit" button

Video: https://images.zenhubusercontent.com/103405139/822560d1-45f8-4571-9998-36a7bd6c1080/whitescreen.mp4

**Environment:**
ML v0.21.35 staging
iPhone 8 // iOS 14.7.1
Samsung Galaxy S8 // Android 8
qqtest.02@gmail.com // Qqww!123
applet - wwwa1 // Qqww!123

**Comment by MaksimYurys** [comment]
Verified as fixed.

Video: https://images.zenhubusercontent.com/103405139/c8356b06-d4b6-4d32-a5fa-f63b60c03aac/catflowwhitescreen.mp4

Environment:
ML v0.21.35 staging
iPhone 8 // iOS 14.7.1
Samsung Galaxy S8 // Android 8
qqtest.02@gmail.com // Qqww!123
applet - wwwa1 // Qqww!123

**Comment by natalia-muzyka** [comment]
@jj105 
The issue is still reproducible. It looks like it is reproducible on the first attempt to complete the flow. 
Video: https://www.screencast.com/t/LGTmn5Ae5

Environment:
ML v0.21.38 staging
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
user-stg@ml.com	123456
config reports v9 / scheduled flow, one completion, daily
Applet password:	Qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/95wvFlMnp0

Environment:
ML v0.21.42 staging
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
