### ISSUE TITLE
App crashes on the second attempt to process the flow after refreshing the Home screen

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2768]
**Description:**
The flow's name is missing, the order of activities mismatches the builder, and app crashes after tapping on the flow after completing it and refreshing the Home screen

**Preconditions**
The app is installed and launched
User is logged in to the account with the activity flow
user3-dev@ml.com / 123456

**Steps to reproduce**

1. Open the applet and complete the activity flow
2. Go to the Home screen and refresh by swiping down
3. Open the applet and pay attention to the completed flow
4. Tap the flow card
5. Observe the result

**Actual result**
The flow's name is missing, the order of activities mismatches the builder, and app crashes after tapping on the flow after completing it and refreshing the Home screen

**Expected result**
The flow's name is displayed, the order of activities matches the builder, and user is able to process the flow again after completing it once and refreshing the Home screen

**Video 1:** https://www.screencast.com/t/1glVY2IU
**Video 2 (crash):** https://www.screencast.com/t/jPvGq1Daj1

**Environment:**
ML v0.21.36 staging
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
user-stg@ml.com / 123456
Activity Flow 1 / My Flow 2, My Flow 3, My Flow 4
Applet password Qwe123!!!

**Comment by MaksimYurys** [comment]
Verified as fixed.

Video: https://images.zenhubusercontent.com/103405139/9f594df8-6ecb-472f-a9c9-61ff50f50db7/2022_07_14_12_58_07_01_.mp4

Environment:
ML v0.21.38 staging
iPhone 8 // iOS 14.7.1
Samsung Galaxy S8 // Android 8
JhoneeMind@gmail.com // Qqww!123
Applet - actflow3 // Qqww!123
