### ISSUE TITLE
The user received an empty Report after passing the activity

### ISSUE THREAD

**Issue by MaksimYurys** [ChildMindInstitute/mindlogger-app#2770]
**Preconditions:**
The user is logged in at the mobile app
The user has an applet with the configured report

**Steps to reproduce:**
1. Pass the activity
2. Go to the user mailbox
3. Download the received report from MindLogger
4. Open the received report from MindLogger

**Actual result:**
The user received an empty Report after passing the activity

**Expected result:**
The user received a filled Report with correct data after passing the activity

Video: https://images.zenhubusercontent.com/103405139/773324c2-e228-459b-9647-ac36cb18dafa/0bf1af1d_7d99_45c1_af18_3c7adc0dc9cf.mp4

Report: 
https://www.dropbox.com/s/jrxaywwy6aufpo0/REPORT_appletA1_activi_2022-07-12-104326.rar?dl=0

Environment:
ML 0.21.36 staging
iPhone 8 // iOS 14.0.7
Samsung Galaxy S8 // Android 8
qqtest.02@gmail.com // Qqww!123
applet - appletA1 // Qqww!123

**Comment by WorldImpex** [comment]
I also tried to send the PDF report using the same IP parameters and I did not receive an email 
@astef021

**Comment by WorldImpex** [comment]
Yes - I created a new applet today using the report feature and it works now. PDF emailed is still broken though

**Comment by natalia-muzyka** [comment]
after the latest deployment, it is still broken.
I didn't receive email after the first completion,
got it after the second completion and downloaded zip, which contains broken pdf.
video: https://www.screencast.com/t/WSRvqcyo

checked with a newly created applet.

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
v0.17.10
user-stg@ml.com / 123456
config reports v5 / test A
Applet password: Qwe123!!!

**Comment by WorldImpex** [comment]
Short Term approach is to put a hyperlink to the S3 bucket that contains the report. The user should download the encrypted PDF from there. 

- Update the body text of the email to "Please [click this link](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/2770) to download the report." making sure the hyperlink is updated for the report 

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/68d067e9-75ac-4a5e-9bb9-d92cfc6450c3)

**Comment by natalia-muzyka** [comment]
@astef021 I want to clarify do I need to create a separate ticket for this issue I mentioned above, or it will be fixed in scope of this ticket:
I didn't receive email after the first completion,
got it after the second completion and downloaded zip, which contains broken pdf.

cc: @WorldImpex
