### ISSUE TITLE
The "Show report at the end of the activity" checkbox is allowed by default

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2771]
**Steps to reproduce**

1. Open a site https://admin-staging.mindlogger.org/
2. Create a new applet with a builder
3. Add a new activity
4. Open the Reports tab on the activity level
5. Pay attention to the screen

**Actual result**
The "Show report at the end of the activity" checkbox is allowed by default

**Expected result**
The "Show report at the end of the activity" and "Make Report available for Export" checkboxes are in greyed out state until:
- user enters 1 'component' to the report
- OR at least one alert message is set up in the activity

**Video:** https://www.screencast.com/t/S7IurkxL1zd

**Environment:**
https://admin-staging.mindlogger.org/
v0.17.9
Win 10 // Chrome 103

**Comment by natalia-muzyka** [comment]
@binaryExDev Right after selecting "show report" and moving to the other tab or saving the applet, the checkbox will look unselected after opening the reports the next time. On the mobile app side summary will be shown.
Video: https://www.screencast.com/t/DPGWNr6Z91

Environment:
https://admin-staging.mindlogger.org/
v0.17.11
Win 10 // Chrome 103
user-stg@ml.com / 123456
config reports 8 / test A

**Comment by MaksimYurys** [comment]
Verified as fixed.

Video: https://images.zenhubusercontent.com/103405139/2e1b0684-996f-4c42-b505-398b8e8d4926/b7a3c178_4a03_4c86_9ae0_b5a8a58ef0a0.mp4

Environment:
ML v0.21.40
iPhone 8 // iOS 14.7.1
Samsung Galaxy S8 // Android 8
JhoneeMind@gmail.com // Qqww!123
ConfReports 3 // Test 3
aplet password - Qqww!123

**Comment by MaksimYurys** [comment]
@devbtech the main bug is reproduced.

Video: https://www.screencast.com/t/LVtR9TGM0

https://admin-staging.mindlogger.org/
v0.17.14
Win 10 // Chrome 103
JhoneeMind@gmail.com // Qqww!123
ConfReports 3 // Test 3
aplet password - Qqww!123

**Comment by natalia-muzyka** [comment]
@devbtech 
the issue is fixed for the new applet, but reproducible for legacy migrated applets
video: https://www.screencast.com/t/qJdqUHSCJMrk
cc: @jj105 

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
loui_ml@protonmail.com / 12345678
daisy chain loop, daisy chain test
Applet password	Qwe123!!!
