### ISSUE TITLE
Round the score to 4 decimals

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2773]
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/4d529a52-0e43-4748-9ee9-982edd78b916)

Environment:
ML v0.21.36 staging
user-stg@ml.com / 123456
Config reports v2 / Test A
Applet password Qwe123!!!

**Comment by MaksimYurys** [comment]
Verified as fixed.

Screenshot: ![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/b6a904d6-9c25-4f08-aa7d-be4c3f6ce114)

Environment:
ML v0.21.40 staging
JhoneeMind@gmail.com // Qqww!123
ConfReports 2 // activity 3
Applet password Qqww!123
