### ISSUE TITLE
Summary screen is not shown if there is the "Show report" allowed only with the alerts and no score ID

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2780]
Video: https://www.screencast.com/t/gfnFi5Y0TSI3

Latest summary Requirements:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/987ac749-7ceb-433b-aaa5-650ed7839f25)

Environment:
ML v0.21.36 staging
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
user-stg@ml.com / 123456
Config reports v4 / Test C
Applet password Qwe123!!!

**Comment by MaksimYurys** [comment]
Verified as fixed.

Screenshot: ![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/5740067d-4783-4d08-84d5-c035ed3fafcf)

Environment:
ML v0.21.40
iPhone 8 // iOS 14.7.1
Samsung Galaxy S8 // Android 8
JhoneeMind@gmail.com // Qqww!123
ConfReports 2 / activity 1
Applet password // Qqww!123
