### ISSUE TITLE
ML-530 ⁃ Add 'time' input type 

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-app#280]
Like the 'timerange' input type, but just for one time.

ex1: About what time did you go to bed last night? 

X:XX AM/PM

**Comment by shnizzedy** [comment]
[`TimeRange`](https://github.com/ChildMindInstitute/mindlogger-app/tree/master/app/widgets/TimeRange) is composed of two `TimePicker`s: https://github.com/ChildMindInstitute/mindlogger-app/blob/b4851968a86bea1f5173a426e95e1f7696f85f13/app/widgets/TimeRange/index.js#L33-L34

I think we just need to import `TimePicker` and add an `if (screen.inputType === 'time')` condition to the large switch in [`app/components/screen/Widget.js`](https://github.com/ChildMindInstitute/mindlogger-app/blob/master/app/components/screen/Widget.js)

**Comment by binarybottle** [comment]
@InheritxSolution -- Please review

**Comment by InheritxSolution** [comment]
**Approved**
The review has done from my side, @binarybottle I am moving this issue to the Done section because this code is already been merged to the branch so I am not able to approve this particular point.
