### ISSUE TITLE
The mobile app crashes on the interim screen after double tapping on the "Submit" button

### ISSUE THREAD

**Issue by MaksimYurys** [ChildMindInstitute/mindlogger-app#2806]
Preconditions:
The user is logged in to the mobile app.
The user has an applet with activity flow.

Steps to reproduce:
1. Start activity flow.
2. Reach interim screen.
3. Double tap on the "Submit" button.
4. Pay attention to the screen.

Actual result:
The mobile app crashes on the interim screen after double tapping on the "Submit" button.

Expected result:
The mobile app continues to work after double tapping on the "Submit" button.

Video: https://images.zenhubusercontent.com/103405139/68aeec54-9a87-4736-a257-a9eb807cfc3e/c5466d31_789a_4e57_950d_04d6f8743a98.mp4

Environment:
ML v0.21.42
iPhone 8 // iOS 14.7.1
Samsung Galaxy S8 // Android 8
JhoneeMind@gmail.com // Qqww!123
Applet with Activity Flow 2 // flow
applet pass // Qqww!123

**Comment by natalia-muzyka** [comment]
Verified as fixed on Android: https://www.screencast.com/t/XQv21EAm

Environment:
ML v0.21.43 staging
Google Pixel 5a // Android 11
user-stg@ml.com	123456
config reports v11
Applet password	Qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified as fixed on iOS: https://www.screencast.com/t/mBxacufN

Environment:
ML v0.21.48 staging
iPhone 7 // iOS 13.1.1
user-stg@ml.com 123456
config reports v11
Applet password Qwe123!!!
