### ISSUE TITLE
App crashes after idle time is left in the flow activity

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2807]
**Preconditions**
The user is logged on admin panel
There is the applet with activity flow
The mobile app is installed and launched
There is the scheduled flow with the idle time option enabled

**Steps to reproduce**

1. Login to the app
2. Proceed to the scheduled flow
3. Start the flow
4. Wait for idle time (don't do anything, just wait on the screen)
5. Observe the result

**Actual result**
App crashes after idle time is left in the flow activity

**Expected result**
The idle time is applied to every activity within the flow. 
Activity is automatically completed after idle time is left in the flow activity if a user was just waiting on the screen. 
- The interim screen is shown if it is not the last activity in the flow 
- OR The "Report summary" screen is shown if this is the last activity in the flow and there is the Summary screen allowed on the builder side. Responses are submitted.
- OR The "Please wait..."=>"Thanks" screen is shown if it is the last activity in the flow with no Summary screen allowed. Responses are submitted.

Video: https://www.screencast.com/t/v1PZw756

@WorldImpex please, advise, on how it should work.
I assume after the idle time is finished: 
- the interim screen or the next activity screen should be shown
- OR the flow should be completed and answers submitted

Environment:
ML v0.21.42 staging
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
user-stg@ml.com	 / 123456
config reports v11 / one-time completion flow
Applet password	Qwe123!!!

**Comment by WorldImpex** [comment]
Interim screen should be shown

**Comment by natalia-muzyka** [comment]
1 - The single activity started crashing after idle time
Video: https://www.screencast.com/t/H6x8LXCIPsH 
Expected: Thanks screen is shown, selected responses are saved and submitted

2 - Flow activity is not automatically moved to the interim screen after idle time
Video: https://www.screencast.com/t/2VHBHqsGsw5
Expected: Interim screen is shown if the activity is not last in the flow. The "Thanks" screen is shown, and selected responses are saved and submitted.

Environment:
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
ML v0.21.48 staging
user-stg@ml.com / 123456
config reports v11 / one-time completion flow
ML v0.21.48 prod
test-user1@com.us
schedule flows / my flow 1 idle time
Applet password Qwe123!!!

**Comment by natalia-muzyka** [comment]
@binarybottle @WorldImpex I want to make sure that we are on the right way and interpreted a requirement for idle time / timer correct:
when admin sets an idle time or timer, this setting should be applied to every activity in the flow, right?
So if there is the 2 minutes timer added to the event, then user has 2 minutes for every activity?

**Comment by anq83** [comment]
re. Summary tech. details please review the last comments in the 
https://github.com/ChildMindInstitute/mindlogger-app/issues/2808

**Comment by WorldImpex** [comment]
I agree this is a good first version. I responded on 2808

**Comment by natalia-muzyka** [comment]
Verified as fixed. For “Idle for activity” logic (sets in schedule): when time is over - user skipped to interim screen and starts next activity in flow, idle counter resets (starts again).

Environment:
ML v0.21.57
iPhone 13 // iOS 15.6
Google Pixel 5a // Android 11
