### ISSUE TITLE
The flow looks always available in the app after saving the schedule

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2813]
**Preconditions**
The user is logged on admin panel
The mobile app is installed and launched

**Steps to reproduce**

1. Set up the schedule for the activity flow in the future time with the notification
2. Refresh the app home screen or log out/log in
3. Proceed to the applet with the scheduled flow
4. Pay attention to the screen

**Actual result**
The flow looks available in the app after saving the schedule to a future time with the notification. The activity flow card is shown as always available instead of the pre-scheduled, as per the design. Notification is shown as per the saved schedule.

**Expected result**
The flow in the app matches the settings and design after saving the schedule to a future time.
Design: https://www.figma.com/file/VYuZ9vFaPfK6JnXeAXG8wW/Pre-SRC-Features?node-id=29%3A145229

**Notes: After uploading a schedule from CSV file schedule is not applied as well. Only notifications are fired.**

**Video**: https://www.screencast.com/t/fPBRmoQM

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
Config reports v13 / Flow 1, Flow 2
Applet password	Qwe123!!!

**Comment by Matchdev120** [comment]
@natalia-muzyka I'm not able to see scheduled events for activity flow in mobile app.

Can you schedule an event for an activity flow and see if you can find the scheduled event on mobile app?

**Comment by natalia-muzyka** [comment]
@Matchdev120 I see Flow, but it looks like available before the activity start time, instead of being greyed out and showing the time (as per design). And it is still on the screen after the activity end time. It looks like the schedule is applied partially, because if I add a notification then it will show up. 

Please, check the design flow "4. Schedulding activity flows", here is described the expected result in details:
https://www.figma.com/file/VYuZ9vFaPfK6JnXeAXG8wW/Pre-SRC-Features?node-id=35%3A4163

**Comment by natalia-muzyka** [comment]
Scheduled flows look as expected on the mobile app side. 
Scheduling(visibility) works as expected if the entire flow is not started or completely finished.
Related issues are created in jira:
https://mindlogger.atlassian.net/browse/MIN-44
https://mindlogger.atlassian.net/browse/MIN-45

Environment:
ML v0.21.57
iPhone 13 // iOS 15.6
Google Pixel 5a // Android 11

cc: @eleonova-scn @anq83
