### ISSUE TITLE
The next screen is not shown after the first tap on the "Next"/"Submit" button in the flow

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2815]
**Preconditions**
The mobile app is installed and launched
The user is logged in

**Steps to reproduce**

1. Proceed to the applet with the activity flow
2. Start the flow, proceed to the interim screen
3. Tap the Submit button
4. Proceed to the next activity
5. Complete the flow
6. Observe the result

**Actual result**
The next screen is not shown after the first tap on the "Next"/"Submit" button in the flow. There is a delay after tapping the Next/Submit.

**Video**: https://www.screencast.com/t/XQv21EAm

**Environment:**
ML v0.21.42 staging
ML v0.21.43 staging
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
user-stg@ml.com	123456
config reports v11
Applet password	Qwe123!!!

**Comment by binaryExDev** [comment]
@WorldImpex @natalia-muzyka Please advise me but I don't think this is a real issue.
Once a user completes an activity, we're preparing the response data and save it in the response queue.
This takes some time and it's what Natalia experienced.

Natalia - I think you tapped on the submit button multiple times so I disabled the button after click on it once.

**Comment by natalia-muzyka** [comment]
@binaryExDev Now it behaves better on the interim screen, thank you! It should be fixed with the next button as well. Even if I use small activities with ~5 questions it is reproducible on every first screen after the interim. 
Video: https://www.screencast.com/t/X6k0a1mL

**Comment by natalia-muzyka** [comment]
Relates to: Sample A instructions are shown again after completing Test A in the flow Trails activity #2838

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/ZYaUjXRYz

Environment:
ML v0.21.53 staging
iPhone 7 // iOS 13.1.1
iPhone 13 // iOS 15.6
Samsung Galaxy S7 // Android 8
Google Pixel 5a // Android 11
