### ISSUE TITLE
The "Score title" with the score goes beyond the screen of the summary screen.

### ISSUE THREAD

**Issue by MaksimYurys** [ChildMindInstitute/mindlogger-app#2822]
Preconditions:
The user logged into the mobile app.
The user has an applet with the configured report.
An applet has an "activity" that has a "Score title" with a long length.

Steps to reproduce:
1. Pass an activity.
2. Pay attention to the summary screen.

Actual result:
The "Score title" with the score goes beyond the screen of the summary screen.

Expected score:
The "Score title" with the score does not go beyond the summary screen.

Screenshots:
**iPhone 8 // iOS 14.7.1**
![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/b237fb53-044c-4bd8-9f51-b631d90964b7)

**Samsung Galaxy S8 // Android 8**
![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/121d7fd2-b3f3-4606-b681-32446f2ee2de)

Environment:
ML v.0.21.48 staging
iPhone 8 // iOS 14.7.1
Samsung Galaxy S8 // Android 8
JhoneeMind@gmail.com // Qqww!123
little Re-testing 2 / activity1763
applet password - Qqww!123

**Comment by natalia-muzyka** [comment]
Verified as fixed on iOS:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/da5947e9-8a88-462b-b753-44c6a4d99b97)

Environment:
ML v.0.21.52 staging
iPhone 7 // iOS 13.1.1

**Comment by yzenchanka** [comment]
Also tested on 
Environment:
ML v.0.21.52 staging
iPhone 7+ DM // iOS 14.4.1
Verified as fixed on iOS
![image](https://user-images.githubusercontent.com/112855442/190604372-94087bf0-2cff-4f9a-9fb4-1b2f18052dc3.png)
