### ISSUE TITLE
The last scheduled activity becomes available after the activity end time

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2826]
**Steps to reproduce**
1. Open a site and log in: https://admin-staging.mindlogger.org/
2. Open a General or Individual calendar (it should be clean)
3. Add one new event:
- no access before activity start time
- activity start time = the current time + 5 minutes
- activity end time = activity start time + 2 minutes
4. Open a mobile app, refresh the Home screen
5. Open the applet with the schedule
6. Wait for activity end time
7. Pay attention to the scheduled event

**Actual result**
Activity becomes available (no schedule) after the activity end time

**Expected result**
Activity disappeared from the screen after the activity end time

**Notes:** The issue is reproducible with the last activity scheduled for the day as well. Reproducible for non-repeated an repeated events (daily, weekly, weekday, monthly).

**Video 1**: https://www.screencast.com/t/bTGeVL6RHHsz
**Video 2**: https://www.screencast.com/t/LLp8MAVk6QCH
**Video 3 (uploaded from CSV):** https://www.screencast.com/t/R9omn7LH

**New videos (04/11/22):**
One event: https://www.screencast.com/t/gQxp3NSngFH
Three events: https://www.screencast.com/t/RlCng5t2GwdX

**Notes: Reproduced with the CSV schedule**

**Environment;**
ML v0.21.48 staging
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
ml_general_acc@protonmail.com 12345678
my applet
Applet password	Qwe123!!!
ML v0.21.57 staging
iPhone 13 // iOS 15.6
Google Pixel 5a // Android 11
test_account2@ml.com / 123456
Schedule check
Schedule check (1)
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
The main issue is it is not possible to set up an activity (by using UI) with no repeats on a particular day now.
Not reproduced if a schedule is uploaded with a CSV.

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/749d2546-741c-49ba-bfa8-914397565680)

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/1db057a9-ec03-4b71-9cbd-32238a3122dd)

**Comment by e-kass** [comment]
Not (currently) related to Ped Screener

**Comment by natalia-muzyka** [comment]
The issue is still reproducible. Sometimes it is reproducible even for repeated events, like Daily, Weekly, Weekday, or Monthly (reproducibility 1/3).

Video: https://www.screencast.com/t/jNKixQnet0s

**Comment by natalia-muzyka** [comment]
Ticket is updated 04/11 the main issue is: The last scheduled activity becomes available after the activity end time

**Comment by natalia-muzyka** [comment]
@Tom1204 @BamMironov the issue is reproduced on all events not, not only on the last for the day. Reproduced also for activity flows.

Video: https://images.zenhubusercontent.com/103405139/69e4d31a-4090-4d55-b1c5-86703eb22d56/bandicam_2022_12_15_17_33_08_328.mp4

Environment:
ML v0.21.71
iPhone 7 // iOS 13.1.1
Samsung Galaxy S7 // Android 8
iPhone 13 // iOS 15.6
Google Pixel 5a // Android 11
test_user30@ml.com / 123456
applet: DBT, Flow

**Comment by yzenchanka** [comment]
Verified as fixed 
Environment:
ML v0.21.74
iPhone 7 Plus // iOS 14.4 
Google Pixel 3XL // Android 10
userfive@ml.com / QAtest123
applet: New applet/A2, B2, Flow, Flow2

**Comment by natalia-muzyka** [comment]
Verified as fixed.

Environment:
iPhone 7 // iOS 13.1.1

Samsung Galaxy S7 // Android 8

iPhone 13 // iOS 15.6

Google Pixel 5a // Android 11

ML v0.21.74 staging
