### ISSUE TITLE
The "Invalid or Expired Link." error message is shown on the page after clicking on the link to reset the password.

### ISSUE THREAD

**Issue by MaksimYurys** [ChildMindInstitute/mindlogger-app#2827]
Preconditions:
The user has an account in the app.
The user has a password reset email.

Actual result:
The "Invalid or Expired Link." error message is shown on the page after clicking on the link to reset the password.

Expected result:
The valid link to recover the password is present in an email after clicking on the link to reset the password.

Screenshot:
![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/e7affd68-7b4f-4d0b-8b82-2d9be024233a)

Environment:
ML v0.21.48 staging
qqqttest01@gmail.com // Qqww!123

**Comment by natalia-muzyka** [comment]
Issue is still reproducible on staging; https://www.screencast.com/t/StKfEy6M

**Comment by MaksimYurys** [comment]
Verified as fixed for prod and stage:
![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/21e57aef-a8fa-4c2b-9aab-d058297c1b10)
