### ISSUE TITLE
Applets are not showing up on android app

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-app#283]
I have four applets showing up on api.mindlogger.org, but the app on my android phone just shows the splash with "about mindlogger".

Would really appreciate it if someone can look into this!

here's my user info:
{
  "_accessLevel": 2,
  "_id": "5d3f6a7c24f88e4856c287bd",
  "_modelType": "user",
  "admin": false,
  "created": "2019-07-29T21:51:56.369000+00:00",
  "creatorId": "5d3f6a7c24f88e4856c287bd",
  "email": "mikemxxiao@gmail.com",
  "emailVerified": false,
  "firstName": "mike",
  "lastName": "xiao",
  "login": "hotavocado",
  "otp": false,
  "public": false,
  "size": 0,
  "status": "enabled"
}

**Comment by shnizzedy** [comment]
@hotavocado what's the response for [GET /user/applets?ids_only=true](https://api.mindlogger.org/api/v1#!/user/user_getOwnApplets)

**Comment by hotavocado** [comment]
@shnizzedy 

[
  "5cf23defc834f010f4b5989e",
  "5d715ba127bc08367a6291bf",
  "5d716a3227bc085351f0550d",
  "5d84ff8ed5553f0dfa44878d",
  "5d85023ed5553f0dfa448794",
  "5d85459ed5553f0dfa44879d",
  "5d854f0ed5553f0dfa4487a9"
]

**Comment by shnizzedy** [comment]
I deactivated the following applets since they have invalid URLs: 

```json
[
  "5cf23defc834f010f4b5989e",
  "5d84ff8ed5553f0dfa44878d"
]
```

Try again?

**Comment by hotavocado** [comment]
Still no luck :(

**Comment by hotavocado** [comment]
This issue is resolved
