### ISSUE TITLE
[PROD] There is a duplicated activity flow in the app in the migrated daisy chain applet

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2832]
**Preconditions**
User is logged in on the admin panel
https:/admin.mindlogger.org/
bernard_ml@protonmail.com / qwe123!!!
Mobile app is installed and launched, user is logged in

**Steps to reproduce**

1. Open the app
2. Proceed to the "daisy chain report" applet
3. Open admin
4. Edit the daisy chain applet
5. Open the Activity flow tab
6. Compare quantity of flows between builder and app

**Actual result**
 There is a duplicated activity flow in the app in the migrated daisy chain applet

**Expected result**
The quantity of flows in the app matches the builder in the migrated daisy chain applet

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/41d2db06-d2df-4eb8-b7ae-6511f6caa92b)

**Environment:**
https:/admin.mindlogger.org/
Win 10 / Chrome 103
ML Pilot v0.21.48 prod
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
bernard_ml@protonmail.com / qwe123!!!
daisy chain report, daisy chain 0.17.76
Applet password:	Qwe123!!!

**Comment by karser** [comment]
Should be fixed
![image.png](https://images.zenhubusercontent.com/62e92fe4e7d41a51869b6319/6b0d14f8-2653-41e8-a5fe-7222cb683dac)

**Comment by natalia-muzyka** [comment]
@karser  I see the issue is fixed for: 
the "daisy chain report", daisy chain ML Pilot 0.17.57, daisy chain report (loop) applets, 

but is still reproducible in:
the "daisy chain 0.17.76", "daisy chain 0.19.25" on the same account

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/25524096-9249-498b-8787-c03dc2e5c3f6)

**Comment by karser** [comment]
@natalia-muzyka  Please check the "daisy chain 0.17.76", "daisy chain 0.19.25" 
If all is good I will run my script and remove other duplicated flows.

**Comment by natalia-muzyka** [comment]
@karser "daisy chain 0.17.76", "daisy chain 0.19.25" are looking fine.
Thank you for noticing the badge issue, we have tickets for it:
The "Hide" badge is selected after unselecting it and saving the applet#1048
The "Hide badge" checkbox works in opposite way to its state#2792
The "Hide badge" checkbox is unselected by default#1041

**Comment by natalia-muzyka** [comment]
@karser  I see duplicated flows on the same account (bernard_ml@protonmail.com / qwe123!!!) in the next applets:
Cumulatives (Natalia) (full)
cumulative retest
daisy chain report (loop)

**Comment by karser** [comment]
@natalia-muzyka I fixed those applets too. The problem was the applets were cached.
![image.png](https://images.zenhubusercontent.com/62e92fe4e7d41a51869b6319/22ce5e37-f474-4658-998a-d7f72dbacd8e)

**Comment by natalia-muzyka** [comment]
@karser applets from my last comment are fixed, but I'm still catching duplicated flows on the other account.
@WorldImpex would you agree to check only the actual applets that are in use by our stakeholders in real programs on prod and fix them only? If yes then, please, share credentials with me.

**Comment by karser** [comment]
I removed duplicated flows for all DB and refreshed the cache for the related applets. Please check @natalia-muzyka

**Comment by natalia-muzyka** [comment]
See no duplicated flows now on my accounts. Verified as fixed.

Environment:
ML Pilot v0.21.48 
Google Pixel 5a // Android 11
Samsung Galaxy Tab S6 SM-T865 // Android  9.0
Apple iPad 9th gen (2021) / iOS 15.5
anita_ml@protonmail.com	qwe123!!!
bruce_ml@protonmail.com	12345678
bernard_ml@protonmail.com	qwe123!!!
