### ISSUE TITLE
[Flanker]The app crashes is the user doesn't give an answers

### ISSUE THREAD

**Issue by MaksimYurys** [ChildMindInstitute/mindlogger-app#2834]
Preconditions:
The user is logged into the mobile
The user has an applet with the "Simple & Choice Reaction Time Task Builder" activity

Steps to reproduce:
1. Launch the "Simple & Choice Reaction Time Task Builder" activity
2. Don't give answers
3. Pay attention to the screen

Actual result:
The app crashes is the user doesn't give an answers

Expected result:
The app doesn't crash if the user doesn't give an answers

Video:
https://images.zenhubusercontent.com/103405139/8d9a2745-ceab-4623-af5f-6ea27ee33ad8/18a647a0_2278_4656_b8d6_bb849b3394dc.mp4

Environment:
MindLogger Pilot v0.21.48 prod
iPhone 8 // 14.7.1

**Comment by natalia-muzyka** [comment]
url to create flanker applet:
https://raw.githubusercontent.com/ChildMindInstitute/mindlogger-flanker-applet/master/protocols/flanker/flanker_schema

video (how to create): https://www.screencast.com/t/kCZeWUkGLZy0

account with activities:
flanker_test@mail.com / 123456
config flanker v5, v6

**Comment by yzenchanka** [comment]
Verified as fixed. The app doesn't crash if the user doesn't give an answers
**Environment:**
Mobile app version 0.21.59
iPhone 7 Plus / iOS 14.4
iPad 7 Gen / iOS 15.4.1
account with activities:
flanker_test@mail.com / 123456
config flanker v5, v6

**Comment by natalia-muzyka** [comment]
Verified as fixed.

Environment:
Mobile app version 0.21.59
iPhone 7 // iOS 13.1.1
iPhone 13 // iOS 15.6
staging account:
flanker_special@ml.com / 123456
Flanker_360, Config Flanker (both activities)
