### ISSUE TITLE
Hidden activity/flow is not shown up in the scheduled start time

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2835]
**Preconditions**
The user is logged on admin panel
There is the applet with activity flow
The mobile app is installed and launched

**Steps to reproduce**

1. Set up the schedule for the activity and activity flow in the future time:
-activity start time
-end time
-notification
2. Hide the activity and flow, save the applet
3. Refresh the app home screen or log out/log in
4. Proceed to the applet with the scheduled hidden activity and flow
5. Wait for the activity start time
6. Pay attention to the screen
7. Wait for notification time
8. Repeat steps 5-7 with the flow.
9. Observe the result

**Actual result**
Hidden activity is not shown up in the scheduled start time. Notification is received.

**Expected result**
If an activity or activity flow is hidden but scheduled, then the activity or activity flow is only shown on that date/ time.

**Requirements:**
https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-builder/700
https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/1552

**Video**: https://www.screencast.com/t/bVYTP3biCMu

**Notes: issue is possibly related to:**
https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/2813

**Environment:**
https://admin.mindlogger.org/
Win 10 / Chrome 103
ML v0.21.48 staging, prod
iPhone 7 // iOS 13.1.1
Samsung Galaxy Tab S6 SM-T865 // Android  9.0
Apple iPad 9th gen (2021) / iOS 15.5
test-user1@com.us / qwerty
Schedule flow
https://admin-staging.mindlogger.org/
user-stg@ml.com
Config reports v13 
Applet password: Qwe123!!!

**Comment by e-kass** [comment]
No scheduling in Ped Screener

**Comment by natalia-muzyka** [comment]
It looks like the requirements were interpreted incorrectly, waiting for a reply here: https://matter-lab.slack.com/archives/C015UPV6B8U/p1665482072787859
