### ISSUE TITLE
BUG: Healthy Brain Network (NIMH Content) V0.30 applet, broken scheduling and applet builder

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-app#2839]
URGENT: This applet has been in use for the last 2 years and has many active users in the HBN research study.

There are some problems with applet **Healthy Brain Network (NIMH Content) V0.30**, which is owned by arno@childmind.org.

1. schedule page is broken
2. applet builder does not load
3. invites are going through but the applet does not show up on the user's phone (I found that this was a general issue for all applets right now, so I made another ticket here:  #2840).

[Please watch Loom video](https://www.loom.com/share/2d5a06cd4e104f25916155a0d5b72f99)

**Comment by natalia-muzyka** [comment]
@karser regarding the builder it looks like something that you are already working at, and we faced the same when we were testing new applet URLs for cognitive applets. Ticket:
https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-builder/910

**Comment by WorldImpex** [comment]
1. Scheduling might be a cache issue. It looks like it works in incognito 
2. Applet builder fixed 
3. Visibility of Applet on device fixed
