### ISSUE TITLE
BUG: Applets are not showing up on user phones after invites go through

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-app#2840]
URGENT: Affects a number of HBN study participants

Steps to replicate:
1. invite an account to an applet as USER
2. accept invite under that account in web.mindlogger.org
3. the invite goes through and the user shows up under the USER table on the admin panel
4. log in under the account on mobile device, the applet does not show up

Here's a video that shows me running into this issue 3 times with 3 different applets and 2 accounts. For context, this video follows from #2839 

[Watch Loom video here](https://www.loom.com/share/23498eb56c5540a09cb8748a0d273cf7)
 
My phone is a OnePlus 8 Pro running Android 11 and MindLogger version 0.21.48

**Comment by natalia-muzyka** [comment]
@karser it looks like the issue that I faced before on some staging and prod accounts. It was resolved for my accounts in the scope of this ticket (maybe here you can find some additional info that can help):
https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-backend/1283

**Comment by WorldImpex** [comment]
@karser Here is the PR that resolved that issue as well https://github.com/ChildMindInstitute/mindlogger-backend/pull/1294

**Comment by karser** [comment]
@WorldImpex looks like that's different. From what I see so far the problem is in "'EMA Assessment (Mid Day)'" activity of "Healthy Brain Network (NIMH content) v0.30" applet. Probably some fields are missing. Looking into that.

**Comment by WorldImpex** [comment]
Resolved for EMA type applets
