### ISSUE TITLE
There is a blank screen after resuming Flanker activity on stimulus or summary screen

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2842]
**Preconditions**
Mobile app is installed and launched.
User is logged in.
There is a Flanker applet or activity on the account.

**Steps to reproduce**

1. Start Flanker activity
2. Begin practice
3. Close activity on a stimulus screen
4. Resume activity
5. Pay attention to the screen
6. Close and restart the activity
7. Proceed to summary screen
8. Close and resume activity
9. Observe the result

**Actual result**
There is a blank screen after resuming Flanker activity on stimulus or summary screen

**Expected result**
After resuming on stimulus screen: trial block/test block is restarted.

**Video:** https://www.screencast.com/t/5H8Jyu2P

**Environment:**
ML v0.21.48 prod, staging
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
Samsung Galaxy Tab S6 SM-T865 // Android  9.0
Apple iPad 9th gen (2021) // iOS 15.5
prod account:
test-user1@com.us	/ qwerty
Flanker_360 (2), cognitive tasks retest (1)
staging account:
flanker_test@mail.com / 123456
Flanker_360 (11), config flanker
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
@anq83 I retested this issue after mentioning it on standup, 
and it looks like the iOS environment was copied to the ticket accidentally. 
I'm sorry for the confusion.
On iOS after resuming the trial is restarted.
Video: https://www.screencast.com/t/QJhsasI6CI

cc: @eleonova-scn @WorldImpex @binarybottle

**Comment by anq83** [comment]
@natalia-muzyka Yes, thanks, I've already reproduced it on Google Pixel 3 XL.
It seems the only OS 'Android' is matter. Working on fix.

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/3cBKXtZxi

ML v.0.21.52 staging
Google Pixel 5a // Android 11
Samsung Galaxy S7 // Android 8

**Comment by natalia-muzyka** [comment]
@anq83 please, take a look at iOS as well,
I'm able to reproduce the issue, but it is floating. 
It reproduces often after a few times resuming the activity.
Video: https://www.screencast.com/t/gEI30Xpjo

cc: @yzenchanka 

Environment:
ML v.0.21.52 staging
iPhone 7 // iOS 13.1.1
iPhone 13 // iOS 15.6

**Comment by anq83** [comment]
@natalia-muzyka ok, thanks, I'll try to reproduce

**Comment by anq83** [comment]
I could not to reproduce it during 1h

**Comment by anq83** [comment]
@natalia-muzyka

**Comment by anq83** [comment]
@natalia-muzyka Discussed during daily meeting, we'll merge to git and deploy the current fix for Android, different components used for Flankers in iOS or Android, so this is safe.
And the fix for iOS we'd prepare later, if we get stable reproduce.
I suppose this is the same (or at least related) issue as when the app crashes on Flanker activity.
I've cought such crashes when Flanker had images, but not all such Flankers will cause crash, just some, it is during idle or resume after idle.
And sometimes before crashes I've observed the blank screen.
We can discuss it later and you'd create a new ticket expecially for iOS.

**Comment by natalia-muzyka** [comment]
Thank you for clarification, @anq83! 
I agree it looks like also related to the crashing issue. When I was able to reproduce a blank screen the app sometimes crashed after a while. I'll investigate more and create a ticket for iOS.

**Comment by natalia-muzyka** [comment]
@anq83 please, take a look at the related issue: https://mindlogger.atlassian.net/browse/MIN-49
We are able to reproduce the issue with Tatiana after a couple of attempts.

**Comment by yzenchanka** [comment]
Verified as fixed. After resuming on stimulus screen: trial block/test block is restarted.
**Environment:**
Mobile app version 0.21.59
iPhone 7 Plus / iOS 14.4
iPad 7 Gen / iOS 15.4.1
**staging accounts:**
flanker_test@mail.com / 123456
Flanker_360 (15)
Applet password: Qwe123!!!
flanker_special@ml.com / 123456
Flanker_360, Config Flanker(both activities)

**Comment by natalia-muzyka** [comment]
Verified as fixed.

Environment:
Mobile app version 0.21.59
iPhone 7 // iOS 13.1.1
iPhone 13 // iOS 15.6
staging account:
flanker_special@ml.com / 123456
Flanker_360, Config Flanker (both activities)
