### ISSUE TITLE
Incorrect TEXT of Checkboxes For Generating Report and Score Summary Screen

### ISSUE THREAD

**Issue by e-kass** [ChildMindInstitute/mindlogger-app#2855]
**TEXT** of checkboxes is incorrect. 

1. (incorrect) “Make Report available for Export” → “Generate Report” (correct)
2. (incorrect) “Show report at the end of the activity” → “Show Score Summary” (correct)

Note: To my knowledge, font, position of checkboxes, etc is correct. ONLY the text itself is incorrect.

![Screen Shot 2022-09-01 at 3.31.14 PM.png](https://images.zenhubusercontent.com/6310fa4035485166fdf9897e/ed9ec6ec-0bde-4b66-8ff9-abb03e32e3f0)

**Comment by TatianaBessonova** [comment]
Verified as fixed. The labels are correct.

**Environment:**
https://admin-staging.mindlogger.org/
Applet builder version v0.18.9-alpha
Chrome 106
![image.png](https://images.zenhubusercontent.com/6343d78c6dec4b57073d9061/44ff5db6-5c0f-4134-bcfa-6d120b905acb)
