### ISSUE TITLE
Score and Section Name Constraints

### ISSUE THREAD

**Issue by e-kass** [ChildMindInstitute/mindlogger-app#2856]
Currently, only letters and underscores are accepted in score names and section names. Spaces, symbols, and numbers must be allowed in score names and section names.

For example, the following should be allowed:

- GAD-7
- Anxiety / Depression
- PHQ-9: Depression Symptoms

![Screen Shot 2022-09-01 at 3.51.06 PM.png](https://images.zenhubusercontent.com/6310fa4035485166fdf9897e/d116f574-93c7-4896-beae-b1fcde553bad)

**Comment by TatianaBessonova** [comment]
Verified as fixed. "Score Title" and "Section Name" fields accept letters, numbers, special characters and spaces.
Environment:
https://admin-staging.mindlogger.org/
Applet builder version v0.18.9-alpha
Chrome 106
