### ISSUE TITLE
Radio Options not Rendering

### ISSUE THREAD

**Issue by henryrossiter** [ChildMindInstitute/mindlogger-app#288]
After reuploading a working applet on a different account, the options on radio screens don't render. All radio screens now look like this:
<a href="url"><img src="https://user-images.githubusercontent.com/31543235/65969929-3a0a7000-e42b-11e9-91c4-f5c80eaa3076.png" height="400" width="200" ></a>
Item schema for the example is at:
https://github.com/henryrossiter/MindLoggerActivitySets/blob/master/items/healthy_homes/living_type.jsonld

**Comment by akeshavan** [comment]
It looks like language defaults to english in the context, so your options are:

1. remove the {"en": ...} key and just have text:

from 
```javascript
"schema:name": {
  "en": "Mobile Home/trailer "
}
```

to 
```javascript
"schema:name": "Mobile Home/trailer "
```

or, 

2. encode language in the expanded form:

```javascript
                "schema:name": {
                    "@language": "en",
                    "@value": "Mobile Home/trailer"
                 }
```

**Comment by henryrossiter** [comment]
Thanks, I was able to fix this. It only works with the second option suggested (expanded form).
