### ISSUE TITLE
⬆️ Update reprolib prefixes to `reprolib:`

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-app#293]
I think these are already stored as global variables in [app/models/json-ld.js](https://github.com/ChildMindInstitute/mindlogger-app/blob/28af82de41236a71f74f23418a8e37ed9b089a88/app/models/json-ld.js#L3-L43), so we should just need to find-and-replace `https://schema.repronim.org/` with `repronim:`.

*Caveat*: Many of these keywords are out of date since [reprolib added a level of nesting to the schema about a month ago](https://github.com/ReproNim/schema-standardization/pull/265). Eg, what we have as `repronim:allow` is now `repronim:terms/allow`.

_Originally posted by @shnizzedy in https://github.com/ChildMindInstitute/mindlogger-app-backend/pull/207#issuecomment-547973883_

**Comment by odziem** [comment]
https://github.com/ChildMindInstitute/mindlogger-app/pull/294 updates the prefixes.
