### ISSUE TITLE
💄 Improve slider widget.

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-app#300]
(make it smoother, more responsive to touches, and better looking; allow user to tap on vertical line to set knob position) -- make sure that when slider bar goes below the screen that the user can scroll down to see the bottom

**Comment by shnizzedy** [comment]
@curtpw here's a reverse-chronological timeline of this issue. Afaik, the October thing is not a priority, just the 2 things mentioned in the "last week" comment.

last week: https://github.com/ChildMindInstitute/mindlogger-app/pull/304
> 1. This PR uses the original (unmaintained, but functional) library, which does not have the tapping functionality.
> 2. The @miblanchard/react-native-slider fork (also not actively maintained) includes the tapping functionality but has a bug where outdated values are returned from onValueChange and onSlidingComplete events.

― https://github.com/ChildMindInstitute/mindlogger-app/pull/304#issuecomment-558858927

October: https://github.com/ChildMindInstitute/mindlogger-app/issues/289
> instead of setting the min value to 0 and max to the length of the items in the list, we need to extract the min and max values from the items in the list and plug it in there.

― https://github.com/ChildMindInstitute/mindlogger-app/issues/289#issue-501068057

June: https://github.com/ChildMindInstitute/mindlogger-app/pull/227

> To summarize what people have been wanting in a better slider bar, I refer to Stu's backlog (https://github.com/orgs/ChildMindInstitute/projects/9#card-22461241) card:
> 
> > React Native app: Improve slider widget (make it smoother, more responsive to touches, and better looking; allow user to tap on vertical line to set knob position) -- make sure that when slider bar goes below the screen that the user can scroll down to see the bottom.

― https://github.com/ChildMindInstitute/mindlogger-app/pull/227#issuecomment-553707557

**Comment by binarybottle** [comment]
Going forward, the following are our current high-priority design improvements for the slider bar: 
- set default value so that the knob position is in the middle of the line
- allow user to tap on the line to set the knob position

The following are also desirable improvements:
- set the orientation to horizontal or vertical
- set the number of tick marks, and their respective labels

We also want to make sure we are using a well-maintained slider bar library.

**Comment by InheritxSolution** [comment]
Hello Arno,

Please find the documentation for slider point.
Documentation contains what we did in the slider task and for what reason we stopped at a point.
[Mind Logger #300 Improve slider widget.docx](https://github.com/ChildMindInstitute/mindlogger-app/files/4002365/Mind.Logger.300.Improve.slider.widget.docx)

Best Regards.

**Comment by binarybottle** [comment]
Contents of docx:

![image](https://user-images.githubusercontent.com/236532/71525436-b3392800-289f-11ea-80a6-15137430408e.png)

**Comment by Eden2016** [comment]
@binarybottle Is there any information on how the ticks would look like from data perspective, what data model would be used to represent them? So I could get everything prepared on the mobile side.

**Comment by binarybottle** [comment]
@Eden2016 -- I believe that the data schema already accounts for step-wise increments.  Please take a look at that.  Continuous values for smooth slider movements are missing.

**Comment by binarybottle** [comment]
Closing this issue because most of the above points have either been resolved, are in separate issues, or are desirable and we will introduce new issues (ticks + labels,  orientation of slider, etc.).
