### ISSUE TITLE
ML-556 ⁃ 📬 No red dot on app icon when it's time to complete an activity

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-app#306]
We should add a red notification dot (like messenger, outlook, etc) that shows up on the top right corner of the app icon when the user is notified to complete an activity.

**Comment by binarybottle** [comment]
Clarification: The activities within the activity list do have red dots on both platforms.  It is the MindLogger icon on an iPhone that doesn't have a dot when there is a due activity (the dot does appear on the icon in Android phones).

**Comment by shnizzedy** [comment]
For issue findability, I'm mentioning that the dots in question are called "badges" on iOS.

**Comment by binarybottle** [comment]
iOS has a small dot to the left of the text below the icon!
![Screenshot 2019-12-08 at 8 35 52 PM](https://user-images.githubusercontent.com/236532/70490070-71e90000-1acb-11ea-924d-ee634a089471.png)

**Comment by binarybottle** [comment]
Henry Rossiter: "I believe [the little dot] indicates the app is in beta"

**Comment by shnizzedy** [comment]
Yes, the orange dot next to an app's title indicates that app was installed via TestFlight; the red badge on an app's icon indicates unresolved notifications.

> When you’ve downloaded the beta app, you’ll see an orange dot next to its name that identifies it as a beta.

― https://testflight.apple.com/

> Your app can display a small red oval containing a white number on your app icon to indicate when there are tasks to perform, such as pending intervention events or assessments. Keep in mind that badging of your app can be turned off, so if your app relies on badging to communicate important information, you run the risk of people missing it.

― https://developer.apple.com/design/human-interface-guidelines/carekit/user-interaction/notifications-and-badging/

**Comment by InheritxSolution** [comment]
![IMG_0686](https://user-images.githubusercontent.com/3973666/70804417-761f6100-1ddc-11ea-95d2-a60f6d5e08be.PNG)

Done.

Please check the red marked app icon into the above screenshot

**Comment by InheritxSolution** [comment]
Hello @binarybottle as per discussed here I am sharing the documentation for the same issue.
[Mind Logger #306 No red dot on app icon.docx](https://github.com/ChildMindInstitute/mindlogger-app/files/4004469/Mind.Logger.306.No.red.dot.on.app.icon.docx)

Let me know your thoughts for the same.

Thanks.

**Comment by binarybottle** [comment]
Swapnil's docx contents:

<img width="708" alt="Screen Shot 2019-12-27 at 12 11 17 PM" src="https://user-images.githubusercontent.com/236532/71525936-22178080-28a2-11ea-9273-12d7895a8252.png">
[Mind.Logger.306.No.red.dot.on.app.icon.docx](https://github.com/ChildMindInstitute/mindlogger-app/files/4005860/Mind.Logger.306.No.red.dot.on.app.icon.docx)
