### ISSUE TITLE
ML-557 ⁃ 📣⏰ Notifications are too subtle

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-app#307]
We should find a way to make the notifications more noticeable. From testing the app so far, notifications don't show on the lock screen, but I was able to find them after scrolling through my list of banner notifications. This is the case for android and ios (I confirmed with a friend earlier today). 

Some ideas:
1. Have the app ask users and automatically enable push notifications on the lock screen
2. Add alarms to the notification, like the alarm clock app. It can ring for several seconds at the scheduled time or vibrate if sound is off. 
3. In the future, sync notifications to the vibration of a wrist wearable

**Comment by shnizzedy** [comment]
I'm getting banner notifications on my lock screen on iOS:

![screenshot: notifications on iOS lock screen](https://user-images.githubusercontent.com/5974438/69975406-2b0c7080-14f5-11ea-8a13-1526567abf2c.png)

**Comment by binarybottle** [comment]
It would be good to also enable configuration of an ALARM -type notification.  
https://matter-lab.slack.com/archives/CRALZK8K0/p1575671335025500

**Comment by InheritxSolution** [comment]
Need more understanding for the alarm stuffs.
I am not able to understand from the provided video.

**Comment by InheritxSolution** [comment]
@binarybottle I have gone through the video that you have shared in your previous comment but not able to understand your concern.

What I understand is like you need to add on one date/time picker where the user can select the date/time and notification gets fired accordingly.

Correct me If I am wrong @binarybottle

**Comment by binarybottle** [comment]
Emulate Spothero ios/android app's alarm?

**Comment by binarybottle** [comment]
@InheritxSolution -- I'm going to have @Eden2016 look into this issue.

**Comment by binarybottle** [comment]
@Eden2016:

> In the case of the notifications issue, I searched for the ready alarm solution on the Net, but there are only implementations for Android, but not iOS.
> So we could add an alarm feature, but only on Android devices
