### ISSUE TITLE
Activity timeout

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-app#308]
As a protocol builder, I want to set a time limit on an activity so that the user can start it within a given number of minutes. 

Description:  The 'Surveys' screen currently shows activities scheduled for future times and ones have already been completed, and a user is able to tap the button and access them. There are some research protocols like NIMH EMA that restricts the times when a user is able to fill out assessments depending on the times the assessments are scheduled. To address this in Mindlogger,  timeout information will be retrieved from the protocol. 

Requirements
1. Add option to set an activity timeout interval (for example 30 min) within the protocol
2. If user is idle for 2 mins while taking an assessment, it autocompletes. 
3. The activity should only be accessible to the user from the scheduled time to X amount of time after the scheduled time, where X is the timeout interval.
4. The user should only be able to start and/or finish the activity before the time out expires. Any answered questions will be accepted if partially completed. 
5. Buttons for future activities can be greyed out, and the user should see something like "scheduled for 3:15pm"
6. Buttons for past activities can be hidden completely

Acceptance Criteria: 
Given I am building a protocol
When I define the timeout of a scheduled activity
Then the user will only have a set amount of time to finish the activity after the scheduled start

Given I am a user 
When I forget to finish a scheduled assessment with a timeout
Then only the questions answered are accepted and I no longer see the assessment on my survey tab

**Comment by binarybottle** [comment]
For some studies it is fine to allow a user to respond when they want to.  Perhaps it would be better to (1) add a configurable option to only show due activities, and/or (2) indicate due items with a red dot and deemphasize non-due items (lower contrast, lower on the screen,...).

**Comment by hotavocado** [comment]
The configurable option sounds like the best bet!

**Comment by WorldImpex** [comment]
moved to #739
