### ISSUE TITLE
ML-561 ⁃ 🔓🔔 Have app ask users to enable lock screen notifications 

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-app#310]
Notifications won't show up on the lock screen unless a user goes to the settings on the phone and enable them manually. There are apps that automatically try to change this setting when the user opens the app for the first time. This would be an important feature to have on Mindlogger to ensure all users are getting notifications in a consistent manner.

**Comment by felipebrunetti94** [comment]
May I try ?

**Comment by InheritxSolution** [comment]
![IMG_0687](https://user-images.githubusercontent.com/3973666/70803726-bf6eb100-1dda-11ea-8f87-9297edf76b99.PNG)

Above is the screenshot which is taking permissions from user at first when app launch.

**Comment by shnizzedy** [comment]
@hotavocado is https://github.com/ChildMindInstitute/mindlogger-app/issues/310#issuecomment-565443780 what you mean for this issue? I've gotten that "“MindLogger” would like to send you notifications" request every time I've installed fresh for at least the 10 most recent versions.

**Comment by hotavocado** [comment]
This is what I mean! More specifically lock screen notifications, not just banners etc.
