### ISSUE TITLE
ML-563 ⁃ Make radio buttons in iOS comparable to those in Android.

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-app#312]
- [ ] radio
- [ ] multi select (checkboxes)
- [ ] text input

> Android radio buttons and checkboxes look good, but an iOS radio selection results in a tiny checkbox rather than a colored dot (as in Android) and in IOS instead of checkboxes, there are radio buttons.

― @binarybottle

**Comment by binarybottle** [comment]
Here is a side-by-side comparison.
![IMG-20191215-WA0001](https://user-images.githubusercontent.com/236532/70867703-278dd600-1f46-11ea-99d6-7cca054630ae.jpg)
![IMG-20191215-WA0002](https://user-images.githubusercontent.com/236532/70867704-278dd600-1f46-11ea-9a4e-95a6e7746855.jpg)

**Comment by henryrossiter** [comment]
I was under the impression that this issue was fixed here: https://github.com/ChildMindInstitute/mindlogger-app/pull/337

Is that not the case? Perhaps it just hasn't been deployed yet?

**Comment by binarybottle** [comment]
That was a different issue, @henryrossiter -- radio vs. check in #337, similar presentation of radio buttons in iOS and Android here.
