### ISSUE TITLE
ML-570 ⁃ iOS notification goes to the list of activities instead of to the activity itself

### ISSUE THREAD

**Issue by binarybottle** [ChildMindInstitute/mindlogger-app#319]
When I tap on a notification in Android it takes me straight to the first question in an activity, whereas if I tap on a notification in iOS, it takes me to the list of activities instead of directly to the questions within the activity.

**Comment by binarybottle** [comment]
I believe that this was due simply to not waiting long enough after responding to the notification / answering questions for the same account on another (Android) device.

**Comment by shnizzedy** [comment]
This issue is maybe worth reopening as a design issue: how do we want to handle cross-device notifications for the same account? Right now, devices don't know about each other, but the account is shared, so the behavior is as described above. I also don't know enough about notifications to know if it's even possible to retract one once it's been sent ― if not, this issue may be moot.

Relatedly, I believe even on a single device if you ignore the notification, go into the app, complete the activity, then later click the notification, it'll take you to the activities menu.

**Comment by binarybottle** [comment]
I am monitoring notifications for the same account on an iPhone and an Android phone, and am left confused.  Sometimes tapping on a notification in iOS leads me directly to the activity's questions, and other times to the activity list.  And once I've completed the activity on one platform, it sometimes does and sometimes does not update what is scheduled on the activity list in the other OS.

**Comment by shnizzedy** [comment]
I think the short answer is, "MindLogger is a complicated platform."

> Sometimes tapping on a notification in iOS leads me directly to the activity's questions, and other times to the activity list.

I *think* this behavior is as described above, where the notification takes you to the activity if you have not yet completed the activity, and to the activity list if you have.

> I've completed the activity on one platform, it sometimes does and sometimes does not update what is scheduled on the activity list in the other OS.

I don't have a clear picture of when the mobile app updates from the server, but my strong intuition here is the answer to that question is the answer to that behavior, ie, the app only knows to update the schedule once it knows you've answered. I'm pretty confident if you manually trigger a refresh (by pulling down the protocols menu, ie, ![pulldown screengrab](https://user-images.githubusercontent.com/5974438/70447630-083a0900-1a6d-11ea-910e-0ac3eb0aefba.gif)) your schedule will update.

**Comment by binarybottle** [comment]
@shnizzedy -- Should this issue stay in the "In progress" column in the HBN EMA kanban board, or should it be moved to "To do"?

**Comment by binarybottle** [comment]
Tonight when I responded to the evening activity on an iPhone, then tried to enter the MindLogger app and refresh activities on an Android phone (same account), the app crashed.

**Comment by shnizzedy** [comment]
> an iPhone, then tried to enter the MindLogger app and refresh activities on an Android phone (same account), the app crashed.

I think https://github.com/ChildMindInstitute/MindLogger-bug-reports/issues/70 is the issue here.

**Comment by binarybottle** [comment]
I think that this points to a different issue that @shnizzedy describes above as "how do we want to handle cross-device notifications for the same account?" that warrants further discussion, but is not relevant to the title of this issue, so closing.
