### ISSUE TITLE
Individualized schedules

### ISSUE THREAD

**Issue by binarybottle** [ChildMindInstitute/mindlogger-app#326]
As a manager or coordinator, I want to set an activity schedule for an individual user of an applet so that my user has customized scheduling of the activity. 

Description: Managers or coordinators need to be able to set schedules for each user of the applet on an activity level individually. This means for User A the activities within a protocol can be scheduled differently every day of the week. The activities can also be scheduled multiple times during that day. This is all managed within the admin panel. 

Acceptance 
Given I am a manager or coordinator
When I want to schedule a certain user to use activities within an applet at a certain time
Then I open my admin panel, select that applet, then user and finally set the schedule for the activity. 

Given I am a manager or coordinator
When I want to edit a schedule of a certain user
Then I navigate back to my admin panel and reopen the schedule for that user's activity.

**Comment by shnizzedy** [comment]
To clarify what's needed for this feature:

## Schema definition
At the schema level, we just need to define whether a change of schedule counts as a different protocol or activity.

1. Whether the default behavior for a given activity or protocol is to allow or disallow different schedules per user
2. Syntax to specify whether to allow or disallow
    1. managers / coordinators to set custom schedules for individual users for a given protocol or activity
    2. users to customize their own schedules for a given protocol or activity

## API
At the API level, we need to create routes for
1. managers / coordinators to `GET` both default and customized schedules
2. managers / coordinators to `PUT` custom schedules on protocols / activities that allow custom schedules
3. users to `GET` both the default schedule and their own applicable custom schedule
4. users to `PUT` their own custom schedule, if allowed.

I think the most natural place for custom schedules to live is in the user `Profile` Object which contains under-the-hood Objects keyed `coordinatorDefined` and `userDefined` that cascade their contents for `displayName` and `email` (ie, 
```javascript
displayName = userDefined.displayName ? userDefined.displayName : coordinatorDefined.displayName
```
). That same kind of logic should work for schedules (userDefined > coordinatorDefined > applet default > protocol default > activity default > none).

## Admin panel
Once the API changes are in place, the admin panel will need to be able to display and set custom schedules for managers / coordinators.

## Mobile app / web app
1. Once the API call to `GET` the one most applicable schedule for a user-applet-activity combination, the apps will need to use that schedule to handle schedule-related behaviors (display sequence, notifications, alerts).
2. Once the API call to `PUT` a custom schedule is in place, users will need an interface to update their own schedules.

**Comment by shnizzedy** [comment]
Here's a flowchart of what's currently in place (black), has API code written that should be in place soon (blue), and is not yet written or is not functional (both red). Note: the blue components do not have interfaces designed or written.

[![notifications flowchart](https://user-images.githubusercontent.com/5974438/72639987-e61d8b80-3934-11ea-9436-24aededb45cc.png)](https://raw.githubusercontent.com/wiki/ChildMindInstitute/mindlogger-app-backend/images/custom-notifications.dia)

Related: https://github.com/ChildMindInstitute/MindLogger-bug-reports/issues/39

**Comment by WorldImpex** [comment]
Data moved to #737 & #738
