### ISSUE TITLE
ML-493 ⁃ 📱🚫Newly posted applets are not showing up on the phone

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-app#333]
@shnizzedy  Hope this helps:

### test 1
1. created two new accounts (hotavocado3) on prod and dev
2. posted HBN_EMA protocol from [reproschema](https://raw.githubusercontent.com/ReproNim/reproschema/master/protocols/ema-hbn/ema-hbn_schema) on both accounts
3. get/applet{id} parses both applets fine. applet ids:
       > prod: `5dfa622e45fe6326f6f4d3b2`
       > dev: `5dfa5792770990c22eafe9ec`
4. both show up on the admin panel, I scheduled both to repeat daily
5. prod version works fine on locally hosted ML Web (reprolib branch)
6. **no applets show up in android app** (6 hours since applets finished posted)

### test 2
1. posted no conditional logic version of [HBN_NIMH](https://raw.githubusercontent.com/hotavocado/HBN_EMA_NIMH2/master/protocols/EMA_HBN_NIMH2/EMA_HBN_NIMH2_schema) applet on prod acct (hotavocado)
2. get/applet{id} parses the applet fine. applet id:
       > `5dfa5bb045fe6326f6f4d3a9`
3. shows up on admin panel, I scheduled it to repeat daily
4. works fine on locally hosted ML Web (reprolib branch)
5. no applets show up in android app at all
6. prior to adding this applet, I had two working applets that showed up in my android app
       > could be related to [this](https://github.com/ChildMindInstitute/MindLogger-bug-reports/issues/66)
7. invited minji.kang as user to this applet
8. get/applet{id} parses fine on her acct
9. applet doesn't show up on her iOS app (1.5 hours after accepting invite)
10. however, her HBN_EMA applet is still on her app and works

**Comment by shnizzedy** [comment]
Probably caused by the bug I'm working on in https://github.com/ChildMindInstitute/mindlogger-app-backend/pull/253

**Comment by hotavocado** [comment]
@shnizzedy this is resolved 🙏
