### ISSUE TITLE
"Last completed" time for an Activity is always the current time (Android)

### ISSUE THREAD

**Issue by binarybottle** [ChildMindInstitute/mindlogger-app#335]
I just noticed that the "Last completed" time for an Activity is always the current time on Android but not on iOS.

![Screenshot_20191219-122449](https://user-images.githubusercontent.com/236532/71195904-d9861480-225c-11ea-86af-9f3356dcee57.png)

**Comment by Eden2016** [comment]
@binarybottle Can't reproduce
