### ISSUE TITLE
Push notification API should be called from backend

### ISSUE THREAD

**Issue by erik-ilyin** [ChildMindInstitute/mindlogger-app#35]
Because of complex logic from settings, it should be called from backend to APNS server

**Comment by shnizzedy** [comment]
I just pushed code to calculate a month's worth of notifications for any activity version: [notificationSchedule.js](https://github.com/ChildMindInstitute/mindlogger-app/blob/notifications/app/containers/activity/notificationSchedule.js)

@erik-ilyin, if you can plug this into the app so it updates the notification schedule when the app updates, we should be able to just iterate over the array returned by `updateNotifications(userActVersion)` (which takes a JSON object returned by getting an Activity Version Folder from Girder) to fill in the `date` parameter of [PushNotification.localNotificationSchedule](https://github.com/zo0r/react-native-push-notification#scheduled-notifications), we should be able to send exactly the notifications we want.
