### ISSUE TITLE
💄 ➡ `skip` Vs `>`

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-app#40]
For screens with no User input and no timer (ie, just a prompt or information), the `skip` control should instead be a right arrow.

For example, the screen below should have a right arrow instead of `skip`:

![Life events screen 1](https://user-images.githubusercontent.com/5974438/46109734-7e778600-c1af-11e8-87b9-c9eba9323d12.png)

**Comment by binarybottle** [comment]
Overruled in the new text-button design.
