### ISSUE TITLE
❔📱 Activities to Display (Revisited)

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-app#42]
We'll probably want to add configuration options regarding completed Activities. For each Activity:

- Can it be accessed between completion and the next notification?
- If so, should the completed data be visible?
- If so, should the completed data be mutable?

Related #41

**Comment by shnizzedy** [comment]
Related: https://github.com/ChildMindInstitute/mindlogger-app-backend/issues/74, https://github.com/ChildMindInstitute/mindlogger-app-admin-panel/issues/11, #54, #57

**Comment by shnizzedy** [comment]
@binarybottle Do we have an issue describing our stopgap Activities-on-app display groupings?

**Comment by binarybottle** [comment]
I have no idea if there is an extant issue about this!  No better time than the present:

"Past due":
Level 1 (top): name highlighted, with time when last notified at right

"Scheduled" (or "Upcoming" or "Coming up"):
Level 2: name + notification time/date at right

"Unscheduled":
- never scheduled; lighter tone text for those that have been done at least once
Level 3: name

OR split up Unscheduled into Unscheduled and Completed:

"Unscheduled":
- never scheduled, yet to be completed
Level 3: name

"Completed":
- never scheduled, but completed (activities that are intended to be done once?)
Level 4: name (in lighter tone?)

It might also be reasonable for limited-time-to-access activities to have a "Missed" section.

**Comment by binarybottle** [comment]
Stu has added categories such as "In Progress", "Unscheduled", "Completed"
