### ISSUE TITLE
🍪 Cache is not refreshing for applets on dev

### ISSUE THREAD

**Issue by binarybottle** [ChildMindInstitute/mindlogger-app#435]
I tried posting [this applet](https://raw.githubusercontent.com/hotavocado/HBN_EMA_NIMH/master/protocols/EMA_HBN_NIMH/EMA_HBN_NIMH_schema) on my dev account this morning, but the applet that shows up is a cached version that is more than two days old. 

I tried get/user/applets and get/applet/{id} with refresh=true, but that didn't work. I published the applet under a different branch and tried to post that, but ended up getting the same cached applet. 

I don't think this is a problem with the user cache, since it was my first time posting this applet on my dev account. 

Any ideas?

**Comment by binarybottle** [comment]
➤ Jon Clucas commented:

By not refreshing, do you mean the server is returning a 5xx (504?) response or that the response contents are not what you expect?

A small point of clarification, https://raw.githubusercontent.com/hotavocado/HBN_EMA_NIMH/master/protocols/EMA_HBN_NIMH/EMA_HBN_NIMH_schema is a protocol, not an applet. On dev, there are at the moment 2 applets built from that protocol: 5df16b6cf6b8897e5cd9e90a and 5df3bbc00bac942d08b3e99a. Both these applets use the protocol cached as 5de6dfc70fda281e6b4c2b28. That protocol includes

{
	"created": "2019-12-03T22:20:55.824Z",
	"updated": "2019-12-13T20:21:11.469Z"
}, so refreshCache is making changes and saving the protocol. @hotavocado what are you expecting different from what you're getting?

One bug I see here is the url fields are parsing out in GET /applet/{id} as null even though they are defined in the raw cached documents.

**Comment by binarybottle** [comment]
➤ Mike Xiao commented:

@shnizzedy I'm getting a 200 when refreshing the cache, but the content isn't updating.

**Comment by binarybottle** [comment]
➤ Jon Clucas commented:

@hotavocado can you post an example of what contents should change that isn't? The timestamp is updating at least…

**Comment by binarybottle** [comment]
➤ Mike Xiao commented:

For applet:  "5df3ea0d0bac942d08b3e9a7"

This URL is updating
Screen Shot 2019-12-13 at 5 36 21 PM ( https://user-images.githubusercontent.com/24463939/70836744-3dc55600-1dcf-11ea-981e-51564fe61c14.png )

However the contents are from more than 2 days ago before I redid the activities. 

example 1: this should by clone1
Screen Shot 2019-12-13 at 5 40 09 PM ( https://user-images.githubusercontent.com/24463939/70836933-e673b580-1dcf-11ea-9c68-4ee406f7c25a.png )

example 2: the old activities still show up in the protocol_schema file
Screen Shot 2019-12-13 at 5 43 57 PM ( https://user-images.githubusercontent.com/24463939/70837020-2fc40500-1dd0-11ea-91bb-62fb83050236.png )

It currently looks like this:
https://github.com/hotavocado/HBN_EMA_NIMH/blob/clone1/protocols/EMA_HBN_NIMH/EMA_HBN_NIMH_schema#L32-L37

**Comment by binarybottle** [comment]
➤ Jon Clucas commented:

@hotavocado can you try again now? If it works, can you review #244? Then I'll also deploy this to prod.

**Comment by binarybottle** [comment]
➤ Mike Xiao commented:

@shnizzedy it's working!

**Comment by binarybottle** [comment]
➤ Mike Xiao commented:

I'm having some trouble adding applets now:

  1. (Under dev, acct hotavocado) I deleted the HBN_EMA_NIMH applet that refreshed correctly after the fix, and attempted to post it again with some new changes. It looks like the post/applet timed out, this is what I get when doing get/user/applets (ids_only=true):
https://user-images.githubusercontent.com/24463939/70950541-eb827000-202e-11ea-99d4-36f7c0131b04.png

Here is the admin panel ~2hrs later:
https://user-images.githubusercontent.com/24463939/70952874-a150bd00-2035-11ea-8a9b-71d3d4889f90.png

  1. I created a new account on dev (hotavocado2), hosted the applet on a new repo with a new name, and attempted to post. 
  2. A little while after I posted the reproschema HBN_EMA applet, which is much smaller and known to work.

After 30-ish minutes, the applets finally posted, and I received the confirmation emails in my spam. get/user/applets (ids_only=true): 
https://user-images.githubusercontent.com/24463939/70952762-3c956280-2035-11ea-9e31-bb10ce4137b8.png
Both applets parse with get/applet{id}

  1. However, the applet tab of the admin panel is showing blank. Note that it doesn't have the 'you have no applets' message.
https://user-images.githubusercontent.com/24463939/70952970-e1b03b00-2035-11ea-80e4-3f1b8fe1d3e5.png
*screenshot was taken about 40 min after apps finished posting

**Comment by binarybottle** [comment]
➤ Jon Clucas commented:

I think this is a problem with #248. I'll revert dev for now and close that PR and try to resolve this. @hotavocado is prod ( https://api.mindlogger.org ) working for you?

**Comment by hotavocado** [comment]
For prod and dev: Applets are showing up on the admin panel, but the user page is stuck on loading. 

<img width="733" alt="Screen Shot 2020-01-01 at 12 41 39 PM" src="https://user-images.githubusercontent.com/24463939/71833623-4f6ee600-307b-11ea-9ad6-f9f7a2637fa5.png">

**Comment by hotavocado** [comment]
For prod and dev: Applets are showing up on the admin panel but the user page is stuck on loading.

![Screen Shot 2020-01-06 at 11 54 03 AM](https://user-images.githubusercontent.com/24463939/71833682-788f7680-307b-11ea-9cfc-062fac35a6f0.png)
