### ISSUE TITLE
"Is this correct?  Is it Sunday Jan 6 but the activity has a Jan 7th date.

### ISSUE THREAD

**Issue by PaulBaier-Boston** [ChildMindInstitute/mindlogger-app#54]
Today's date is Jan 6, but the "Sleep Behavior" has Jan 7.  Is this desired behavior?  Should it be today's date because the user hasn't put in the data yet (thus why "Sleep Behavior" is blue"?

![image](https://user-images.githubusercontent.com/46427256/50741599-3663f880-11cd-11e9-8734-d8c937a8f129.png)

**Comment by PaulBaier-Boston** [comment]
viewed on IOS

**Comment by PaulBaier-Boston** [comment]
There definitely lot seems to be a bug on the date next to Sleep Activity.  Yesterday mine was a day forward.  This am (630a) Jan 7 it oddly says 10:46a next to it

**Comment by binarybottle** [comment]
The new date entry widget appears to be fine.
