### ISSUE TITLE
Sleep Behavior Activity has a time time next to it.  Bug?

### ISSUE THREAD

**Issue by PaulBaier-Boston** [ChildMindInstitute/mindlogger-app#57]
It's unclear why there is timestamp next to "Sleep Behavior" is user supposed to answer the question by this time.  On IOS

![image](https://user-images.githubusercontent.com/46427256/50770521-9d2cf480-1255-11e9-91f1-aeb98390a60c.png)

**Comment by PaulBaier-Boston** [comment]
test comment

**Comment by binarybottle** [comment]
Completion times and dates now displayed within activity box.
