### ISSUE TITLE
ML-583 ⁃ TEST FROM GIT TO JIRA - TITLE

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#589]
THIS IS THE DESCRIPTION

**Comment by binarybottle** [comment]
And this is my comment.

**Comment by binarybottle** [comment]
➤ Wil Van Auken commented:

does it change if i comment

**Comment by WorldImpex** [comment]
@binarybottle testing the jira dup comment

**Comment by binarybottle** [comment]
I didn’t add that comment above – I’m merely mentioned in [~accountid:5d70180bc7002d0d9dc2c247]'s comment

**Comment by binarybottle** [comment]
➤ Wil Van Auken commented:

comment to git
