### ISSUE TITLE
ML-582 ⁃ JIRA TO GIT - STORY - TITLE

### ISSUE THREAD

**Issue by binarybottle** [ChildMindInstitute/mindlogger-app#590]
THIS IS DESCRIPTION

┆Attachments: <a href="https://matter-lab.atlassian.net/secure/attachment/10000/Admin+Platform+-+Desk+-+InVision.png">Admin Platform - Desk - InVision.png</a>

**Comment by binarybottle** [comment]
➤ Wil Van Auken commented:

TEST COMMENTS ON STORY

**Comment by WorldImpex** [comment]
![Unito app](https://user-images.githubusercontent.com/22243307/71680475-36eb8c80-2d58-11ea-8375-c48b09fcc125.png)

**Comment by binarybottle** [comment]
This is a comment about [~accountid:5d70180bc7002d0d9dc2c247]'s test comment, to test how users appear and references to other users appear within Jira and back on GitHub…

**Comment by binarybottle** [comment]
@WorldImpex -- This is looking weird.  Everything is attributed to me, unless done within GitHub itself, and check out the conversion of "@Wil..." to your account id above...

**Comment by binarybottle** [comment]
Now Arno is adding his first comment in Jira to this issue
