### ISSUE TITLE
Set Response Option Alerts 

### ISSUE THREAD

**Issue by binarybottle** [ChildMindInstitute/mindlogger-app#602]
As an editor, I want to set an alert for a response option so that the owner, manager and reviewer are aware of different situations 

Use Case: We want to way to flag a response option to alert a clinician/ doctor about a possible suicidal situation from the admin dashboard 

Requirements: 
* Allow the editor to turn on an alert flag and add a comment to a response option in an item 
* If the user selects that response option then the owner, manager, and reviewer receive a notification to their dashboard and an email is generated 
** Email: "There is an alert on your dashboard. Please login" and hyperlink 'login' to the admin notification
French translation:
Il y a une alerte sur votre tableau de bord. Veuillez vous connecter
* At first login the owner, manager, reviewer should be shown a message about the notification with a link to the dashboard where the entry is shown outlined in red

![Screen Shot 2020-12-30 at 5.36.27 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/3621e608-eba8-4442-beab-2559efa35c99)

![Admin Dash - Notifications.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/9ff5dc30-5bed-4ff1-9512-2e90cc2e62f4)

**Comment by sergeysemenuta** [comment]
Works as expected regarding the requirements.
Verified on: https://admin-staging.mindlogger.org/
Closing this ticket out
