### ISSUE TITLE
Token Tower integrated within MindLogger as "TokenLogger"

### ISSUE THREAD

**Issue by binarybottle** [ChildMindInstitute/mindlogger-app#617]
TokenLogger proposal:  Token Tower integrated within MindLogger

(December 15th, 2019)

We have chosen to start with OPTION 1 below

Variables:
 - T = number of tokens currently allocatedP = number of tokens to get next prize
 - 🜂T = change in the number of tokens over some duration of time 
 
State:
 - T

Conditions:
 - P - T < number of tokens indicating user is close to getting the prize
 - P - T > number of tokens indicating user is far from getting the prize
 - 🜂T > number of tokens indicating user has made progress
 - 🜂T < number of tokens indicating user is not making progress

Responses:
 - Launch an activity in MindLogger
 - Schedule an activity in MindLogger
 - Unschedule an activity in MindLogger
 - Assign an unscheduled activity in MindLogger

Examples:
 - If the user is not making progress (🜂T small), launch an activity in MindLogger.
 - If the user is within 10 tokens of attaining a prize, trigger an activity in MindLogger that encourages the user and asks a few questions.
 - When the user has attained a prize, unschedule a recurring activity in MindLogger.
 - Setup, Behavior, Summary, and Token screens and Data website

In the options below, some or all of the following would need to be built:
 - Setup screen: The parent/doctor needs to set up the child’s app to add/remove behaviors, pictures, and prizes.
 - Behavior screen: The parent/doctor needs to access a list of customized behaviors, so that when a behavior is selected, a corresponding number of tokens are given to or taken from the child.
 - Data website: The parent/doctor needs to view and download the child’s data through a website.
 - Summary screen: Summary of the number of tokens and how close to the next prize.
 - Token screen (already in the Token Tower app): View of personalized tokens

Token Tower within MindLogger

Option 1: NO screen for the child
 - Setup screen (website or parent’s Token Tower)
 - Behavior selection screen (parent’s Token Tower)
 - Summary screen (parent’s Token Tower)

Option 2: 1 screen for the child to see tokens
 - Setup screen (website or parent’s Token Tower)
 - Token screen (child’s Token Tower) with personalized images
 - Behavior selection screen (parent’s Token Tower)

Option 3: NO screens for the child; personalized tokens viewed on parent's screen
 - Setup screen (website or parent’s Token Tower)
 - Token screen (parent’s Token Tower) with personalized images
 - Camera screen (parent’s Token Tower)
 - Behavior selection screen (parent’s Token Tower)

Option 4: 1 screen for the child to see tokens
 - Setup screen (website or parent’s Token Tower)
 - Token screen (child’s Token Tower) with personalized images
 - Camera screen (parent’s Token Tower)
 - Behavior selection screen (parent’s Token Tower)

Option 5: 2 screens for the child (child can take photos)
 - Setup screen (website or parent’s Token Tower)
 - Token screen (child’s Token Tower) with personalized images
 - Camera screen (child’s Token Tower)
 - Behavior selection screen (parent’s Token Tower)

**Comment by binarybottle** [comment]
1)   Who will use MindLogger application (Parent or ?)?
Parents
2)   Can you please draw or write the flow from the first screen or after login/register into MindLogger app?
If you try out the HBN EMA applet, you will see how to access any activity in any applet.
3)   User will insert data into checkboxes or that data will be received from some databases?
User will check the appropriate boxes each time they use that activity (or exit)
Is there existing endpoints for that part if we need to fetch data for checkboxes?
N/A
(DBT Diary Card) SCREEN
Ignore — this was just an example to show a current version of the checkbox survey screen
(Prize Screen) Screen: √ “Redeem!” button routes you to the last screen (HBN EMA) Data SCREEN?
Redeeming a token just leads to that prize and checkbox getting grayed out with a message at the bottom of the screen: “X tokens redeemed for prize Y”
(HBN EMA) Data SCREEN
Ignore — this is an example Data screen; the applet’s data are presented here.  As long as the output from TokenLogger is in line with (or updates) the schema, then the data will appear on the TokenLogger’s own Data screen

**Comment by binarybottle** [comment]
Arno 8:30 PM
@Marco -- Thank you for the flow diagram.  The flow is correct, from login to applet list to activity list to Tokens screen.  No need for a progress bar. (edited) 
Screen Shot 2019-12-19 at 8.26.08 PM.png 
Screen Shot 2019-12-19 at 8.26.08 PM.png


Good. But if pressing either button takes you to the Prizes screen, then perhaps we should only have one button in the middle at the bottom that reads "Prizes" that also saves the checkbox responses and updates the number of tokens on the Prizes screen. (edited) 
Screen Shot 2019-12-19 at 8.33.29 PM.png 
Screen Shot 2019-12-19 at 8.33.29 PM.png


Arno 8:52 PM
In keeping with the Tokens screen, let's have a single button at the bottom in the middle that reads "Tokens". Whenever a radio button is pressed to select a prize, have a popup that reads "Redeem X tokens for Y?" with "Yes" and "No" buttons.  And when you press "Yes", it takes you to a modal that reads "X tokens redeemed for prize Y", and exiting this modal (like exiting the other modal screens) takes you to the Home screen. (edited) 
Screen Shot 2019-12-19 at 8.46.33 PM.png 
Screen Shot 2019-12-19 at 8.46.33 PM.png

**Comment by WorldImpex** [comment]
Moved this information under the Epic https://github.com/ChildMindInstitute/mindlogger-app/issues/611https://github.com/ChildMindInstitute/mindlogger-app/issues/611
