### ISSUE TITLE
⬇️Dropdown selection looks/feels awkward on mobile app 

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-app#618]
![dropdown](https://user-images.githubusercontent.com/24463939/71852958-139e4580-30a8-11ea-8ac6-95af66412b80.gif)

When selecting a choice in an dropdown item, the question disappears and only the dropdown bar remains. Would it be possible to keep the dropdown selector and question on the same page?

**Comment by shnizzedy** [comment]
#635 might resolve this issue once deployed.

**Comment by WorldImpex** [comment]
Dropdowns have been replaced with radio buttons for now
