### ISSUE TITLE
User cannot set time in Assessment 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#619]
Expected Results: When the user is in an assessment, clicking on the time brings up a screen to set the time they did something 
Actual Results: Clicking on the time to set, opens a white blank screen 

Environment: iPhone 6s 13.3/ v0.9.11

[Image from iOS.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/9b7eb629-5cc3-4130-8b5d-82bfb14fbe64)!

**Comment by WorldImpex** [comment]
@Eden2016 This is reproducible on the newest version 0.9.12. 
![RPReplay_Final1578746098](https://user-images.githubusercontent.com/22243307/72204391-64fe5a00-3445-11ea-8a12-e2a1b08de43d.gif)

**Comment by WorldImpex** [comment]
@Eden2016 This is reproducible

**Comment by shnizzedy** [comment]
> @Eden2016 This is reproducible

@WorldImpex, in v0.9.13?

**Comment by WorldImpex** [comment]
@shnizzedy Yes you are correct v0.9.13 did fix it
