### ISSUE TITLE
Data Tab Does Not Show Relevant Data To User

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#626]
Expected Results: Data tab shows the user the questions and answers over time 
Actual Results: User sees the question and answer on a what might be a bar but there needs to be a better visual for the user 

Environment: iPhone 6s 13.3/ v0.9.11

![File (1).jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/7e2a1ea4-c556-4fcb-9b24-931bc5c8b2f4)

**Comment by shnizzedy** [comment]
Also, the status quo of this data view is showing the latest response per screen per activity per day, so if a user completes an activity more than once on a calendar day, only the most recent response for each screen in that activity is plotted.

**Comment by WorldImpex** [comment]
Duplicate of https://app.zenhub.com/workspace/o/childmindinstitute/mindlogger-app/issues/630
