### ISSUE TITLE
Pre-Questionnaire does not disappear after completion

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#627]
Expected Results: After completing prequestionnaire, it should save inputs and move to the completed section
Actual Results: The button stays in unscheduled section and user can 'resubmit' after completing the assessment 

Environment: iPhone 6s 13.3/ v0.9.11 NIMH

![File.jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/a8497ad6-5524-4ff9-a2a8-f8ed1c4b4a82)

**Comment by shnizzedy** [comment]
This might be desired behavior? Do we want users to be able to revisit this activity as desired?

**Comment by WorldImpex** [comment]
@binarybottle Do you want users to always see the pre questionnaire under unscheduled? Are the responses from the user stored anywhere?

**Comment by shnizzedy** [comment]
> Are the responses from the user stored anywhere?

The responses are (or should be) stored on the database with timestamps everytime any activity is completed. I think depending on the research questions, someone would want the most recent or the changes over time, or both.

**Comment by WorldImpex** [comment]
This is the desired effect that might be iterated on in the future
![Slack   Arno   MATTER Lab](https://user-images.githubusercontent.com/22243307/72349751-1b16ad80-36ab-11ea-8ab8-e8d6d360423d.png)
