### ISSUE TITLE
PreQuestionnaire - Social Media Question

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#628]
Expected Results: When user answer's no to the "Do you have a social media account?" the user skips the "what social media accounts do you use?" 
Actual Results: The user is asked after saying no "What social media accounts do you use?"

Environment: iPhone 6s 13.3/ v0.9.11

![File (1).jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/71661ee5-063d-414c-8681-179eef7b7858)

**Comment by henryrossiter** [comment]
What activity set is this from? I expect the schema is causing this behavior.

**Comment by hotavocado** [comment]
resolved via https://github.com/hotavocado/HBN_EMA_NIMH2/commit/27c307f254e22dc15118ab81d195cf2111f04caa

**Comment by WorldImpex** [comment]
confirmed fixed 

![ezgif-5-19ed99081d3d](https://user-images.githubusercontent.com/22243307/72358602-d561e100-36ba-11ea-9947-284f4c4b6c18.gif)
