### ISSUE TITLE
⬆ Review required packages; purge and upgrade as relevant.

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-app#63]
for [mindlogger-app](https://github.com/ChildMindInstitute/mindlogger-app) and [mindlogger-app-panel](https://github.com/ChildMindInstitute/mindlogger-app-admin-panel)

**Comment by shnizzedy** [comment]
Related: #45

**Comment by binarybottle** [comment]
Stu and Henry have been purging.  This is a perennial issue and not worth setting as a one-time goal.
