### ISSUE TITLE
Add tick marks and labels to slider bar

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#631]
Add hash marks and labels below the slider bar, like the following:
 
![Screen Shot 2019-12-19 at 11.10.56 AM.png](https://images.zenhubusercontent.com/5e10f69ef29cd5521b1d65e1/74d947aa-96c8-4ea2-bc92-0c7d286fc450)

**Comment by binarybottle** [comment]
Except no slash between "very" and "sad".

**Comment by WorldImpex** [comment]
@binarybottle Cool! I will make a bug ticket for that

**Comment by Kgwenzi** [comment]
Hello, I would like to help out

**Comment by WorldImpex** [comment]
Hello @Kgwenzi, let me know if you have questions on the requirement. This is a simple hash mark and label UI we are looking to have implemented

**Comment by ProNinoGit120** [comment]
This is the updated slider bar.
[Uploading... Screen Shot 2020-03-19 at 6.04.13 AM.png ]

**Comment by sergeysemenuta** [comment]
Verified on
iPhone 7 //iOS 11.4.1// MindLogger Version 0.11.11 (128)
Huawei P20 // Android 8.1.0 //  MindLogger v 0.11.11
![Screenshot_20200323-102254.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/38fcfa9b-42bd-4dfc-8628-6861315772d2)
