### ISSUE TITLE
Audio Image Record Not Rendering Properly

### ISSUE THREAD

**Issue by henryrossiter** [ChildMindInstitute/mindlogger-app#633]
Issue
- [this item](https://github.com/ReproNim/reproschema/blob/master/activities/MindLoggerDemo/items/audio-image-record) from the MindLogger Demo protocol is not rendering properly
- Renders the default 'There was a problem loading this screen' message
- Likely related to: ```"inputType": "audioImageRecord"```

Environment
- MindLogger 0.9.11
- Android 7.0

Example

<img src="https://user-images.githubusercontent.com/31543235/71990649-fe80fe00-31f0-11ea-977b-462bdbbb38ef.png" alt="drawing" width="200"/>

**Comment by sergeysemenuta** [comment]
Fixed on:
Staging
ML v 0.14.29 (249) 
iPhone XR // iOS 13.2.3
Galaxy s10 // Android 9
Video:https://www.screencast.com/t/JGXnR9sL9xJe
![2020-12-22_13-00-41.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/61abe04b-f167-4298-8fd7-7011d5c4669b)
