### ISSUE TITLE
Acitivies on Calendar do not show on Day/Week

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#644]
Expected Results: When user inputs activities on month screen of the calendar, the show up on the other filtered tabs (day, week)
Actual Results: Activites do not show on day or week filter 

 ![ezgif-7-f16afe6c1afd.gif](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/abdc8c1f-fd46-4213-975e-81889fa104a4)

**Comment by shnizzedy** [comment]
In the screengrab above, the events are set one-time on January 9 and not showing on January 14, which is correct. Here's a screengrab of switching views for a recurring event, which shows in each view.

![screengrab recurring event](https://user-images.githubusercontent.com/5974438/72187325-5e300280-33c5-11ea-94d3-280af20703e2.gif)
