### ISSUE TITLE
Email Invite For New User Not Received

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#645]
Expected Results: Sending an invitation would automatically be received to the email address
Actual Results: No email received

![mindlogger-admin (9).png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/3a113ed1-a7bb-4dc8-baeb-df7130430631)

**Comment by shnizzedy** [comment]
This is expected behavior ― the admin panel _generates_ invitations but does not _send_ them. Email addresses are not a requirement for generating an invitation. Adding functionality for the interface to send an email if an invitation includes an email address would resolve this issue.

**Comment by sergeysemenuta** [comment]
After sending invitation to the user the email invite is received. 
Checked on dev server using Swagger doc.
![2020-05-25_18-23-24.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/c8af0198-9f95-4821-9396-ab7e7e9eeedb)
