### ISSUE TITLE
TokenLogger Activity Builder

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#652]
As an editor, I want to create a token activity so that my patient's parent can log behavioral events in MindLogger 

Requirements
* Editors need the ability to create an activity so that parents can enter the child's behavioral data in exchange for tokens. 
* Editors should be able to enter plain text behavioral events ( "Yelled in anger") and associate it with a number of tokens positive or negative (-5 tokens). 
Default List of Behaviors 
* The editor should also be given the ability to select behaviors and the associated number of tokens as default. This default selection will auto-populate new activities created in the future. 
* Default Token options can be added and removed from the list

![Token Builder.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/f15982b6-d8fb-4c05-91db-426ebf9cc21b)

**Comment by WorldImpex** [comment]
Creating adding and removing of TL behaviors in an applet with positive and negative TokenLogger values works as expected. Behaviors are recorded in the exported doc but do not contain the Token Value ![Screen Shot 2020-10-30 at 7.43.48 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/6c1b401a-6bee-4b22-8031-2fea3e2b50c7)

Templating does not function as expected but a separate issue has been created for that #113

**Comment by sergeysemenuta** [comment]
Works as expected  according to Requirements except the issue [113](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-builder/113)

Closing this ticket out
