### ISSUE TITLE
Displayed Data Error

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#656]
Expected Results: Dotted line runs horizontal to display each day 
Actual Results: Dotted line runs vertically 

![File (3).jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/79207cd6-b22c-4d9e-8809-cf4a5fcc89fe)

**Comment by shnizzedy** [comment]
I think that's a lineplot that graphs values over time

**Comment by shnizzedy** [comment]
That is, I think over time that prompt should look something like 
![mockup over time with question](https://user-images.githubusercontent.com/5974438/72290947-561dd000-361c-11ea-9a69-612397fd48ca.png)

**Comment by WorldImpex** [comment]
This is still considered a UI bug as the placement overlaps the wording and the graph will as well like in the example

**Comment by WorldImpex** [comment]
The fix is being handled in [671](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/671)
