### ISSUE TITLE
TokenPrizes Builder

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#660]
As an editor, I want to create a way for my user to spend the tokens earn so that I can reinforce good behavior 

Requirements: 
- If a token is created in an activity then the option to Create Token Prizes is available 
- Allow the editor to set only positive values, a description and upload an image for each radio item that is added to the list 
- Allow the editor to delete and edit each field 
- When the user saves this, it will create an activity in the app that will be implemented in #949

![TokenLogger Prizes Creator (1).png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/d68fa84e-494e-4433-8aa2-d0d24f208530)

**Comment by WorldImpex** [comment]
1. Image URL does not function - Could it be easily replaced with upload image? 
![Screen Shot 2021-01-10 at 6.24.36 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/7618e677-292c-4049-977d-70d9b4c8553f)
2. Edit Icon does not seem intuitive. In the editing state, can we show a save button to replace the pencil? 
![Screen Shot 2021-01-10 at 6.29.43 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/8a14ef88-9440-4ced-8421-7dac1396234a)
3. If an item in TokenPrizes Builder is not 'saved' the user can still save the form 
![ezgif-5-17bf4d1d9499.gif](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/af5bdd99-af9c-4531-92bd-a633a0eafcbd)
4. "create" icon should change to "edit" when TokenPrizes have been created 
![Screen Shot 2021-01-10 at 6.35.02 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/c0511cb3-b84f-4345-aed4-2e2dfde4ec6b)

**Comment by devbtech** [comment]
Above issues are fixed except uploading image function. We will knock it out later.

**Comment by sergeysemenuta** [comment]
The image upload functionality is pointed out in another ticket. Other issues are fixed.
Closing this ticket out
Checked on:
https://admin-staging.mindlogger.org/
Win 10 //  Chrome 87
