### ISSUE TITLE
Slider Bar Start Location

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#664]
Expected Results: Slider bar starts in the middle of the bar
Actual Results: Slider start position is to the left of middle 

![Screenshot_20200114-182329.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/6a2e59fc-9655-4a10-82be-3012fb3f60fe)

**Comment by binarybottle** [comment]
The slider bar knob is off-center in the DBT diary card, but not in the EMA.

**Comment by shnizzedy** [comment]
If the slider is discrete and has an even number of notches (as seems to be the case in the screenshot), how would it ever be in the center?

**Comment by WorldImpex** [comment]
This would be an aesthetically pleasing fix

**Comment by WorldImpex** [comment]
The below has 6 options which would traditionally cause the slider bar to be off center. This issue has been fixed 

![File (1).jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/63792f97-96be-488d-b62b-959d0f5d7689)
