### ISSUE TITLE
Remove numbers above slider bar

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#665]
Expected Results: As the slider is moved there are no numbers around it 
Actual Results: As the slider is moved, there is a number above it that changes

 ![Screenshot_20200114-182351.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/f30d5a31-8661-4ea8-b071-d2ca25b9d8b2)

**Comment by shnizzedy** [comment]
This behavior is probably undesired, but helpful for testing #289! ¯\_(ツ)_/¯

**Comment by WorldImpex** [comment]
Fixed in [#692](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/692l)
