### ISSUE TITLE
🐛 Neither scheduled nor random notifications are working

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-app#67]
![screenshot_20190103-105519.png](https://trello-attachments.s3.amazonaws.com/5bdca6be9677f381d701cd51/5c2fb8b206e2798352e58988/1c4f4a6396ec0ea785eb2806b4b73752/screenshot_20190103-105519.png)

Ref https://trello.com/c/RP4TLmsA, https://trello.com/c/x1eNX6xc

**Comment by shnizzedy** [comment]
Currently, notifications seem to be appearing as expected, but when a user taps on a notification, instead of always going to the activity mentioned in that notification (the desired behavior), the app sometimes (usually? always?) navigates to the activity list.

**Comment by binarybottle** [comment]
@shnizzedy -- Has anyone tested notifications on ios and android recently?

**Comment by shnizzedy** [comment]
@binarybottle We haven't built this functionality into v0.2 yet. That's what https://github.com/ChildMindInstitute/mindlogger-admin/issues/1, ["Scheduling"](https://github.com/orgs/ChildMindInstitute/projects/9#card-21664148), and https://github.com/ChildMindInstitute/mindlogger-app-backend/issues/144 are about. I'm closing this issue as moot since it's about v0.1.
