### ISSUE TITLE
Plot Line overlaps Data fields 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#671]
Expected Behavior: The plotline does not overlap other words on the page 
Actual Behavior: The plotline overlaps other text 

![IMG_0092.PNG](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/ac550068-0fc7-4405-b655-a7971e5cd57d)

**Comment by Eden2016** [comment]
Finished. This is how is looking
![Screen Shot 2020-01-21 at 10.51.48.png](https://images.zenhubusercontent.com/5e24e1b652024f7e504b6275/b948e4c9-4f2b-4676-a81e-3983794eccc7)

**Comment by WorldImpex** [comment]
Fixed 

![File (8).jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/8f70254f-1e7e-4e22-af37-3b3b4faf0c76)
