### ISSUE TITLE
Redesign Progress Bar

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#672]
Update the progress bar to stand out more on the page like this: 

![1_291DLyj0EOnL4sa0NG_k-A.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/618bba7a-0f15-49c9-b09f-275293216d4e)

**Comment by Eden2016** [comment]
I have a couple of option for the styling of the progress bar.
Option 1:
![Screen Shot 2020-01-16 at 11 56 57](https://user-images.githubusercontent.com/16896205/72546350-a6817180-3858-11ea-8855-873adfbe405c.png)
Changed the background color to gray and the width of the progress bar.

Option 2:
![Screen Shot 2020-01-16 at 12 05 02](https://user-images.githubusercontent.com/16896205/72546429-c31da980-3858-11ea-803c-687f8c05f8ad.png)
Changed the background color to gray, change the progress bar color to the blue of the previous image, added border radius and increased the width of the progress bar.

Which one should I push?

**Comment by WorldImpex** [comment]
@Eden2016 Please go with the second option with the rounded edges.  Could you make the bar thicker?

**Comment by WorldImpex** [comment]
Confirmed

![File.jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/f476d65f-b5e4-4292-98d6-62adf6ef2a10)

**Comment by WorldImpex** [comment]
Confirmed

![File.jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/f476d65f-b5e4-4292-98d6-62adf6ef2a10)
