### ISSUE TITLE
Convert Drop downs with Numbers only to Dial

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#673]
Instead of the user selecting from a dropdown, the user should have a verticle text spinner 

![Blank Diagram (2)](https://user-images.githubusercontent.com/22243307/72478224-7afe7880-37bf-11ea-8431-3527fdf777eb.png)

![ezgif-7-3114c4416ec3](https://user-images.githubusercontent.com/22243307/72549211-47bef680-385e-11ea-9b6c-74820d901216.gif)

**Comment by binarybottle** [comment]
This would be good for "How long did you sleep"-type questions.  Otherwise, if there are a limited number of choices, radio buttons are fine as well.

**Comment by WorldImpex** [comment]
Related #618
