### ISSUE TITLE
Options Overflow The Page - See More

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#675]
When options overflow past the fold, we want a "See More" which the user clicks and expands so the user understands to scroll further down
![Blank Diagram.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/c8f624d6-713e-4bda-a5ef-27b5ee35f6e2)

**Comment by binarybottle** [comment]
Other suggestions for clean arrow-like icons welcome!

**Comment by Eden2016** [comment]
Solved. This is how is working right now.
https://www.loom.com/share/1f526c2dd7634812b088ee751f04283b

**Comment by WorldImpex** [comment]
Please have the see more option disappear if the user scrolls manually to the bottom of the page 

![ezgif-7-b483da99463a](https://user-images.githubusercontent.com/22243307/72990710-a20c0a00-3dbe-11ea-9813-2bf12f29f7e8.gif)

**Comment by WorldImpex** [comment]
Fixed 

![ezgif-7-9e83ab981556](https://user-images.githubusercontent.com/22243307/73354502-dd498580-4263-11ea-9d7b-03c283637a1d.gif)
