### ISSUE TITLE
'static' input isn't parsing in Mindlogger

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-app#678]
![Screenshot_20200113_131106_lab childmindinstitute data](https://user-images.githubusercontent.com/24463939/72280586-a853f680-3606-11ea-8726-ab99059154f6.jpg)

Here is the item json:
https://github.com/hotavocado/HBN_EMA_NIMH2/blob/master/activities/day_set/items/Event0#L11

**Comment by shnizzedy** [comment]
`static` is not a handled `inputType` in the widget switch:

https://github.com/ChildMindInstitute/mindlogger-app/blob/c32ff44adcd4bb605a4dcd5a488c1c72e181db53/app/components/screen/Widget.js#L24-L196

I suspect changing https://github.com/ChildMindInstitute/mindlogger-app/blob/c32ff44adcd4bb605a4dcd5a488c1c72e181db53/app/components/screen/Widget.js#L194 to 
```javascript
if (screen.inputType === 'markdown-message' || screen.inputType === 'static') { 
```
would resolve this issue.

**Comment by hotavocado** [comment]
thanks @shnizzedy, just opened a PR! #679
