### ISSUE TITLE
iOS time picker says "Pick a date" instead of "Pick a time"

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-app#68]
!["Pick a date"](https://trello-attachments.s3.amazonaws.com/5bdca6be9677f381d701cd51/5c1d1475aadbe74573a990cf/db80f12909fb488d492e76454c0d32a4/_url%3Dhttps_3A_2F_2Fslack-files.com_2Ffiles-email_2FTDUCR6ZRP-FEZ8H5R08-4ac6ef6d7d-7154bb17_2Fimage.png)

Ref https://trello.com/c/TKjAvBD9

**Comment by binarybottle** [comment]
Redesigned and working.
