### ISSUE TITLE
Unable to Reset Password

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#683]
Expected Behavior: User receives an email with a reset link which is clicked and the user is able to change the password on the account
Actual Behavior: User receives email but the reset link does not work 
Environment: iPhone 6s/ 13.3 - Production Server - Account: wavanauken@gmail.com

"A temporary access token was requested on your behalf. You can access the MindLogger system at https://api.mindlogger.info#useraccount/5dfb633b58003e2022b41fc9/token/EuKLPrRlWL3lUdLll9wsNZJDSvzeEWwJk1PSnRfOknvR5XtaBvVxGPJRk87rT5Aj Once you access the system, you will have the option to update your password."

![ezgif-7-e177f3a606b5.gif](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/6afc80f5-f126-4588-ba02-6958dea59bc0)

**Comment by shnizzedy** [comment]
Ah! Somewhere the old `mindlogger.info` (instead of `mindlogger.org`) is still set apparently. I thought I caught all of those. This issue might actually be in the configuration on AWS rather than in the code.

**Comment by WorldImpex** [comment]
Reset behavior has not been fully implemented so forgot password needs to be re-scoped
