### ISSUE TITLE
Text Overflow onto Checkboxes

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#691]
Expected Results: Text does not overflow on to checkboxes 
Actual Results: Text overflows onto checkbox

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/47e4423c-d57c-4dd2-8a36-c49767d84f12)

**Comment by hotavocado** [comment]
Please note this is an issue for both checkboxes and radio buttons, for any item where inputType = 'radio'.
Fix should probably happen here: https://github.com/ChildMindInstitute/mindlogger-app/blob/master/app/widgets/Radio.js

**Comment by WorldImpex** [comment]
Bug still reproducible 

![IMG_0185.PNG](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/3e4f96b5-947c-480c-b0f2-12e1fc16e450)

**Comment by WorldImpex** [comment]
fixed 

![File (10).jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/f81fc0f8-bd01-4c8b-a63f-25aad95f690f)
