### ISSUE TITLE
Update Progress Bar with the original blue color

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#693]
Old Color 
![File (1).jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/caa071bb-57c6-4130-a70b-d3bd9d44495b)

New Color 
![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/84d40bb8-7360-4144-bef6-1c107c2f1bf6)

**Comment by shnizzedy** [comment]
:raised_hand_with_fingers_splayed: I vote for using `skin.colors.primary`, which uses the primary color of the skin in use and defaults to #0067A0 (![#0067A0](https://placehold.it/15/0067A0?text=+)) if none is provided https://github.com/ChildMindInstitute/mindlogger-app/blob/c85a208fda83c0decce0e0516019dbbdd89f0a4a/app/config.js#L6
