### ISSUE TITLE
🐎✨Speed up radio/checklist widget response animation

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-app#698]
![button_animation](https://user-images.githubusercontent.com/24463939/73007752-13f24c80-3ddb-11ea-809f-53149eb5b747.gif)

Currently there is around a 0.5 second frame where the radio button/checklist turns gray/faded blue when the choice is selected. Would it be possible to eliminate this frame to speed up user experience?

**Comment by Eden2016** [comment]
@hotavocado is this behavior on Android/iPhone, physical device or simulator?

**Comment by hotavocado** [comment]
This is on my android phone

**Comment by WorldImpex** [comment]
Since react-native version has been updated, the code should be tested and updated.

**Comment by WorldImpex** [comment]
This has been fixed since the db migration
