### ISSUE TITLE
❔Visibility doesn't work when item.value == 0

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-app#700]
Example: 

https://github.com/hotavocado/HBN_EMA_NIMH2/blob/master/activities/day_set/day_set_schema#L512

In this case, Context1a will become visible if user selects the choice with value=1 for Context1.

However, if the condition is changed to `"Context1a": "Context1 == 0"`, Context1a **will not** be visible when the user selects the choice with value=0 for Context1. So far 0 is the only value I know of that is causing problems.

To address this temporarily, I updated all items with choices with value = 0 to value = 1, and value = 1 to value = 2 etc.

**Comment by hotavocado** [comment]
@nino hope this helps:

I've created a test applet with these items:
`question1`: please select an option (1=yes, 0=no)
`question1_no`: only visible when question1 == 0
`question1_yes`: only visible when question1 == 1
Here is the [visibility object](https://github.com/hotavocado/visibility-test/blob/master/activities/visibility_test/visibility_test_schema#L34-L37) for this activity

The problem is that `question1_no` never shows up, even when you select 'no' for `question1`, while `question1_yes` will show up as expected when you select 'yes' for `question1`.

<img src="https://user-images.githubusercontent.com/24463939/80129920-cc0fcc80-8565-11ea-9e8d-f7c57d7602fb.gif" alt="visibility_test" width="400">

Here is the protocol url for the applet: https://raw.githubusercontent.com/hotavocado/visibility-test/master/protocols/visibility-test/visibility-test_schema

**Comment by sergeysemenuta** [comment]
Works as expected.
Video: https://www.dropbox.com/s/u8rw69vxrzdyyzq/IMG_2022.MP4?dl=0
Checked on:
Dev server
iPhone 7 // iOS 13.4.1 // v 0.11.35
Huawei P20 // Android 9.0 // v 0.11.35
iPhone 5s // iOS 12.3.1// v 0.11.35
Redmi Note 8 Pro // Android 10 // v 0.11.35
Redmi Note 3 Pro // Android 6.0.1 // v 0.11.35
