### ISSUE TITLE
Updating Applet Cache Does Not Work

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#704]
Description: User tries to update the applet cache both below ways but does not receive an updated applet 

1.  User on homescreen of mindlogger and pulls down on applets
2. User navigates to admin panel and does a refresh on the API dashboard 

Expected Results: User sees new features and changes of NIMH applet (images, functionality, etc)
Actual Results: There is no change to user's applet but user can confirm with others the applet has changed

**Comment by hotavocado** [comment]
I haven't been test new versions of the NIMH applet because the cached applet won't refresh. 
I used to be able to do: get/user/applets (refreshCache = true) to refresh applet but that hasn't been working since around the end of last week.

**Comment by WorldImpex** [comment]
I was able to load a new applet on dev and confirm that images and content was available that wasn't before the fix
