### ISSUE TITLE
Audio Stimulus Does not play

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#705]
Audio does not play in Mindlogger Demo Applet 

![ezgif-7-7a8e4b5242ca](https://user-images.githubusercontent.com/22243307/73074551-e31c2100-3e87-11ea-99c9-240baef3720c.gif)

**Comment by devbtech** [comment]
In Demo applet, it still doesn't play the audio but it's the problem with demo applet itself. We don't have valid audio file for audio stimulus item.
