### ISSUE TITLE
Update Style of See More Button

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#713]
Update the "See More" button as a simple down arrow in a circle that overlaps the progress bar, like the circle at the bottom of the screen in the attached picture. Let's make our button a white circle with a blue outline and a blue downward caret/arrow inside the button.

![BD50X.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/e7ade9bd-f5b1-4e64-b338-55bd711b0020)

**Comment by binarybottle** [comment]
Actually, a blue circular arrow button could intersect our navigation strip at the bottom just as in the picture, because the Undo button would only appear after a selection is made and the arrow button has disappeared!

**Comment by WorldImpex** [comment]
@binarybottle So something like this but in the colors discussed? 
![Blank Diagram (2)](https://user-images.githubusercontent.com/22243307/73265083-3b159900-41a2-11ea-8852-06f9f47d2b16.png)

**Comment by binarybottle** [comment]
Yes -- perhaps it would look good if it were a white circle with a blue outline with a blue carrot (instead of a blue circle with a white carrot). That way the button wouldn't stand out too much. The problem is that currently the button dominates the whole screen -- very distracting!

**Comment by WorldImpex** [comment]
![Blank Diagram (3)](https://user-images.githubusercontent.com/22243307/73267350-df99da00-41a6-11ea-9428-6985db440a29.png)

Here is a rough depiction of the expectation

**Comment by binarybottle** [comment]
I would prefer one of the following, with the outline thin (like the font below) and the caret thick (or triangle filled in), and everything in the color of the font and progress bar:

![Screen Shot 2020-01-28 at 10.42.29 AM.png](https://images.zenhubusercontent.com/5e10f69ef29cd5521b1d65e1/30cd9517-5fae-4cd7-aa53-e4fba2ff81f5)

**Comment by WorldImpex** [comment]
![IMG_0378.PNG](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/84570994-ea7d-46da-a378-c15885e2edc2)

done
