### ISSUE TITLE
Unselected slider knob has an offset gray circle, is inconsistently filled, and is too big

### ISSUE THREAD

**Issue by binarybottle** [ChildMindInstitute/mindlogger-app#715]
Expected: 
1. The slider bar's knob should be an unfilled, dashed circle if untouched or after tapping the Undo button.
2. The knob should be about the same size as the selected knob (dashed circle with a radius equal to the radius of the selected knob + width of the dashed line).

Current state: 
1. The knob is sometimes unfilled, and sometimes filled in with gray. It also has a gray circle in addition to the dashed circle, and this gray circle is offset from the dashed circle.
2. The unselected knob is much bigger than the selected knob.

![Screenshot_20200127-180136](https://user-images.githubusercontent.com/236532/73221609-53989b80-412f-11ea-9fe8-83eb682411aa.png)
![Screenshot_20200127-180212](https://user-images.githubusercontent.com/236532/73221610-53989b80-412f-11ea-8a1b-6525bed56f1f.png)
![Screenshot_20200127-180244](https://user-images.githubusercontent.com/236532/73221611-53989b80-412f-11ea-9a6a-4a73a86c66ae.png)

**Comment by WorldImpex** [comment]
fixed 
https://docs.google.com/document/d/1xgLoA1EoSonHfVTmckoMDAFkUU2u_V0PXdDx3yUgGnI/edit?usp=sharing

**Comment by WorldImpex** [comment]
![RPReplay_Final1580394778](https://user-images.githubusercontent.com/22243307/73458697-acd91880-4343-11ea-8902-5d072c726f39.gif)


Fixed!
