### ISSUE TITLE
NIMH - EMA question presentation inconsistent (question marks and colons)

### ISSUE THREAD

**Issue by binarybottle** [ChildMindInstitute/mindlogger-app#716]
The questions are not consistently presented.

Expected:
All questions end with a question mark, and all statements with a colon.

Current:
Some questions do not end with a question mark, and some statements end with a period.

**Comment by hotavocado** [comment]
resolved via https://github.com/hotavocado/HBN_EMA_NIMH2/commit/eb31643484523661dd27fe3fb93a1fa7bde74d68

**Comment by WorldImpex** [comment]
I have not found any punctuation issues thus far
