### ISSUE TITLE
Add a final screen to the NIMH - EMA app, which otherwise ends suddenly

### ISSUE THREAD

**Issue by binarybottle** [ChildMindInstitute/mindlogger-app#717]
We should add a screen at the end of this very long questionnaire. When you get to the screen pictured here, the progress bar is not anywhere near done because of the conditional logic ahead, so the user will likely tap the Done button, thinking it is yet another Next button, without thinking that they won't be able to go back. If instead of a Done button it were a Next button that led to a final screen, I think that would be more reasonable. That final screen can say something like "Tapping the Done button will exit the questionnaire."  [Note also that there is no "No" or "None" response option!]

![Screenshot_20200127-172125](https://user-images.githubusercontent.com/236532/73220256-fea75600-412b-11ea-95d9-c0462eb9ae9e.png)

**Comment by hotavocado** [comment]
Great suggestion!

**Comment by hotavocado** [comment]
resolved via:
https://github.com/hotavocado/HBN_EMA_NIMH2/commit/eb31643484523661dd27fe3fb93a1fa7bde74d68

**Comment by WorldImpex** [comment]
![File.jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/93361ebd-b1f9-41af-9bfa-5d072c22146a)

Fixed!
