### ISSUE TITLE
Going backwards and choosing a new path can crash an activity

### ISSUE THREAD

**Issue by binarybottle** [ChildMindInstitute/mindlogger-app#718]
When I got to the end of the NIMH - EMA questionnaire on my Pixel 4 XL (Android), I backtracked a few questions and changed my answers.  Now it crashes at this screen:

![Screenshot_20200127-180037](https://user-images.githubusercontent.com/236532/73221753-a40ff900-412f-11ea-8472-4b8b47bf2956.png)

**Comment by henryrossiter** [comment]
@binarybottle Do you know where I can find this applet? I want to make sure I test with the same one that caused the issue. Also, which of the applet's activities was this occurring on?

**Comment by WorldImpex** [comment]
@henryrossiter https://raw.githubusercontent.com/hotavocado/HBN_EMA_NIMH2/master/protocols/EMA_HBN_NIMH2/EMA_HBN_NIMH2_schema

**Comment by henryrossiter** [comment]
I spent a few hours this morning trying to recreate this issue. I was able to advance to the end of the survey, backtrack, change my answers multiple times without crashes. I recorded videos of the test I ran but they are too long to upload here.

Maybe it's only a specific combination of answers that crashes the activity?

**Comment by WorldImpex** [comment]
@henryrossiter I think the key here is to answer some conditional logic questions like answering yes to all of the headache questions and then navigating to the very first headache question and answering no which will make the other questions previously answered break. I haven't tried this myself but it was my hunch. If you already did that. then we can consider this fixed until it comes up again

**Comment by WorldImpex** [comment]
@henryrossiter I was testing something else and tried my above hypothesis and it failed. SO I think we can close this ticket out until it happens again

**Comment by henryrossiter** [comment]
> @henryrossiter I think the key here is to answer some conditional logic questions like answering yes to all of the headache questions and then navigating to the very first headache question and answering no which will make the other questions previously answered break. I haven't tried this myself but it was my hunch. If you already did that. then we can consider this fixed until it comes up again

This is the approach I used! I completed and re-completed the activity with different conditional-logic answers.
