### ISSUE TITLE
Revise NIMH - EMA headache questions

### ISSUE THREAD

**Issue by binarybottle** [ChildMindInstitute/mindlogger-app#719]
Q1: "Are you currently experiencing a headache?" - Yes
    Q2: "Is this the same headache that you reported for last assessment?" - Yes/No (same follow-up)
        Q3:  "Have you experienced a headache since the last questionnaire?" - Yes
            Q4: "What time did the headache begin?" - 5pm
                Q5: "Is this headache still present?" - Yes
                    ....QX: "Since the last questionnaire, did you do any of the following to prevent a headache?"

- Q2 should read "reported in the last assessment?"
- Q2 and Q3 should be consistent -- is it an "assessment" or a "questionnaire"?
- Q3 & Q5: Of course I have and still am having a headache -- I already said I have one in Q1!
- QX: There is no "No" or "None" option!

The question order should be changed with better logic:

Q1: "Are you currently experiencing a headache?" - Yes
    Q2: "Is this the same headache that you reported for last assessment?" - **Yes**
        ...severity questions...

Q1: "Are you currently experiencing a headache?" - Yes
    Q2: "Is this the same headache that you reported for last assessment?" - **No**
        Q4: "What time did the headache begin?" - 5pm
            ...severity questions...

**Comment by hotavocado** [comment]
resolved via:
https://github.com/hotavocado/HBN_EMA_NIMH2/commit/67bb00307debe99584c4f97495994298c0874740

**Comment by WorldImpex** [comment]
@hotavocado It looks like both paths might be missing the severity questions. Show this be called an assessment or questionnaire for Q2?

**Comment by WorldImpex** [comment]
@hotavocado I am still seeing the same issue on my device after updating the cache on the API. Could you check and post a video if it is fixed on your end?

**Comment by hotavocado** [comment]
I'm using v0.24 of the applet, the headache questions are behaving as expected. When you say 'no' to headache, it should immediately skip to the prevention question.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/24463939/76559078-d756df00-6474-11ea-974b-f6c117f1e522.gif)
