### ISSUE TITLE
🐛 🍎 After creating a new user in the app, the app returns to the login screen, but closing and reopening goes to activities logged in as the new user just created.

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-app#72]
I think the app should go straight to activities upon new account creation rather than back to the login screen.

Ref https://trello.com/c/pu8OWWEt

**Comment by binarybottle** [comment]
@shnizzedy -- Is this still the case?

**Comment by shnizzedy** [comment]
> @shnizzedy -- Is this still the case?

Nope, resolved!
