### ISSUE TITLE
App Crashes with No Data on Data Tab

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#721]
Expected Results: 
Actual Results: 
Description: 
Environment: Pixel 4XL - NIMH applet

**Comment by binarybottle** [comment]
Demo applet crashes when no data stored and tap on "Data" button at the bottom.
(Logged in as @hotavocado)

**Comment by WorldImpex** [comment]
I am not experiencing this on iPhone 6s

**Comment by sergeysemenuta** [comment]
Checked on the devices: 
Google Pixel 3a XL // Android 9
Xiaomi Mi 8 // Android 8.1.0
_MindLogger version: 0.11.4_ // NIMH applet

iPhone X // iOS 13.3
iPhone 5s // iOS 12.3.1
_MondLogger Version 0.9.13 (106)_ //  NIMH applet
 I wasn't able to reproduce this issue

**Comment by WorldImpex** [comment]
I am experiencing this on iPhone 6s with no data on the account sent crash report at 12:28 PM EST

**Comment by sergeysemenuta** [comment]
Replicated this issue on iPhone 7 //iOS 11.4.1// MindLogger Version 0.11.11 (128)
Log: https://www.dropbox.com/s/zwtqn21tfoosqve/MDCApp-2020-03-23-103624.ips.beta?dl=0

**Comment by sergeysemenuta** [comment]
The issue is fixed.
Checked on :
Dev server
iPhone 7 // iOS 11.4.1 // v 0.11.15(132)
Huawei P20 // Android 8.1.0 // v0.11.15

**Comment by WorldImpex** [comment]
Another example of a data tab crash

[https://app.zenhub.com/files/103405139/31aee348-3ab5-4f6b-9f7f-e6eac76c94d8/download](https://app.zenhub.com/files/103405139/31aee348-3ab5-4f6b-9f7f-e6eac76c94d8/download)

**Comment by WorldImpex** [comment]
@sergeysemenuta could try different devices to see if you can recreate

**Comment by sergeysemenuta** [comment]
The issue is not reproduced.
Checked on:
Dev server (NIMH, DEMO, DBT applets)
iPhone 7 // iOS 11.4.1 //  v 0.11.35  
Huawei P20 // Android 9.0 // v 0.11.35  
iPhone 5s // iOS 12.3.1// v 0.11.35
Redmi Note 8 Pro // Android 10 // v 0.11.35 
Redmi Note 3 Pro // Android 6.0.1 // v 0.11.35
