### ISSUE TITLE
Data Tab - X-axis Title Update

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#723]
Please move the x-axis title to the left side of the screen. 

![Screenshot_20200127-174745.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/c5f77070-e3a5-4cd2-a46c-0f723fd2ddc0)

**Comment by binarybottle** [comment]
Rationale:  Having a string to the right suggests that it refers to the rightmost values (sad is to the right, as in the slider activity, rather than sad is low on the y-axis).  If we space the plots sufficiently, having the bottom string from an upper plot and top string from a lower plot shouldn't be confusing.

**Comment by henryrossiter** [comment]
Could you provide a link to the applet that the screenshots are from?

**Comment by WorldImpex** [comment]
@henryrossiter Labels have disappeared in previous versions but since there was a change to it, the bug ticket wasn't necessary

**Comment by henryrossiter** [comment]
> @henryrossiter Labels have disappeared in previous versions but since there was a change to it, the bug ticket wasn't necessary

Sorry, I don't follow. I'm looking for the url to the protocol that I can use to test this out.

**Comment by WorldImpex** [comment]
https://raw.githubusercontent.com/hotavocado/HBN_EMA_NIMH2/master/protocols/EMA_HBN_NIMH2/EMA_HBN_NIMH2_schema

Thanks,

Wil Van Auken 
World Impex
9805-B York Rd
Ste 225
Cockeysville, MD 21030
410.771.0626 Local
1.800.736.3550
1.410.771.1585 Fax

**Comment by WorldImpex** [comment]
looks great! works as expected 

![File.jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/b25efd98-44be-40ce-93e6-7a82b5af97d2)
