### ISSUE TITLE
Applets on Phone do not match applets on admin panel

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#724]
Description: DBT, NIMH, and mindlogger demo are available in the app but missing NIMH in admin panel 

login wvanauken1 in production 

![File (1).jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/07edd1a1-76b6-40bf-b902-335cecacef28)
![mindlogger-admin.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/810526cd-379b-46bf-b5fd-f7fbf8944dbc)

**Comment by shnizzedy** [comment]
The set of applets a user sees in the mobile app is all of those for which that user has the role `user`.

The set of applets a user sees in the admin panel is all those for which that user has the role `coordinator` or `manager`.

Those sets can be identical, completely disjoint, or anything in-between.

**Comment by WorldImpex** [comment]
@hotavocado added me as a user to NIMH so that would be the reason wavanauken1 does not see NIMH in the admin panel
