### ISSUE TITLE
Slider doesn't work properly

### ISSUE THREAD

**Issue by devbtech** [ChildMindInstitute/mindlogger-app#730]
Odd error occurs in the slider when I try the following actions in Mindlogger Demo Applet

- drag handle to the very left of the slider
- click on the the very left of the slider
- click on the upper/lower part of the very left of the slider

![2020-01-28_18-47-26 (1).gif](https://images.zenhubusercontent.com/5e248ca6aaf6ad9f4a061291/06179d3a-a60d-47b6-841e-2c5700755f1f)

**Comment by WorldImpex** [comment]
Fixed 

![RPReplay_Final1580390975](https://user-images.githubusercontent.com/22243307/73454967-26b9d380-433d-11ea-9121-522f2ee9f47a.gif)
