### ISSUE TITLE
Upgrade React Native in order to use Firebase 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#733]
React Native has never been upgraded and is not allowing firebase to work properly so we need to upgrade RN

**Comment by henryrossiter** [comment]
@devbtech For reference, here are the changes we made last time we upgraded RN: https://github.com/ChildMindInstitute/mindlogger-app/commit/4c8188adaab3a7be6d2bca295fb539bf3c52c80a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
