### ISSUE TITLE
Individualized schedules

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#737]
As a manager or coordinator, I want to set an activity schedule for an individual user of an applet so that my user has customized scheduling of the activity.

Description: Managers or coordinators need to be able to set schedules for each user of the applet on an activity level individually. This means for User A the activities within a protocol can be scheduled differently every day of the week. The activities can also be scheduled multiple times during that day. This is all managed within the admin panel.

At the API level, we need to create routes for
1. managers / coordinators to GET both default and customized schedules
2. managers / coordinators to PUT custom schedules on protocols / activities that allow custom schedules

Here's a flowchart of what's currently in place (black), has API code written that should be in place soon (blue), and is not yet written or is not functional (both red). Note: the blue components do not have interfaces designed or written.
![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/93ff22d1-ecb4-47a1-a504-c0440cba0296)

More Resources: Click [Here](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/326) or [here](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-bug-reports/39)

Acceptance
Given I am a manager or coordinator
When I want to schedule a certain user to use activities within an applet at a certain time
Then I open my admin panel, select that applet, then user and finally set the schedule for the activity.

Given I am a manager or coordinator
When I want to edit a schedule of a certain user
Then I navigate back to my admin panel and reopen the schedule for that user's activity.

**Comment by WorldImpex** [comment]
Relates to #741, #740, #738

**Comment by WorldImpex** [comment]
Group Schedules

**Comment by sergeysemenuta** [comment]
The Individual scheduling works as expected
Checked on the Prod server on the
iPhone 7 // iOS 11.4.1 //  v 0.11.21   
Huawei P20 // Android 8.1.0 // v 0.11.21  
iPhone 5s // iOS 12.3.1// v 0.11.21
Closing the ticket.
