### ISSUE TITLE
Activity Timeout 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#739]
As a manager/ coordinator, I want to set a time limit on a scheduled activity so that the user only has so much time to complete an activity. 

Description: When an activity is scheduled, the manager/coordinator needs a way to limit the amount of time a user can access the activity( Activity Timeout). This activity timeout is set in days, hours and minutes by the manager/coordinator. This timeout information should be set when a manager/coordinator is setting a schedule for an applet. The manager/coordinator would set the time the activity will become available (developed in #772) and then set the timeout of when the activity would expire

Example: A manager/coordinator sets an activity to be available at 12:00 PM and then is given the option to set the activity timeout. The manager/coordinator enters 2 hours and 20 mins for the timeout and saves the calendar event. This reflects on the user side as the activity being available to start at 12:00 PM and at 2:20 PM, the user can no longer access the activity and it is no longer on the available activities to start. 

Requirements
1. Add option to set an activity timeout interval in days, hours, minutes (for example 30 min) for each activity
3. The activity should only be accessible to the user from the scheduled time to X amount of time after the scheduled time, where X is the timeout interval.
4. If the schedule was set and the timeout time passes, then the user can no longer see the activity. Any answered questions will be accepted if partially completed.
5. The user should only be able to start the activity before the time out expires. If the activity is started before the timeout expires, the user can complete it at the user's leisure if there isn't a idle time set (idle time is developed in #774) 

Acceptance Criteria:
Given I am a manager/coordinator
When I define the timeout of a scheduled activity
Then from the start date/time the user's access with expire at the timeout. 

Given I am a user
When I forget to finish a scheduled assessment with a timeout
Then only the questions answered are accepted and I no longer see the assessment on my survey tab

**Comment by WorldImpex** [comment]
Timeout does not work now. 

Steps to recreate: 
1. Set a start time and timeout in the future. 
2. Check to see if there is access to activity after start time. 
3. Check to see if there is access to activity after timeout time 
4. See results

Expected Results: After the time out time, the user cannot access the activity anymore
Actual Results: The activity is still available for the user to start 

![Screen Shot 2020-03-30 at 7.49.32 AM.png]
(https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/d64c55ca-4975-49f2-8fc3-c58b94a7c7cd)

![File (2).jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/5ec038ad-24ad-449a-9539-1dfca06a1216)

**Comment by sergeysemenuta** [comment]
Works as expected according to the Requirements, Description.
Checked on the:
Prod server
iPhone 7 // iOS 11.4.1 //  v 0.11.21   
Huawei P20 // Android 8.1.0 // v 0.11.21 
iPhone 5s // iOS 12.3.1// v 0.11.21
