### ISSUE TITLE
Smooth Slider in Applet Builder 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#743]
As an editor, I want to add a smooth slider bar so that the user does not have to select whole numbers. 

Requirements:
1. Allow the user to choose between a discrete slider (what we have today) and a continuous (what a smooth slider is)
2. If the user chooses continuous, require the user to enter the min and maximum values and labels 
3. #745 is the implementation for the in-app experience 

Given I am an editor
When I am in the builder
Then I should have an item option of a continuous slider bar

**Comment by henryrossiter** [comment]
@WorldImpex I'm not sure what this issue is- can you provide more detail?

**Comment by WorldImpex** [comment]
This relates to #745. A smooth slider is a slider without predetermined points where the user can slide to any place on the bar. I'll add more to this once it gets closer but if you are needing more to do. I can get to it in the AM

**Comment by sergeysemenuta** [comment]
Works as expected on the applet builder.
Checked on:
https://admin-new.mindlogger.org/
![2021-02-26_11-47-59.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/f022d7dc-2e18-4a09-b6bf-8a414e7d27f6)
