### ISSUE TITLE
Smooth Slider Type 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#745]
As a protocol builder, I want to give the option for a smooth slider so that the user is not constrained to predetermined answers 

Description: This will allow a user to move the slider button anywhere on the bar to input the user's response. The location of where the slider is left is to the hundredths place, which would not be visible to the user. 

Requirements
- The user should be able to drag and drop the slider in either direction on the slider bar. 
- The user should be able to click on the slider away from the slider location button and the location button jump to the clicked area. 

Acceptance Criteria
Given I am a protocol builder
When I want to give the user a smooth slider option
Then I select smooth slider option, define the min and max and the descriptions of each in the protocol builder

Given I am a user 
When a smooth slider option is displayed
Then I can move the slider to any position on the slider bar by clicking and dragging

**Comment by sergeysemenuta** [comment]
Checked on the applet builder and app side. Works as expected.
Video: https://www.screencast.com/t/1XgKSrhg
https://admin-new.mindlogger.org/
ML v 0.15.5 
Pixel 4XL//Android 11
iPhone X // iOS 13.3
