### ISSUE TITLE
ℹ️Add pop-up tooltip box for choices

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-app#748]
As a user, I want to see tooltips on answers that have descriptions so that I understand the question and answer more clearly. 
As an editor, I want to add tooltips to help explain the response options a user has so that the user makes the right choice. 

Description: For radio buttons, the user should be displayed a tooltip if there is a tip associated with that question. If there is not a tooltip associated, then the tooltip question mark should not be displayed. The user will have the ability to click the question mark that opens a textbox with information regarding that set of radio buttons. 

Requirements
- If the tooltip has text, then show the tooltip to the user
- If the tooltip does not have text, then do not show the tooltip 
- When the user clicks outside of the tooltip textbox, the tooltip closes
- This will only be for radio button and checkboxes 

User Journey:
Choices with a description will show a question mark icon
1. The user taps the question mark icon
2. A tooltip that renders markdown pops up with text for the user, and disappears when user taps anywhere outside the tooltip

Implementation with applet schema:
For choices with a description, we can add a `schema:description` key, and the tooltip will render the value of this key.

https://github.com/hotavocado/DBT_diary_card/blob/e9d188f05b96893261c121cdfec6da2006f0e0a6/activities/dbt_daily/items/distress_tolerance#L13-L17

Acceptance Criteria
Given I am a user
When I land on a radio button activity that has descriptions
Then I can click on a tooltip to learn more about the activity 

![tooltip](https://user-images.githubusercontent.com/24463939/73858783-f1aef480-4806-11ea-8092-c171ea4247a1.png)

**Comment by sergeysemenuta** [comment]
Raised 2 issues related to this task [1520](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/1520) [1521](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/1521)

**Comment by sergeysemenuta** [comment]
@WorldImpex It is implemented as just plain text. I'm not able to add markdown features bold text, ordered. unordered list clickable links etc.
![2021-02-16_14-10-06.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/7948a708-125a-462f-95f7-05e65cf748ee)
https://admin-staging.mindlogger.org/
Win 10 //  Chrome 88

**Comment by sergeysemenuta** [comment]
Closing the task
Works as expected
