### ISSUE TITLE
Calendar Entries Stack

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#751]
Expected Results: As the user enters new calendar entries to a particular day they start a list and are prioritized by full-day entry and then by the time of day 
Actual Results: Entries stack on top of each other and do not allow the user to easily see what the schedule is for that day 

![mindlogger-admin.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/1b1dc531-5dbf-4cdd-b7fe-7c55885141b7)

**Comment by WorldImpex** [comment]
@ProNinoGit120 I can still reproduce the same from before

**Comment by WorldImpex** [comment]
Please have calendar events stack as All day and then the time throughout the day in priority. 

Example the below image should be 
8AM 
9AM
5PM  

If there was an all day event then it would be 
All day event 
8AM 
9AM 
5PM 

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/e7e4cedf-3c89-41c6-9b0f-5c9b5ac72801)

**Comment by WorldImpex** [comment]
![Screen Shot 2020-02-17 at 4.45.05 PM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/f96f5bbd-503d-4c03-bce2-0a09d42d68ed)

An existing user must change the calendar from month to day and back to month for this fix to show up

**Comment by ProNinoGit120** [comment]
![Screen Shot 2020-02-18 at 7.05.33 AM.png](https://images.zenhubusercontent.com/5e248d759c666007f1a71211/b74f665b-dbf2-4513-af91-4e2e25a09826)

Sorted calendar entries in order of priority and left a space between entries.

**Comment by WorldImpex** [comment]
![mindlogger-admin.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/b9a292fa-90f4-41d5-b458-c598a9b18e99)

Stack as expected
