### ISSUE TITLE
Permit setting a different background color for activity screens other than white (and suitable contrasting font color)

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-app#76]
Ref https://trello.com/c/je5QkDGy

**Comment by binarybottle** [comment]
While the original spirit of this issue was to have full formatting flexibility (think dark mode), I believe this issue is somewhat redundant with another issue that deals with font color and moot now that Stu has implemented full-screen images in the visual stimulus-response widget.
