### ISSUE TITLE
I want my device to dictate when a notification is sent

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#768]
The manager/coordinator should enter the time as it is in the admin panel currently but the user's device is what decides the time the notification will officially go off. 

Example: The manager/coordinator will enter the time on a 24-hour scale. The timezone that the notification will actually fire will be determined by the time where the mobile device is present. A manager/coordinator will set a time of 1600 for a notification and when the user's mobile device says it is 4:00PM in the timezone the device is currently in, the notification will send. 

Requirement: Pull the user's device time to dictate when the push notification would send. (Right not the time set is in GMT)

**Comment by devbtech** [comment]
Added timezone field in User Model and notification is sent based on timezone of each user/device. Currently available on development server.
Need to send timezone of device while authenticate on mobile - ` /authenticate` end point
