### ISSUE TITLE
Branding/reskinning capabilities

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-app#77]
Ref https://trello.com/c/TVg1h7Fe

**Comment by shnizzedy** [comment]
https://docs.google.com/spreadsheets/d/e/2PACX-1vTh-gEiInU6aMVF-EP4NtJdfC7E7Fk_dF0vK7aDuKQwkePRE_v1C3ARuzH43DYZ9yWtXcOLohXCb7GE/pubhtml?gid=0&single=true

**Comment by binarybottle** [comment]
Has Henry taken care of this issue, @shnizzedy?
