### ISSUE TITLE
Notifications Not Firing

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#777]
Steps to recreate
1. log into MindLogger admin and select dev server (username wvanauken)
2. Select Healthy Brain Network and setup a calendar event for an activity with notification 5 minutes in the future for GMT time zone
3. Save event 
4. Save calendar 
5. Wait for notification 

Expected Results; User received a notification in 5 minutes 
Actual Results: User does not receive any notification 

![AwesomeScreenshot-2020-2-21-1582313813025](https://user-images.githubusercontent.com/22243307/75065931-df47e280-54b7-11ea-83b5-b64487ca7dab.gif)

**Comment by WorldImpex** [comment]
It looks like I received all notifications the next day 

![IMG_0329](https://user-images.githubusercontent.com/22243307/75096305-65256580-556c-11ea-8fc3-69ebeffeb79d.PNG)

**Comment by devbtech** [comment]
This should be resolved - currently updated to development server

**Comment by WorldImpex** [comment]
@devbtech I am getting a network timeout on dev when trying to set a notification 

![Screen Shot 2020-02-24 at 4.08.45 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/142f03f5-489b-44bc-b3a1-6c8b40b18a2f)

**Comment by WorldImpex** [comment]
notifications firing as expected now. Set a notification for 8 AM following day and it fired
