### ISSUE TITLE
Send timezone of device while authenticate on mobile

### ISSUE THREAD

**Issue by devbtech** [ChildMindInstitute/mindlogger-app#778]
`/user/authentication` end point has new timezone field.
Need to send timezone of device while mobile is authenticated. 

Format of new Timezone field -
```
type  :  number
default value : 0

ex.
-3 :   GMT -3
0  :   GMT
-5 :   GMT -5
```

![image.png](https://images.zenhubusercontent.com/5e248ca6aaf6ad9f4a061291/38a5897f-cdc2-4308-83d1-5a8b231a612f)
FYI, currently this updated endpoint is only available on development server - (https://dev.mindlogger.org/api/v1#!/user/user_login)

**Comment by WorldImpex** [comment]
works as expected
