### ISSUE TITLE
Data Tab has markup from Protocol

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#779]
Expected Behavior: Image URLs and markup text are removed from questions 
Actual Results: Image URLs and markup is visible to the user 

![File (2).jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/9b20d946-3d1e-45d2-bb35-a94c3b3aefda)

**Comment by WorldImpex** [comment]
@ProNinoGit120 Please remove the asterisk around text =  ** text **

**Comment by sergeysemenuta** [comment]
Verified on
iPhone 7 //iOS 11.4.1// MindLogger Version 0.11.11 (128)
Huawei P20 // Android 8.1.0 // MindLogger v 0.11.11
![IMG_1855.PNG](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/21ab1b03-81ea-4714-8d88-4c66b0846feb)
