### ISSUE TITLE
Update Style of See More button - Above progress bar

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#781]
Move the button above the progress bar within the bottom response option. Put a slight shadow behind it to show the user it is not part of the activity. 

![IMG_0378.PNG](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/0d708619-5368-4971-b3be-c67b3c49066c)

**Comment by ProNinoGit120** [comment]
![Screen Shot 2020-03-04 at 12.09.58 PM.png](https://images.zenhubusercontent.com/5e248d759c666007f1a71211/fd3ca2a4-6ce4-4144-b914-598aa671ce55)

**Comment by WorldImpex** [comment]
confirmed the above has been implemented and works as expected
