### ISSUE TITLE
Discovery - Aligning Code Coverage/ Definition of Done

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#786]
In an effort to develop MindLogger to become more stable and have more robust code coverage. The development team needs to investigate the best plan and way to adopt a better definition of done. If the development team adopts this practice to their definition of a done task, then going forward a developer will know that once the issue is complete, it must meet the criteria discovered from this task.

**Comment by henryrossiter** [comment]
mindlogger-app currently has just 11 tests implemented with [Yarn's testing framework](https://classic.yarnpkg.com/en/docs/cli/test/). These are local, offline tests designed to verify the app's JSONLD expansion logic. The tests can be found at ```\app\models\__tests__\json-ld.test.js```.


This discovery includes:
- Testing libraries
    - [Enzyme](https://enzymejs.github.io/enzyme/docs/guides/react-native.html)
    - [react-native-testing-library](https://github.com/callstack/react-native-testing-library)
    - lots of other options!
- Triggering tests with CI/CD
    - Bitrise integration
- When to write new tests
    - Should all new pull requests that introduce new features should include tests?

**Comment by henryrossiter** [comment]
Moving this out of in-progress as the discovery portion is done. For documentation, here are the testing schemes used on each project:
- Admin Panel
    - vue-test-utils + Jest
    - tests folder created: https://github.com/ChildMindInstitute/mindlogger-admin/tree/master/tests/
    - tests are run automatically on pull requests with Travis
- Mindlogger App Backend
    - pytest
    - testing library at test/testLib.py
