### ISSUE TITLE
Align Images to center that are above questions

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#787]
![File.jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/87504790-c7ce-4127-b61d-672ee1f2b476)

**Comment by hotavocado** [comment]
hi @ProNinoGit120, there eventually will be a change in the schema content to fix this issue. Currently I'm adding the header images like this:
`"question": "\r\n\r\n![new/thoughtBalloon.png](https://raw.githubusercontent.com/hotavocado/HBN_EMA_NIMH2/master/images/new/thoughtBalloon.png =150x150)\r\n\r\nWhich of the **following categories** best describes the area of your life in which the **event occurred**?"`

It would be easiest for me if a style was added to the .css controlling the item screens, and I can just call it like this `![new/thoughtBalloon.png#center](https://raw.githubusercontent.com/hotavocado/HBN_EMA_NIMH2/master/images/new/thoughtBalloon.png =150x150)`

I've also tried something like this: `<p align=\"center\"><img src=\"https://raw.githubusercontent.com/hotavocado/openmoji/master/color/svg/new/wgt3x.png\" width=\"150\" height=\"150\"></p>` but the app just renders the raw html

**Comment by ProNinoGit120** [comment]
Thanks Mike.
I just used "alignItems: 'center'" to fix this issue.

**Comment by hotavocado** [comment]
Hmm okay, does that mean the text will be centered too?

**Comment by WorldImpex** [comment]
Image aligned to the middle of the page

![File (2).jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/2d6d65a1-4f83-4d0b-8ccd-ae6fcf5b68a0)
