### ISSUE TITLE
'See more' button is hidden behind progress bar

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-app#789]
![Screenshot_20200302_142857_lab childmindinstitute data](https://user-images.githubusercontent.com/24463939/75710454-97cd0d80-5c92-11ea-95d2-a7e6c7436456.jpg)
Does the see more button look like this on anyone else's phone? I'm running android. It'd be nice to move the button higher a little so it isn't hidden!

**Comment by binarybottle** [comment]
Woah, that's not good!  We have been discussing moving the button above the progress bar, which should take care of this issue.  @WorldImpex -- perhaps we should raise the priority on that?

**Comment by WorldImpex** [comment]
@hotavocado @binarybottle It is probably due to Andriod vs iOS. We have #781 that will change this. So this might be a mute point going forward.

**Comment by binarybottle** [comment]
Will that be ready for HBN?

**Comment by WorldImpex** [comment]
It can be but that UI issue will increase the delay @binarybottle. I have moved it into the sprint and will prioritize it for launch of HBN

**Comment by WorldImpex** [comment]
Fixed with #781
