### ISSUE TITLE
The app crashes after disabling the Internet connection and then clicking on the "Resume" button on the "Resume activity" popup

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#797]
**Steps to reproduce:**

1. Launch and log in to the app as an existing user (e.g. s123 // 123456) 
2. Navigate the "Surveys" screen and turn off the wifi connection
3. Close the app
4. Launch the app
5. Tap and hold the "EMA Assessment (Morning) block
6. Click the "Resume" button
7. Pay attention to the result
8. Launch the app and turn on the wifi connection
9. Repeat steps 5, 6
10. Pay attention to the result

**Actual result:** The app crashes after disabling the Internet connection and then clicking on the "Resume" button on the "Resume activity" popup
**Video:** https://www.dropbox.com/s/lhahoy0tdh0hz4i/IMG_1190.MP4?dl=0
 **Log :** https://www.dropbox.com/s/jthv2uqbvn47me5/MDCApp-2020-03-05-104915.ips.beta?dl=0
**Expected result:** The app doesn't crash after disabling the Internet connection and then clicking on the "Resume" button on the "Resume activity" popup.

**Environment:**
MondLogger Version v 0.11.8
iPhone X // iOS 13.3

MindLogger Version 0.11.4
Xiaomi Mi 8 // Android 8.1.0

**Comment by sergeysemenuta** [comment]
The issue is reproduced on the iOS build: v 0.11.8 // iPhone X // iOS 13.3 as well

**Comment by Eugenia299** [comment]
Not  reproduceв  on 
https://admin-new.mindlogger.org/
Win 10 // Chrome 87
MindLogger app version 0.14.33
Device:
iPhone 11 Pro Max // iOS 13.5.1 
Samsung Galaxy S10 // Android 9
iPhone 8 // iOS 14
