### ISSUE TITLE
I want to save changes made to an existing Applet

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#801]
As an editor, I want to edit an in progress applet and have the option to save so that I can keep the applet updated for my users.

Requirements:
- Save Changes to Existing Applet: By saving a protocol that is in progress (applet has users and schedules defined), the applet is updated with the new data. 
- Items can be added, edited, and removed
- The existing data is still stored with the original criterion
- Changes are not made to the users or schedule of the original applet
- The user would see the 'same applet' but with the new changes made
- We need to store the original submissions with the original items and after the changed the next submission of the activity will show the 'new' activity submission and the existing for that day

Data visualization - App
- Added items are simply added to the list 
- Deleted items are removed from the list once 8 days have passed 
- Edited items are updated to the new content inputted

Data Visualization - Dashboard 
- Data should be shown from each version which clearly shows the date of change 
- Owners. managers and reviewers should be able to easily see the version changes
   - Allow the version toggled off and on in the chart. When on the bars will show and the key for the color of the bars will show. When turned off, no bars will show and the key will not be shown 
      - If it is a minor change a grey bar will show on the data charts 
      - If it is a major change a red bar will show on the data charts 
- When looking at a date range that contains a change in version, show the version numbers with the items and allow for the user to filter by version number
- Added items are simply added to the list but will not show data prior to being added 
- Deleted items will be shown for the previous version and the future version will remove that item from the list 
- Edited items are updated to the new content inputted

![Blank Diagram (3).png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/5a14a14f-b5ef-40a7-9bff-43cc5beed9a8)

Version Control
- Major = Any items added or removed 
- Minor = Any items edited, about page updated, or any other fields changed outside of a major change. 
- Version 1 will always be the first uploaded applet for the owner, manager, editor (1.0)
- If a major change is made = 2.0 
- If a minor change is made = 1.1 

Acceptance Criteria
Given I am an editor 
When I edit a protocol in progress
Then the data is still linked together historically

Given I am an editor
When I edit a protocol in progress
Then when I save the new changes, the user's applets are updated 

Not in scope
- Editing protocols #119

**Comment by sergeysemenuta** [comment]
Closing this ticket out as working as expected on https://admin-staging.mindlogger.org/
https://www.screencast.com/t/Mx41O6jL50Uv
