### ISSUE TITLE
The images for the question items are cut off on the landscape mode

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#805]
**Steps to reproduce:**
1. Log in to the app as an existing user (e.g. s123 /123456)
2. Tap on the "Healthy Brain network (NIMH content) v0.22" applet
3. Select the EMA Assessment (Morning) or (Mid day)/(Night) questionnaire 
4. Go to the screens with checkboxes
5. Rotate the device to landscape mode
6. Look at the images on the screen

**Actual result:** The images for the question items are cut off on the landscape mode
![Screenshot_2020-03-06-14-51-07-169_lab.childmindinstitute.data.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/e3d3b06c-49d2-4cc0-8dac-064d2fb002a6)
**Expected result:** The images for the question items should be fully visible on the portrait  and landscape modes

**Environment:**
MindLogger Version 0.11.4
Xiaomi Mi 8 // Android 8.1.0

**Comment by henryrossiter** [comment]
One way to prevent this is to disable rotation for the entire app. Is anyone aware of any applets that require landscape orientation?

**Comment by natalia-muzyka** [comment]
Rotation is disabled on iOS and Android.
