### ISSUE TITLE
It is not possible to turn off the Celluar Data on the "User Settings" screen

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#809]
**Steps to reproduce:**
1. Log in to the app as an existing user (e.g. s123 / 123456)
2. Navigate to the "User Settings" screen
4. Try to turn off the Cellular Data using the toggle button

**Actual result:** It is not possible to turn off the Celluar Data on the "User Settings" screen
**Video:** https://www.dropbox.com/s/wwnwfqpinfqllak/2020-03-06_15-58-15.MP4?dl=0
**Expected result:** It should be possible to turn off the Cellular Data using the toggle button on the "User Settings" screen

**Environment:**
Xiaomi Mi 8 // Android 8.1.0
MindLogger version: 0.11.4
**iOS build: v 0.11.8**
MondLogger Version 0.9.13 (106)
iPhone X // iOS 13.3

**Comment by sergeysemenuta** [comment]
The issue is relevant for the iOS build: v 0.11.8 as well

**Comment by natalia-muzyka** [comment]
@WorldImpex are we going to move back this option or ticket can be closed?
