### ISSUE TITLE
User loses identity in App when changing password

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#810]
Steps to Recreate
1. User navigates to account settings and clicks change password
2. User's name is filled in and the user needs to enter old password and new password
3. User clicks submit 
4. See results

Expected Result: User's password is updated
Actual Results: User loses identity in app 

Environment: iPhone 6s 13.3.1 | MindLogger 0.11.8

![File.jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/d6d9e9d6-1f7a-43df-b2dc-742f8befff8a)

**Comment by sergeysemenuta** [comment]
The issue is fixed
Checked on:
Dev server
iPhone 7 // iOS 13.4.1 // v 0.11.32  
Huawei P20 // Android 8.1.0 // v 0.11.32  
Video: https://www.dropbox.com/s/n471yvaaflb8mg8/IMG_2007.MP4?dl=0
