### ISSUE TITLE
Keyboard hides textbox

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#811]
Steps to recreate: 
1. Open DBT Diary Card applet and select "Events and Goals (With some images)"
2. On first question, select textbox
3. See Results

Expected Results: User can see the textbox and the keyboard on the same screen
Actual Results: Textbox is hidden by native keyboard 

![File (1).jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/0f0699d5-6c0c-4d51-a7e7-6424e1e4c243)

**Comment by sergeysemenuta** [comment]
Verified on:
api-new
ML v 0.15.5 
Pixel 4XL//Android 11
iPhone X // iOS 13.3
![2021-02-25_11-02-35.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/37ae469e-a0d0-41ef-9a2e-96e107bb3aaf)
