### ISSUE TITLE
Table Text Number Issues

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#812]
Requirements: 
1. If the scale is only to a 5 rating then only allow the user to record 0-5
2. When the user reaches 5, the next tap should start the sequence over again
3. If there are yes/no questions, then each tap will cycle yes then no then back to yes, etc 

![ezgif-7-39d30defb97d](https://user-images.githubusercontent.com/22243307/76227953-702bf700-61f6-11ea-8226-c8d4e6192c56.gif)

**Comment by sergeysemenuta** [comment]
Issues found:
1. It is possible to specify negative values on the "Table counter" screen by long pressing into the table cell
**Expected:** It shouldn't be possible to specify negative values on the "Table counter" 
2. The tooltips are displayed on the 'Table Text' screen
   * A short-press increases the counter
   * A long-press decreases the counter 
**Expected:** The tooltips are displayed on the 'Table Text' screen. the should display only on the  "Table counter" screen
**Video:** https://www.screencast.com/t/vV0qL0lXFeZ
**Environment:**
Staging
MindLogger app v 0.13.29
Samsung Galaxy S10 // Android 9
iPhone X // iOS 13.3
Pixel 4 XL // Android 11

**Comment by sergeysemenuta** [comment]
The issues are fixed.
https://www.screencast.com/t/ocArfrWd7
Environment:
Staging
MindLogger app v 0.13.31
Samsung Galaxy S10 // Android 9
iPhone X // iOS 13.3
Pixel 4 XL // Android 11

**Comment by sergeysemenuta** [comment]
The tooltips are displayed on the 'Table Text' screen
![2020-11-11_14-10-12.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/955d20f2-5a3b-4217-8b56-1a8f033d6af6)
A short-press increases the counter
A long-press decreases the counter
**Expected:** The tooltips are displayed on the 'Table Text' screen. They should display only on the "Table counter" screen
Environment:
Staging
MindLogger app v 0.13.31
Samsung Galaxy S10 // Android 9
iPhone X // iOS 13.3

**Comment by Eugenia299** [comment]
The issue mentioned in the comment above is fixed
Tested on:
https://admin-new.mindlogger.org/
Win 10 // Chrome 87
MindLogger app version 0.14.36
Devices:
iPhone X // iOS 13.3
iPhone 8 Plus // iOS 13.3
Google Pixel 3a XL / Android 11
