### ISSUE TITLE
Bulleted text not showing 

### ISSUE THREAD

**Issue by minji5924** [ChildMindInstitute/mindlogger-app#816]
![IMG_5934](https://user-images.githubusercontent.com/24580794/76234897-b4bc9000-6200-11ea-9096-13446c097aa3.PNG)

For this app, the consent process has to be included in within the survey. After the newest update, the app seems to cutting off just the bullet point part of the consent. The bullet points seems to be showing up, but the text is not.

**Comment by WorldImpex** [comment]
This is fixed now
