### ISSUE TITLE
The title of the "Delete your Account & Data" button is cut off on the "User Settings" screen

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#822]
**Steps to reproduce:**
1. Log in to the app as an existing user
2. Navigate to the "User Settings" screen
3. Pay attention to the "Delete your Account & Data" button

**Actual result:** The title of the "Delete your Account & Data"  button is cut off on the "User Settings" screen
![IMG_1423.PNG](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/32ddbfa0-7ac7-4f24-8642-a6c475216659)
**Expected result:** The title of the "Delete your Account & Data" button  should be fully visible on the "User Settings" screen

**Environment:**
iOS build: v 0.11.8 
MondLogger Version 0.9.13 (106)
iPhone 5s // iOS 12.3.1

**Comment by sergeysemenuta** [comment]
The issue is relevant for the  iOS build: v 0.11.8 as well

**Comment by sergeysemenuta** [comment]
The issue is actual for tablets as well
MindLogger app v 0.11.21
iPad Air 2//iOS 11.2.1
![IMG_0352.PNG](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/9c875217-3da6-4124-a741-3d9f8c7974b8)

**Comment by WorldImpex** [comment]
Check updated button

**Comment by sergeysemenuta** [comment]
The updated button is displayed without issues
Checked on :
iPhone 5s // iOS 12.3.1// v 0.11.35  
![IMG_1546.PNG](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/e1c1948b-206e-46df-a3b3-5bb4bd10eb40)
