### ISSUE TITLE
Update Invitation Message to User

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#824]
New message when opening an invitation:

Welcome to MindLogger! You were invited by **First name & Last name (email address)** to be a **user role** on **Applet Name**. 

Below are the users that have access to your data: 

Users who can see your data for this applet:
   **First name & Last Name (email address)**
Users who can change this applet's settings, including who can access your data:
   **First name & Last Name (email address)**
Users who can change this applet's settings, but who cannot change who can see your data: 
   **First name & Last Name (email address)**

Accept Invitation - Decline Invitation 

![Screen Shot 2020-03-10 at 5.04.02 PM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/139db5c5-cf67-46a9-a6e0-0697d2c57b16)

**Comment by binarybottle** [comment]
The last one should read "Users who can change this applet's settings, but who cannot change who can see your data"

**Comment by henryrossiter** [comment]
MindLogger no longer requires new users to first & last names or emails, see
- https://github.com/ChildMindInstitute/mindlogger-app-backend/issues/263
- https://github.com/ChildMindInstitute/MindLogger-bug-reports/issues/74

With this in mind, we are displaying users' display name, as seen in the screenshot above. Every user has a display name. Should this be changed?

**Comment by WorldImpex** [comment]
@henryrossiter Perfect! Thanks for pointing that out. Yes email not available is sufficient
