### ISSUE TITLE
NIMH applet. Some images for the question items are cut off on the portrait mode 

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#828]
**Steps to reproduce:**
1. Log in to the app as an existing user
2. Tap on the "Healthy Brain network (NIMH content) v0.22" applet
3. Select the EMA Assessment (Morning) or (Mid day)/(Night) questionnaire
4. Go to the screens with checkboxes
6. Look at the images on the screens

**Actual result:** Some images for the question items are cut off on the portrait mode 
![IMG_1224.PNG](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/8a68c661-61d8-4560-8bdd-46e3e45f2354)
**Expected result:** The images for the question items shouldn't be cut off on the portrait mode 
**Environment:**
iOS build: **v 0.11.8**
iPhone X // iOS 13.3

**Comment by hotavocado** [comment]
experiencing this on android as well

**Comment by hotavocado** [comment]
@WorldImpex Hi just wanted to bring this your attention, this issue should be a pretty easy fix. For DBT, all the icons I've been making are circles and the sides will be cut off! We just need to make the display window for the images a square, keeping the current height. Right now it's a rectangle.

**Comment by sergeysemenuta** [comment]
The issue is fixed
Checked on:
Dev server
iPhone 7 // iOS 13.4.1 // v 0.11.32  
Huawei P20 // Android 8.1.0 // v 0.11.32  
iPhone 5s // iOS 12.3.1// v 0.11.32
Redmi Note 8 Pro // Android 10 //v 0.11.32
![IMG_1536.PNG](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/caa03b0f-ef90-439e-8300-7c6412c9e252)
