### ISSUE TITLE
EMA Morning_sleep time

### ISSUE THREAD

**Issue by abadioli** [ChildMindInstitute/mindlogger-app#83]
![img_0090](https://user-images.githubusercontent.com/48026772/53435013-cea87d80-39c5-11e9-8e90-abce1d8b7839.jpg)
Not a fan of typical apple "time selector," perhaps a sliding bar would be more user-friendly. Thoughts?

I'm of the thought that simpler = better...

**Comment by binarybottle** [comment]
Consolidating all design-related issues...
