### ISSUE TITLE
The app crashes after tapping the "Data" menu button

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#833]
**Preconditions:**
The user completed all the questionaries for the NIMH applet
**Steps to reproduce:**
1. Install and launch the app
2. Log in 
3. Tap the "Data" tab
4. Pay attention to the result

**Actual result:** The app crashes after tapping the "Data" menu button
**Crash log:** https://www.dropbox.com/s/k6ypmg8gypywl9h/MDCApp-2020-03-13-174735.ips.beta?dl=0
**Video:** https://www.dropbox.com/s/hbmzaq66eoe3w58/IMG_1250.MP4?dl=0
**Expected result:** The app doesn't crash  after  tapping the "Data" menu button

**Environment:**
iOS build: v 0.11.8 
iPhone X // iOS 13.3

**Comment by WorldImpex** [comment]
I was able to try this on iPhone 6s without any data on the data tab and with data on the data tab. No crash with new build. Please check again

**Comment by sergeysemenuta** [comment]
The issue is fixed.
Checked on :
Dev server
iPhone 7 // iOS 11.4.1 // v 0.11.15(132)
Huawei P20 // Android 8.1.0 // v0.11.15
