### ISSUE TITLE
Display name bug for new applets

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-app#838]
Before yesterday, applet display name showed up correctly. They were generated by parsing `"skos:prefLabel"` in the protocol schema. Now it just shows the URL:

![Screenshot_20200318_103116_lab childmindinstitute data](https://user-images.githubusercontent.com/24463939/76971904-406ea480-6904-11ea-8cb4-e822de0593f8.jpg)

**Comment by WorldImpex** [comment]
![IMG_0688 (1).PNG](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/45306756-cd8e-42f0-bb11-8062a3dbd35e)
