### ISSUE TITLE
Emotional and physical states (mood circupflex)

### ISSUE THREAD

**Issue by abadioli** [ChildMindInstitute/mindlogger-app#84]
Switching from words to images for MOOD slider?

From Pick-a-mood: "We advise to not use words to ensure quick and intuitive usage. The cartoons have been developed and validated to be used without words. Verbal labels can be used when reporting results."

The faces would be standardized for HIGH v LOW applicable to each question.

![img_0097](https://user-images.githubusercontent.com/48026772/53438188-58a81480-39cd-11e9-8fa0-fe1613c4d6a5.PNG)

**Comment by binarybottle** [comment]
Consolidating all design-related issues...
