### ISSUE TITLE
Gap Fill for Notifications/ Scheduling

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#841]
To do
Notifications
- Add the ability to set multiple notifications for activity
- Add randomization option where the user sets the start and randomized end time so that a notification will fire between that time at random
- If not complete then send notification needs to be implemented. If the user has not started an activity by the time inputted by the manager then a notification will fire
Offline version - Notifications need to be stored locally 

Scheduling 
- Remove extra timeout field 
Offline version - Schedule needs to be stored locally

**Comment by devbtech** [comment]
not complet option and offline version would be ignored for this launch

**Comment by sergeysemenuta** [comment]
The functionality to set multiple notifications for activity and the randomization option are implemented and work as expected.
Checked on the Admin panel on the https://admin.mindlogger.org/#/
iPhone 7 // iOS 11.4.1 //  v 0.11.21   
Huawei P20 // Android 8.1.0 // v 0.11.21  iPhone 5s // iOS 12.3.1// v 0.11.21

The offline version has not implemented yet
