### ISSUE TITLE
Timeout does not stop the user from taking activity after deadline

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#847]
Expected Results: With a timeout below, the user after 12:15 PM should not be able to start the activity
Actual Results: User is able to start the activity after 12:15 PM

![Screen Shot 2020-03-22 at 12.22.16 PM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/32080033-f966-4579-a046-d4c94f01b906)

**Comment by WorldImpex** [comment]
Timeout does not work now. 

Steps to recreate: 
1. Set a start time and timeout in the future. 
2. Check to see if there is access to activity after start time. 
3. Check to see if there is access to activity after timeout time 
4. See results

Expected Results: After the time out time, the user cannot access the activity anymore
Actual Results: The activity is still available for the user to start 

![Screen Shot 2020-03-30 at 7.49.32 AM.png]
(https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/d64c55ca-4975-49f2-8fc3-c58b94a7c7cd)

![File (2).jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/5ec038ad-24ad-449a-9539-1dfca06a1216)

**Comment by WorldImpex** [comment]
This is still reproducible

**Comment by WorldImpex** [comment]
Steps to recreate
1. Create a timeout in the future
2. Sign into mobile for that user 
3. Wait until after timeout to see status of activity
4. See results 

Expected Results: The activity is no longer available for the user to start 
Actual Results: The activity is in unscheduled and able to be started by the user 

Additional information: If the user starts the activity before the timeout, then the activity remains available after the timeout for the user to complete. The user should have until midnight that day to complete. An idle timer will be developed in #774

**Comment by sergeysemenuta** [comment]
Checked on dev server.
The issue is still reproducible following the steps in the comment above
![timeout.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/14e7a523-57c1-4a4d-96e7-a3373108e34f)

**Comment by WorldImpex** [comment]
fixed!
