### ISSUE TITLE
Context of Assessment

### ISSUE THREAD

**Issue by abadioli** [ChildMindInstitute/mindlogger-app#85]
Has your child taken off THEIR activity monitor today? --> should be HIS (HER)
following screen: What time did HE take it off/put it back on?
     - should there be an indicator if the time END precedes time START? (see iPhone calendar)
![img_0098](https://user-images.githubusercontent.com/48026772/53439095-4929cb00-39cf-11e9-8ea6-eae35eb5ba95.jpg)

**Comment by abadioli** [comment]
Same for EMA Evening slide 2
![img_b6d40f8f55d9-1](https://user-images.githubusercontent.com/48026772/53439512-2d72f480-39d0-11e9-9479-1163b5d63703.jpeg)

**Comment by shnizzedy** [comment]
We don't currently have the capability to dynamically update content, so we'd have to have a `he/him` version and a `she/her` version of the same questions to achieve this change prior to building that functionality.

Related: https://github.com/ChildMindInstitute/mindlogger-app-backend/issues/92, https://github.com/ChildMindInstitute/mindlogger-app-backend/issues/93

That said, `they`, `them`, and `their` are acceptable gender-non-specific singular words.

#### _they_, pronoun
### OED
>  2. In anaphoric reference to a singular noun or pronoun of undetermined gender: he or she.
### Wiktionary
> 2. (the third-person singular, sometimes proscribed) A single person, previously mentioned, especially if of unknown or non-binary gender, but not if previously named and identified as male or female. [since the 1300s]
 
#### _them_, pronoun
### OED
>  4. In anaphoric reference to a singular noun or pronoun of undetermined gender: him or her. Cf. they pron.
### Wiktionary
> 2. Objective case of they: third-person singular pronoun used after a preposition or as the object of a verb.

#### _their_
### OED, adjective
> 4.  In relation to a singular noun or pronoun of undetermined gender: his or her. Cf. they pron. 2, them pron. 4; nobody pron. 1b, somebody n.
### Wiktionary, determiner
> 2. Belonging to someone (one person, singular).
