### ISSUE TITLE
Deleting event implementation

### ISSUE THREAD

**Issue by devbtech** [ChildMindInstitute/mindlogger-app#853]
related to 
https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/852

with the same route

now deleting works like this:
we delete any event schedule in admin and click save button. after this. server will get empty events for the same route. it will dissapere on admin but still present in DB

for example if i don't like to be notified by some event for example today at 6pm i delete it and that's all
but not after deleting i will be notified anyway

**Comment by WorldImpex** [comment]
This works as expected. The manager deletes a scheduled event and the user's device reflects the change from scheduled to unscheduled
