### ISSUE TITLE
Inviting New User on Dev Server Does Not Work

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#854]
Steps to recreate 
1. On an applet you manage, sign in and create an invitation for a user
2. Copy the last part of the URL per the below
As the new user, sign into API swagger docs page 
1. . POST invitation URL snippet to the below URL 
![Screen Shot 2020-03-23 at 7.01.53 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/166990ea-3a55-4a96-abbe-56a4239c0d39)
3. Wait an hour
4. Sign into MindLogger app to see if applet has posted
5. View results 

Expected Results: The new user has a new applet from the invitation to see 
Actual Results: No change to MindLogger app. Swagger docs does not have a new applet shown in get/user/applets. ADMIN Panel shows two new users 

![Screen Shot 2020-03-23 at 7.10.30 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/492be0cc-f77f-4497-b890-64828a40fda2)

**Comment by sergeysemenuta** [comment]
Inviting New User on Dev Server works as expected.

![2020-03-27_14-24-50.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/7ac04843-64b7-4186-87ee-7f2f938d9283)
