### ISSUE TITLE
 NIMH Applet.The app works very slow after completing all the questionnaires

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#855]
Steps to reproduce:
1.Log in to the app
2. Complete all the questionnaires for the NIMH Applet
3. Tap the "Data" tab
4. Scroll the screen
5. Tap other buttons Surveys, About, Settings, etc
6. Pay attention to the result

Actual result: The app works very slow after completing all the questionnaires. Some buttons don't respond on tapping
Video: https://www.dropbox.com/s/nz6ngwbornj0h6s/VID_20200323_153552%280%29.mp4?dl=0
Expected result: The app works without any delays after completing all the questionnaires

Environment:
iPhone 7 //iOS 11.4.1// MindLogger Version 0.11.11 (128)
Huawei P20 // Android 8.1.0 // MindLogger v 0.11.11

**Comment by WorldImpex** [comment]
Moving from Survey to About are quick but Data to survey or Data to About is slow

**Comment by sergeysemenuta** [comment]
The issue is still reproducible for me
Video: https://www.dropbox.com/s/cptudk6xg3fmo4t/IMG_1466.MOV?dl=0
Checked on the
Dev server
iPhone 7 // iOS 11.4.1 //  v 0.11.21   
Huawei P20 // Android 8.1.0 // v 0.11.21 
 iPhone 5s // iOS 12.3.1// v 0.11.21

**Comment by sergeysemenuta** [comment]
Reproducible on the MindLogger v 0.11.28 as well
