### ISSUE TITLE
NIMH Applet. The items for the questions are not displayed on the "Data" tab 

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#856]
Precondition:
The user completed the questionaries for the NIMH Applet.
Steps to reproduce:
1. Log in to the app
2. Navigate to the NIMH Applet
3. Tap the "Data" tab
4. Look at the screen

Actual result: The items for the questions are not displayed on the "Data" tab 
![IMG_1858.PNG](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/e129c6ad-744d-4993-9e79-9f3a2b40ce40)
Expected result: The items for the questions should be displayed on the "Data" tab 
Additional info: This issue is not reproduced on iOS  0.11.11 (128) but repro on Android v 0.11.11

Environment:
Huawei P20 // Android 8.1.0 // MindLogger v 0.11.11

**Comment by WorldImpex** [comment]
fixed 
![File (5).jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/208ba47c-1ab7-42b4-9054-4a54bd138e00)
