### ISSUE TITLE
The values for the questions with slide bars are not displayed on the "Data" tab

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#857]
Steps to reproduce:
1. Log in to the app
2. Complete the EMA  Assessment (Morning) questionnaire
4. Navigate to the "Data" tab
5. Look at the graph for the question "How would you rate the quality of your sleep?"

Actual result: The values for the questions with slide bars are not displayed on the "Data" tab
![Screenshot_20200323-175049.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/3078ca8a-3c4d-4acd-a956-2a9a63dbad84)
Expected result: The values for the questions with slide bars should be displayed on the "Data" tab

Environment:
iPhone 7 //iOS 11.4.1// MindLogger Version 0.11.11 (128)
Huawei P20 // Android 8.1.0 // MindLogger v 0.11.11

**Comment by WorldImpex** [comment]
as expected
