### ISSUE TITLE
NIMH Applet. The calendar is cut off  on the landscape/portrait mode

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#859]
**Steps to reproduce:**
1. Launch and log in to the app 
2. Select the NIMH Applet
3. Choose the EMA Assessment (Morning) questionnaire
4. Open the calendar
5. Rotate your device into landscape mode
6. Look at the screen
7. Close the calendar and open again
8. Rotate your device into portrait mode
9. Look at the screen
**Actual result:** The calendar is cut off  on the landscape/portrait mode
**Video:** https://www.dropbox.com/s/g2nzbbpo5vvv5yd/20200324_141517.mp4?dl=0
**Expected result:** The calendar shouldn't be cut off  on the landscape/portrait mode
**Environment:** 
Huawei P20 // Android 8.1.0 // MindLogger v 0.11.11

**Comment by natalia-muzyka** [comment]
The rotation is turned off. The ticket can be closed.
