### ISSUE TITLE
Episode Characteristics

### ISSUE THREAD

**Issue by abadioli** [ChildMindInstitute/mindlogger-app#86]
Unk instead of Unknown (in all screens).... also, in other assessments "Do Not Know" is used. Perhaps it's a good idea to have continuity and have them all be one or the other.
![img_d28ea99cec50-1](https://user-images.githubusercontent.com/48026772/53439189-85f5c200-39cf-11e9-85de-8106b58520fe.jpeg)

**Comment by shnizzedy** [comment]
Related: https://github.com/ChildMindInstitute/mindlogger-app-backend/issues/33, https://github.com/ReproNim/schema-standardization/issues/39

**Comment by binarybottle** [comment]
Consolidating all design-related issues...
