### ISSUE TITLE
NIMH Applet. The app crashes on the Pre-questionnaire after tapping the "Done" button

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#860]
**Steps to reproduce:**
1. Launch and log in to the app (e.g Devserg / 123456)
2. Select the NIMH Applet
3. Tap the "Pre-Questionnaire"
4. Answer the questions and tap the "Done" button
5. Pay attention to the result

**Actual result:**  The app crashes on the Pre-questionnaire after tapping the "Done" button
**Video:** https://www.dropbox.com/s/b3dhbkeu0lcz9xv/IMG_1862.MP4?dl=0
**Log:** https://www.dropbox.com/s/ieugt711hl2zo25/MDCApp-2020-03-24-143214.ips.beta?dl=0
**Expected result:** The app doesn't crash on the Pre-questionnaire after tapping the "Done" button

**Environment:**
Server - https://dev.mindlogger.org/api/v1
iPhone 7 //iOS 11.4.1// MindLogger Version 0.11.11 (128)
Huawei P20 // Android 8.1.0 // MindLogger v 0.11.11

**Additional info:** The app crashes on the "Headache" questions as well for the "EMA Assessment (Mid Day)

**Comment by WorldImpex** [comment]
Fixed 
![ezgif-3-72798ed26b55](https://user-images.githubusercontent.com/22243307/77540592-bbdad380-6e79-11ea-899d-e6bda884216f.gif)
