### ISSUE TITLE
NIMH Applet. The extra characters are displayed on some question screens

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#861]
**Steps to reproduce**:
1. Launch and log in to the app (e.g Devserg / 123456)
2. Select the NIMH Applet
3. Tap the "EMA Assessment (Mid Day)"
4. Observe question screens
5. Pay attention to the result

**Actual result:** The extra characters are displayed on some question screens
![IMG_1863.PNG](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/bfef28a6-28f0-4a52-948d-1cdf6feb01d1)
**Expected result:**  The extra characters shouldn't be displayed on some question screens

**Environment:**
Server - https://dev.mindlogger.org/api/v1
iPhone 7 //iOS 11.4.1// MindLogger Version 0.11.11 (128)
Huawei P20 // Android 8.1.0 // MindLogger v 0.11.11

**Comment by WorldImpex** [comment]
Fixed 

![File (4).jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/426e03c4-ebcd-45a9-ae1c-198a49585b92)
