### ISSUE TITLE
Unscheduled activities now disappear after completion

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-app#864]
By default, after adding an applet using `post/applet{url}`, all activities are visible, accessible, and unscheduled. 

As long as these activities are unscheduled, they should be accessible indefinitely. Now, completing an unscheduled activity will hide it:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/24463939/77684418-5b7a8d80-6f70-11ea-8804-d0458c403f53.gif)

Please make unscheduled activities always accessible again!

**Comment by WorldImpex** [comment]
fixed
