### ISSUE TITLE
Unable to refresh applets or add new versions

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-app#865]
`get/applet/{id}` with `refreshCache=true` is no longer refreshing applets on prod. Also, adding an applet that has already been added to Mindlogger before using `post/applet{url}` will generate a cached applet instead of pulling updated info from the Github.

An example, try to post [this applet](https://raw.githubusercontent.com/hotavocado/visibility-test/master/protocols/visibility-test/visibility-test_schema) into your account and compare the contents of the 'test' activity with the [version on github](https://github.com/hotavocado/visibility-test/tree/master/activities/test). They don't match, the new additions are missing.

**Comment by WorldImpex** [comment]
this should be fixed when #667 is deployed

**Comment by WorldImpex** [comment]
![mindlogger-admin (4).png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/f8d416ae-58bb-4972-9f83-6012aa421809)

fixed
