### ISSUE TITLE
NIMH Applet is very slow/ Cannot navigate back to ML Dashboard

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#873]
Steps to recreate: 
1. Open the NIMH applet 
2. Try to navigate back to dashboard, data, about 
3. See results

Expected Results: User can easily move to each page
Actual Results: Sometimes the buttons do not seem to work. Other times it is minutes before going to the selected page 

![RPReplay_Final1585567845](https://user-images.githubusercontent.com/22243307/77909055-9f181480-725a-11ea-9cb1-36e8f5fb1d30.gif)

Environment iPhone 6s 13.3.1 
MindLogger 0.11.16

**Comment by sergeysemenuta** [comment]
The issue is reproducible on 
iPhone 7 // iOS 11.4.1 // v 0.11.17(134)
Huawei P20 //Android 8.1.0 // v 0.11.17
as well

**Comment by sergeysemenuta** [comment]
Unable to check now because of the issue:https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/873

**Comment by sergeysemenuta** [comment]
Checked on the dev server on Phone 7 // iOS 11.4.1 //v0.11.19 
The issue is still reproducible
The app works very slow

https://www.screencast.com/t/UyISGDew

**Comment by WorldImpex** [comment]
Speed is back up now that the app isn't updating schedule as much
