### ISSUE TITLE
If user switches on mobile from dev to production server, the title doesn't change

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#881]
Steps to Recreate: 
1. Open MindLogger on mobile device 
2. If app is pointed at dev environment, change the URL to api.mindlogger.org/api/v1 
3. Hit submit
4. See results on login page

Expected Result: MindLogger title changes from MindLogger (dev) to MindLogger
Actual Results: The title shows MindLogger (dev) in either case

![File (3).jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/f87153a2-81ba-46cf-a779-46f97090abf1)

**Comment by henryrossiter** [comment]
This is a backend issue. The title comes directly from ```GET context/skin```

**Comment by WorldImpex** [comment]
fixed in #882 - title still doesn't change
