### ISSUE TITLE
The app crashes after trying to select another applet on the home screen

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#883]
Steps to repro:
1. Launch the app
2. Log in (e.g. Snake // 123456 )
3. Open the NIMH applet
4. Go to the home screen
5. Select another applet
6. Pay attention to the result

Actual result: The app crashes after trying to select another applet on the home screen
Note: Afte launching the app again the white screen is shown
Video: https://www.screencast.com/t/nyo5KAEzwNH
Expected result: The app is not crashed after trying to select another applet on the home screen

Environment: 
Dev server
 iPhone 7 // iOS 11.4.1 //v0.11.19

**Comment by WorldImpex** [comment]
seems to be fixed - iphone 6s

**Comment by sergeysemenuta** [comment]
The issue is fixed.
Checked on:
Dev server
iPhone 7 // iOS 11.4.1 //v0.11.27
