### ISSUE TITLE
Balance between useful feedback + overwhelming applets/activities

### ISSUE THREAD

**Issue by abadioli** [ChildMindInstitute/mindlogger-app#89]
I am aware that it becomes a lot for the parent filing out these assessments on a daily/multiple basis, however I think it would be great to examine how useful the feedback is.... perhaps additional followup questions, etc could be added to the following (see images)..
<img width="235" alt="screen shot 2019-02-26 at 14 29 27" src="https://user-images.githubusercontent.com/48026772/53440587-ed614100-39d2-11e9-92ec-980da16bba94.png">
<img width="362" alt="screen shot 2019-02-26 at 14 29 37" src="https://user-images.githubusercontent.com/48026772/53440601-f2be8b80-39d2-11e9-870d-36fd7eefdcb2.png">

**Comment by abadioli** [comment]
Drop-down (not on new screen bc too much) with typical Pain/Allergy meds + other
Same for next screen (with drop-down of prescriptions that are already in patient's profile

![img_0102](https://user-images.githubusercontent.com/48026772/53440721-374a2700-39d3-11e9-93e0-fb721874bc9d.PNG)
![img_0103](https://user-images.githubusercontent.com/48026772/53440722-374a2700-39d3-11e9-8e6d-3c69f56cdfd3.PNG)

**Comment by binarybottle** [comment]
Tables, drop-downs, and follow-up questions are fine to think about where we're not too concerned about increasing user burden, but in our Parent EMA case, we have to keep it tight.  We'll consider these options for future cases...
