### ISSUE TITLE
I want a offline Schedule

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#891]
Every user's device should store a week's worth of scheduling incase the user's device goes offline

**Comment by WorldImpex** [comment]
additional information in [#10](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-bug-reports/10)

**Comment by sergeysemenuta** [comment]
This feature works as expected on the https://admin-staging.mindlogger.org/ (Win 10 // Chrome Version 90.0.4430.212)
Closing this task

**Comment by sergeysemenuta** [comment]
This feature works as expected on the https://admin-staging.mindlogger.org/ (Win 10 // Chrome Version 90.0.4430.212)
Closing this task
