### ISSUE TITLE
 The App crashes at the end of the NIMH assessment

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#897]
Steps to repro:
1. Launch the app
2. Log in as an existing user (e.g. foxy // 123456)
3. Open the MIMH applet
4. Select the EMA Assessment (Morning)
5. Answer the questions
6. On the question "How severe was the pain  you experienced since you woke up?" the app crashes

Note: After opening the app again and tapping the resume button the app crashes again. On the android devices the app crashes randomly on different questions most of them with the slide bars

Actual result: The App crashes at the end  of NIMH assessment
Video: https://www.dropbox.com/s/plsf4d4ge811z4s/IMG_1900.MP4?dl=0
Android video:https://www.dropbox.com/s/wms4mx6n0ag6biw/Screenrecorder-2020-04-03-19-11-37-988.mp4?dl=0
Android log:https://www.dropbox.com/s/rrck7oo6bi27hmb/crashandro.txt?dl=0
Log:https://www.dropbox.com/s/ibyil7uzm33t5ob/MDCApp-2020-04-03-164456.ips.beta?dl=0
Expected result: The App doesn't crash at the end  of NIMH assessment

Environment:
Dev server
iPhone 7 // iOS 11.4.1 // v 0.11.21 (138)
Redmi Note 8 Pro // Android 10 //v 0.11.21

**Comment by WorldImpex** [comment]
might be related to #803

**Comment by sergeysemenuta** [comment]
The issue is not reproduced.
Checked on:
Dev server
iPhone 7 // iOS 11.4.1 // v 0.11.32
Redmi Note 8 Pro // Android 10 //v 0.11.32
