### ISSUE TITLE
Applets on admin panel and phone don't match

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-app#899]
I posted several applets to account hotavocado16 (pw: xiaoxiao712) last week, some are showing up on my phone and not the admin panel, others are showing up on admin panel but not my phone. 

Admin panel:
<img width="1392" alt="Screen Shot 2020-04-06 at 10 28 04 AM" src="https://user-images.githubusercontent.com/24463939/78570205-ab6c1680-77f2-11ea-8733-92b6881c5783.png">

Phone:
<img width="300" alt="phoneapplets" src="https://user-images.githubusercontent.com/24463939/78570260-bd4db980-77f2-11ea-8c2f-2260dd0b49b7.jpg">

When doing get/user/applets on dev.mindlogger.org, I get this:
<img width="952" alt="Screen Shot 2020-04-06 at 10 32 13 AM" src="https://user-images.githubusercontent.com/24463939/78570362-e1a99600-77f2-11ea-9847-256b8d16a57b.png">

These ids correspond to the applets currently showing up on my phone, 1. is visibility test 2. is ML demo, 3. is NIMH EMA

**Comment by hotavocado** [comment]
Applets cleared from all my accounts yesterday, and new ones I added are showing up on both my phone and admin panel as expected. Unable to replicate this issue for now.

**Comment by henryrossiter** [comment]
One possible cause for this is your user role.

On MindLogger App, we display every applet that the logged in user is at least 'user' for.

On the Admin Panel, we only display applets for which the logged in user is a 'manager'.

I'm not sure if this is the cause of the reported behavior but it is something to keep in mind.

**Comment by hotavocado** [comment]
An update:

Yesterday on the dbttest account, the DBT applet disappeared from my phone so I posted it again by doing post/applet on api.mindlogger.org. Just now, I refreshed applets on this account. This is what I'm seeing on the admin panel and my phone:

<img width="900" alt="Screen Shot 2020-04-13 at 8 45 56 PM" src="https://user-images.githubusercontent.com/24463939/79174747-97637e80-7dc9-11ea-8ac0-d03b57d9e2c9.png">

<img width="300" alt="phone_screenshot" src="https://user-images.githubusercontent.com/24463939/79174760-a0545000-7dc9-11ea-941a-12e2399910c0.jpg">

The applet that disappeared from my phone is still in the admin panel, and it refreshed.

**Comment by sergeysemenuta** [comment]
I was not able to reproduce the issue.
All applets from admin panel match the applets on the app
Video: https://www.dropbox.com/s/uc0uocqchfklaen/2020-05-15_19-05-28.MP4?dl=0
Checked on:
Dev server
https://dev.mindlogger.org/
Phone 7 // iOS 13.4.1 // v 0.11.34  
Huawei P20 // Android 8.1.0 // v 0.11.34
