### ISSUE TITLE
Completion tracker

### ISSUE THREAD

**Issue by abadioli** [ChildMindInstitute/mindlogger-app#90]
On top of screen in some activities but not others. Regardless of format of activity, would be helpful for them to know progress in each

![img_b6d40f8f55d9-1](https://user-images.githubusercontent.com/48026772/53440947-be979a80-39d3-11e9-9f64-5305e85feef4.jpeg)
![img_0102](https://user-images.githubusercontent.com/48026772/53440967-c9eac600-39d3-11e9-8007-5bebb5177570.PNG)

**Comment by shnizzedy** [comment]
On [app.mindlogger.info](https://app.mindlogger.info), the progress bar is a configurable option for editors:
![Show progress bar on top](https://user-images.githubusercontent.com/5974438/53446536-3c15d780-39e1-11e9-93ff-01342d9cccac.png)
On [mindlogger.anisha.pizza](https://mindlogger.anisha.pizza) and in the mobile app settings, this option is not yet configurable.
