### ISSUE TITLE
Calendar events stack outside of day

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#900]
Steps to recreate: 
1. Select applet 
2. Create a schedule with multiple events in one day
3. See Results

Expected Results: Users can see the events expand when the user hovers over them 
Actual Results: User cannot see the events 

Note: If the user tries to look at the weekly chart, the events do not show up there 

![Screen Shot 2020-04-07 at 8.14.07 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/79591071-00b6-4dd7-b32b-22420b59d5e6)

**Comment by WorldImpex** [comment]
This is reproducible on individual schedules

**Comment by WorldImpex** [comment]
#917 should fix this

**Comment by sergeysemenuta** [comment]
I Reproduced the issue on the admin panel on the dev server
https://www.screencast.com/t/8LPZbBL3

**Comment by sergeysemenuta** [comment]
The issue is fixed.
Checked on:
Dev server
 https://admin.mindlogger.org/ 
Win 10 // Chrome
![2020-05-22_20-23-13.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/7931ffa8-36a9-4c3a-b2ac-4949891a4d34)
