### ISSUE TITLE
The capital letters  are not accepted in the "Username" field on the "Sign Up" form

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#907]
Steps to repro:
1. Install the app
2. Launch the app
3. Tap the "New User" link
4.  Specify username which starts with a capital letter/s
5. Tap on the "Display name" field
6. Pay attention to the username field

Actual result: The capital letters are not accepted in the "Username" field on the "Sign Up" form. The validation message is shown.
Video: https://www.dropbox.com/s/j5bly2y6rn344re/IMG_1911.MP4?dl=0
Expected result: The capital letters are accepted in the "Username" field on the "Sign Up" form. No validation message is shown

Environment:
iPhone 7 // iOS 11.4.1 //  v 0.11.21   
Huawei P20 // Android 8.1.0 // v 0.11.21  
iPhone 5s // iOS 12.3.1// v 0.11.21

**Comment by WorldImpex** [comment]
There was a change in approach to using email so this is mute
