### ISSUE TITLE
Received notifications are duplicated for the events

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#912]
**Steps to reproduce:**
1. Log into prod environment https://admin.mindlogger.org/#/
2. Select the NIMH applet
3. Set app the schedule for the event with notifications (Pre-questionnaire any other events)
4. Log in to the app and wait for the scheduled time
5. Pay attention to the notification screen

**Note:** The issue is actual for the general and individual scheduling

**Actual result:** Received notifications are duplicated for the events
![IMG_1923.PNG](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/5cf6a345-3a32-4135-9f36-a0bc72f3d0ce)
**Expected result:** Only one notification should be received for the event

**Environment:**
Prod server
iPhone 7 // iOS 11.4.1 //  v 0.11.22
Huawei P20 // Android 8.1.0 // v 0.11.22

**Comment by WorldImpex** [comment]
fixed
