### ISSUE TITLE
Hide next until the user makes a selection

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#916]
- On all questions, hide the next button until the user makes a selection on all question types. 
- If the user hits undo, reset the entire item and remove the next button.

**Comment by sergeysemenuta** [comment]
The issue is fixed
Checked on:
 iPhone 7 // iOS 13.4.1 // v 0.11.27  
Redmi Note 8 Pro // Android 10 //v 0.11.27
