### ISSUE TITLE
Applets disappearing on Dev

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#920]
Steps to recreate: 
1. Log into dev account with existing applet(s)
2. See applet(s)
3. Log into MindLogger App with same credentials
5. See applet disappear

Expected results: Applet is on device
Actual Results: applet is not on device and disappears from admin panel

**Comment by ProNinoGit120** [comment]
Applets are not added and appeared after refresh for the new applets on dev.
The added applets are also not appeared on MindLogger app.
