### ISSUE TITLE
Require MRN/ Insitutional Field 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#928]
Requirements
* We need the MRN field to be required so users can be assigned to reviewers in the future. 
* Enforce a unique naming convention for the field 
* Replace "Institutional ID" or "MRN" name with " Secret User ID" in admin and data export

**Comment by sergeysemenuta** [comment]
The  Secret User ID is required for the user roles

In the following places, the   "Institutional ID" or "MRN" name is not replaced with " Secret User ID":
1. CSV file
![2021-01-27_14-45-29.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/f75969e9-82d9-47e1-a4f1-e372f38862cc)
2.Pending invitation section
![2021-01-27_14-47-33.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/6a0acd34-7af7-4713-a93d-96b9df1a0231)
3. User Data Export modal
![2021-01-27_14-50-54.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/0b457ddb-6009-4299-a2a3-749338142fb6)
4. View Data modal
![2021-01-27_14-52-04.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/9396e0eb-067d-44e3-b02f-18e7216c520b)
5. USERS tab
![2021-01-27_14-55-24.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/579fa23c-313a-4556-a778-03285d3047cf)
Checked on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 87

**Comment by sergeysemenuta** [comment]
The issues in the comment above are fixed
![2021-02-08_12-33-50.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/bf6cdcc4-5196-4f39-8641-ca666f848703)
Unable to check updates on the alert list because of the issue[781](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/781)
