### ISSUE TITLE
Login Error on Dev

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#933]
Steps to recreate: 
1. Navigate to admin dashboard 
2. Log into an account (manager/ abcd123)
3. See results 

Expected Results: Land on applet dashboard 
Actual Results: See error screen 

![mindlogger-admin (1).png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/73f4d012-6350-42e5-b404-c4efde1c1678)

**Comment by henryrossiter** [comment]
Diagnosis: Browsers can only hold a finite amount of data in localStorage. Users with many applets and lots of scheduling data get this error because the browser is unable to store it all.

Still working on a solution.
