### ISSUE TITLE
Unable to log in to the app and  the admin panel

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#939]
Preconditions:
The user is registered on MindLogger and on the admin panel
Steps to reproduce:
1. Open the site https://admin.mindlogger.org/#/
2. Log into the prod server using your credentials ( snakeprod / 123456)
3. Try to log in into the app as well
5. Pay attention to the result

Actual result: It is not possible  to log in to the app and  the admin panel. The log in failed message is shown on the app. The invalid credentials message is shown on the admin panel.
https://www.dropbox.com/s/v9aacd53u1q1eyk/2020-04-22_16-00-59.MP4?dl=0
Expected result: The user is logged insuccessfully on the app and  the admin panel 

Environment:
Prod server
https://admin.mindlogger.org/#/login
iPhone 7 // iOS 13.4.1 // v 0.11.22

**Comment by WorldImpex** [comment]
fixed
