### ISSUE TITLE
Individual scheduling. The schedule settings are reset after setting up the schedule for another user on the admin panel and the app

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#943]
Steps to reproduce:
1. Login to the admin panel as a manager
2. Select the NIMH applet and navigate to the users page
3. Set up individual scheduling for user A and save (The events are saved and displayed on the calendar)
4. Log in as user A to the app and  open the NIMH applet ( The events fron step 3 are scheduled )
5. As a manager set app individual shedul for user B and save
6. Go back to the user's A calendar
7. Pay attention to the result

**Actual result:** The schedule settings are reset after setting up the schedule for another user on the admin panel and the app. The calendar is empty for the User A  on the  admin panel and scheduled events becomes  unscheduled on the app.  

Video: https://www.dropbox.com/s/loph4feovyk570y/2020-04-23_18-22-55.MP4?dl=0

Expected result: All events should be shown  for each user and group of users  on  the  admin panel for the individual scheduling

Environment:
Dev server
https://admin.mindlogger.org/
iPhone 7 // iOS 13.4.1 // v 0.11.22  
Huawei P20 // Android 8.1.0 // v 0.11.22

**Comment by WorldImpex** [comment]
I could not recreate

**Comment by sergeysemenuta** [comment]
I replicated the isssue again.

**Comment by sergeysemenuta** [comment]
The issue is not reproduced.
Environment:
Dev server
https://admin.mindlogger.org/
iPhone 7 // iOS 13.4.1 // v 0.11.35
Huawei P20 // Android 9.0 // v 0.11.35
iPhone 5s // iOS 12.3.1// v 0.11.35
Redmi Note 8 Pro // Android 10 // v 0.11.35
Redmi Note 3 Pro // Android 6.0.1 // v 0.11.35
