### ISSUE TITLE
The "Are you sure you want to change whether this event occurs all day?" pop-up is not shown up after unchecking  the "All day" checkbox on the modal window

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#944]
Steps to reproduce:
1. Log in to the admin panel https://admin.mindlogger.org/
2. Navigate to the schedule page (Individual or general)
3. Click  the "+" button
4. Click the  pencil icon
5. Uncheck the "All day" checkbox
6. Pay attention to the result

Actual result: The "Are you sure you want to change whether this event occurs all day?" pop-up is not shown up after unchecking  the "All day" checkbox on the modal window

Video: https://www.dropbox.com/s/3x0imrieox6vrt7/2020-04-23_18-33-12.MP4?dl=0

Note: After refreshing the page the pop-up "Are you sure you want to change whether this event occurs all day?"  is displayed

Expected result: The "Are you sure you want to change whether this event occurs all day?" pop-up is  shown up after unchecking  the "All day" checkbox on the modal window without refreshing the page

Environment:
https://admin.mindlogger.org/
Dev server
Win 10 // Chrome 81 // Edge

**Comment by henryrossiter** [comment]
I'm able to replicate this on some devices/browsers but not all. Sometimes, it works perfectly and the code that causes the confirmation modal window to appear hasn't been changed recently.

I think it may be an issue with the ```this.$dayspan``` reference, but I'm not sure yet.

**Comment by sergeysemenuta** [comment]
Checked on dev server on https://admin.mindlogger.org/site (Chrome, Firefox ,Edge)

I don't see the confirmation popup after unchecking the "All day" checkbox  at all

@WorldImpex @henryrossiter Do you have any thoughts? If that expected we can close the issue if not it should be fixed

**Comment by WorldImpex** [comment]
@sergeysemenuta If the event is actually changing without the confirmation screen. We can close. I didn't like the confirmation box anyway.

**Comment by sergeysemenuta** [comment]
Thanks @WorldImpex 

Closing the ticket
