### ISSUE TITLE
The "Healthy Brain Network" applet is not displayed on  the admin panel 

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#948]
**Steps to reproduce:**
1. Log in to the admin panel https://admin.mindlogger.org/ (e.g. snake //123456)
2. Add the "Healthy Brain Network EMA" applet 
3. Wait for several minutes
4. Refresh the page
5. Observe avaliable applets
6. Log in to the app and look at the screen

**Actual result:** The "Healthy Brain Network" applet is not displayed on  the admin panel but displayed on the mobile app

**Video:** https://www.dropbox.com/s/xxpj5zi684xdhja/2020-04-24_18-01-28.MP4?dl=0

**Expected result:** The "Healthy Brain Network" applet is displayed on  the admin panel and on the app 

**Environment:**
Dev server
Win 10 //Chrome 81

**Comment by WorldImpex** [comment]
fixed
