### ISSUE TITLE
TokenPrizes Redemption 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#949]
As a user, I want to spend the tokens I have earned so that I can buy prizes for my behaviors in a TokenLogger Activity 

Requirements 
- Show an activity that lists token prizes, their value and the user's accumulated amount of tokens 
- If the user selects a prize show a confirmation screen 
- If the user selects yes on the confirmation screen then we show the confirmation screen - Can we customize this? 
- If the user selects no, then show the list of items again 

![TokenStore (1).png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/6056c08e-5aac-485f-a63c-ae1c70a5f40f)

**Comment by WorldImpex** [comment]
1. Edited items disappear from confirmation page in app 
Steps to recreate 
- Create a TokenPrize
- Edit the items 
- Check device 
Expected: Item confirmation page still works
Actual: Confirmation page is blank 
![RPReplay_Final1610279749.gif](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/8aafbc79-0d09-443f-aed3-9f23327020dd)

2. Change confirmation screen text to "Do you want *TokenPrize Name* for *PrizeValue* tokens? Please ensure the sentence reads as written

**Comment by sergeysemenuta** [comment]
The 1st issue in the comment above is fixed.
The 2nd- fails

**Comment by sergeysemenuta** [comment]
The issues are fixed.
![2021-01-28_14-45-11.gif](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/6b286c07-af3b-4ffb-8610-fc91da67b006)
Verified on:
Staging
ML v 0.14.76
Pixel 4XL//Android 11
iPhone XR // iOS 13.0
