### ISSUE TITLE
Remove Number Above Slider 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#963]

**Comment by sergeysemenuta** [comment]
The number is not shown above the slider.
Checked on:
Dev server
iPhone 7 // iOS 13.4.1 // v 0.11.32
Huawei P20 // Android 8.1.0 // v 0.11.32
iPhone 5s // iOS 12.3.1// v 0.11.32
Redmi Note 8 Pro // Android 10 //v 0.11.32
![IMG_1537.PNG](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/4d60bd8f-3acb-46c2-91c6-a63d127edb87)
