### ISSUE TITLE
Invitation Network Error When Accepting - Prod 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#967]
Steps to recreate 
1. Receive an invitation on prod (web.mindlogger.org/#/invitation/5ea84e1ea7a805c30d04fb93) 
2. Open invitation and try to accept it
3. See results 

Expected Results: You would see a confirmation screen 
Actual Results: You see a network error after clicking accept 

Enviroment macos using chrome

**Comment by sergeysemenuta** [comment]
Replicated this issue on the Redmi Note 8 Pro // Android 10
Chrome version 81.0.4044.117
![Screenshot_2020-04-28-20-16-24-945_com android chrome](https://user-images.githubusercontent.com/39083532/80518059-a7b15700-898e-11ea-9ab1-8a829199f432.jpg)

**Comment by WorldImpex** [comment]
Reproduced on Safari - macos 

![Screen Shot 2020-04-29 at 7.45.13 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/2cde2918-ebfa-4422-bb68-9b8f20b91a17)

**Comment by WorldImpex** [comment]
Reproducible on Safari macOS 

![Screen Shot 2020-04-29 at 7.45.13 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/61e405ff-31a1-4960-927a-f1104b91aa99)

**Comment by sergeysemenuta** [comment]
Reproducible on Safari after Signing  up following the invitation link on Redmi Note 8 Pro // Android 10 //Safari
 ![Screenshot_2020-04-30-11-51-26-914_org.mozilla.firefox.jpg](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/e01ce986-5ecc-4d75-b14c-69b26fa4d665)

**Comment by sergeysemenuta** [comment]
The invitations were accepted without errors
Checked on:
Redmi Note 8 Pro // Android 10 //Default browser//Chrome//Firefox
iPhone 7 // iOS 13.4.1 //Safari//Chrome
Win 10 // Chrome 81//Firefox 75//Edge

**Comment by WorldImpex** [comment]
passed on macOS browsers desktop - chrome, safari, and firefox

**Comment by WorldImpex** [comment]
Failed on iphone 6s safari browser so opened a different ticket #986
