### ISSUE TITLE
It is not possible to remove applets from the admin panel

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#968]
Steps to reproduce:
1. Log in to the admin panel https://admin.mindlogger.org/ (devnext // 123456)
3. Navigate to the  applets page and try to delete the applets
4. Pay attention to the result
5. Log out from the admin panel wait for several minutes and log in again
4. Repeat the step 3
5. Pay ayttention to the result

Actual result: It is not possible to remove applets from the admin panel.The applets are displayed on the admin panel and on the app
Video: https://www.dropbox.com/s/zdvhelgtvcw6ndx/2020-04-28_18-58-24.MP4?dl=0
Note: 500 error is shown in browser console after clicking the "Delete" button
Expected result: It should be possible to remove applets from the admin panel.

Environment:
Dev server
Win 10 x 64 // Chrome //   https://admin.mindlogger.org/#/  
iPhone 7 // iOS 13.4.1 // v 0.11.22

**Comment by WorldImpex** [comment]
Works on iPhone 6s

**Comment by sergeysemenuta** [comment]
Checked on dev server on the https://admin.mindlogger.org/
