### ISSUE TITLE
Invitation Network Error Opening Link - Safari

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#969]
Steps to recreate: 
1. Copy an invitation link 
2. Paste the link into incognito Safari browser 
3. See Results 

Expected Results: Page loads allowing the user to accept or decline the invitation 
Actual Results: Network Error is shown intermittently 

Safari macOS chrome and iPhone 6s

**Comment by WorldImpex** [comment]
![Screen Shot 2020-04-29 at 10.41.55 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/f1b59e1a-7503-4421-990f-d87ffd4b51a9)

**Comment by sergeysemenuta** [comment]
The issue is not reproduced on the iPhone 7 // iOS 13.4.1 // Safari
