### ISSUE TITLE
The NIMH applet is not displayed  on the app after accepting the invitation

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#987]
Steps to repro:
1. Log in to the admin panel  https://admin.mindlogger.org/ (devnext //123456)
2. Select the NIMH applet
3. Navigate to users page
4. Create several invitations with user role
5. Accept those invitations as other users (usea, useb, userc etc.)
6. Wait for several minutes
7. Log in to the app as usea, useb, userc
8. Pay attention to the home screen

Actual result:The NIMH applet is not displayed  on the app after accepting the invitation
![2020-05-05_20-05-57](https://user-images.githubusercontent.com/39083532/81095821-346b9000-8f0e-11ea-8b80-90a3b92b310e.png)

Expected result: All users after accepting the invitations should have the NIMH applet on the app

Environment:
Dev server
iPhone 7 // iOS 13.4.1 // v 0.11.29 
Huawei P20 // Android 8.1.0 // v 0.11.29
iPhone 5s // iOS 12.3.1// v 0.11.29
Redmi Note 8 Pro // Android 10 //v 0.11.29

**Comment by WorldImpex** [comment]
Applet 5eb2aeece9934b80c1eebb6c is shown in swagger docs for dev

**Comment by sergeysemenuta** [comment]
The same behavior for users that were invited to be a coordinator/editor/reviewer  of the applet
Works as expected only for the user that is invited to be a manager of the applet

**Comment by sergeysemenuta** [comment]
Reproduced this  issue again .The applet is not displayed on the app after accepting an invitation using the API calls on Swagger. 
Note: The applet ID is not displayed after accepting  an invitation on https://dev.mindlogger.org/api/v1#!/user/user_getOwnApplets
iPhone 7 // iOS 13.4.1 //  v 0.11.35  
Huawei P20 // Android 9.0 // v 0.11.35

**Comment by sergeysemenuta** [comment]
The issue is actual for all applets

**Comment by sergeysemenuta** [comment]
The applets are displayed on the app after accepting the invitation. Checked all roles and different applets.
Environment:
Win 10 x 64 // Chrome //   https://admin.mindlogger.org/#/  dev.mindlogger.org/api/v1
Mobile devices:
iPhone 7 // iOS 13.4.1 //  v 0.11.35  
Huawei P20 // Android 9.0 // v 0.11.35  
Redmi Note 8 Pro // Android 10 // v 0.11.35 
iPhone 5s // iOS 12.3.1// v 0.11.35
